/* ============================================================
   THE tool registry — single source of truth.

   Every tool's identity, taxonomy and discovery metadata lives here and
   nowhere else. Search reads this file; tool components never carry
   search metadata of their own.

   Adding a tool: add an entry here and create js/tools/<id>.js. The id
   is the module filename, the URL hash, and the analytics key.

   `intents` is the field that makes search work for people who do not
   know what the tool is called. Write them as the task, in the words
   someone would actually use: 'compress photo', not 'image compression'.

   Retired ids belong in ALIASES in ./schema.js so old links still land.
   ============================================================ */

/** @typedef {import('./schema.js').Tool} Tool */

function svg(paths) {
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${paths}</svg>`;
}

/** @type {Tool[]} */
export const TOOLS = [
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Words, characters, sentences, paragraphs, and reading time',
    category: 'text',
    keywords: ['word', 'words', 'wordcnt', 'wrd', 'count', 'counter', 'character', 'char', 'letters', 'length', 'sentence', 'paragraph', 'reading time', 'stats', 'calculator', 'text length', 'metrics'],
    synonyms: ['character count', 'letter count', 'word count'],
    intents: ['count words', 'how many words', 'count characters', 'reading time', 'essay length', 'check word limit'],
    related: ['text-diff', 'case-converter', 'document-analyzer'],
    accepts: ['text', 'markdown'],
    weight: 78,
    icon: svg('<path d="M3 7h18"/><path d="M3 12h12"/><path d="M3 17h15"/>'),
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Transform text to UPPER, lower, camelCase, snake_case, kebab-case',
    category: 'text',
    secondary: ['developer'],
    keywords: ['case', 'convert', 'uppercase', 'lowercase', 'camelcase', 'snakecase', 'kebabcase', 'titlecase', 'capitalize', 'text case', 'change case', 'format text', 'lower', 'upper'],
    synonyms: ['change case', 'capitalisation', 'capitalization'],
    intents: ['make text uppercase', 'convert to lowercase', 'camel case', 'snake case', 'title case', 'fix capitalisation'],
    related: ['slug-generator', 'find-replace', 'word-counter'],
    accepts: ['text'],
    produces: ['text'],
    weight: 72,
    icon: svg('<path d="M3 17l5-12h1l5 12"/><path d="M5 13h6"/><path d="M16 17v-5a2.5 2.5 0 1 1 5 0v5"/>'),
  },
  {
    id: 'find-replace',
    name: 'Find & Replace',
    description: 'Search and replace text with regex & case options',
    category: 'text',
    secondary: ['developer'],
    keywords: ['find', 'replace', 'search', 'swap', 'substitute', 'regex replace', 'find and replace', 'change text', 'string replace'],
    synonyms: ['search and replace', 'substitute text'],
    intents: ['replace text', 'find and replace', 'swap words', 'bulk edit text'],
    related: ['regex-tester', 'remove-duplicates', 'sort-lines'],
    accepts: ['text', 'json', 'csv', 'code', 'markdown'],
    produces: ['text'],
    weight: 62,
    icon: svg('<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.35-4.35"/><path d="M8 11h6"/>'),
  },
  {
    id: 'sort-lines',
    name: 'Sort Lines',
    description: 'Alphabetize, reverse, shuffle, or sort lines by length',
    category: 'text',
    keywords: ['sort', 'order', 'alphabetize', 'shuffle', 'reverse', 'lines', 'organize', 'organise', 'list', 'line sorter', 'rearrange', 'a to z', 'z to a'],
    synonyms: ['alphabetise', 'alphabetize', 'order lines'],
    intents: ['sort a list', 'alphabetise lines', 'shuffle lines', 'reverse a list', 'sort by length'],
    related: ['remove-duplicates', 'find-replace', 'word-counter'],
    accepts: ['text', 'csv'],
    produces: ['text'],
    weight: 60,
    icon: svg('<path d="M3 6h18"/><path d="M7 12h10"/><path d="M10 18h4"/>'),
  },
  {
    id: 'remove-duplicates',
    name: 'Remove Duplicates',
    description: 'Deduplicate lines with case-sensitivity & trimming options',
    category: 'text',
    secondary: ['developer'],
    keywords: ['dedup', 'duplicate', 'deduplicate', 'remove duplicates', 'unique', 'distinct', 'filter lines', 'clean text', 'strip duplicates'],
    synonyms: ['dedupe', 'deduplicate', 'unique lines'],
    intents: ['remove duplicate lines', 'get unique values', 'clean a list', 'strip repeats'],
    related: ['sort-lines', 'find-replace', 'csv-to-json'],
    accepts: ['text', 'csv'],
    produces: ['text'],
    weight: 58,
    icon: svg('<polyline points="20 6 9 17 4 12"/>'),
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Convert any text into a URL-friendly slug',
    category: 'text',
    secondary: ['developer', 'design'],
    keywords: ['slug', 'slugify', 'url string', 'friendly url', 'hyphenate', 'dash', 'seo url', 'permalink', 'convert text to url'],
    synonyms: ['url slug', 'permalink', 'slugify'],
    intents: ['make a url slug', 'seo friendly url', 'turn title into url'],
    related: ['case-converter', 'url-codec'],
    accepts: ['text'],
    produces: ['text'],
    weight: 48,
    icon: svg('<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>'),
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Generate customizable dummy placeholder text',
    category: 'text',
    secondary: ['design'],
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy text', 'filler', 'generator', 'sample text', 'lipsum', 'fake text', 'mock text', 'words'],
    synonyms: ['placeholder text', 'dummy text', 'filler text'],
    intents: ['generate placeholder text', 'dummy paragraphs', 'fake text for mockup'],
    related: ['word-counter', 'random-number'],
    produces: ['text'],
    weight: 46,
    icon: svg('<path d="M3 6h18"/><path d="M3 10h18"/><path d="M3 14h12"/><path d="M3 18h15"/>'),
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write markdown with live side-by-side HTML preview',
    category: 'text',
    secondary: ['developer'],
    keywords: ['markdown', 'md', 'preview', 'editor', 'gfm', 'html', 'live preview', 'render', 'text editor', 'formatting'],
    synonyms: ['md preview', 'markdown renderer'],
    intents: ['preview markdown', 'render markdown', 'markdown to html', 'check readme formatting'],
    related: ['html-entity-codec', 'document-analyzer'],
    accepts: ['markdown', 'text'],
    produces: ['markdown'],
    weight: 56,
    icon: svg('<rect x="2" y="3" width="20" height="18" rx="1"/><path d="M12 3v18"/><path d="M6 15v-6l2.5 3L11 9v6"/>'),
  },
  {
    id: 'document-analyzer',
    name: 'Document Analyzer',
    description: 'Local text document analysis: counts, reading time, and top keywords',
    category: 'text',
    secondary: ['images-files'],
    keywords: ['document', 'analyze', 'analyse', 'analyser', 'analyzer', 'text', 'file', 'read', 'keywords', 'nlp', 'word count', 'reading time', 'stats'],
    synonyms: ['text file stats', 'file reader'],
    intents: ['analyse a text file', 'read a txt file', 'word frequency', 'file statistics'],
    related: ['word-counter', 'text-diff'],
    accepts: ['text', 'markdown', 'csv', 'json'],
    produces: ['markdown', 'text'],
    weight: 40,
    icon: svg('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/>'),
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two text blocks and highlight additions & deletions',
    category: 'text',
    secondary: ['developer'],
    keywords: ['diff', 'difference', 'compare', 'comparison', 'text diff', 'changes', 'checker', 'dff', 'line diff', 'git diff', 'what changed', 'additions'],
    synonyms: ['compare text', 'difference checker', 'file compare'],
    intents: ['compare two texts', 'what changed', 'diff two versions', 'spot the difference'],
    related: ['word-counter', 'find-replace'],
    accepts: ['text', 'json', 'csv', 'code', 'markdown'],
    weight: 70,
    icon: svg('<path d="M16 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8z"/><path d="M15 3v5h5"/><path d="M9 12h6"/><path d="M12 9v6"/>'),
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, beautify, minify, and validate JSON data',
    category: 'developer',
    secondary: ['text'],
    keywords: ['json', 'jso', 'josn', 'format', 'beautify', 'minify', 'validate', 'parser', 'prettify', 'json lint', 'parse json', 'beautifier', 'object'],
    synonyms: ['json beautifier', 'json validator', 'json pretty print', 'json linter'],
    intents: ['format this json', 'prettify json', 'validate json', 'fix my json', 'minify json', 'json is invalid'],
    related: ['csv-to-json', 'base64-codec', 'regex-tester'],
    accepts: ['json'],
    produces: ['json'],
    weight: 92,
    icon: svg('<path d="M9 3H7a2 2 0 0 0-2 2v3c0 1.1-.9 2-2 2 1.1 0 2 .9 2 2v3a2 2 0 0 0 2 2h2"/><path d="M15 3h2a2 2 0 0 1 2 2v3c0 1.1.9 2 2 2-1.1 0-2 .9-2 2v3a2 2 0 0 1-2 2h-2"/>'),
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV table data into a JSON array',
    category: 'developer',
    secondary: ['text'],
    keywords: ['csv', 'json', 'convert', 'data', 'table', 'spreadsheet', 'excel', 'export', 'import', 'comma separated', 'parse csv'],
    synonyms: ['csv converter', 'spreadsheet to json'],
    intents: ['csv to json', 'convert csv', 'turn a spreadsheet into json', 'parse csv'],
    related: ['json-formatter', 'remove-duplicates'],
    accepts: ['csv'],
    produces: ['json'],
    weight: 74,
    icon: svg('<rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="9" y1="21" x2="9" y2="9"/>'),
  },
  {
    id: 'base64-codec',
    name: 'Base64 Codec',
    description: 'Encode and decode UTF-8 text to/from Base64',
    category: 'developer',
    secondary: ['security'],
    keywords: ['base64', 'b64', 'encode', 'decode', 'codec', 'converter', 'string', 'utf8', 'binary', 'text format'],
    synonyms: ['base64 encoder', 'base64 decoder', 'b64'],
    intents: ['encode base64', 'decode base64', 'base64 to text', 'text to base64'],
    related: ['url-codec', 'hash-generator', 'jwt-decoder'],
    accepts: ['text'],
    produces: ['text'],
    weight: 76,
    icon: svg('<path d="M3 8h14M7 4l-4 4 4 4"/><path d="M21 16H7M17 12l4 4-4 4"/>'),
  },
  {
    id: 'url-codec',
    name: 'URL Codec',
    description: 'Encode and decode URLs and query components',
    category: 'developer',
    keywords: ['url', 'uri', 'encode', 'decode', 'urlencode', 'urldecode', 'escape', 'percent encoding', 'link', 'web link', 'query param'],
    synonyms: ['percent encoding', 'url encoder', 'url decoder', 'uri encode'],
    intents: ['encode a url', 'decode url', 'escape query string', 'percent encode'],
    related: ['base64-codec', 'net-url-analyzer', 'slug-generator'],
    accepts: ['text'],
    produces: ['text'],
    weight: 64,
    icon: svg('<path d="M10 14a5 5 0 0 0 7.07 0l2.83-2.83a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 10a5 5 0 0 0-7.07 0L4.1 12.83a5 5 0 0 0 7.07 7.07l1.71-1.71"/>'),
  },
  {
    id: 'html-entity-codec',
    name: 'HTML Entity Codec',
    description: 'Escape and unescape HTML special characters',
    category: 'developer',
    secondary: ['text'],
    keywords: ['html', 'entity', 'entities', 'escape', 'unescape', 'special characters', 'sanitize', 'html code', 'tags', 'encode'],
    synonyms: ['html escape', 'html entities', 'htmlspecialchars'],
    intents: ['escape html', 'decode html entities', 'convert special characters'],
    related: ['url-codec', 'markdown-preview'],
    accepts: ['text', 'html'],
    produces: ['text'],
    weight: 44,
    icon: svg('<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>'),
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Inspect and decode JSON Web Tokens header, payload & expiry',
    category: 'developer',
    secondary: ['security'],
    keywords: ['jwt', 'token', 'auth', 'bearer', 'decode', 'jsonwebtoken', 'header', 'payload', 'claims', 'expiration', 'authentication', 'security token'],
    synonyms: ['json web token', 'jwt parser', 'token decoder'],
    intents: ['decode a jwt', 'read token claims', 'check token expiry', 'inspect bearer token'],
    related: ['base64-codec', 'hash-generator'],
    accepts: ['text'],
    produces: ['json'],
    weight: 68,
    icon: svg('<rect x="3" y="11" width="18" height="10" rx="2"/><circle cx="12" cy="16" r="1"/>'),
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with instant visual match highlighting',
    category: 'developer',
    secondary: ['text'],
    keywords: ['regex', 'regx', 'regexp', 'regular expression', 'test', 'tester', 'matcher', 'pattern', 'find', 'validate regex', 'expression'],
    synonyms: ['regexp tester', 'regular expression', 'pattern matcher'],
    intents: ['test a regex', 'build a regular expression', 'match pattern', 'why does my regex not work'],
    related: ['find-replace', 'json-formatter'],
    weight: 80,
    icon: svg('<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.35-4.35"/><path d="M8 11h.01M11 11h.01M14 11h.01"/>'),
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-1, SHA-256, SHA-384, and SHA-512 cryptographic hashes',
    category: 'developer',
    secondary: ['security'],
    keywords: ['hash', 'sha', 'sha256', 'sha512', 'sha1', 'crypto', 'checksum', 'digest', 'generator', 'encrypt', 'security', 'md5'],
    synonyms: ['checksum', 'md5', 'sha256', 'sha1', 'digest'],
    intents: ['hash a string', 'generate sha256', 'md5 of text', 'make a checksum'],
    related: ['password-generator', 'base64-codec', 'uuid-generator'],
    weight: 70,
    icon: svg('<path d="M4 9h16"/><path d="M4 15h16"/><path d="M10 3l-2 18"/><path d="M16 3l-2 18"/>'),
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate bulk cryptographically secure v4 UUIDs',
    category: 'developer',
    secondary: ['security'],
    keywords: ['uuid', 'guid', 'v4', 'unique id', 'generator', 'random id', 'key', 'identifiers', 'generate id'],
    synonyms: ['guid', 'unique id', 'uuid v4'],
    intents: ['generate a uuid', 'random id', 'make guids', 'bulk unique ids'],
    related: ['random-number', 'hash-generator', 'password-generator'],
    produces: ['text'],
    weight: 66,
    icon: svg('<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>'),
  },
  {
    id: 'cron-parser',
    name: 'Cron Parser',
    description: 'Read a cron schedule in plain English and see when it next runs',
    category: 'developer',
    keywords: ['cron', 'crontab', 'schedule', 'parser', 'time', 'task', 'job', 'interval', 'timer', 'frequency', 'explain cron'],
    synonyms: ['crontab', 'cron expression', 'schedule syntax'],
    intents: ['what does this cron mean', 'explain crontab', 'when does this cron run', 'build a cron schedule'],
    related: ['timestamp-converter', 'business-days'],
    accepts: ['text'],
    produces: ['text'],
    weight: 50,
    icon: svg('<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>'),
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    category: 'developer',
    secondary: ['numbers'],
    keywords: ['timestamp', 'time', 'unix', 'epoch', 'date', 'datetime', 'clock', 'converter', 'tmes', 'stamp', 'milliseconds', 'timezone'],
    synonyms: ['unix time', 'epoch converter', 'iso date'],
    intents: ['convert unix timestamp', 'epoch to date', 'date to timestamp', 'what time is this epoch'],
    related: ['business-days', 'cron-parser'],
    weight: 72,
    icon: svg('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/>'),
  },
  {
    id: 'number-base-converter',
    name: 'Number Base',
    description: 'Convert numbers across Binary, Octal, Decimal, and Hexadecimal',
    category: 'developer',
    secondary: ['numbers'],
    keywords: ['number', 'base', 'binary', 'octal', 'decimal', 'hex', 'hexadecimal', 'radix', 'converter', 'bin', 'dec', 'math', 'system'],
    synonyms: ['radix', 'hex converter', 'binary converter', 'base 16'],
    intents: ['decimal to binary', 'hex to decimal', 'convert to octal', 'binary to hex'],
    related: ['color-converter', 'hash-generator'],
    weight: 58,
    icon: svg('<path d="M6 6v12M4 6h4M4 18h4"/><circle cx="16" cy="8" r="3.5"/><circle cx="16" cy="17" r="3.5"/>'),
  },
  {
    id: 'code-playground',
    name: 'Code Playground',
    description: 'Write and run JavaScript, TypeScript, Python, and SQL — no install, runs in your browser',
    category: 'developer',
    keywords: ['code', 'compiler', 'interpreter', 'run code', 'playground', 'repl', 'ide', 'editor', 'javascript', 'js', 'typescript', 'ts', 'python', 'py', 'sql', 'sqlite', 'execute', 'compile', 'programming', 'coding', 'sandbox', 'online compiler', 'student', 'practice', 'exercise', 'script'],
    synonyms: ['online compiler', 'repl', 'code runner', 'sandbox', 'interpreter'],
    intents: ['run python in browser', 'test javascript', 'run sql', 'try code without installing', 'online ide'],
    related: ['json-formatter', 'regex-tester'],
    accepts: ['code'],
    produces: ['code'],
    weight: 84,
    offline: false,   // runtimes are downloaded on first use
    icon: svg('<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>'),
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Shrink JPEG, PNG and WebP files with a live quality preview',
    category: 'images-files',
    keywords: ['image', 'compress', 'compressor', 'shrink', 'reduce', 'optimise', 'optimize', 'size', 'photo', 'picture', 'jpeg', 'jpg', 'png', 'webp', 'quality', 'smaller', 'file size', 'upload limit'],
    synonyms: ['shrink image', 'reduce file size', 'optimise image', 'optimize image'],
    intents: ['compress photo', 'make image smaller', 'reduce photo size', 'image too large to upload', 'compress png', 'shrink jpg'],
    related: ['image-converter', 'image-resizer', 'image-metadata'],
    weight: 96,
    icon: svg('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 12h8"/><path d="M12 8l-4 4 4 4"/><path d="M12 8l4 4-4 4"/>'),
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert between PNG, JPEG, WebP and AVIF without uploading anything',
    category: 'images-files',
    keywords: ['image', 'convert', 'converter', 'format', 'png', 'jpg', 'jpeg', 'webp', 'avif', 'gif', 'bmp', 'heic', 'change format', 'transcode'],
    synonyms: ['change image format', 'image format converter'],
    intents: ['png to webp', 'jpg to png', 'webp to jpg', 'heic to jpg', 'convert image format', 'png to jpg'],
    related: ['image-compressor', 'image-resizer', 'image-to-pdf'],
    weight: 94,
    icon: svg('<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/>'),
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize by pixels or percentage, with the aspect ratio locked if you want',
    category: 'images-files',
    secondary: ['design'],
    keywords: ['image', 'resize', 'resizer', 'scale', 'dimensions', 'width', 'height', 'pixels', 'thumbnail', 'shrink', 'enlarge', 'photo'],
    synonyms: ['scale image', 'change dimensions'],
    intents: ['resize an image', 'change image dimensions', 'make thumbnail', 'resize for instagram', 'scale photo down'],
    related: ['image-cropper', 'image-compressor', 'aspect-ratio'],
    weight: 88,
    icon: svg('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M15 9h-6v6"/><path d="M9 9l6 6"/>'),
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop to a selection or a fixed ratio, straight in the browser',
    category: 'images-files',
    secondary: ['design'],
    keywords: ['image', 'crop', 'cropper', 'trim', 'cut', 'square', 'ratio', 'photo', 'framing', 'aspect'],
    synonyms: ['trim image', 'cut image'],
    intents: ['crop a photo', 'cut out part of an image', 'crop to square', 'trim edges'],
    related: ['image-resizer', 'aspect-ratio', 'image-compressor'],
    weight: 80,
    icon: svg('<path d="M6 2v14a2 2 0 0 0 2 2h14"/><path d="M18 22V8a2 2 0 0 0-2-2H2"/>'),
  },
  {
    id: 'image-metadata',
    name: 'Image Metadata',
    description: 'See what EXIF data a photo carries — including GPS — and strip it out',
    category: 'images-files',
    secondary: ['security'],
    keywords: ['image', 'metadata', 'exif', 'gps', 'location', 'privacy', 'strip', 'remove', 'camera', 'photo', 'geotag', 'clean'],
    synonyms: ['exif viewer', 'exif remover', 'strip metadata'],
    intents: ['remove metadata from image', 'strip exif', 'does my photo have gps', 'view exif data', 'remove location from photo'],
    related: ['image-compressor', 'image-converter'],
    weight: 82,
    icon: svg('<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="12" cy="10" r="2.5"/><path d="M12 14v4"/><path d="M9 18h6"/>'),
  },
  {
    id: 'watermark-remover',
    name: 'AI Watermark Remover',
    description: 'Erase unwanted text, stamps and watermarks with smart content-aware fill',
    category: 'images-files',
    secondary: ['design'],
    keywords: ['watermark', 'watermark remover', 'remove watermark', 'erase text', 'clean photo', 'stamp remover', 'text removal', 'inpainting', 'retouch', 'photo clean', 'remove logo', 'unwanted text', 'image clean'],
    synonyms: ['erase watermark', 'remove text from photo', 'photo retouch', 'watermark eraser'],
    intents: ['remove watermark', 'erase text from image', 'remove stamp from photo', 'clean text off image', 'retouch watermark'],
    related: ['image-compressor', 'image-cropper', 'image-resizer'],
    weight: 85,
    icon: svg('<path d="M12 19l7-7 3 3-7 7-3-3z"/><path d="M18 13l-1.5-7.5L2 2l3.5 14.5L13 18l5-5z"/><path d="M2 2l7.586 7.586"/><circle cx="11" cy="11" r="2"/>'),
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Turn photos into a single PDF with page size and orientation control',
    category: 'images-files',
    keywords: ['image', 'pdf', 'convert', 'jpg to pdf', 'png to pdf', 'photos', 'scan', 'document', 'combine', 'pages'],
    synonyms: ['photos to pdf', 'jpg to pdf', 'png to pdf'],
    intents: ['image to pdf', 'combine photos into a pdf', 'scan to pdf', 'jpg to pdf'],
    related: ['pdf-merge', 'image-converter', 'pdf-split'],
    weight: 86,
    icon: svg('<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/><path d="M14 21h7v-7"/>'),
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine several PDFs into one and reorder the pages',
    category: 'images-files',
    keywords: ['pdf', 'merge', 'combine', 'join', 'append', 'concatenate', 'documents', 'reorder', 'one file'],
    synonyms: ['combine pdf', 'join pdf', 'pdf combiner'],
    intents: ['merge pdfs', 'combine two pdfs', 'join pdf files into one', 'append pdf'],
    related: ['pdf-split', 'image-to-pdf'],
    weight: 90,
    icon: svg('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M12 18v-6"/><path d="M9 15h6"/>'),
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    description: 'Extract, delete or rotate pages and save the result',
    category: 'images-files',
    keywords: ['pdf', 'split', 'extract', 'pages', 'separate', 'delete pages', 'rotate', 'page range', 'divide'],
    synonyms: ['extract pdf pages', 'separate pdf', 'pdf splitter'],
    intents: ['split a pdf', 'extract pages from pdf', 'delete pdf pages', 'rotate pdf pages', 'take one page out of a pdf'],
    related: ['pdf-merge', 'image-to-pdf'],
    weight: 88,
    icon: svg('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M8 15h8"/>'),
  },
  {
    id: 'pdf-editor',
    name: 'PDF Editor',
    description: 'Annotate, highlight, draw on and convert PDFs — add text, images and shapes',
    category: 'images-files',
    keywords: ['pdf', 'editor', 'edit', 'annotate', 'annotation', 'highlight', 'draw', 'text', 'sign', 'markup', 'redact', 'comment', 'convert', 'docx', 'word', 'excel', 'pptx', 'powerpoint'],
    synonyms: ['pdf annotator', 'pdf markup', 'edit pdf', 'pdf converter'],
    intents: ['edit a pdf', 'annotate a pdf', 'add text to pdf', 'highlight pdf', 'draw on pdf', 'convert pdf to word', 'pdf to docx', 'pdf to excel', 'pdf to powerpoint', 'pdf to pptx', 'sign a pdf'],
    related: ['pdf-merge', 'pdf-split', 'image-to-pdf'],
    accepts: ['markdown', 'text'],
    produces: ['markdown', 'text'],
    weight: 92,
    icon: svg('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M16 13H8"/><path d="M16 17H8"/><path d="M10 9H8"/>'),
  },
  {
    id: 'calculator',
    name: 'Calculator',
    description: 'Universal calculating engine for standard, scientific, programmer, financial, engineering, graphing, RPN and statistics',
    category: 'numbers',
    secondary: ['developer', 'business', 'science'],
    keywords: ['calculator', 'calc', 'scientific calculator', 'programmer calculator', 'financial calculator', 'tvm', 'math', 'arithmetic', 'algebra', 'graphing calculator', 'rpn', 'complex numbers', 'matrices', 'vectors', 'statistics', 'derivatives', 'integrals'],
    synonyms: ['scientific calc', 'math solver', 'ti-84', 'hp-12c', 'programmer calc', 'rpn calculator'],
    intents: ['calculate', 'solve equation', 'scientific math', 'hex dec converter', 'time value of money', 'plot function', 'rpn stack', 'matrix determinant'],
    related: ['percentage-calculator', 'unit-converter', 'number-base-converter'],
    weight: 98,
    icon: svg('<rect x="4" y="2" width="16" height="20" rx="2"/><line x1="8" y1="6" x2="16" y2="6"/><line x1="16" y1="14" x2="16" y2="18"/><path d="M16 10h.01"/><path d="M12 10h.01"/><path d="M8 10h.01"/><path d="M12 14h.01"/><path d="M8 14h.01"/><path d="M12 18h.01"/><path d="M8 18h.01"/>'),
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, increases, and decreases easily',
    category: 'numbers',
    secondary: ['business'],
    keywords: ['percent', 'percentage', 'math', 'calculator', 'calc', 'increase', 'decrease', 'fraction', 'discount', 'tax'],
    synonyms: ['percent calculator', 'percent change'],
    intents: ['what percent is', 'percentage increase', 'work out a discount', 'percentage difference'],
    related: ['margin-markup', 'vat-calculator', 'unit-converter'],
    weight: 82,
    icon: svg('<line x1="19" y1="5" x2="5" y2="19"/><circle cx="6.5" cy="6.5" r="2.5"/><circle cx="17.5" cy="17.5" r="2.5"/>'),
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert length, weight, temperature and digital storage',
    category: 'numbers',
    keywords: ['unit', 'units', 'convert', 'converter', 'length', 'weight', 'mass', 'metric', 'imperial', 'digital', 'temperature', 'celsius', 'fahrenheit', 'kelvin', 'mb', 'gb', 'km', 'miles', 'lbs', 'kilograms', 'stone', 'inches', 'cm'],
    synonyms: ['measurement converter', 'metric converter', 'imperial'],
    intents: ['convert kg to lbs', 'cm to inches', 'celsius to fahrenheit', 'miles to km', 'convert units'],
    related: ['number-base-converter', 'percentage-calculator', 'aspect-ratio'],
    weight: 90,
    icon: svg('<path d="M12 3v18M3 12h18"/>'),
  },
  {
    id: 'random-number',
    name: 'Random Number',
    description: 'Generate single or multiple unique random numbers',
    category: 'numbers',
    keywords: ['random', 'number', 'rng', 'rand', 'dice', 'roll', 'generate number', 'randomizer', 'picker'],
    synonyms: ['rng', 'dice roller', 'number picker'],
    intents: ['pick a random number', 'roll dice', 'random pick', 'draw a winner'],
    related: ['uuid-generator', 'password-generator'],
    weight: 62,
    icon: svg('<path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"/><path d="M12 12v9"/>'),
  },
  {
    id: 'business-days',
    name: 'Business Days Calculator',
    description: 'Count working days between dates, or find a deadline N working days out',
    category: 'numbers',
    secondary: ['business'],
    keywords: ['business days', 'working days', 'weekdays', 'deadline', 'date', 'calculator', 'sla', 'due date', 'holidays', 'workdays', 'between dates', 'project', 'schedule', 'delivery'],
    synonyms: ['working days', 'date difference', 'days between dates', 'age calculator'],
    intents: ['days between two dates', 'working days until', 'deadline date', 'how old am i', 'add days to a date'],
    related: ['timestamp-converter', 'pto-accrual'],
    weight: 76,
    icon: svg('<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 10h18"/><path d="M8 4V2"/><path d="M16 4V2"/><path d="M8 14h.01"/><path d="M12 14h.01"/><path d="M16 14h.01"/><path d="M8 18h.01"/><path d="M12 18h.01"/>'),
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert color values seamlessly between HEX, RGB, and HSL',
    category: 'design',
    secondary: ['developer'],
    keywords: ['color', 'colour', 'clor', 'hex', 'rgb', 'hsl', 'converter', 'swatch', 'picker', 'palette', 'convert color', 'css color'],
    synonyms: ['hex to rgb', 'rgb to hex', 'hsl converter', 'colour converter'],
    intents: ['hex to rgb', 'convert a colour', 'rgb to hsl', 'what is this hex code', 'contrast check'],
    related: ['color-palette-generator', 'number-base-converter'],
    weight: 84,
    icon: svg('<circle cx="12" cy="12" r="9"/>'),
  },
  {
    id: 'color-palette-generator',
    name: 'Color Palette',
    description: 'Generate beautiful random color palettes instantly',
    category: 'design',
    keywords: ['color', 'palette', 'colours', 'generator', 'random colors', 'hex', 'scheme', 'theme', 'design', 'swatches'],
    synonyms: ['colour palette', 'swatches', 'colour scheme'],
    intents: ['generate a colour palette', 'find matching colours', 'random palette', 'brand colours'],
    related: ['color-converter', 'aspect-ratio'],
    weight: 70,
    icon: svg('<circle cx="12" cy="12" r="9"/><path d="M12 3v18"/><path d="M3 12h18"/>'),
  },
  {
    id: 'aspect-ratio',
    name: 'Aspect Ratio',
    description: 'Calculate aspect ratios and rescale image/video dimensions',
    category: 'design',
    secondary: ['images-files', 'numbers'],
    keywords: ['aspect', 'ratio', 'resolution', 'dimension', 'width', 'height', 'scale', 'rescale', '16:9', '4:3', 'image size', 'video size', 'calculate'],
    synonyms: ['ratio calculator', 'resolution calculator'],
    intents: ['work out aspect ratio', 'resize keeping ratio', '16:9 dimensions', 'what height for this width'],
    related: ['image-resizer', 'unit-converter'],
    weight: 60,
    icon: svg('<rect x="2" y="4" width="20" height="16" rx="2"/>'),
  },
  {
    id: 'qr-generator',
    name: 'QR Generator',
    description: 'Generate customizable QR codes with PNG download',
    category: 'design',
    secondary: ['everyday'],
    keywords: ['qr', 'qrcode', 'qr code', 'barcode', 'generator', 'make qr', 'download qr', 'url qr', 'scan'],
    synonyms: ['qr code', 'barcode'],
    intents: ['make a qr code', 'qr code for a link', 'qr for wifi', 'download qr code'],
    related: ['url-codec', 'image-converter'],
    weight: 88,
    icon: svg('<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="15" y="15" width="2" height="2"/><rect x="19" y="15" width="2" height="2"/><rect x="15" y="19" width="2" height="2"/><rect x="19" y="19" width="2" height="2"/>'),
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Create strong passwords with length control & strength meter',
    category: 'security',
    secondary: ['developer'],
    keywords: ['password', 'pasword', 'pwd', 'pass', 'sec', 'secret', 'generator', 'strong password', 'entropy', 'random password', 'generate pass', 'key maker'],
    synonyms: ['passphrase', 'random password', 'strong password'],
    intents: ['generate a strong password', 'random passphrase', 'secure password', 'make a password'],
    related: ['hash-generator', 'uuid-generator', 'random-number'],
    weight: 92,
    icon: svg('<rect x="5" y="11" width="14" height="10" rx="1"/><path d="M8 11V7a4 4 0 1 1 8 0v4"/>'),
  },
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Build a professional invoice with line items and tax, then print or save as PDF',
    category: 'business',
    keywords: ['invoice', 'bill', 'billing', 'receipt', 'quote', 'estimate', 'line items', 'client', 'freelance', 'accounting', 'pdf', 'print', 'tax', 'vat', 'payment', 'due', 'business'],
    synonyms: ['bill', 'billing', 'receipt maker'],
    intents: ['create an invoice', 'make a bill for a client', 'invoice pdf', 'send an invoice'],
    related: ['vat-calculator', 'timesheet', 'margin-markup'],
    accepts: ['json'],
    produces: ['json'],
    weight: 88,
    icon: svg('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M8 13h8"/><path d="M8 17h5"/>'),
  },
  {
    id: 'vat-calculator',
    name: 'VAT & Sales Tax',
    description: 'Add or strip tax from any amount, with reverse calculation and multi-rate support',
    category: 'business',
    secondary: ['numbers'],
    keywords: ['vat', 'sales tax', 'tax', 'gst', 'hst', 'value added tax', 'add tax', 'remove tax', 'net', 'gross', 'inclusive', 'exclusive', 'reverse vat', 'percentage', 'accounting'],
    synonyms: ['sales tax', 'gst', 'tax calculator'],
    intents: ['add vat', 'remove vat from a price', 'work out sales tax', 'price excluding tax'],
    related: ['percentage-calculator', 'margin-markup', 'invoice-generator'],
    weight: 80,
    icon: svg('<path d="M9 14l6-6"/><circle cx="9.5" cy="8.5" r="1.5"/><circle cx="14.5" cy="14.5" r="1.5"/><rect x="3" y="3" width="18" height="18" rx="3"/>'),
  },
  {
    id: 'margin-markup',
    name: 'Margin & Markup',
    description: 'Convert between cost, price, margin and markup — and price a product properly',
    category: 'business',
    secondary: ['numbers'],
    keywords: ['margin', 'markup', 'gross margin', 'profit margin', 'cost', 'price', 'pricing', 'selling price', 'discount', 'retail', 'wholesale', 'profit', 'sales', 'accounting'],
    synonyms: ['profit margin', 'markup calculator', 'pricing'],
    intents: ['work out profit margin', 'what price to sell at', 'markup vs margin', 'price a product'],
    related: ['break-even', 'vat-calculator', 'percentage-calculator'],
    weight: 78,
    icon: svg('<path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><line x1="7" y1="7" x2="7.01" y2="7"/>'),
  },
  {
    id: 'break-even',
    name: 'Break-Even Analysis',
    description: 'Find the units and revenue where you stop losing money, with a visual break-even chart',
    category: 'business',
    keywords: ['break even', 'breakeven', 'break-even', 'fixed costs', 'variable costs', 'contribution margin', 'units', 'profit', 'loss', 'analysis', 'pricing', 'business plan', 'startup', 'margin of safety'],
    synonyms: ['breakeven point', 'contribution margin'],
    intents: ['when do i break even', 'how many units to sell', 'fixed and variable costs'],
    related: ['margin-markup', 'unit-economics', 'runway-calculator'],
    weight: 68,
    icon: svg('<path d="M3 3v18h18"/><path d="M6 18L20 6"/><path d="M6 8l14 10"/>'),
  },
  {
    id: 'amortization-schedule',
    name: 'Amortization Schedule',
    description: 'Full payment-by-payment loan breakdown with extra payments and interest saved',
    category: 'business',
    secondary: ['numbers'],
    keywords: ['amortization', 'amortisation', 'schedule', 'loan', 'mortgage', 'payment', 'principal', 'interest', 'table', 'extra payment', 'payoff', 'balance', 'monthly payment', 'debt'],
    synonyms: ['loan calculator', 'mortgage calculator', 'repayment schedule', 'amortisation'],
    intents: ['loan repayment schedule', 'monthly mortgage payment', 'how much interest will i pay', 'pay off loan early', 'car loan'],
    related: ['compound-interest', 'npv-irr'],
    weight: 84,
    icon: svg('<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 10h18"/><path d="M8 4V2"/><path d="M16 4V2"/><path d="M8 14h3"/><path d="M8 18h3"/>'),
  },
  {
    id: 'compound-interest',
    name: 'Compound Interest',
    description: 'Calculate investment growth over time with monthly contributions',
    category: 'business',
    secondary: ['numbers'],
    keywords: ['finance', 'compound', 'interest', 'investment', 'growth', 'calculator', 'money', 'stock', 'returns', 'yield', 'savings'],
    synonyms: ['savings calculator', 'interest calculator', 'investment growth'],
    intents: ['compound interest', 'how much will my savings grow', 'future value', 'investment return'],
    related: ['amortization-schedule', 'npv-irr'],
    weight: 74,
    icon: svg('<path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>'),
  },
  {
    id: 'npv-irr',
    name: 'NPV, IRR & Payback',
    description: 'Evaluate an investment: net present value, internal rate of return, and payback period',
    category: 'business',
    keywords: ['npv', 'irr', 'payback', 'net present value', 'internal rate of return', 'discount rate', 'cash flow', 'investment', 'roi', 'capital budgeting', 'project', 'valuation', 'finance', 'wacc', 'dcf'],
    synonyms: ['discounted cash flow', 'dcf', 'payback period', 'roi'],
    intents: ['net present value', 'internal rate of return', 'is this investment worth it', 'discount cash flows'],
    related: ['compound-interest', 'unit-economics', 'break-even'],
    weight: 58,
    icon: svg('<path d="M12 1v22"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>'),
  },
  {
    id: 'depreciation-calculator',
    name: 'Depreciation Schedule',
    description: 'Straight-line, declining balance, and sum-of-years depreciation with a full yearly table',
    category: 'business',
    keywords: ['depreciation', 'asset', 'assets', 'straight line', 'declining balance', 'double declining', 'sum of years', 'syd', 'book value', 'salvage', 'useful life', 'accounting', 'fixed assets', 'capex', 'writedown', 'amortize', 'tax'],
    synonyms: ['asset depreciation', 'straight line', 'declining balance'],
    intents: ['depreciate an asset', 'book value schedule', 'straight line depreciation', 'writing down an asset'],
    related: ['amortization-schedule', 'financial-analyzer'],
    weight: 54,
    icon: svg('<path d="M3 3v18h18"/><polyline points="7 8 11 12 15 9 21 15"/>'),
  },
  {
    id: 'cap-table',
    name: 'Cap Table & Dilution',
    description: 'Model ownership across funding rounds and see exactly who gets diluted',
    category: 'business',
    keywords: ['cap table', 'capitalization table', 'equity', 'dilution', 'shares', 'ownership', 'founder', 'investor', 'seed', 'series a', 'safe', 'convertible', 'option pool', 'esop', 'valuation', 'startup', 'ceo', 'stake'],
    synonyms: ['equity table', 'dilution calculator', 'shareholding'],
    intents: ['model dilution', 'who owns what after a round', 'founder equity split', 'option pool'],
    related: ['runway-calculator', 'unit-economics'],
    weight: 52,
    icon: svg('<circle cx="12" cy="12" r="9"/><path d="M12 3v9l7 4.5"/>'),
  },
  {
    id: 'runway-calculator',
    name: 'Runway & Burn Rate',
    description: 'How many months of cash you have left, with growth and hiring factored in',
    category: 'business',
    keywords: ['runway', 'burn rate', 'burn', 'cash', 'months left', 'startup', 'founder', 'ceo', 'out of money', 'fundraising', 'net burn', 'gross burn', 'mrr', 'growth', 'hiring', 'cash flow'],
    synonyms: ['burn rate', 'cash runway'],
    intents: ['how long until we run out of money', 'monthly burn', 'cash runway', 'when do we need to raise'],
    related: ['cap-table', 'unit-economics', 'break-even'],
    weight: 60,
    icon: svg('<path d="M12 2l3 6 6 .9-4.5 4.2 1.1 6-5.6-3-5.6 3 1.1-6L3 8.9 9 8z"/>'),
  },
  {
    id: 'unit-economics',
    name: 'Unit Economics',
    description: 'CAC, LTV, payback period and the ratios investors will ask you about',
    category: 'business',
    keywords: ['unit economics', 'cac', 'ltv', 'clv', 'customer acquisition cost', 'lifetime value', 'churn', 'retention', 'arpu', 'payback', 'saas', 'metrics', 'growth', 'ceo', 'startup', 'ratio'],
    synonyms: ['cac ltv', 'customer acquisition cost', 'lifetime value'],
    intents: ['work out cac and ltv', 'is my saas profitable per customer', 'payback period per customer'],
    related: ['runway-calculator', 'break-even', 'npv-irr'],
    weight: 54,
    icon: svg('<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/>'),
  },
  {
    id: 'payroll-cost',
    name: 'Employee Cost Calculator',
    description: 'What a hire actually costs you once taxes, benefits and overhead are added',
    category: 'business',
    keywords: ['payroll', 'employee cost', 'salary', 'hire', 'hiring', 'benefits', 'employer tax', 'ni', 'national insurance', 'pension', 'overhead', 'fully loaded', 'headcount', 'hr', 'budget', 'total cost'],
    synonyms: ['employee cost', 'cost of hiring', 'fully loaded cost'],
    intents: ['what does an employee really cost', 'cost of a hire', 'employer taxes and benefits'],
    related: ['salary-converter', 'meeting-cost', 'timesheet'],
    weight: 62,
    icon: svg('<rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/>'),
  },
  {
    id: 'salary-converter',
    name: 'Salary Converter',
    description: 'Convert between hourly wages and annual salaries instantly',
    category: 'business',
    secondary: ['numbers'],
    keywords: ['salary', 'hourly', 'wage', 'income', 'pay', 'paycheck', 'converter', 'money', 'job', 'work', 'annual'],
    synonyms: ['hourly to annual', 'wage converter', 'pay rate'],
    intents: ['hourly rate to salary', 'annual to monthly pay', 'what is my hourly rate', 'day rate'],
    related: ['payroll-cost', 'timesheet'],
    weight: 72,
    icon: svg('<rect x="2" y="6" width="20" height="12" rx="2"/><path d="M12 12h.01M17 12h.01M7 12h.01"/>'),
  },
  {
    id: 'meeting-cost',
    name: 'Meeting Cost Calculator',
    description: 'Live counter showing what this meeting is costing the company right now',
    category: 'business',
    keywords: ['meeting', 'cost', 'time', 'salary', 'waste', 'productivity', 'attendees', 'hourly rate', 'timer', 'stopwatch', 'burn', 'office', 'corporate', 'ceo', 'manager'],
    synonyms: ['cost of a meeting', 'time cost'],
    intents: ['what is this meeting costing', 'cost of everyone in the room'],
    related: ['payroll-cost', 'timesheet'],
    weight: 56,
    icon: svg('<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>'),
  },
  {
    id: 'timesheet',
    name: 'Timesheet & Billables',
    description: 'Log hours by task and rate, then total up what to invoice',
    category: 'business',
    keywords: ['timesheet', 'time sheet', 'billable', 'hours', 'tracking', 'consultant', 'freelance', 'rate', 'invoice', 'logging', 'work', 'project', 'client', 'timekeeping', 'utilization'],
    synonyms: ['billable hours', 'time tracking', 'hours log'],
    intents: ['log billable hours', 'what to invoice a client', 'track project hours'],
    related: ['invoice-generator', 'salary-converter', 'payroll-cost'],
    produces: ['csv'],
    weight: 64,
    icon: svg('<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 10h18"/><path d="M8 4V2"/><path d="M16 4V2"/><path d="M12 14v3"/><path d="M12 14h3"/>'),
  },
  {
    id: 'pto-accrual',
    name: 'PTO & Leave Tracker',
    description: 'Track accrued holiday, days taken, and what balance is left',
    category: 'business',
    keywords: ['pto', 'paid time off', 'holiday', 'vacation', 'leave', 'accrual', 'annual leave', 'days off', 'balance', 'hr', 'sick days', 'carryover', 'entitlement', 'tracker'],
    synonyms: ['annual leave', 'holiday tracker', 'vacation balance'],
    intents: ['how much holiday do i have left', 'track annual leave', 'accrued vacation'],
    related: ['business-days', 'timesheet'],
    weight: 50,
    icon: svg('<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 10h18"/><path d="M8 4V2"/><path d="M16 4V2"/><polyline points="9 15 11 17 15 13"/>'),
  },
  {
    id: 'subscription-analyzer',
    name: 'Cost Analyzer',
    description: 'See how much recurring expenses drain from you over a decade',
    category: 'business',
    secondary: ['everyday'],
    keywords: ['subscription', 'cost', 'recurring', 'expense', 'analyzer', 'analyser', 'finance', 'money', 'drain', 'coffee', 'streaming', 'budget'],
    synonyms: ['recurring costs', 'subscription tracker'],
    intents: ['what am i spending on subscriptions', 'annual cost of my subscriptions', 'cancel unused subscriptions'],
    related: ['compound-interest', 'currency-exchange'],
    weight: 58,
    icon: svg('<path d="M22 12h-4l-3 9L9 3l-3 9H2"/>'),
  },
  {
    id: 'financial-analyzer',
    name: 'Financial Analyzer',
    description: 'A plain-English spreadsheet for analyzing transactions without formulas',
    category: 'business',
    keywords: ['spreadsheet', 'excel', 'finance', 'table', 'grid', 'analyzer', 'analyser', 'dashboard', 'transactions', 'money', 'csv'],
    synonyms: ['spreadsheet', 'financial model'],
    intents: ['build a small financial model', 'spreadsheet with formulas', 'run the numbers'],
    related: ['npv-irr', 'depreciation-calculator', 'break-even'],
    weight: 46,
    icon: svg('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M3 15h18M9 3v18M15 3v18"/>'),
  },
  {
    id: 'email-signature',
    name: 'Email Signature Builder',
    description: 'Design a clean corporate email signature and copy it straight into your mail client',
    category: 'business',
    secondary: ['design'],
    keywords: ['email signature', 'signature', 'sign off', 'outlook', 'gmail', 'html signature', 'corporate', 'branding', 'contact', 'footer', 'professional', 'business card', 'builder'],
    synonyms: ['signature builder', 'email footer'],
    intents: ['make an email signature', 'html signature for outlook', 'professional email footer'],
    related: ['invoice-generator', 'qr-generator'],
    weight: 54,
    icon: svg('<rect x="2" y="4" width="20" height="16" rx="2"/><path d="M22 7l-10 6L2 7"/>'),
  },
  {
    id: 'currency-exchange',
    name: 'Currency Exchange',
    description: 'Real-time global currency exchange rates',
    category: 'business',
    secondary: ['everyday', 'numbers'],
    keywords: ['currency', 'money', 'exchange', 'forex', 'rates', 'usd', 'eur', 'ngn', 'conversion', 'realtime'],
    synonyms: ['exchange rate', 'forex', 'money converter'],
    intents: ['convert currency', 'usd to naira', 'exchange rate today', 'how much is this in pounds'],
    related: ['unit-converter', 'subscription-analyzer'],
    weight: 86,
    offline: false,
    icon: svg('<circle cx="12" cy="12" r="10"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 18V6"/>'),
  },
  {
    id: 'net-subnet',
    name: 'Subnet Calculator',
    description: 'Calculate Network, Broadcast, and Host Range from an IP/CIDR',
    category: 'networking',
    secondary: ['developer'],
    keywords: ['subnet', 'calculator', 'cidr', 'network', 'broadcast', 'host', 'ip', 'mask'],
    synonyms: ['cidr calculator', 'netmask', 'ip range', 'ipv6'],
    intents: ['calculate subnet', 'what is my network address', 'cidr to netmask', 'how many hosts in a /24', 'ipv4 to ipv6'],
    related: ['ip-lookup', 'net-url-analyzer'],
    weight: 74,
    icon: svg('<rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/>'),
  },
  {
    id: 'ip-lookup',
    name: 'IP Lookup',
    description: 'Instantly find your public IP address, ISP, and location',
    category: 'networking',
    keywords: ['ip', 'address', 'lookup', 'isp', 'location', 'network', 'internet', 'whois'],
    synonyms: ['geolocation', 'what is my ip', 'ip address info'],
    intents: ['what is my ip address', 'where is this ip', 'ip geolocation', 'who owns this ip'],
    related: ['net-subnet', 'net-dns-lookup', 'net-whois'],
    weight: 80,
    offline: false,
    icon: svg('<rect x="2" y="14" width="20" height="8" rx="2" ry="2"/><line x1="6" y1="18" x2="6" y2="18"/><line x1="10" y1="18" x2="10" y2="18"/><path d="M12 14V10"/><path d="M18 14V6"/><path d="M6 14V2"/>'),
  },
  {
    id: 'net-dns-lookup',
    name: 'DNS Lookup',
    description: 'Query DNS records (A, MX, TXT, CNAME) for any domain',
    category: 'networking',
    keywords: ['dns', 'lookup', 'records', 'domain', 'mx', 'txt', 'a', 'cname'],
    synonyms: ['dns records', 'nslookup', 'dig', 'mx record'],
    intents: ['look up dns records', 'find mx records', 'check a records', 'dns for a domain'],
    related: ['net-reverse-dns', 'net-whois', 'net-ssl-viewer'],
    weight: 66,
    offline: false,
    icon: svg('<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>'),
  },
  {
    id: 'net-reverse-dns',
    name: 'Reverse DNS Lookup',
    description: 'Resolve an IP address back to its hostname',
    category: 'networking',
    keywords: ['dns', 'reverse', 'ip', 'hostname', 'resolve', 'ptr'],
    synonyms: ['ptr record', 'reverse lookup'],
    intents: ['reverse dns lookup', 'what hostname is this ip', 'ptr record'],
    related: ['net-dns-lookup', 'ip-lookup'],
    weight: 44,
    offline: false,
    icon: svg('<path d="M21 2v6h-6"/><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M3 22v-6h6"/><path d="M21 12a9 9 0 0 1-15 6.7L3 16"/>'),
  },
  {
    id: 'net-whois',
    name: 'WHOIS Lookup',
    description: 'Find domain registration details, dates, and contacts',
    category: 'networking',
    keywords: ['whois', 'domain', 'lookup', 'registration', 'info', 'registrar'],
    synonyms: ['domain owner', 'registration lookup'],
    intents: ['who owns this domain', 'whois lookup', 'when does this domain expire'],
    related: ['net-domain-availability', 'net-dns-lookup'],
    weight: 58,
    offline: false,
    icon: svg('<circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/>'),
  },
  {
    id: 'net-domain-availability',
    name: 'Domain Availability',
    description: 'Check if a domain name is available for registration',
    category: 'networking',
    secondary: ['business'],
    keywords: ['domain', 'available', 'availability', 'register', 'check'],
    synonyms: ['domain checker', 'is domain taken'],
    intents: ['is this domain available', 'check domain name', 'find a free domain'],
    related: ['net-whois', 'net-dns-lookup'],
    weight: 62,
    offline: false,
    icon: svg('<circle cx="12" cy="12" r="10"/><polyline points="9 12 12 15 15 9"/>'),
  },
  {
    id: 'net-ssl-viewer',
    name: 'SSL Certificate Viewer',
    description: 'View SSL/TLS certificate details (issuer, expiry, validity)',
    category: 'networking',
    secondary: ['security'],
    keywords: ['ssl', 'tls', 'certificate', 'security', 'https', 'expiry', 'valid'],
    synonyms: ['certificate checker', 'tls', 'https certificate'],
    intents: ['check ssl certificate', 'when does my certificate expire', 'is https set up correctly'],
    related: ['net-dns-lookup', 'net-url-analyzer'],
    weight: 56,
    offline: false,
    icon: svg('<rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>'),
  },
  {
    id: 'net-url-analyzer',
    name: 'URL Analyzer',
    description: 'Parse and break down a URL into its raw components completely offline',
    category: 'networking',
    secondary: ['developer'],
    keywords: ['url', 'analyzer', 'analyser', 'parse', 'breakdown', 'uri', 'domain'],
    synonyms: ['url parser', 'query string parser', 'link inspector'],
    intents: ['break down a url', 'parse query parameters', 'what is in this link', 'inspect a url'],
    related: ['url-codec', 'net-subnet', 'net-sitemap'],
    weight: 60,
    icon: svg('<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>'),
  },
  {
    id: 'net-sitemap',
    name: 'Sitemap & Robots Viewer',
    description: 'Quickly view a site\\\'s robots.txt directives and search for sitemaps',
    category: 'networking',
    keywords: ['sitemap', 'robots.txt', 'seo', 'spider', 'crawler', 'viewer'],
    synonyms: ['robots.txt', 'seo crawler', 'sitemap viewer'],
    intents: ['check robots.txt', 'find a sitemap', 'is my site crawlable'],
    related: ['net-url-analyzer', 'net-dns-lookup'],
    weight: 42,
    offline: false,
    icon: svg('<rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="9" y1="21" x2="9" y2="9"/>'),
  },
  {
    id: 'net-mac-lookup',
    name: 'MAC Address Lookup',
    description: 'Identify the manufacturer/vendor of a MAC Address',
    category: 'networking',
    keywords: ['mac', 'address', 'lookup', 'vendor', 'manufacturer', 'oui', 'network'],
    synonyms: ['oui lookup', 'mac vendor', 'hardware address'],
    intents: ['what device is this mac address', 'mac address vendor', 'identify hardware'],
    related: ['ip-lookup', 'net-subnet'],
    weight: 40,
    offline: false,
    icon: svg('<rect x="2" y="4" width="20" height="16" rx="2"/><path d="M10 4v4"/><path d="M14 4v4"/><path d="M4 10h16"/><path d="M4 14h16"/>'),
  },
  {
    id: 'anatomy-explorer',
    name: 'Anatomy Explorer',
    description: '517 real anatomical structures in 3D — isolate systems, click to identify, slice through planes',
    category: 'modeling',
    keywords: ['anatomy', 'human body', 'body', 'medical', 'med school', 'medicine', 'skeleton', 'bones', 'organs', 'muscles', 'circulatory', 'nervous', 'respiratory', 'digestive', 'anatomical', '3d', 'model', 'modeler', 'physiology', 'biology', 'study', 'heart', 'lungs', 'brain', 'liver', 'kidney', 'ribcage', 'spine', 'skull', 'bodyparts3d', 'atlas', 'dissection', 'terminologia', 'fma', 'z-anatomy', 'cadaver', 'vertebra', 'femur', 'cerebellum', 'anatomy explorer'],
    synonyms: ['human body', 'anatomy atlas', '3d anatomy', 'body systems'],
    intents: ['look at human anatomy in 3d', 'find a bone', 'where is the liver', 'view the skeleton', 'identify a muscle'],
    related: ['container-planner'],
    task: 'lookup',
    weight: 70,
    icon: svg('<circle cx="12" cy="4.5" r="2.5"/><path d="M12 7v7"/><path d="M8 9h8"/><path d="M12 14l-2.5 7"/><path d="M12 14l2.5 7"/>'),
  },
  {
    id: 'container-planner',
    name: 'Container Quote Builder',
    description: 'Model a container or portacabin in 3D, then price the conversion into a printable client quotation',
    category: 'modeling',
    secondary: ['business'],
    keywords: ['container', 'portacabin', 'porta cabin', 'portakabin', 'shipping container', 'cabin', 'conex', 'iso container', 'site office', 'modular', 'prefab', 'layout', 'floor plan', 'floorplan', 'planner', 'modeler', '3d', 'building', 'construction', 'office', '20ft', '40ft', 'high cube', 'conversion', 'cabin design', 'quote', 'quotation', 'estimate', 'estimating', 'boq', 'bill of quantities', 'costing', 'takeoff', 'tender', 'pricing', 'sales', 'proposal', 'materials', 'cladding', 'insulation', 'sandwich panel', 'aluco', 'acp', 'plywood', 'gypsum', 'pvc', 'vinyl', 'rate book', 'neoterm'],
    synonyms: ['portacabin', 'shipping container', 'container conversion', 'site office', 'cabin quote'],
    intents: ['quote a container conversion', 'design a portacabin', 'price a site office', 'container floor plan', 'bill of quantities for a cabin'],
    related: ['invoice-generator', 'margin-markup', 'anatomy-explorer'],
    weight: 74,
    icon: svg('<rect x="2" y="7" width="20" height="11" rx="1"/><path d="M6 7v11"/><path d="M10 7v11"/><path d="M14 7v11"/><path d="M18 7v11"/>'),
  },
  {
    id: 'architecture-editor',
    name: 'Architecture Editor',
    description: 'Simple floor plan editor: detect or draw walls, doors, windows & rooms without CAD complexity',
    category: 'modeling',
    secondary: ['design', 'images-files'],
    keywords: ['architecture', 'floor plan', 'floorplan', 'blueprint', 'house plan', 'architect', 'walls', 'doors', 'windows', 'room layout', 'draw floor plan', 'sketch plan', 'dimensions', 'home design', 'renovation', 'interior layout', 'measurements'],
    synonyms: ['floor plan editor', 'blueprint editor', 'house plan maker', 'room planner', 'sketch floorplan'],
    intents: ['edit floor plan', 'modify architectural drawing', 'draw walls and doors', 'create floorplan', 'sketch room layout', 'edit blueprint'],
    related: ['container-planner', 'pdf-editor', 'aspect-ratio'],
    weight: 76,
    icon: svg('<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 22V12h6v10"/><path d="M12 2v7"/>'),
  },
  {
    id: 'file-hash',
    name: 'File Checksum',
    description: 'Verify a download is genuine by comparing its fingerprint against the published one',
    category: 'security',
    secondary: ['images-files', 'developer'],
    keywords: ['hash', 'checksum', 'sha256', 'sha-256', 'sha1', 'sha512', 'file hash', 'verify', 'integrity', 'fingerprint', 'digest', 'md5', 'signature', 'tamper', 'download check'],
    synonyms: ['file integrity check', 'verify download', 'sha256 of a file'],
    intents: ['check a downloaded file', 'verify a checksum', 'is this file genuine', 'sha256 of a file', 'has this file been tampered with'],
    related: ['hash-generator', 'image-metadata', 'password-generator'],
    weight: 76,
    icon: svg('<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/>'),
  },
  {
    id: 'contrast-checker',
    name: 'Contrast Checker',
    description: 'Check colour contrast against WCAG, and get the nearest shade that passes',
    category: 'design',
    secondary: ['security'],
    keywords: ['contrast', 'wcag', 'accessibility', 'a11y', 'ratio', 'legibility', 'readable', 'aa', 'aaa', 'colour contrast', 'color contrast', 'text colour', 'compliance'],
    synonyms: ['wcag checker', 'accessibility contrast', 'colour ratio'],
    intents: ['is this text readable', 'check colour contrast', 'does this pass wcag', 'accessible text colour', 'fix low contrast'],
    related: ['color-converter', 'color-palette-generator'],
    weight: 74,
    icon: svg('<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 1 0 18z" fill="currentColor" stroke="none"/>'),
  },
  {
    id: 'timer',
    name: 'Timer & Stopwatch',
    description: 'Countdown or stopwatch with laps, a chime, and the time in the tab title',
    category: 'everyday',
    secondary: ['numbers'],
    keywords: ['timer', 'stopwatch', 'countdown', 'alarm', 'pomodoro', 'clock', 'minutes', 'lap', 'egg timer', 'interval', 'time', 'reminder', 'chime'],
    synonyms: ['countdown timer', 'online stopwatch', 'pomodoro timer'],
    intents: ['set a timer', 'start a stopwatch', 'time something', 'countdown 5 minutes', 'pomodoro'],
    related: ['business-days', 'meeting-cost', 'timesheet'],
    weight: 84,
    icon: svg('<circle cx="12" cy="13" r="8"/><path d="M12 9v4l2.5 2"/><path d="M9 2h6"/>'),
  },
  {
    id: 'case-digest',
    name: 'Case Digest',
    description: 'Extract facts, issues, holding, ratio decidendi & authorities with plain-English summary',
    category: 'law',
    secondary: ['text'],
    keywords: ['case', 'digest', 'judgment', 'ruling', 'law', 'legal', 'case brief', 'facts', 'ratio decidendi', 'holding', 'precedent', 'supreme court', 'appeal', 'court', 'lawyer', 'brief'],
    synonyms: ['case brief', 'judgment summary', 'legal digest', 'case summary'],
    intents: ['digest a case', 'summarize a judgment', 'extract ratio decidendi', 'case brief generator', 'explain case in simple terms'],
    related: ['case-comparator', 'legal-document-analyzer', 'legal-research'],
    accepts: ['text', 'markdown'],
    produces: ['text', 'markdown'],
    weight: 88,
    icon: svg('<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/><path d="M10 6h6"/><path d="M10 10h6"/><path d="M10 14h4"/>'),
  },
  {
    id: 'case-comparator',
    name: 'Case Comparator',
    description: 'Compare two judgments side by side: facts, holdings, ratio & precedential relations',
    category: 'law',
    secondary: ['text'],
    keywords: ['case comparison', 'compare cases', 'distinguish precedent', 'legal precedent', 'compare judgments', 'ratio comparison', 'law', 'court comparison'],
    synonyms: ['compare precedents', 'distinguish case', 'case side by side'],
    intents: ['compare two cases', 'distinguish precedent', 'compare rulings', 'check similarities in case law'],
    related: ['case-digest', 'legal-document-analyzer', 'legal-research'],
    weight: 82,
    icon: svg('<path d="M16 3h5v5"/><path d="M8 3H3v5"/><path d="M12 21V3"/><path d="M3 8l6 6-6 6"/><path d="M21 8l-6 6 6 6"/>'),
  },
  {
    id: 'legal-document-analyzer',
    name: 'Legal Document Analyzer',
    description: 'Extract parties, dates, covenants, defined terms & liabilities from contracts & statutes',
    category: 'law',
    secondary: ['business', 'text'],
    keywords: ['contract', 'agreement', 'legal analyzer', 'covenants', 'obligations', 'parties', 'liabilities', 'statute', 'nda', 'lease', 'pleading', 'defined terms'],
    synonyms: ['contract analyzer', 'lease inspector', 'agreement review'],
    intents: ['analyze a contract', 'extract obligations from agreement', 'find defined terms', 'review legal instrument'],
    related: ['case-digest', 'legal-pdf', 'document-analyzer'],
    weight: 85,
    icon: svg('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/>'),
  },
  {
    id: 'legal-research',
    name: 'Legal Research Planner',
    description: 'Structure legal questions into issues, doctrines, Boolean queries & authority matrix',
    category: 'law',
    secondary: ['reference', 'text'],
    keywords: ['legal research', 'research question', 'boolean search', 'lawpavilion', 'bailii', 'canlii', 'legal issues', 'doctrines', 'authorities', 'case law search'],
    synonyms: ['research matrix', 'legal issue tree', 'law query builder'],
    intents: ['plan legal research', 'generate boolean law query', 'break down legal question', 'find applicable legal concepts'],
    related: ['case-digest', 'case-comparator', 'dictionary'],
    weight: 80,
    icon: svg('<circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/><path d="M11 8v6"/><path d="M8 11h6"/>'),
  },
  {
    id: 'legal-pdf',
    name: 'Legal PDF Bundle & Stamping',
    description: 'Court bundle pagination, sequential Bates numbering, redaction & e-filing optimization',
    category: 'law',
    secondary: ['images-files'],
    keywords: ['bates numbering', 'court bundle', 'redact pdf', 'legal pdf', 'e-filing', 'compress legal pdf', 'bates stamp', 'court exhibits', 'redaction'],
    synonyms: ['bates stamper', 'court bundle maker', 'pdf redactor'],
    intents: ['apply bates numbering to pdf', 'redact confidential details', 'prepare court bundle', 'optimize pdf for e-filing'],
    related: ['pdf-merge', 'pdf-editor', 'legal-document-analyzer'],
    weight: 86,
    icon: svg('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><path d="M9 15h6"/><path d="M9 11h6"/><path d="M9 19h4"/>'),
  },
  {
    id: 'text-cleaner',
    name: 'Clean Text',
    description: 'Strip zero-width characters, invisible Unicode markers, smart quotes & unusual whitespace',
    category: 'text',
    secondary: ['developer'],
    keywords: ['clean text', 'text cleaner', 'clean', 'cleaner', 'strip', 'invisible characters', 'zero width', 'zwsp', 'zwnj', 'zwj', 'bom', 'soft hyphen', 'whitespace', 'nbsp', 'non-breaking space', 'plain text', 'sanitise', 'sanitize', 'normalise', 'smart quotes', 'curly quotes', 'word paste', 'pdf paste', 'clipboard hygiene'],
    synonyms: ['clean text', 'sanitize text', 'remove invisible characters', 'zero width remover', 'plain text sanitizer'],
    intents: ['clean text', 'remove invisible characters', 'strip zero width spaces', 'clean up pasted text', 'remove smart quotes', 'fix text from pdf', 'sanitize text'],
    related: ['case-converter', 'find-replace', 'remove-duplicates', 'word-counter'],
    accepts: ['text', 'markdown', 'csv', 'json', 'code'],
    produces: ['text'],
    weight: 84,
    icon: svg('<path d="M3 5h18"/><path d="M3 10h12"/><path d="M3 15h8"/><path d="M15 15l6 6"/><path d="M21 15l-6 6"/>'),
  },
  {
    id: 'algorithm-lab',
    name: 'Algorithm Lab',
    description: 'Watch sorting and searching algorithms run step by step on data you choose',
    category: 'developer',
    secondary: ['numbers'],
    keywords: ['algorithm', 'visualiser', 'visualizer', 'sorting', 'sort', 'bubble sort', 'quicksort', 'merge sort', 'insertion sort', 'selection sort', 'heap sort', 'binary search', 'linear search', 'data structure', 'big o', 'complexity', 'animation', 'step through', 'computer science'],
    synonyms: ['sorting visualiser', 'algorithm animation', 'data structure visualiser'],
    intents: ['visualise sorting', 'how does quicksort work', 'see an algorithm run', 'compare sorting algorithms', 'understand binary search', 'big o complexity'],
    related: ['code-playground', 'uml-diagram'],
    weight: 80,
    icon: svg('<rect x="3" y="13" width="3.5" height="8"/><rect x="8.5" y="9" width="3.5" height="12"/><rect x="14" y="5" width="3.5" height="16"/><rect x="19.5" y="11" width="3.5" height="10"/>'),
  },
  {
    id: 'uml-diagram',
    name: 'UML Diagram',
    description: 'Write a diagram as text and get a class, sequence, state or ER drawing you can export',
    category: 'developer',
    secondary: ['design'],
    keywords: ['uml', 'diagram', 'class diagram', 'sequence diagram', 'state diagram', 'er diagram', 'entity relationship', 'flowchart', 'mermaid', 'architecture', 'modelling', 'modeling', 'plantuml', 'draw', 'chart'],
    synonyms: ['mermaid diagram', 'class diagram maker', 'sequence diagram tool'],
    intents: ['draw a uml diagram', 'make a class diagram', 'sequence diagram from text', 'diagram as code', 'entity relationship diagram', 'flowchart from text'],
    related: ['algorithm-lab', 'code-playground', 'markdown-preview'],
    accepts: ['uml'],
    produces: ['uml'],
    weight: 78,
    offline: false,   // the diagram engine is fetched on first use
    icon: svg('<rect x="3" y="3" width="7" height="5" rx="1"/><rect x="14" y="3" width="7" height="5" rx="1"/><rect x="8.5" y="15" width="7" height="5" rx="1"/><path d="M6.5 8v3.5h11V8"/><path d="M12 11.5V15"/>'),
  },
  {
    id: 'logic-lab',
    name: 'Logic Lab',
    description: 'Wire logic gates together and watch the signals move, with a live truth table and Boolean expression',
    category: 'developer',
    secondary: ['numbers'],
    keywords: ['logic', 'logic gates', 'gate', 'and', 'or', 'not', 'nand', 'nor', 'xor', 'xnor', 'truth table', 'boolean', 'digital', 'circuit', 'simulator', 'karnaugh', 'sum of products', 'half adder', 'multiplexer', 'combinational', 'electronics'],
    synonyms: ['logic gate simulator', 'truth table generator', 'digital circuit simulator', 'boolean calculator'],
    intents: ['simulate logic gates', 'build a truth table', 'how does a half adder work', 'boolean expression from a circuit', 'test a logic circuit', 'xor from nand'],
    related: ['algorithm-lab', 'number-base-converter', 'ohms-law'],
    weight: 82,
    icon: svg('<path d="M3 8h4"/><path d="M3 16h4"/><path d="M7 5h5a7 7 0 0 1 0 14H7z"/><path d="M19 12h2"/>'),
  },
  {
    id: 'ohms-law',
    name: 'Ohm’s Law & Power',
    description: 'Enter any two of voltage, current, resistance or power and get the rest, plus resistor combinations',
    category: 'numbers',
    secondary: ['developer'],
    keywords: ['ohm', 'ohms law', 'voltage', 'current', 'resistance', 'power', 'watts', 'amps', 'volts', 'electrical', 'electronics', 'circuit', 'series', 'parallel', 'resistor', 'p=vi', 'v=ir'],
    synonyms: ['electrical calculator', 'watts calculator', 'power calculator'],
    intents: ['work out current from voltage and resistance', 'how many watts', 'calculate resistance', 'resistors in parallel', 'what resistor do i need'],
    related: ['resistor-code', 'voltage-drop', 'logic-lab'],
    weight: 84,
    icon: svg('<path d="M12 2v4"/><path d="M12 18v4"/><path d="M8 6h8l-2 4h-4l2 4H8"/>'),
  },
  {
    id: 'resistor-code',
    name: 'Resistor Colour Code',
    description: 'Read the bands on a resistor, or find the bands for a value you need',
    category: 'numbers',
    secondary: ['developer', 'design'],
    keywords: ['resistor', 'colour code', 'color code', 'bands', 'ohms', 'electronics', 'component', 'tolerance', 'e24', 'e12', '4 band', '5 band', 'brown black red', 'identify resistor'],
    synonyms: ['resistor calculator', 'colour band decoder', 'resistor value'],
    intents: ['what resistor is this', 'read resistor bands', 'resistor colour code', 'what colour is a 4.7k resistor', 'decode resistor'],
    related: ['ohms-law', 'voltage-drop'],
    weight: 80,
    icon: svg('<path d="M2 12h4"/><path d="M18 12h4"/><rect x="6" y="7" width="12" height="10" rx="3"/><path d="M9.5 7v10"/><path d="M12 7v10"/><path d="M14.5 7v10"/>'),
  },
  {
    id: 'voltage-drop',
    name: 'Voltage Drop & Cable Size',
    description: 'Check whether a cable can carry the load over the distance, and get the smallest size that passes',
    category: 'numbers',
    secondary: ['business'],
    keywords: ['voltage drop', 'cable', 'wire', 'sizing', 'ampacity', 'current rating', 'electrical', 'installation', 'volt drop', 'conductor', 'copper', 'aluminium', 'mm2', 'three phase', 'cable calculator', 'wiring'],
    synonyms: ['cable sizing calculator', 'wire gauge calculator', 'volt drop calculator'],
    intents: ['what cable size do i need', 'calculate voltage drop', 'is this cable big enough', 'cable for a long run', 'wire sizing'],
    related: ['ohms-law', 'resistor-code'],
    weight: 76,
    icon: svg('<path d="M4 8c4 0 4 8 8 8s4-8 8-8"/><path d="M2 16h2"/><path d="M20 8h2"/>'),
  },
  {
    id: 'beam-calculator',
    name: 'Beam Calculator',
    description: 'Reactions, shear, bending moment and deflection for simply supported and cantilever beams',
    category: 'numbers',
    secondary: ['business'],
    keywords: ['beam', 'structural', 'civil engineering', 'deflection', 'bending moment', 'shear', 'load', 'cantilever', 'simply supported', 'udl', 'point load', 'steel', 'timber', 'span', 'i beam', 'stress', 'mechanical'],
    synonyms: ['structural beam calculator', 'deflection calculator', 'bending moment calculator'],
    intents: ['how much will this beam deflect', 'size a steel beam', 'bending moment for a span', 'cantilever deflection', 'is this beam strong enough'],
    related: ['concrete-estimator', 'container-planner', 'unit-converter'],
    weight: 74,
    icon: svg('<path d="M3 8h18"/><path d="M3 12h18"/><path d="M5 12v5"/><path d="M19 12v5"/><path d="M12 4v4"/>'),
  },
  {
    id: 'concrete-estimator',
    name: 'Concrete & Rebar',
    description: 'Volume, cement bags, sand, stone and reinforcement for a pour, with costs',
    category: 'business',
    secondary: ['numbers'],
    keywords: ['concrete', 'cement', 'rebar', 'reinforcement', 'slab', 'footing', 'foundation', 'mix', 'volume', 'bags', 'sand', 'aggregate', 'granite', 'construction', 'civil', 'quantity', 'estimate', 'pour', 'm3'],
    synonyms: ['concrete calculator', 'cement bag calculator', 'rebar estimator'],
    intents: ['how much concrete do i need', 'how many bags of cement', 'concrete for a slab', 'rebar quantity', 'cost of a concrete pour'],
    related: ['container-planner', 'beam-calculator', 'margin-markup'],
    weight: 78,
    icon: svg('<path d="M3 20h18"/><path d="M5 20V9l7-5 7 5v11"/><path d="M9 20v-6h6v6"/>'),
  },
  {
    id: 'metronome',
    name: 'Metronome',
    description: 'Keep time with accents, subdivisions and tap tempo, driven by the audio clock so it does not drift',
    category: 'music',
    keywords: ['metronome', 'tempo', 'bpm', 'beat', 'click track', 'practice', 'timing', 'rhythm', 'time signature', 'tap tempo', 'subdivision', 'triplet', 'accent', 'pulse', 'music'],
    synonyms: ['online metronome', 'click track', 'beat keeper'],
    intents: ['keep time while practising', 'set a tempo', 'what is the bpm', 'practise with a click', 'metronome at 120'],
    related: ['tempo-delay', 'tuner', 'timer'],
    weight: 88,
    icon: svg('<path d="M12 3l6 18H6l6-18z"/><path d="M8.5 14h7"/><path d="M12 21V9"/>'),
  },
  {
    id: 'tuner',
    name: 'Instrument Tuner',
    description: 'Tune by ear through the microphone, with cents accuracy and a reference pitch you can set',
    category: 'music',
    secondary: ['security'],
    keywords: ['tuner', 'tune', 'tuning', 'guitar', 'bass', 'ukulele', 'violin', 'pitch', 'microphone', 'cents', 'a440', 'concert pitch', 'chromatic', 'intonation', 'flat', 'sharp', 'in tune', 'music'],
    synonyms: ['guitar tuner', 'chromatic tuner', 'pitch detector', 'online tuner'],
    intents: ['tune my guitar', 'is this note in tune', 'what note am i playing', 'tune a ukulele', 'chromatic tuner'],
    related: ['chord-finder', 'metronome'],
    weight: 90,
    offline: true,
    icon: svg('<path d="M12 2a3 3 0 0 1 3 3v6a3 3 0 0 1-6 0V5a3 3 0 0 1 3-3z"/><path d="M5 10v1a7 7 0 0 0 14 0v-1"/><path d="M12 18v4"/>'),
  },
  {
    id: 'chord-finder',
    name: 'Chord & Scale Finder',
    description: 'See any chord or scale on a fretboard and keyboard, hear it, and find the chords that fit a key',
    category: 'music',
    keywords: ['chord', 'scale', 'guitar', 'fretboard', 'piano', 'keyboard', 'key', 'notes', 'triad', 'seventh', 'pentatonic', 'blues', 'mode', 'dorian', 'mixolydian', 'transpose', 'music theory', 'shapes', 'voicing'],
    synonyms: ['chord chart', 'scale finder', 'guitar chords', 'chord dictionary'],
    intents: ['how do i play a chord', 'notes in a chord', 'what chords are in a key', 'guitar scale shapes', 'what is a dorian scale', 'chords that go together'],
    related: ['tuner', 'metronome', 'tempo-delay'],
    weight: 84,
    icon: svg('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 4v10"/><path d="M11 4v10"/><path d="M15 4v10"/><path d="M19 4v10"/><path d="M3 14h18"/>'),
  },
  {
    id: 'tempo-delay',
    name: 'Tempo & Delay Times',
    description: 'Delay, reverb and note lengths in milliseconds and Hz for a tempo, with tap tempo',
    category: 'music',
    secondary: ['numbers'],
    keywords: ['delay', 'tempo', 'bpm', 'milliseconds', 'ms', 'reverb', 'pre-delay', 'note length', 'dotted', 'triplet', 'lfo', 'hz', 'sync', 'daw', 'producer', 'mixing', 'bar length', 'tap tempo'],
    synonyms: ['delay time calculator', 'bpm to ms', 'tempo calculator'],
    intents: ['delay time for this tempo', 'bpm to milliseconds', 'dotted eighth delay', 'how long is a bar', 'tempo sync my lfo', 'work out the bpm'],
    related: ['metronome', 'chord-finder', 'timer'],
    weight: 80,
    icon: svg('<path d="M3 12h3l2-6 3 12 3-9 2 3h5"/>'),
  },
  {
    id: 'wiki',
    name: 'Wiki',
    description: 'Search Wikipedia and read it properly, with the facts pulled out and the source one click away',
    category: 'reference',
    keywords: ['wikipedia', 'wiki', 'encyclopedia', 'encyclopaedia', 'research', 'article', 'lookup', 'knowledge', 'wikidata', 'facts', 'reference', 'reading', 'random article', 'cite', 'citation'],
    synonyms: ['wikipedia search', 'encyclopedia', 'research tool'],
    intents: ['look something up', 'search wikipedia', 'who was', 'what is', 'read about a topic', 'research a subject', 'random article', 'cite a wikipedia article'],
    related: ['dictionary', 'bible', 'quran'],
    weight: 92,
    offline: false,
    icon: svg('<path d="M4 4h4l3 10 3-10h2l3 10 3-10h2"/><path d="M3 20h18"/>'),
  },
  {
    id: 'dictionary',
    name: 'Dictionary',
    description: 'Definitions, pronunciation and origins from two dictionaries at once, so rare words still resolve',
    category: 'reference',
    secondary: ['text'],
    keywords: ['dictionary', 'define', 'definition', 'meaning', 'word', 'vocabulary', 'thesaurus', 'synonym', 'antonym', 'etymology', 'pronunciation', 'phonetic', 'spelling', 'wiktionary', 'lexicon', 'what does mean'],
    synonyms: ['define a word', 'word meaning', 'english dictionary'],
    intents: ['what does this word mean', 'define a word', 'how do you pronounce', 'find a synonym', 'word origin', 'is this a real word'],
    related: ['wiki', 'text-cleaner', 'word-counter'],
    weight: 90,
    offline: false,
    icon: svg('<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/><path d="M9 7h7"/><path d="M9 11h5"/>'),
  },
  {
    id: 'bible',
    name: 'Bible',
    description: 'Read any passage in nine translations, select verses, and copy them properly referenced',
    category: 'reference',
    keywords: ['bible', 'scripture', 'verse', 'chapter', 'testament', 'gospel', 'psalm', 'proverbs', 'kjv', 'king james', 'web', 'asv', 'christian', 'passage', 'reference', 'bible study', 'devotion'],
    synonyms: ['holy bible', 'scripture reader', 'bible verses'],
    intents: ['look up a bible verse', 'read a psalm', 'find a scripture', 'john 3:16', 'copy a bible passage', 'compare bible translations'],
    related: ['quran', 'wiki', 'dictionary'],
    weight: 84,
    offline: false,
    icon: svg('<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/><path d="M12 6v6"/><path d="M9.5 8.5h5"/>'),
  },
  {
    id: 'quran',
    name: 'Quran',
    description: 'Read the Quran in Arabic with translation, transliteration and recitation, and keep your place',
    category: 'reference',
    keywords: ['quran', 'koran', 'qur an', 'surah', 'ayah', 'verse', 'islam', 'muslim', 'arabic', 'recitation', 'tilawah', 'tajweed', 'juz', 'mushaf', 'translation', 'transliteration', 'sajdah', 'uthmani'],
    synonyms: ['holy quran', 'quran reader', 'quran recitation'],
    intents: ['read the quran', 'listen to quran recitation', 'find a surah', 'quran translation in english', 'ayat al kursi', 'surah yasin'],
    related: ['bible', 'wiki', 'dictionary'],
    weight: 84,
    offline: false,
    icon: svg('<path d="M12 3l1.9 4.3 4.6.5-3.4 3.1 1 4.5-4.1-2.4-4.1 2.4 1-4.5L5.5 7.8l4.6-.5z"/><path d="M4 20h16"/>'),
  },
  {
    id: 'flowchart',
    name: 'Flowchart to Code',
    description: 'Draw program logic as a flowchart and get working code in seven languages',
    category: 'developer',
    secondary: ['design'],
    keywords: ['flowchart', 'flow chart', 'flowgorithm', 'pseudocode', 'algorithm', 'diagram', 'logic', 'code generation', 'loop', 'condition', 'branch', 'programming', 'beginner', 'visual programming', 'if else', 'while loop'],
    synonyms: ['flowgorithm', 'flowchart maker', 'pseudocode to code', 'visual programming'],
    intents: ['draw a flowchart', 'turn a flowchart into code', 'plan program logic', 'pseudocode to python', 'flowchart for a loop', 'visualise an algorithm'],
    related: ['code-playground', 'algorithm-lab', 'uml-diagram'],
    produces: ['code'],
    weight: 80,
    icon: svg('<rect x="9" y="2" width="6" height="4" rx="1"/><path d="M12 6v4"/><path d="M12 10l-4 4 4 4 4-4z"/><path d="M12 18v4"/>'),
  },
  {
    id: 'speed-test',
    name: 'Speed Test',
    description: 'Measure download, upload, latency and jitter — and see which server you are actually reaching',
    category: 'networking',
    secondary: ['everyday'],
    keywords: ['speed', 'speedtest', 'speed test', 'internet speed', 'bandwidth', 'mbps', 'download speed', 'upload speed', 'latency', 'ping', 'jitter', 'throughput', 'connection', 'wifi', 'broadband', 'network speed', 'how fast'],
    synonyms: ['bandwidth test', 'internet speed test', 'network test', 'ping test'],
    intents: ['how fast is my internet', 'test my connection', 'check my wifi speed', 'why is my internet slow', 'measure download speed', 'what is my ping'],
    related: ['ip-lookup', 'net-dns-lookup', 'net-subnet'],
    weight: 94,
    offline: false,
    icon: svg('<path d="M12 21a9 9 0 1 1 9-9"/><path d="M12 12l5-3"/><circle cx="12" cy="12" r="1.4"/><path d="M12 3v2"/><path d="M21 12h-2"/><path d="M5 12H3"/>'),
  },
  {
    id: 'weather-forecast',
    name: 'Weather Forecast',
    description: 'Get current conditions and 3-day forecast anywhere',
    category: 'everyday',
    keywords: ['weather', 'forecast', 'temperature', 'climate', 'sun', 'rain', 'meteo', 'open-meteo', 'conditions'],
    synonyms: ['forecast', 'temperature', 'rain'],
    intents: ['what is the weather', 'will it rain', 'forecast for this week', 'temperature today'],
    related: ['interactive-map', 'unit-converter'],
    weight: 68,
    offline: false,
    icon: svg('<path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"/>'),
  },
  {
    id: 'interactive-map',
    name: 'Interactive Map',
    description: 'Search, pan, and zoom across the globe instantly',
    category: 'everyday',
    keywords: ['map', 'maps', 'globe', 'leaflet', 'location', 'geography', 'search location', 'address'],
    synonyms: ['map', 'coordinates', 'latitude longitude'],
    intents: ['find coordinates', 'look at a map', 'latitude and longitude of a place'],
    related: ['weather-forecast', 'ip-lookup'],
    weight: 44,
    offline: false,
    icon: svg('<polygon points="3 6 9 3 15 6 21 3 21 18 15 21 9 18 3 21"/><line x1="9" y1="3" x2="9" y2="18"/><line x1="15" y1="6" x2="15" y2="21"/>'),
  },
  {
    id: 'periodic-table',
    name: 'Periodic Table of Elements',
    description: 'Interactive scientific periodic table with IUPAC properties, electronegativity heatmaps and electron shells',
    category: 'science',
    secondary: ['reference'],
    keywords: ['periodic', 'table', 'elements', 'chemistry', 'mendeleev', 'atoms', 'atomic weight', 'valency', 'electrons'],
    intents: ['look up element', 'periodic table', 'atomic mass', 'electron configuration'],
    related: ['chemical-equation-balancer', 'stoichiometry-calculator', 'compound-database'],
    weight: 85,
    offline: true,
    icon: svg('<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>'),
  },
  {
    id: 'chemical-equation-balancer',
    name: 'Chemical Equation Balancer',
    description: 'Balance chemical reactions using exact Gaussian elimination nullspace solver with step-by-step matrix derivation',
    category: 'science',
    secondary: ['numbers'],
    keywords: ['balance', 'equation', 'reaction', 'stoichiometry', 'chemistry', 'reactants', 'products', 'moles'],
    intents: ['balance chemical equation', 'reaction balancer', 'stoichiometric balance'],
    related: ['stoichiometry-calculator', 'periodic-table', 'compound-database'],
    weight: 82,
    offline: true,
    icon: svg('<circle cx="12" cy="12" r="10"/><path d="M12 8v8M8 12h8"/>'),
  },
  {
    id: 'stoichiometry-calculator',
    name: 'Stoichiometry & Reaction Yields',
    description: 'Calculate theoretical yield, limiting reagents, mass-to-mole conversions, and excess reactant remaining',
    category: 'science',
    secondary: ['numbers'],
    keywords: ['stoichiometry', 'limiting reagent', 'theoretical yield', 'molar mass', 'moles', 'grams', 'chemistry calculation'],
    intents: ['calculate limiting reactant', 'stoichiometry calculator', 'theoretical yield'],
    related: ['chemical-equation-balancer', 'periodic-table', 'compound-database'],
    weight: 80,
    offline: true,
    icon: svg('<path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>'),
  },
  {
    id: 'compound-database',
    name: 'Chemical Compound Database',
    description: 'Search 1,000+ chemical formulas, IUPAC names, pharmaceuticals, CAS numbers, physical constants, and GHS safety data',
    badge: '1,000+ compounds',
    category: 'science',
    secondary: ['reference'],
    keywords: ['compound', 'chemicals', 'cas number', 'iupac', 'molar mass', 'formula', 'density', 'safety', 'pharmaceutical', 'drug', 'medicine', 'biochemistry', 'organic', 'inorganic'],
    intents: ['look up compound', 'chemical formula lookup', 'cas search', 'drug lookup', 'pharmaceutical database'],
    related: ['periodic-table', 'chemical-equation-balancer', 'stoichiometry-calculator'],
    weight: 75,
    offline: true,
    icon: svg('<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>'),
  },

  {
    id: 'payment-hub',
    name: 'Payment Hub & Receive Money',
    description: 'Accept payments and receive money via Dedicated Virtual Bank Accounts, Cards and Crypto rails with instant settlements',
    category: 'business',
    secondary: ['numbers', 'everyday'],
    keywords: ['payment', 'receive money', 'virtual account', 'bank transfer', 'card', 'crypto', 'lightning', 'invoice payment', 'checkout'],
    intents: ['receive money', 'accept payment', 'create payment link', 'virtual bank account'],
    related: ['invoice-generator', 'container-planner', 'amortization-schedule'],
    weight: 88,
    offline: true,
    icon: svg('<rect x="2" y="5" width="20" height="14" rx="2"/><line x1="2" y1="10" x2="22" y2="10"/>'),
  },
  {
    id: 'file-compressor',
    name: 'File Compressor',
    description: 'Compress files and folders into ZIP, TAR, and GZ archives',
    category: 'images-files',
    secondary: ['developer', 'business'],
    keywords: ['compress', 'compressor', 'zip', 'tar', 'gzip', 'gz', 'archive', 'pack', 'deflate', 'file compression'],
    synonyms: ['zip creator', 'zip maker', 'file compressor', 'tar creator'],
    intents: ['compress files', 'create a zip', 'make zip archive', 'zip multiple files', 'tar files'],
    related: ['file-decompressor', 'image-compressor', 'pdf-merge'],
    weight: 90,
    offline: true,
    icon: svg('<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/>'),
  },
  {
    id: 'file-decompressor',
    name: 'File Decompressor',
    description: 'Inspect, preview, and extract ZIP, TAR, GZ, and TGZ archives',
    category: 'images-files',
    secondary: ['developer'],
    keywords: ['decompress', 'unzip', 'extract', 'untar', 'gunzip', 'archive', 'unpack', 'open zip'],
    synonyms: ['zip opener', 'archive extractor', 'unzip tool', 'tar extractor'],
    intents: ['unzip files', 'open a zip', 'extract archive', 'read zip without extracting', 'untar file'],
    related: ['file-compressor', 'pdf-editor', 'text-cleaner'],
    weight: 89,
    offline: true,
    icon: svg('<polyline points="4 14 10 14 10 20"/><polyline points="20 10 14 10 14 4"/><line x1="14" y1="10" x2="21" y2="3"/><line x1="3" y1="21" x2="10" y2="14"/>'),
  },
  {
    id: 'audio-tag-editor',
    name: 'Audio Tag & MP3 Editor',
    description: 'Edit ID3 tags, song titles, artists, lyrics, and embed album cover art',
    category: 'music',
    secondary: ['images-files'],
    keywords: ['id3', 'mp3', 'tag', 'audio', 'metadata', 'album art', 'cover art', 'lyrics', 'song title', 'artist', 'edit mp3'],
    synonyms: ['id3 editor', 'mp3 tagger', 'music tag editor', 'album art embedder'],
    intents: ['edit mp3 tags', 'change album art', 'add lyrics to mp3', 'fix song title', 'change audio metadata'],
    related: ['tuner', 'metronome', 'image-cropper'],
    weight: 86,
    offline: true,
    icon: svg('<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>'),
  },
  {
    id: 'video-player',
    name: 'Video Player',
    description: 'Offline video player with subtitle loader, speed controls, and frame snapshot',
    category: 'everyday',
    secondary: ['images-files'],
    keywords: ['video', 'player', 'mp4', 'webm', 'subtitles', 'srt', 'vtt', 'playback speed', 'snapshot', 'frame capture'],
    synonyms: ['media player', 'movie player', 'subtitles player'],
    intents: ['play video', 'watch video offline', 'load srt subtitles', 'capture video frame', 'slow down video'],
    related: ['audio-tag-editor', 'image-cropper', 'speaker-cleaner'],
    weight: 85,
    offline: true,
    icon: svg('<polygon points="5 3 19 12 5 21 5 3"/>'),
  },
  {
    id: 'data-bot',
    name: 'Data Bot',
    description: 'Visualize large datasets in charts, graphs, percentages, and plain-English insights',
    category: 'business',
    secondary: ['developer', 'numbers', 'science'],
    keywords: ['data', 'bot', 'charts', 'graphs', 'visualize', 'analytics', 'statistics', 'csv', 'json', 'pivot table', 'percentages', 'insights', 'big data', 'excel'],
    synonyms: ['data visualizer', 'chart bot', 'dataset analyzer', 'graph maker'],
    intents: ['visualize dataset', 'create charts from csv', 'analyze large data', 'generate data insights', 'data pivot table'],
    related: ['financial-analyzer', 'calculator', 'percentage-calculator'],
    weight: 95,
    offline: true,
    icon: svg('<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/>'),
  },
  {
    id: 'speaker-cleaner',
    name: 'Speaker Cleaner',
    description: 'Eject water and clear dust from speakers using 165Hz resonant sound waves',
    category: 'everyday',
    secondary: ['music'],
    keywords: ['speaker', 'cleaner', 'water eject', 'eject water', 'fix speaker', '165hz', 'sub bass', 'dust cleaner', 'muffled sound'],
    synonyms: ['water ejector', 'sound cleaner', 'speaker water remover', 'fix wet speaker'],
    intents: ['clean phone speaker', 'eject water from speaker', 'fix muffled audio', 'speaker sound wave cleaner'],
    related: ['tuner', 'video-player', 'metronome'],
    weight: 92,
    offline: true,
    icon: svg('<polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14M15.54 8.46a5 5 0 0 1 0 7.07"/>'),
  },
  {
    id: 'notes',
    name: 'Notes',
    description: 'Apple Notes style offline note space with folders, checklists, and rich formatting',
    category: 'text',
    secondary: ['everyday', 'business'],
    keywords: ['notes', 'apple notes', 'notebook', 'memo', 'checklist', 'to-do', 'todo', 'rich text', 'offline notes', 'folders', 'ruled paper'],
    synonyms: ['apple notes', 'quick notes', 'scratchpad', 'notepad'],
    intents: ['take notes', 'write note', 'make a checklist', 'apple notes offline', 'organize thoughts'],
    related: ['text-cleaner', 'word-counter', 'markdown-preview'],
    weight: 96,
    offline: true,
    icon: svg('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>'),
  },
];

export default TOOLS;
