/**
 * Reference data for the Boeing 737-800 package.
 *
 * Figures are attributed to the public sources in SOURCES. Where a figure
 * depends on the operator's options (engine rating, seating, brakes) the
 * text says so; where geometry or placement is a Toolbox approximation the
 * component says so. Nothing here is taken from a maintenance or flight
 * crew operations manual, and nothing here is for operational use.
 */
import { makeDescriber, makeSheet, cap } from './package-data.mjs';

export const SOURCES = {
  acapsNG: { label: 'Boeing — Next-Generation 737 Airplane Characteristics for Airport Planning', url: 'https://www.boeing.com/content/dam/boeing/v2/airports/acaps/737NG_REV_C.pdf' },
  acaps: { label: 'Boeing — 737 Airplane Characteristics for Airport Planning (D6-58325-6)', url: 'https://www.boeing.com/content/dam/boeing/boeingdotcom/commercial/airports/acaps/737.pdf' },
  wiki: { label: 'Wikipedia — Boeing 737 Next Generation', url: 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation' },
  cfm: { label: 'Wikipedia — CFM International CFM56', url: 'https://en.wikipedia.org/wiki/CFM_International_CFM56' },
  mtu: { label: 'MTU Aero Engines — CFM56-7B', url: 'https://www.mtu.de/engines/commercial-aircraft-engines/narrowbody-and-regional-jets/cfm56-2/-5b/-7/' },
  gear: { label: 'The Boeing 737 Technical Site — Landing gear', url: 'https://www.b737.org.uk/landinggear.htm' },
  tyres: { label: 'Dunlop Aircraft Tyres — Boeing 737 Next Generation', url: 'https://www.dunlopaircrafttyres.co.uk/aircraft/boeing-737-next-generation-tires/' },
  controls: { label: 'AviationHunt — Boeing 737 flight control surfaces', url: 'https://www.aviationhunt.com/boeing-737-flight-control-surfaces/' }
};

const APPROX = 'Shape and position are a Toolbox approximation for orientation; not a Boeing drawing.';
const TRAINING = 'Described for learning. Operators’ procedures and fits vary; always follow the approved manuals.';

export const LAYERS = [
  { id: 'airframe', label: 'Fuselage & fairings' },
  { id: 'doors', label: 'Doors & exits' },
  { id: 'glass', label: 'Windows & windshields' },
  { id: 'wings', label: 'Wings & tail' },
  { id: 'controls', label: 'Flight control surfaces' },
  { id: 'engines', label: 'Engines & nacelles' },
  { id: 'gear', label: 'Landing gear' },
  { id: 'lighting', label: 'Exterior lighting' },
  { id: 'sensors', label: 'Probes & antennas' },
  { id: 'cockpit', label: 'Flight deck' },
  { id: 'cabin', label: 'Cabin' },
  { id: 'cargo', label: 'Cargo holds' },
  { id: 'structure', label: 'Structure' },
  { id: 'systems', label: 'Fuel, APU & systems' }
];

const engineNo = s => (s === 'left' ? 'No. 1 (left)' : 'No. 2 (right)');
const SECTIONS = {
  41: ['Section 41 — nose and flight deck', 'From the radome bulkhead to just behind the flight deck, including the nose-gear well and the electronics bay beneath the flight deck.'],
  43: ['Section 43 — forward fuselage', 'Forward cabin barrel over the forward cargo hold.'],
  44: ['Section 44 — centre fuselage', 'Centre barrel carrying the wing centre section, the overwing exits and the main-gear wheel well.'],
  46: ['Section 46 — aft fuselage', 'Aft cabin barrel over the aft cargo hold, up to the aft entry and service doors.'],
  47: ['Section 47 — aft fuselage and tail', 'Tapering barrel behind the aft doors, closed by the aft pressure bulkhead; carries the vertical fin and tailplane.'],
  48: ['Section 48 — tail cone', 'Unpressurised tail cone housing the auxiliary power unit and its exhaust.']
};

const FAMILIES = [
  /* ----------------------------------------------------------- airframe */
  { test: /^fuselage_section_(\d+)$/, data: (id, m) => ({ label: SECTIONS[m[1]][0], category: 'Airframe', layer: 'airframe', description: `${SECTIONS[m[1]][1]} Aluminium-alloy semi-monocoque skin, frames and stringers. The fuselage is 3.76 m (12 ft 4 in) wide.`, location: 'Fuselage.', sources: ['acapsNG'] }) },
  { test: /^radome$/, data: () => ({ label: 'Radome', category: 'Airframe', layer: 'airframe', description: 'Composite nose cone that is transparent to radar. It protects the weather-radar antenna and hinges upward at its top edge for access.', location: 'Nose.', maintenance: 'Inspect for lightning-strike damage, erosion and bird strikes; a damaged radome distorts the radar picture.' }) },
  { test: /^wing_body_fairing$/, data: () => ({ label: 'Wing-to-body fairing', category: 'Airframe', layer: 'airframe', description: 'Composite fairing that smooths airflow where the wing meets the fuselage. It encloses the air-conditioning packs and the landing-gear beams.', location: 'Belly, around the wing root.' }) },
  { test: /^ee_access_hatch$/, data: () => ({ label: 'Electronics bay access hatch', category: 'Airframe', layer: 'airframe', description: 'Hatch in the belly behind the nose gear that gives ground access to the electronics and equipment (E&E) bay.', location: 'Underside of the nose, behind the nose gear.', accuracyNote: APPROX }) },
  { test: /^apu_exhaust$/, data: () => ({ label: 'APU exhaust', category: 'APU', layer: 'systems', description: 'Exhaust outlet of the auxiliary power unit at the very end of the tail cone.', location: 'Tip of the tail cone.' }) },
  /* ---------------------------------------------------------------- doors */
  { test: /^door_(l|r)(1|2)$/, data: (id, m) => ({
    label: `${m[1] === 'l' ? 'Entry' : 'Service'} door ${m[1].toUpperCase()}${m[2]}`, category: 'Doors', layer: 'doors',
    description: m[1] === 'l'
      ? 'Passenger entry door. A plug door, larger than the opening it closes, so cabin pressure holds it shut. It lifts slightly, swings out and forward, and carries the evacuation slide in a pack on its lower inside face.'
      : 'Galley service door, used for catering. Like the entry doors it is a plug door with an evacuation slide, and it is an emergency exit.',
    location: `${m[1] === 'l' ? 'Left' : 'Right'} side, ${m[2] === '1' ? 'forward, just behind the flight deck' : 'aft, near the rear galley'}.`,
    specs: { 'Opening': m[1] === 'l' ? '0.86 × 1.83 m (34 × 72 in)' : '0.76 × 1.65 m (30 × 65 in)' },
    maintenance: 'Slides are armed before flight and disarmed before the door is opened at the gate.', sources: ['acapsNG']
  }) },
  { test: /^overwing_exit_(left|right)_(forward|aft)$/, data: (id, m) => ({ label: `Overwing exit, ${m[1]} ${m[2]}`, category: 'Doors', layer: 'doors', description: 'Type III emergency exit over the wing. The 737-800 has two on each side. On most Next-Generation aircraft the hatch is hinged at the top and swings up and out when the handle is pulled; passengers step onto the wing and slide off its trailing edge.', location: `${cap(m[1])} side over the wing, ${m[2]} of the pair.`, specs: { Opening: 'About 0.51 × 0.97 m (20 × 38 in)' } }) },
  { test: /^cargo_door_(forward|aft)$/, data: (id, m) => ({ label: `${cap(m[1])} cargo door`, category: 'Doors', layer: 'doors', description: `Inward-opening plug door to the ${m[1]} hold, swung up inside the hold. Bags are loaded by hand or with a belt loader; the 737 holds are bulk-loaded.`, location: 'Right side, lower fuselage.', specs: { Opening: m[1] === 'forward' ? '1.22 × 1.30 m (48 × 51 in)' : '1.22 × 1.22 m (48 × 48 in)' }, sources: ['acapsNG'] }) },
  { test: /^flight_deck_door$/, data: () => ({ label: 'Flight deck door', category: 'Flight deck', layer: 'cockpit', description: 'Reinforced, bullet-resistant door between the cabin and the flight deck, locked from the flight deck.', location: 'Front of the cabin.' }) },
  { test: /^flight_deck_bulkhead$/, data: () => ({ label: 'Flight deck bulkhead', category: 'Flight deck', layer: 'cockpit', description: 'Partition between the flight deck and the forward galley and lavatory.', location: 'Behind the pilots’ seats.' }) },
  /* ---------------------------------------------------------------- glass */
  { test: /^windshield_no(\d)_(left|right)$/, data: (id, m) => ({ label: `Flight deck window No. ${m[1]}, ${m[2]}`, category: 'Glass', layer: 'glass', description: m[1] === '1' ? 'Front windshield: laminated glass with an electrically heated layer for anti-icing and strength against bird strikes.' : m[1] === '2' ? 'Side windshield. On the 737 the No. 2 windows can be opened on the ground and used as an emergency exit by the crew.' : 'Side window behind the pilots.', location: `${cap(m[2])} side of the flight deck.`, accuracyNote: APPROX }) },
  { test: /^cabin_windows_(left|right)$/, data: (id, m) => ({ label: `Cabin windows, ${m[1]}`, category: 'Glass', layer: 'glass', description: 'Passenger windows: two acrylic panes and an inner scratch pane. The small hole in the middle pane balances pressure so the outer pane carries the load.', location: `${cap(m[1])} side of the cabin.` }) },
  /* ----------------------------------------------------------- wings, tail */
  { test: /^wing_(left|right)$/, data: (id, m) => ({ label: `${cap(m[1])} wing`, category: 'Wings', layer: 'wings', description: 'Swept, two-spar aluminium wing (25° at quarter chord) with 6° of dihedral. The box between the spars is the main fuel tank.', location: `${cap(m[1])} side.`, specs: { 'Wing area (both)': '124.6 m² (1,341 sq ft)', Sweep: '25° at quarter chord' }, sources: ['acapsNG', 'wiki'] }) },
  { test: /^winglet_(left|right)$/, data: (id, m) => ({ label: `Blended winglet, ${m[1]}`, category: 'Wings', layer: 'wings', description: 'Aviation Partners Boeing blended winglet, 2.49 m (8 ft 2 in) tall. Reduces induced drag, saving roughly 3–5 % fuel on longer flights; adds 1.47 m to the span.', location: `${cap(m[1])} wingtip.`, specs: { 'Span with winglets': '35.79 m (117 ft 5 in)', 'Span without': '34.32 m (112 ft 7 in)' }, sources: ['acapsNG'] }) },
  { test: /^flap_track_fairings_(left|right)$/, data: (id, m) => ({ label: `Flap track fairings, ${m[1]}`, category: 'Wings', layer: 'wings', description: 'Streamlined "canoe" fairings covering the tracks and screw jacks that move the trailing-edge flaps.', location: `Under the ${m[1]} wing trailing edge.`, accuracyNote: APPROX }) },
  { test: /^horizontal_stabilizer_(left|right)$/, data: (id, m) => ({ label: `Horizontal stabiliser, ${m[1]}`, category: 'Tail', layer: 'wings', description: 'Tailplane half. The whole stabiliser pivots to trim the aircraft in pitch, driven by a jackscrew; the elevator hinges from its trailing edge.', location: 'Tail.', specs: { Span: '14.35 m (47 ft 1 in)' }, sources: ['acapsNG'] }) },
  { test: /^vertical_fin$/, data: () => ({ label: 'Vertical fin', category: 'Tail', layer: 'wings', description: 'Fixed fin with a dorsal fillet. Gives directional stability; the rudder hinges from its trailing edge.', location: 'Top of the tail; its tip is the highest point, 12.55 m (41 ft 2 in) above the ground.', sources: ['acapsNG'] }) },
  { test: /^stabilizer_jackscrew$/, data: () => ({ label: 'Stabiliser trim jackscrew', category: 'Flight controls', layer: 'controls', description: 'Ball-screw actuator that moves the stabiliser leading edge up or down. Driven by an electric trim motor, the autopilot, or the pilots through the trim wheels and cables.', location: 'Inside the tail, ahead of the stabiliser pivot.', maintenance: 'Its lubrication and wear checks are safety-critical inspections.', accuracyNote: APPROX }) },
  /* ------------------------------------------------------- control surfaces */
  { test: /^aileron_(left|right)$/, data: (id, m) => ({ label: `Aileron, ${m[1]}`, category: 'Flight controls', layer: 'controls', description: 'Outboard trailing-edge surface that rolls the aircraft; the ailerons move in opposite directions. Hydraulically powered, with manual reversion through cables if both hydraulic systems fail.', location: `${cap(m[1])} wing, outboard trailing edge.`, sources: ['controls'] }) },
  { test: /^elevator_(left|right)$/, data: (id, m) => ({ label: `Elevator, ${m[1]}`, category: 'Flight controls', layer: 'controls', description: 'Pitches the nose up or down. Hydraulically powered with manual reversion; balance tabs help the pilot in manual mode.', location: `${cap(m[1])} stabiliser trailing edge.`, sources: ['controls'] }) },
  { test: /^rudder$/, data: () => ({ label: 'Rudder', category: 'Flight controls', layer: 'controls', description: 'Yaws the nose left or right, controlled by the pedals. Powered by a main rudder power control unit with a standby unit.', location: 'Trailing edge of the fin.', sources: ['controls'] }) },
  { test: /^flap_(inboard|outboard)_(left|right)$/, data: (id, m) => ({ label: `${cap(m[1])} trailing-edge flap, ${m[2]}`, category: 'High-lift devices', layer: 'controls', description: 'Double-slotted flap that runs aft on tracks and tilts down, adding wing area and camber for takeoff and landing. Selected with the flap lever at 1, 2, 5, 10, 15, 25, 30 or 40.', location: `${cap(m[2])} wing trailing edge, ${m[1] === 'inboard' ? 'inboard of the engine' : 'outboard of the engine'}.`, sources: ['controls'] }) },
  { test: /^slat_(\d)_(left|right)$/, data: (id, m) => ({ label: `Leading-edge slat ${m[1]}, ${m[2]}`, category: 'High-lift devices', layer: 'controls', description: 'Slat on the leading edge outboard of the engine. It moves forward and down with the flaps, opening a slot that keeps airflow attached at high angles of attack.', location: `${cap(m[2])} wing leading edge, outboard of the engine.`, sources: ['controls'] }) },
  { test: /^krueger_flap_(\d)_(left|right)$/, data: (id, m) => ({ label: `Krueger flap ${m[1]}, ${m[2]}`, category: 'High-lift devices', layer: 'controls', description: 'Hinged panel under the inboard leading edge that swings down and forward when the flaps are extended.', location: `${cap(m[2])} wing, lower leading edge between the fuselage and the engine.`, sources: ['controls'] }) },
  { test: /^spoiler_(\d)_(left|right)$/, data: (id, m) => ({ label: `Spoiler ${m[1]}, ${m[2]} (${['1', '6'].includes(m[1]) ? 'ground' : 'flight'})`, category: 'Flight controls', layer: 'controls', description: ['1', '6'].includes(m[1]) ? 'Ground spoiler: rises only on the ground, after touchdown or in a rejected takeoff, to dump lift and put weight on the wheels for braking.' : 'Flight spoiler: rises on one wing to help the ailerons roll the aircraft, rises on both wings as a speed brake, and on the ground with the ground spoilers.', location: `${cap(m[2])} wing upper surface, ahead of the flaps (numbered from inboard).`, sources: ['controls'], accuracyNote: APPROX }) },
  /* -------------------------------------------------------------- engines */
  { test: /^engine_inlet_cowl_(left|right)$/, data: (id, m) => ({ label: `Engine inlet cowl, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Inlet that slows and guides air into the fan. The lower lip is flattened because the 737 sits close to the ground; its leading edge is kept free of ice with bleed air.', location: `${engineNo(m[1])} engine, front of the nacelle.`, sources: ['cfm'] }) },
  { test: /^engine_fan_cowl_(left|right)$/, data: (id, m) => ({ label: `Fan cowl doors, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Two hinged panels around the fan case, latched underneath. They open upward to reach the accessory gearbox, oil tank and other line-maintenance items.', location: `${engineNo(m[1])} engine, middle of the nacelle.`, maintenance: 'Latch checks are part of every walk-around: an unlatched fan cowl can separate in flight.' }) },
  { test: /^thrust_reverser_(left|right)$/, data: (id, m) => ({ label: `Thrust reverser sleeves, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Translating sleeves that slide aft after landing, uncovering cascade vanes and closing blocker doors so fan air is turned forward to slow the aircraft.', location: `${engineNo(m[1])} engine, rear of the nacelle.`, sources: ['cfm'] }) },
  { test: /^thrust_reverser_cascades_(left|right)$/, data: (id, m) => ({ label: `Thrust reverser cascades, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Rings of turning vanes, exposed when the sleeves move aft, that direct the fan stream forward.', location: `${engineNo(m[1])} engine, under the reverser sleeves.` }) },
  { test: /^engine_fan_(left|right)$/, data: (id, m) => ({ label: `Fan and spinner, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'CFM56-7B fan, 1.55 m (61 in) across, with 24 wide-chord titanium blades. Most of the engine’s thrust comes from air the fan drives around the core (bypass ratio about 5.1–5.5).', location: `${engineNo(m[1])} engine, behind the inlet.`, specs: { 'Fan diameter': '1.55 m (61 in)', Blades: '24' }, sources: ['cfm', 'mtu'] }) },
  { test: /^engine_core_(left|right)$/, data: (id, m) => ({ label: `CFM56-7B core engine, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Two-spool turbofan core: booster, 9-stage high-pressure compressor, annular combustor, single-stage high-pressure turbine, and a 4-stage low-pressure turbine driving the fan.', location: `${engineNo(m[1])} engine, inside the nacelle.`, specs: { Thrust: '24,200–27,300 lbf (108–121 kN), by rating', Model: 'CFM56-7B24 / -7B26 / -7B27 (operator choice)' }, sources: ['cfm', 'mtu'] }) },
  { test: /^engine_core_cowl_(left|right)$/, data: (id, m) => ({ label: `Core cowl, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Cowl round the core engine, inside the fan duct.', location: `${engineNo(m[1])} engine, behind the reverser.` }) },
  { test: /^engine_exhaust_nozzle_(left|right)$/, data: (id, m) => ({ label: `Primary exhaust nozzle, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Nozzle for the hot core exhaust.', location: `${engineNo(m[1])} engine, rear.` }) },
  { test: /^engine_exhaust_plug_(left|right)$/, data: (id, m) => ({ label: `Exhaust plug, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Centre body that shapes the core exhaust flow.', location: `${engineNo(m[1])} engine, rear.` }) },
  { test: /^engine_accessory_gearbox_(left|right)$/, data: (id, m) => ({ label: `Accessory gearbox, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Gearbox driven from the core that runs the fuel pump, oil pumps, hydraulic pump and the integrated drive generator. On the CFM56-7 it sits on the side of the fan case, which is what allows the flattened lower nacelle.', location: `${engineNo(m[1])} engine, lower side of the fan case.`, accuracyNote: APPROX }) },
  { test: /^engine_oil_tank_(left|right)$/, data: (id, m) => ({ label: `Engine oil tank, ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Oil reservoir for the engine’s bearings and gearboxes, serviced through a filler behind the fan cowl.', location: `${engineNo(m[1])} engine, on the fan case.`, maintenance: 'Check the quantity shortly after shutdown, as the manual directs; overfilling is also a fault.', accuracyNote: APPROX }) },
  { test: /^engine_pylon_(left|right)$/, data: (id, m) => ({ label: `Engine strut (pylon), ${engineNo(m[1])}`, category: 'Engines', layer: 'engines', description: 'Structure that hangs the engine ahead of and below the wing and carries the fuel, bleed-air and hydraulic lines. Its fuse pins let the engine break away cleanly in an extreme load.', location: `Under the ${m[1]} wing.` }) },
  { test: /^engine_fire_handles$/, data: () => ({ label: 'Engine and APU fire switches', category: 'Flight deck', layer: 'cockpit', description: 'Fire handles for engine 1, the APU and engine 2. Pulling a handle shuts off fuel, bleed air, hydraulics and the generator for that engine; turning it fires an extinguisher bottle.', location: 'Fire protection panel on the aft electronic panel.', accuracyNote: APPROX }) },
  /* ---------------------------------------------------------------- gear */
  { test: /^main_gear_shock_strut_(left|right)$/, data: (id, m) => ({ label: `Main gear shock strut, ${m[1]}`, category: 'Landing gear', layer: 'gear', description: 'Oleo-pneumatic strut (nitrogen and hydraulic fluid) that absorbs landing loads. It hangs from the wing rear spar and a gear beam, and retracts inboard so the wheels lie in the fuselage well. The 737’s main-gear wells have no doors: the tyres’ outer faces complete the belly line.', location: `Under the ${m[1]} wing root.`, sources: ['gear'] }) },
  { test: /^main_gear_(torsion_links|side_brace|strut_door)_(left|right)$/, data: (id, m) => ({ label: `Main gear ${m[1].replace(/_/g, ' ')}, ${m[2]}`, category: 'Landing gear', layer: 'gear', description: { torsion_links: 'Scissor links that stop the inner cylinder turning in the outer one while letting it slide.', side_brace: 'Folding brace that locks the gear down and folds as it retracts.', strut_door: 'Panel on the strut that closes the leg’s part of the wheel well when retracted.' }[m[1]], location: `${cap(m[2])} main gear.`, sources: ['gear'] }) },
  { test: /^main_tyre_(inboard|outboard)_(left|right)$/, data: (id, m) => ({ label: `Main tyre, ${m[2]} ${m[1]}`, category: 'Landing gear', layer: 'gear', description: 'Bias or radial main tyre, inflated with nitrogen. Each main gear carries two.', location: `${cap(m[2])} main gear, ${m[1]} wheel.`, specs: { Size: 'H44.5 × 16.5-21' }, maintenance: 'Pressure is checked cold, daily; a fusible plug in the wheel releases pressure if the brakes overheat.', sources: ['tyres', 'gear'] }) },
  { test: /^main_wheel_(inboard|outboard)_(left|right)$/, data: (id, m) => ({ label: `Main wheel, ${m[2]} ${m[1]}`, category: 'Landing gear', layer: 'gear', description: 'Split-hub wheel with fusible plugs and a tyre-pressure indicator on some aircraft.', location: `${cap(m[2])} main gear.` }) },
  { test: /^main_wheel_brake_(inboard|outboard)_(left|right)$/, data: (id, m) => ({ label: `Wheel brake, ${m[2]} ${m[1]}`, category: 'Landing gear', layer: 'gear', description: 'Multi-disc brake (steel or carbon, by option) with anti-skid and autobrake control. Wear pins show how much lining is left.', location: `Inside the ${m[2]} ${m[1]} main wheel.`, maintenance: 'Brake wear is checked on the walk-around by the length of the wear pins.' }) },
  { test: /^main_wheel_well$/, data: () => ({ label: 'Main wheel well', category: 'Landing gear', layer: 'gear', description: 'Bay in the centre fuselage behind the wing box where the main wheels stow. The hydraulic reservoirs and many system components are reachable here.', location: 'Belly, behind the wing centre section.', accuracyNote: APPROX }) },
  { test: /^nose_gear_(shock_strut|drag_brace|steering)$/, data: (id, m) => ({ label: `Nose gear ${m[1].replace(/_/g, ' ')}`, category: 'Landing gear', layer: 'gear', description: { shock_strut: 'Oleo strut of the nose gear; it retracts forward into the well under the flight deck.', drag_brace: 'Folding brace that locks the nose gear down.', steering: 'Hydraulic nose-wheel steering, commanded by the captain’s tiller (up to about 78°) or, over a smaller range, by the rudder pedals.' }[m[1]], location: 'Nose gear, below the flight deck.', sources: ['gear'] }) },
  { test: /^nose_(tyre|wheel)_(left|right)$/, data: (id, m) => ({ label: `Nose ${m[1]}, ${m[2]}`, category: 'Landing gear', layer: 'gear', description: m[1] === 'tyre' ? 'Nose-wheel tyre; the nose gear has two.' : 'Nose-wheel rim.', location: 'Nose gear.', specs: m[1] === 'tyre' ? { Size: '27 × 7.75-15' } : undefined, sources: ['tyres'] }) },
  { test: /^nose_gear_door_(left|right)$/, data: (id, m) => ({ label: `Nose gear door, ${m[1]}`, category: 'Landing gear', layer: 'gear', description: 'Door that closes the nose-gear well once the gear is up.', location: 'Underside of the nose.' }) },
  /* ------------------------------------------------------------ lighting */
  { test: /^navigation_light_(left|right)$/, data: (id, m) => ({ label: `Position light, ${m[1]}`, category: 'Lighting', layer: 'lighting', description: `${m[1] === 'left' ? 'Red' : 'Green'} forward position light, with a white light facing aft.`, location: `${cap(m[1])} wingtip.` }) },
  { test: /^strobe_lights$/, data: () => ({ label: 'Anti-collision strobes', category: 'Lighting', layer: 'lighting', description: 'White flashing strobes on each wingtip and the tail cone, switched on when entering the runway.', location: 'Wingtips and tail cone.' }) },
  { test: /^anti_collision_beacon_(upper|lower)$/, data: (id, m) => ({ label: `Red anti-collision beacon, ${m[1]}`, category: 'Lighting', layer: 'lighting', description: 'Red rotating beacon. It goes on before engine start or pushback and tells ground staff to keep clear.', location: m[1] === 'upper' ? 'Top of the fuselage.' : 'Belly, behind the wing.' }) },
  { test: /^landing_lights$/, data: () => ({ label: 'Landing lights', category: 'Lighting', layer: 'lighting', description: 'Fixed landing lights in the wing roots (some aircraft also have retractable outboard lights).', location: 'Wing-root leading edges.', accuracyNote: APPROX }) },
  { test: /^runway_turnoff_lights$/, data: () => ({ label: 'Runway turnoff lights', category: 'Lighting', layer: 'lighting', description: 'Lights angled outward to show taxiway exits.', location: 'Wing-root leading edges.', accuracyNote: APPROX }) },
  { test: /^taxi_light$/, data: () => ({ label: 'Taxi light', category: 'Lighting', layer: 'lighting', description: 'Forward-facing light on the nose-gear strut; it retracts with the gear.', location: 'Nose gear strut.' }) },
  { test: /^logo_lights$/, data: () => ({ label: 'Logo lights', category: 'Lighting', layer: 'lighting', description: 'Lights on the stabilisers shining on the airline’s logo on the fin.', location: 'Upper surfaces of the horizontal stabiliser.', accuracyNote: APPROX }) },
  { test: /^wing_illumination_lights$/, data: () => ({ label: 'Wing illumination lights', category: 'Lighting', layer: 'lighting', description: 'Lights on the fuselage that light up the wing leading edges so the crew can check for ice at night.', location: 'Fuselage sides above the wing roots.' }) },
  /* ------------------------------------------------------------- sensors */
  { test: /^pitot_probes$/, data: () => ({ label: 'Pitot probes', category: 'Sensors', layer: 'sensors', description: 'Heated probes that measure ram-air pressure for airspeed: captain’s, first officer’s and auxiliary. Blocked or iced pitots give false airspeed.', location: 'Nose, below the flight deck windows.', maintenance: 'Covers are fitted on the ground and must be removed before flight; the probes are hot when heat is on.', accuracyNote: APPROX }) },
  { test: /^angle_of_attack_vanes$/, data: () => ({ label: 'Angle-of-attack vanes', category: 'Sensors', layer: 'sensors', description: 'Vanes that align with the local airflow to measure angle of attack for the stall warning (stick shaker) and flight instruments.', location: 'Each side of the nose.', accuracyNote: APPROX }) },
  { test: /^total_air_temperature_probe$/, data: () => ({ label: 'Total air temperature probe', category: 'Sensors', layer: 'sensors', description: 'Measures the air temperature including the heating from compression, for engine and air-data calculations.', location: 'Left side of the nose.', accuracyNote: APPROX }) },
  { test: /^static_ports$/, data: () => ({ label: 'Static ports', category: 'Sensors', layer: 'sensors', description: 'Flush ports that sense outside static pressure for the altimeter and vertical speed. The area around them must be kept clean and unpainted.', location: 'Both sides of the forward fuselage.', accuracyNote: APPROX }) },
  { test: /^elevator_feel_pitots$/, data: () => ({ label: 'Elevator feel pitot probes', category: 'Sensors', layer: 'sensors', description: 'Probes on the fin that feed the elevator feel computer, which makes the control column heavier as speed rises.', location: 'Each side of the vertical fin.', accuracyNote: APPROX }) },
  { test: /^antennas$/, data: () => ({ label: 'Antennas', category: 'Sensors', layer: 'sensors', description: 'VHF communication, ATC transponder, TCAS and GPS antennas on the top and bottom of the fuselage.', location: 'Top and bottom of the fuselage.', accuracyNote: APPROX }) },
  { test: /^weather_radar_antenna$/, data: () => ({ label: 'Weather radar antenna', category: 'Sensors', layer: 'sensors', description: 'Flat-plate antenna that scans ahead for precipitation and wind shear; shown on the navigation displays.', location: 'Inside the radome.' }) },
  /* --------------------------------------------------------- flight deck */
  { test: /^flight_deck_floor$/, data: () => ({ label: 'Flight deck floor', category: 'Flight deck', layer: 'cockpit', description: 'Floor of the flight deck, above the electronics bay and nose-gear well.', location: 'Flight deck.' }) },
  { test: /^main_instrument_panel$/, data: () => ({ label: 'Main instrument panel', category: 'Flight deck', layer: 'cockpit', description: 'Forward panel carrying the six display units, standby instruments, landing-gear lever and autobrake selector.', location: 'In front of the pilots.' }) },
  { test: /^display_units_(captain|first_officer|center)$/, data: (id, m) => ({ label: { captain: 'Captain’s display units (PFD and ND)', first_officer: 'First officer’s display units (PFD and ND)', center: 'Centre display units (engines)' }[m[1]], category: 'Flight deck', layer: 'cockpit', description: m[1] === 'center' ? 'Upper display shows primary engine indications and alerts; the lower one shows secondary engine data or systems pages.' : 'Outboard: primary flight display (attitude, speed, altitude, heading, flight-mode annunciations). Inboard: navigation display (map, route, weather, traffic).', location: m[1] === 'center' ? 'Centre of the main panel.' : `${m[1] === 'captain' ? 'Left' : 'Right'} side of the main panel.` }) },
  { test: /^standby_flight_display$/, data: () => ({ label: 'Integrated standby flight display', category: 'Flight deck', layer: 'cockpit', description: 'Independent standby attitude, altitude and airspeed display (older aircraft have separate standby instruments).', location: 'Main panel, left of centre.', accuracyNote: APPROX }) },
  { test: /^landing_gear_lever$/, data: () => ({ label: 'Landing gear lever', category: 'Flight deck', layer: 'cockpit', description: 'Selects gear UP, OFF or DOWN. The handle is wheel-shaped so it can be recognised by touch; three green lights confirm the gear is down and locked.', location: 'Centre panel, right of the engine display.' }) },
  { test: /^autobrake_selector$/, data: () => ({ label: 'Autobrake selector', category: 'Flight deck', layer: 'cockpit', description: 'Selects automatic braking for landing (1, 2, 3, MAX) or rejected takeoff (RTO).', location: 'Centre panel.', accuracyNote: APPROX }) },
  { test: /^glareshield$/, data: () => ({ label: 'Glareshield', category: 'Flight deck', layer: 'cockpit', description: 'Hood over the instrument panel that keeps sunlight off the displays; the autopilot and EFIS controls are on its face.', location: 'Top of the main panel.' }) },
  { test: /^mode_control_panel$/, data: () => ({ label: 'Mode control panel (MCP)', category: 'Flight deck', layer: 'cockpit', description: 'Autopilot, flight director and autothrottle controls: speed, heading, altitude and vertical speed selectors, the lateral and vertical mode buttons and the autopilot engage switches.', location: 'Centre of the glareshield.' }) },
  { test: /^efis_control_panels$/, data: () => ({ label: 'EFIS control panels', category: 'Flight deck', layer: 'cockpit', description: 'One per pilot: barometric setting, minimums, navigation display mode and range, and map overlays (weather, airports, waypoints, terrain).', location: 'Glareshield, each side of the MCP.' }) },
  { test: /^master_caution_lights$/, data: () => ({ label: 'Fire warning and master caution lights', category: 'Flight deck', layer: 'cockpit', description: 'Red FIRE WARN and amber MASTER CAUTION lights in front of each pilot, with the six-pack system annunciator panel that tells you which overhead panel to look at.', location: 'Outer ends of the glareshield.' }) },
  { test: /^overhead_panel$/, data: () => ({ label: 'Overhead panel', category: 'Flight deck', layer: 'cockpit', description: 'Systems panel: flight controls, fuel, electrical, APU, engine start, hydraulics, air conditioning and pressurisation, anti-ice, and lights.', location: 'Ceiling above the pilots.' }) },
  { test: /^forward_overhead_panel$/, data: () => ({ label: 'Forward overhead panel', category: 'Flight deck', layer: 'cockpit', description: 'Front part of the overhead panel.', location: 'Ceiling, just behind the windshield.', accuracyNote: APPROX }) },
  { test: /^control_stand$/, data: () => ({ label: 'Control stand (throttle quadrant)', category: 'Flight deck', layer: 'cockpit', description: 'Pedestal between the pilots with the thrust and reverse levers, speed brake lever, flap lever, stabiliser trim wheels and cutout switches, parking brake and start levers.', location: 'Between the pilots’ seats.' }) },
  { test: /^thrust_levers$/, data: () => ({ label: 'Thrust levers', category: 'Flight deck', layer: 'cockpit', description: 'Set engine thrust; they move by themselves when the autothrottle is engaged. TO/GA switches below the knobs, and autothrottle disconnect switches on the outboard sides. Reverse thrust levers ride on their fronts.', location: 'Control stand.' }) },
  { test: /^flap_lever$/, data: () => ({ label: 'Flap lever', category: 'Flight deck', layer: 'cockpit', description: 'Selects flap position UP, 1, 2, 5, 10, 15, 25, 30 or 40. Gates at 1 and 15 stop over-selection during a go-around.', location: 'Right side of the control stand.' }) },
  { test: /^speed_brake_lever$/, data: () => ({ label: 'Speed brake lever', category: 'Flight deck', layer: 'cockpit', description: 'Raises the spoilers: FLIGHT DETENT in the air, UP on the ground. In ARMED it deploys all spoilers automatically at touchdown.', location: 'Left side of the control stand.' }) },
  { test: /^stabilizer_trim_wheels$/, data: () => ({ label: 'Stabiliser trim wheels', category: 'Flight deck', layer: 'cockpit', description: 'Wheels on each side of the stand that turn whenever the stabiliser trims, and can be wound by hand to trim manually.', location: 'Sides of the control stand.' }) },
  { test: /^start_levers$/, data: () => ({ label: 'Engine start levers', category: 'Flight deck', layer: 'cockpit', description: 'IDLE opens the fuel valve and powers ignition during start; CUTOFF shuts the engine down.', location: 'Control stand, behind the thrust levers.' }) },
  { test: /^parking_brake_lever$/, data: () => ({ label: 'Parking brake lever', category: 'Flight deck', layer: 'cockpit', description: 'Set with the brake pedals pressed; a red light shows it is set.', location: 'Front left of the control stand.', accuracyNote: APPROX }) },
  { test: /^aft_electronic_panel$/, data: () => ({ label: 'Aft electronic panel', category: 'Flight deck', layer: 'cockpit', description: 'Radios, audio control panels, transponder and TCAS, weather radar, fire protection, and the aileron and rudder trim.', location: 'Rear of the pedestal.' }) },
  { test: /^control_column_(captain|first_officer)$/, data: (id, m) => ({ label: `Control column, ${m[1] === 'captain' ? 'captain' : 'first officer'}`, category: 'Flight deck', layer: 'cockpit', description: 'Push for nose down, pull for nose up. The two columns are linked; it shakes (stick shaker) as a stall warning.', location: `In front of the ${m[1] === 'captain' ? 'left' : 'right'} seat.` }) },
  { test: /^control_wheel_(captain|first_officer)$/, data: (id, m) => ({ label: `Control wheel, ${m[1] === 'captain' ? 'captain' : 'first officer'}`, category: 'Flight deck', layer: 'cockpit', description: 'Turn to roll; carries the stabiliser trim switches, autopilot disconnect and microphone switches.', location: `Top of the ${m[1] === 'captain' ? 'captain’s' : 'first officer’s'} column.` }) },
  { test: /^rudder_pedals_(captain|first_officer)$/, data: (id, m) => ({ label: `Rudder pedals, ${m[1] === 'captain' ? 'captain' : 'first officer'}`, category: 'Flight deck', layer: 'cockpit', description: 'Push left or right to move the rudder; press the tops for wheel brakes. They also steer the nose wheel a few degrees.', location: `Footwell of the ${m[1] === 'captain' ? 'left' : 'right'} seat.` }) },
  { test: /^pilot_seat_(captain|first_officer)$/, data: (id, m) => ({ label: `Pilot seat, ${m[1] === 'captain' ? 'captain (left)' : 'first officer (right)'}`, category: 'Flight deck', layer: 'cockpit', description: 'Adjustable seat with a five-point harness. Pilots set their eye height with the reference marks on the centre windshield post.', location: `${m[1] === 'captain' ? 'Left' : 'Right'} side of the flight deck.` }) },
  { test: /^headrest_(captain|first_officer)$/, data: (id, m) => ({ label: `Seat headrest, ${m[1] === 'captain' ? 'captain' : 'first officer'}`, category: 'Flight deck', layer: 'cockpit', description: 'Headrest of the pilot seat.', location: 'Top of the pilot seat.' }) },
  { test: /^observer_seat$/, data: () => ({ label: 'Observer (jump) seat', category: 'Flight deck', layer: 'cockpit', description: 'Fold-down seat for a check pilot, inspector or extra crew.', location: 'Behind the captain.', accuracyNote: APPROX }) },
  { test: /^windshield_wipers$/, data: () => ({ label: 'Windshield wipers', category: 'Flight deck', layer: 'cockpit', description: 'Wipers for the No. 1 windshields, used in rain on the ground and at low speed.', location: 'Base of the front windshields.', accuracyNote: APPROX }) },
  /* ---------------------------------------------------------------- cabin */
  { test: /^cabin_floor$/, data: () => ({ label: 'Cabin floor', category: 'Cabin', layer: 'cabin', description: 'Floor panels over the floor beams, with seat tracks for the passenger seats. The cabin is 3.54 m (11 ft 7 in) wide.', location: 'Cabin.', sources: ['acapsNG'] }) },
  { test: /^floor_beams$/, data: () => ({ label: 'Floor beams', category: 'Structure', layer: 'structure', description: 'Transverse beams that carry the cabin floor and separate the cabin from the cargo holds.', location: 'Below the cabin floor.' }) },
  { test: /^passenger_seats_(forward|main)_cabin$/, data: (id, m) => ({ label: m[1] === 'forward' ? 'Passenger seats, forward cabin (2-2)' : 'Passenger seats, main cabin (3-3)', category: 'Cabin', layer: 'cabin', description: m[1] === 'forward' ? 'A typical two-class layout: 16 wider seats four abreast at about 38 in pitch.' : 'Six abreast at about 31 in pitch. Airlines choose their own layout: typically 162 in two classes, up to 189 in one class (the exit limit).', location: 'Cabin.', accuracyNote: 'Seating shown is one representative layout; each airline configures its own.' }) },
  { test: /^overhead_bins_(left|right)$/, data: (id, m) => ({ label: `Overhead bins, ${m[1]}`, category: 'Cabin', layer: 'cabin', description: 'Stowage bins above the seats.', location: `${cap(m[1])} side of the cabin.` }) },
  { test: /^cabin_ceiling_panels$/, data: () => ({ label: 'Cabin ceiling panels', category: 'Cabin', layer: 'cabin', description: 'Ceiling lining with lighting and air outlets.', location: 'Cabin ceiling.' }) },
  { test: /^galley_(forward|aft)$/, data: (id, m) => ({ label: `${cap(m[1])} galley`, category: 'Cabin', layer: 'cabin', description: 'Galley with ovens, water boiler, trolleys and stowage.', location: m[1] === 'forward' ? 'Right side, behind the flight deck.' : 'Rear of the cabin.', accuracyNote: APPROX }) },
  { test: /^lavator(y_forward|ies_aft)$/, data: (id, m) => ({ label: m[1] === 'y_forward' ? 'Forward lavatory' : 'Aft lavatories', category: 'Cabin', layer: 'cabin', description: 'Lavatory with a vacuum toilet and a smoke detector.', location: m[1] === 'y_forward' ? 'Left side, behind the flight deck.' : 'Rear cabin, both sides.', accuracyNote: APPROX }) },
  { test: /^flight_attendant_seats$/, data: () => ({ label: 'Flight attendant seats', category: 'Cabin', layer: 'cabin', description: 'Fold-down seats by the exits for cabin crew during taxi, takeoff and landing.', location: 'By the forward and aft doors.', accuracyNote: APPROX }) },
  /* ---------------------------------------------------------------- cargo */
  { test: /^cargo_hold_(forward|aft)$/, data: (id, m) => ({ label: `${cap(m[1])} cargo hold`, category: 'Cargo', layer: 'cargo', description: `Lined, pressurised and fire-protected bulk hold ${m[1] === 'forward' ? 'ahead of the wing' : 'behind the main-gear well'}. Together the holds give about 44 m³ (1,555 cu ft).`, location: 'Below the cabin floor.', sources: ['wiki'] }) },
  /* ------------------------------------------------------------ structure */
  { test: /^(forward|aft)_pressure_bulkhead$/, data: (id, m) => ({ label: `${cap(m[1])} pressure bulkhead`, category: 'Structure', layer: 'structure', description: m[1] === 'forward' ? 'Bulkhead that closes the front of the pressurised fuselage, behind the radome.' : 'Domed bulkhead that closes the rear of the pressure vessel; everything behind it (tail cone, APU) is unpressurised.', location: m[1] === 'forward' ? 'Behind the radome.' : 'Behind the aft galley.' }) },
  { test: /^keel_beam$/, data: () => ({ label: 'Keel beam', category: 'Structure', layer: 'structure', description: 'Heavy beam along the bottom of the fuselage that carries bending loads past the cut-out of the main-gear well.', location: 'Centre fuselage, between the wheel wells.', accuracyNote: APPROX }) },
  { test: /^wing_center_box$/, data: () => ({ label: 'Wing centre section', category: 'Structure', layer: 'structure', description: 'Spars and ribs of the wing box passing through the fuselage, joining the two wings; it also forms the centre fuel tank.', location: 'Centre fuselage, below the cabin floor.' }) },
  { test: /^wing_spars_(left|right)$/, data: (id, m) => ({ label: `Wing spars, ${m[1]}`, category: 'Structure', layer: 'structure', description: 'Front and rear spars, the main bending members of the wing. The fuel tank lies between them.', location: `${cap(m[1])} wing.` }) },
  /* -------------------------------------------------------------- systems */
  { test: /^fuel_tank_main_(left|right)$/, data: (id, m) => ({ label: `Main fuel tank ${m[1] === 'left' ? '1 (left)' : '2 (right)'}`, category: 'Fuel', layer: 'systems', description: 'Integral tank in the wing box, feeding its own engine through two boost pumps; a crossfeed valve connects the two sides.', location: `${cap(m[1])} wing, between the spars.`, specs: { 'Total fuel (all tanks)': '26,020 L (6,875 US gal)' }, sources: ['acapsNG', 'wiki'] }) },
  { test: /^fuel_tank_center$/, data: () => ({ label: 'Centre fuel tank', category: 'Fuel', layer: 'systems', description: 'Tank in the wing centre section and inboard wing roots. It is used first, while the main tanks stay full; its pumps are switched off when it is empty.', location: 'Centre wing section under the cabin.', sources: ['wiki'] }) },
  { test: /^fuel_surge_tank_(left|right)$/, data: (id, m) => ({ label: `Surge tank, ${m[1]}`, category: 'Fuel', layer: 'systems', description: 'Vent tank near the wingtip that catches fuel that overflows through the vent system and lets the tanks breathe.', location: `${cap(m[1])} wing, outboard.`, accuracyNote: APPROX }) },
  { test: /^single_point_refuelling_panel$/, data: () => ({ label: 'Single-point refuelling station', category: 'Fuel', layer: 'systems', description: 'Pressure refuelling connection and control panel. The fueller sets the quantity for each tank and the valves close automatically.', location: 'Under the right wing, outboard of the engine.', accuracyNote: APPROX }) },
  { test: /^apu$/, data: () => ({ label: 'Auxiliary power unit (APU)', category: 'APU', layer: 'systems', description: 'Small gas turbine (Honeywell 131-9B on most Next-Generation aircraft) that supplies electrical power and bleed air for air conditioning and engine starting on the ground, and backup power in flight.', location: 'Tail cone.', sources: ['wiki'] }) },
  { test: /^apu_inlet_door$/, data: () => ({ label: 'APU air inlet door', category: 'APU', layer: 'systems', description: 'Door that opens when the APU is started and closes after shutdown.', location: 'Right side of the tail cone.', accuracyNote: APPROX }) },
  { test: /^air_conditioning_packs$/, data: () => ({ label: 'Air conditioning packs', category: 'Systems', layer: 'systems', description: 'Two air-cycle machines that cool and condition engine or APU bleed air for the cabin and flight deck, and supply pressurisation air.', location: 'Wing-to-body fairing, under the centre wing section.' }) },
  { test: /^hydraulic_reservoirs$/, data: () => ({ label: 'Hydraulic reservoirs', category: 'Systems', layer: 'systems', description: 'Reservoirs for hydraulic systems A and B and the standby system (3,000 psi). A and B power the flight controls, gear, brakes, flaps and reversers; standby backs up the rudder, reversers and leading-edge devices.', location: 'Main wheel well.', accuracyNote: APPROX }) },
  { test: /^electronics_equipment_bay$/, data: () => ({ label: 'Electronics and equipment (E&E) bay', category: 'Systems', layer: 'systems', description: 'Racks of avionics computers, power distribution and the main battery.', location: 'Below the flight deck and forward cabin.', accuracyNote: APPROX }) },
  { test: /^main_battery$/, data: () => ({ label: 'Main battery', category: 'Systems', layer: 'systems', description: 'Nickel-cadmium battery that powers essential systems when no generator is available and starts the APU.', location: 'Electronics bay.', accuracyNote: APPROX }) },
  { test: /^oxygen_cylinder$/, data: () => ({ label: 'Crew oxygen cylinder', category: 'Systems', layer: 'systems', description: 'Supplies the flight crew’s quick-donning masks. Passengers’ masks are fed by chemical generators above the seats.', location: 'Forward lower fuselage.', accuracyNote: APPROX }) }
];

export const describeComponent = makeDescriber({ families: FAMILIES, sources: SOURCES, defaultSources: ['acapsNG'], accuracyNote: 'Geometry is a representative procedural model built from published dimensions.' });

export function specSheet() {
  return makeSheet({
    vehicle: 'Boeing 737-800', generation: 'Next Generation',
    sources: SOURCES, sourceKeys: ['acapsNG', 'acaps', 'wiki', 'cfm', 'mtu', 'tyres', 'gear', 'controls'],
    groups: [
      { title: 'Overview', rows: [['Type', 'Narrow-body twin-engine jet airliner'], ['Family', 'Next-Generation 737 (-600, -700, -800, -900)'], ['First flight', '31 July 1997'], ['Entered service', '1998 (launch customer Hapag-Lloyd)'], ['Flight crew', 'Two pilots'], ['Seating', 'Typically 162 in two classes; up to 189 (exit limit)']] },
      { title: 'Dimensions', rows: [['Length', '39.47 m (129 ft 6 in)'], ['Wingspan', '35.79 m (117 ft 5 in) with blended winglets; 34.32 m (112 ft 7 in) without'], ['Height', '12.55 m (41 ft 2 in)'], ['Fuselage width', '3.76 m (12 ft 4 in)'], ['Cabin width', '3.54 m (11 ft 7 in)'], ['Wing area', '124.6 m² (1,341 sq ft)'], ['Wing sweep', '25° at quarter chord'], ['Wheelbase', '15.60 m (51 ft 2 in)'], ['Main gear track', '5.72 m (18 ft 9 in)']] },
      { title: 'Weights', rows: [['Maximum takeoff weight', '79,010 kg (174,200 lb)'], ['Maximum landing weight', '66,360 kg (146,300 lb)'], ['Operating empty weight', 'About 41,000 kg (90,700 lb); varies by operator']] },
      { title: 'Engines', rows: [['Engines', '2 × CFM International CFM56-7B'], ['Thrust', '24,200–27,300 lbf (108–121 kN) each, by rating (-7B24 / -7B26 / -7B27)'], ['Fan diameter', '1.55 m (61 in), 24 blades'], ['Bypass ratio', 'About 5.1–5.5'], ['APU', 'Honeywell 131-9B (most aircraft)']] },
      { title: 'Performance & fuel', rows: [['Cruise speed', 'Mach 0.785 typical'], ['Maximum operating Mach', '0.82'], ['Range', 'About 2,935 nmi (5,436 km) with typical passengers'], ['Service ceiling', '41,000 ft'], ['Fuel capacity', '26,020 L (6,875 US gal)']] },
      { title: 'Landing gear & doors', rows: [['Gear', 'Retractable tricycle; main gear retracts inboard into doorless wells'], ['Main tyres', '4 × H44.5 × 16.5-21'], ['Nose tyres', '2 × 27 × 7.75-15'], ['Passenger doors', 'Two entry doors (left) and two service doors (right), 0.86 × 1.83 m and 0.76 × 1.65 m'], ['Emergency exits', 'Four overwing exits (two each side)'], ['Cargo', 'Forward and aft bulk holds, about 44 m³ (1,555 cu ft), doors on the right side']] },
      { title: 'Systems', rows: [['Hydraulics', 'Systems A and B, plus standby, at 3,000 psi'], ['Flight controls', 'Hydraulically powered ailerons, elevators and rudder, with manual reversion for ailerons and elevators'], ['High-lift', 'Double-slotted trailing-edge flaps; leading-edge slats outboard and Krueger flaps inboard'], ['Spoilers', 'Six per wing: four flight spoilers and two ground spoilers'], ['Displays', 'Six flat-panel display units']] }
    ],
    disclaimer: `Figures come from Boeing’s airport-planning data and the public sources listed. Individual aircraft differ by operator options, engine rating and modification status. ${TRAINING} Not for operational use.`
  });
}
