/** Boeing 737-800 package definition for build-procedural-vehicle.mjs. */
import { build737 } from './b737-model.mjs';
import { describeComponent, specSheet, LAYERS } from './b737-data.mjs';

export const B737_PACKAGE = {
  vehicle: { id: 'boeing-737-800', make: 'Boeing', model: '737-800', displayName: 'Boeing 737-800', year: null, years: [1998], generation: 'Next Generation (737NG)', variant: 'Passenger · blended winglets · CFM56-7B', bodyStyle: 'Narrow-body airliner', category: 'aircraft', accuracy: 'representative' },
  build: build737,
  describe: describeComponent,
  specSheet,
  layers: LAYERS,
  layerLabel: 'Airframe, flight deck, cabin and systems',
  attribution: 'Procedural Boeing 737-800 model generated by Toolbox from published dimensions and specifications',
  notes: 'Procedural model of the Boeing 737-800 (Next Generation) with blended winglets and CFM56-7B engines. Length, wingspan, height, fuselage width and height, wheelbase, main-gear track and tyre sizes follow Boeing’s published airport-planning figures; section shapes, the wing planform between those points, the cabin layout and the placement of systems are Toolbox approximations for orientation. Doors, landing gear, flight controls, high-lift devices, spoilers, engine cowls and thrust reversers move about their real hinge lines. For learning only, not for operational use.',
  quickActions: [
    { id: 'gear', group: 'Landing gear', on: 'Retract landing gear', off: 'Extend landing gear' },
    { id: 'flaps', articulations: ['flaps_30'], on: 'Extend flaps and slats (landing)', off: 'Retract flaps and slats' },
    { id: 'spoilers', articulations: ['speedbrake_ground'], on: 'Deploy all spoilers', off: 'Stow spoilers' },
    { id: 'doors', group: 'Doors', on: 'Open passenger and service doors', off: 'Close passenger and service doors' },
    { id: 'cargo', group: 'Cargo doors', on: 'Open cargo doors', off: 'Close cargo doors' },
    { id: 'reversers', articulations: ['reverser_left', 'reverser_right'], on: 'Deploy thrust reversers', off: 'Stow thrust reversers' },
    { id: 'cowls', articulations: ['fan_cowl_left', 'fan_cowl_right'], on: 'Open engine fan cowls', off: 'Close engine fan cowls' },
    { id: 'shell', layers: ['airframe', 'doors', 'glass'], on: 'Hide fuselage skin (see inside)', off: 'Show fuselage skin' }
  ],
  cabin: { head: 'headrest_captain', headAt: [0.5, 0.45, 0.5], forward: 0.32, down: 0.06, look: 'mode_control_panel', lookAt: [0.5, 0.3, 0.3] },
  catalogEntry: {
    id: 'boeing-737-800', make: 'Boeing', model: '737-800', year: null, years: '1998–2020',
    generation: 'Next Generation (737NG)', variant: 'Passenger · blended winglets · CFM56-7B', bodyStyle: 'Narrow-body airliner', category: 'aircraft',
    aliases: ['737', 'B737', 'B738', 'Boeing 737', '737-800', '737NG', '737 NG', 'Next Generation', 'airliner', 'jet', 'plane', 'aircraft', 'airplane', 'aeroplane'],
    specifications: { bodyStyle: 'Narrow-body airliner', layout: 'Low wing, twin underwing turbofans', engine: { code: '2 × CFM56-7B' }, curbWeight: 'MTOW 79,010 kg (174,200 lb)', wheelbase: '15.60 m (51 ft 2 in)' }
  }
};
