/** Cessna 172S Skyhawk SP package definition for build-procedural-vehicle.mjs. */
import { build172 } from './c172-model.mjs';
import { describeComponent, specSheet, LAYERS } from './c172-data.mjs';

export const C172_PACKAGE = {
  vehicle: { id: 'cessna-172s', make: 'Cessna', model: '172S Skyhawk SP', displayName: 'Cessna 172S Skyhawk SP', year: null, years: [1998], generation: '172S', variant: 'Four-seat trainer and tourer · Lycoming IO-360', bodyStyle: 'Light aircraft', category: 'aircraft', accuracy: 'representative' },
  build: build172,
  describe: describeComponent,
  specSheet,
  layers: LAYERS,
  layerLabel: 'Airframe, cockpit, engine and systems',
  attribution: 'Procedural Cessna 172S model generated by Toolbox from published dimensions and specifications',
  notes: 'Procedural model of the Cessna 172S Skyhawk SP. Length, wingspan, height, wing area, wheelbase, propeller diameter and tyre sizes follow the published Pilot’s Operating Handbook figures; section shapes, planform details and the placement of engine and cabin items are Toolbox approximations for orientation. The panel shown is the conventional six-instrument layout; most aircraft built from 2005 have the Garmin G1000 instead. Doors, flaps, ailerons, elevator, trim tab, rudder, nose-wheel steering, cowling, oil door, dipstick, fuel caps and seats move about their real hinges. For learning only; the aircraft’s own handbook governs any real flight.',
  quickActions: [
    { id: 'doors', group: 'Doors', on: 'Open doors', off: 'Close doors' },
    { id: 'flaps', articulations: ['flaps_30'], on: 'Extend flaps (30°)', off: 'Retract flaps' },
    { id: 'cowling', articulations: ['cowling_upper'], on: 'Remove upper cowling', off: 'Refit upper cowling' },
    { id: 'fuel', articulations: ['fuel_cap_left', 'fuel_cap_right'], on: 'Remove fuel caps', off: 'Refit fuel caps' },
    { id: 'shell', layers: ['airframe', 'doors', 'glass'], on: 'Hide fuselage skin (see inside)', off: 'Show fuselage skin' }
  ],
  cabin: { head: 'headrest_front_left', headAt: [0.5, 0.45, 0.5], forward: 0.28, down: 0.04, look: 'flight_instruments', lookAt: [0.5, 0.5, 0.5] },
  catalogEntry: {
    id: 'cessna-172s', make: 'Cessna', model: '172S Skyhawk SP', year: null, years: '1998–present',
    generation: '172S', variant: 'Four-seat trainer and tourer · Lycoming IO-360', bodyStyle: 'Light aircraft', category: 'aircraft',
    aliases: ['Cessna', '172', 'C172', 'Cessna 172', 'Skyhawk', 'Skyhawk SP', '172S', 'plane', 'aircraft', 'airplane', 'aeroplane', 'light aircraft', 'trainer'],
    specifications: { bodyStyle: 'Light aircraft', layout: 'Strut-braced high wing, single piston engine', engine: { code: 'Lycoming IO-360-L2A, 180 hp' }, curbWeight: 'MTOW 2,550 lb (1,157 kg)', wheelbase: 'About 65 in (1.65 m)' }
  }
};
