/**
 * Reference data for the Toyota Corolla packages.
 *
 * Every figure below is attributed to a public source listed in SOURCES.
 * Where a figure is grade-, market- or year-dependent the text says so; where
 * geometry or packaging is a Toolbox approximation the component carries an
 * `accuracyNote`. Nothing here is copied from a factory repair manual.
 */

export const SOURCES = {
  wikiE170: { label: 'Wikipedia — Toyota Corolla (E170)', url: 'https://en.wikipedia.org/wiki/Toyota_Corolla_(E170)' },
  wikiE140: { label: 'Wikipedia — Toyota Corolla (E140)', url: 'https://en.wikipedia.org/wiki/Toyota_Corolla_(E140)' },
  wikiZR: { label: 'Wikipedia — Toyota ZR engine', url: 'https://en.wikipedia.org/wiki/Toyota_ZR_engine' },
  edmunds2014: { label: 'Edmunds — 2014 Corolla features & specs', url: 'https://www.edmunds.com/toyota/corolla/2014/features-specs/' },
  fleet2014: { label: 'Automotive Fleet — 2014 Corolla lineup and standard features', url: 'https://www.automotive-fleet.com/news/toyota-details-msrp-and-standard-features-for-2014-corolla-model-lineup' },
  carsTrims2014: { label: 'Cars.com — 2014 Corolla trim levels explained', url: 'https://www.cars.com/articles/2014-toyota-corolla-explaining-the-trim-levels-1420663045628/' },
  toyotaClub: { label: 'Toyota-Club.net — US Corolla (2013–2019) fluids & capacities', url: 'https://www.toyota-club.net/files/techdata/ttx/corolla_170u.htm' },
  oilDiy: { label: 'OilChangeDIY — 2015 Corolla oil & fluid specifications', url: 'https://www.oilchangediy.com/vehicles/toyota/corolla/2015' },
  torque: { label: 'TorqueSpec Database — 2003–2019 Corolla torque specs', url: 'https://torque-spec-database.com/2003-2019-toyota-corolla-torque-specs/' },
  plugs: { label: 'PlugSpecs — Toyota Corolla spark plugs', url: 'https://plugspecs.com/best-spark-plugs-for-toyota-corolla/' },
  wheels2014: { label: 'Avtoreference — 2014 Corolla wheel & tyre fitment', url: 'https://avtoreference.com/en/auto/toyota/corolla/2014/' },
  carspecs2013: { label: 'CarSpecs — 2013 Corolla S specifications', url: 'https://www.carspecs.us/cars/2013/toyota/corolla/31216' }
};

const COMMON_ENGINE = {
  code: '2ZR-FE', displacement: '1.8 L (1,798 cc) inline-4', bore: '80.5 mm × 88.3 mm',
  valvetrain: 'DOHC 16-valve, Dual VVT-i, timing chain', block: 'All-aluminium block and head',
  output: '132 hp (98 kW) @ 6,000 rpm · 128 lb-ft (174 N·m) @ 4,400 rpm', compression: '10.0 : 1'
};

export const GENERATIONS = {
  e170: {
    key: 'e170', code: 'E170', years: '2014–2016', modelYears: [2014, 2015, 2016],
    title: '2014–2016 Toyota Corolla', market: 'North America', platform: 'Toyota New MC platform',
    engine: { ...COMMON_ENGINE, eco: '2ZR-FAE with Valvematic on LE Eco grades — 140 hp, 10.5 : 1 compression' },
    transmissions: '6-speed manual (L, S Plus) · 4-speed automatic (L) · CVTi-S continuously variable (LE, LE Eco, S; S adds paddle shifters with 7 simulated steps)',
    tyres: '195/65R15, 205/55R16 or 215/45R17 depending on grade (15-inch steel to 17-inch alloy)',
    brakes: 'Ventilated front discs (275 mm). Rear drums (229 mm) on most grades; solid rear discs (259 mm) on S Plus / S Premium',
    airbags: 'Eight: driver and front-passenger front, driver knee, front-passenger seat-cushion, front seat-mounted side, and side curtains',
    headlamps: 'LED low beams with halogen high beams and LED daytime running lights (standard)',
    audio: 'L: four-speaker audio with USB. LE and above: Entune Audio with 6.1-inch touchscreen, six speakers and backup camera',
    dims: { length: '182.6 in (4,638 mm)', width: '69.9 in (1,775 mm)', height: '57.3 in (1,455 mm)', wheelbase: '106.3 in (2,700 mm)', trackF: '60.3 in', trackR: '60.4 in', curb: 'About 2,800 lb (LE / S, Edmunds); varies by grade', turning: '35.6 ft', cargo: '13.0 cu ft', cd: '0.29 (LE / S)', fuel: '13.2 US gal (50 L), regular unleaded', mpg: 'LE CVT: 28 city / 37 highway / 31 combined mpg; LE Eco up to 42 mpg highway' },
    interior: { frontHead: '38.3 in', frontLeg: '42.3 in', frontShoulder: '54.8 in', frontHip: '53.0 in', rearHead: '37.1 in', rearLeg: '41.4 in', rearShoulder: '54.8 in', rearHip: '43.9 in' },
    sources: ['wikiE170', 'edmunds2014', 'fleet2014', 'carsTrims2014', 'wikiZR']
  },
  e140: {
    key: 'e140', code: 'E140', years: '2013', modelYears: [2013],
    title: '2013 Toyota Corolla', market: 'North America', platform: 'Toyota MC platform',
    engine: { ...COMMON_ENGINE },
    transmissions: '5-speed manual or 4-speed automatic with ECT-i',
    tyres: 'P195/65R15 on 15-inch steel wheels (listed for the 2013 S automatic); fitment varies by grade',
    brakes: 'Front discs with rear drums (9.0 in / 229 mm), four-wheel ABS',
    airbags: 'Dual front, front seat-mounted side-impact, and side-curtain airbags',
    headlamps: 'Halogen headlamps',
    audio: 'Grade-dependent head unit (AM/FM/CD with USB on most grades)',
    dims: { length: '179.3 in (base) / 180.0 in (S)', width: '69.3–69.4 in', height: '57.7 in (1,465 mm)', wheelbase: '102.4 in (2,600 mm)', trackF: '60.2 in', trackR: '60.4 in', curb: '2,635–2,767 lb depending on grade', turning: '35.4 ft', cargo: '12.3 cu ft', cd: 'Not published in the cited sources', fuel: '13.2 US gal (50 L), regular unleaded', mpg: '4-speed automatic: 26 city / 34 highway / 29 combined mpg' },
    interior: { frontHead: '38.8 in', frontLeg: '41.7 in', rearHead: '37.2 in', rearLeg: '36.3 in' },
    sources: ['wikiE140', 'carspecs2013', 'wikiZR']
  }
};

export const LAYERS = [
  { id: 'body', label: 'Body panels & closures' },
  { id: 'glass', label: 'Glass' },
  { id: 'lighting', label: 'Lighting' },
  { id: 'trim', label: 'Exterior trim' },
  { id: 'structure', label: 'Body structure' },
  { id: 'interior', label: 'Interior' },
  { id: 'safety', label: 'Airbags (SRS)' },
  { id: 'engine', label: 'Engine & transaxle' },
  { id: 'bay', label: 'Engine-bay systems' },
  { id: 'chassis', label: 'Suspension, steering & brakes' },
  { id: 'wheels', label: 'Wheels & tyres' },
  { id: 'fuel', label: 'Fuel & exhaust' }
];

const APPROX = 'Shape and position are a Toolbox approximation for orientation; not a factory drawing.';
const APPROX_PKG = 'Packaging position is approximate. Confirm location on the vehicle or in the owner’s manual before servicing.';

const cap = s => s.charAt(0).toUpperCase() + s.slice(1);
function where(id) {
  const m = id.match(/(front|rear)?_?(left|right)$/);
  if (!m) return { side: null, pos: null, text: '' };
  const side = m[2], pos = m[1] || null;
  const driver = side === 'left' ? 'driver side on left-hand-drive cars' : 'passenger side on left-hand-drive cars';
  return { side, pos, text: `${pos ? cap(pos) + ' ' : ''}${side} (${driver})` };
}

/**
 * Component families. `test` matches component ids; `data(id, g)` returns metadata.
 * Order matters: the first matching family wins.
 */
const FAMILIES = [
  // ---------------------------------------------------------------- Body
  { test: /^hood$/, data: () => ({ label: 'Bonnet (hood)', category: 'Body', layer: 'body', description: 'Steel front lid covering the engine bay. Hinged at the cowl and held open by a manual prop rod; the latch is released from a lever inside the cabin, then a safety catch under the front edge.', location: 'Front of the vehicle, between the wings.', maintenance: 'Keep the latch and safety catch lubricated. Always seat the prop rod in its bonnet slot before working underneath.', failures: 'Latch cable stretch (bonnet will not release), worn hinge bushes, stone chips on the leading edge.' }) },
  { test: /^hood_inner_frame$/, data: () => ({ label: 'Bonnet inner reinforcement', category: 'Body', layer: 'body', description: 'Stamped inner frame bonded to the bonnet skin. Provides stiffness, pedestrian-impact crush space and mounting points for the latch striker and insulation.', location: 'Underside of the bonnet.' }) },
  { test: /^hood_hinges$/, data: () => ({ label: 'Bonnet hinges', category: 'Body', layer: 'body', description: 'Pivot hinges bolted to the cowl-side wing flanges; the bonnet rotates about them when opened.', location: 'Rear corners of the bonnet, near the windscreen base.' }) },
  { test: /^hood_prop_rod$/, data: () => ({ label: 'Bonnet prop rod', category: 'Body', layer: 'body', description: 'Manual support rod. Clips along the front body structure when stowed and locates into a slot under the bonnet when raised.', location: 'Front of the engine bay.', accuracyNote: APPROX_PKG }) },
  { test: /^hood_latch$/, data: () => ({ label: 'Bonnet latch', category: 'Body', layer: 'body', description: 'Primary latch released by the cabin lever and cable; a secondary safety catch prevents the bonnet opening fully at speed.', location: 'Centre of the radiator support, under the bonnet leading edge.' }) },
  { test: /^front_bumper_cover$/, data: () => ({ label: 'Front bumper cover', category: 'Body', layer: 'body', description: 'Painted plastic fascia over the energy absorber and bumper reinforcement. Carries the grilles, fog-lamp openings and licence-plate mounting.', location: 'Front of the vehicle.', failures: 'Cracked mounting tabs after minor impacts; misaligned gaps at the wing brackets.' }) },
  { test: /^rear_bumper_cover$/, data: () => ({ label: 'Rear bumper cover', category: 'Body', layer: 'body', description: 'Painted plastic rear fascia covering the rear bumper reinforcement. Carries the rear reflectors.', location: 'Rear of the vehicle.' }) },
  { test: /^rear_end_panel$/, data: () => ({ label: 'Rear end panel', category: 'Body', layer: 'body', description: 'Body panel between the boot opening and the rear bumper; carries the boot latch striker and seals the lower boot opening.', location: 'Rear, below the boot lid.' }) },
  { test: /^front_fender_/, data: id => ({ label: `Front wing (fender), ${where(id).side}`, category: 'Body', layer: 'body', description: 'Bolt-on front wing panel shaping the front wheel arch; its top flange meets the bonnet shut line.', location: where(id).text, failures: 'Minor impact damage is common; the panel is bolted on and replaceable without welding.' }) },
  { test: /^rocker_panel_/, data: id => ({ label: `Rocker panel (sill), ${where(id).side}`, category: 'Body', layer: 'body', description: 'Box-section sill beneath the doors. A key side-impact and floor-stiffness member; also a factory jacking area.', location: where(id).text, maintenance: 'Use the notched pinch-weld jacking points only. Inspect for corrosion in salted-road climates.' }) },
  { test: /^rear_quarter_panel_/, data: id => ({ label: `Rear quarter panel, ${where(id).side}`, category: 'Body', layer: 'body', description: 'Welded rear body side from the rear door to the tail lamp, forming the rear wheel arch and C-pillar base. Repair requires cutting and welding.', location: where(id).text }) },
  { test: /^wheel_well_liner_/, data: id => ({ label: `Wheel-arch liner, ${where(id).text.split(' (')[0].toLowerCase()}`, category: 'Body', layer: 'body', description: 'Plastic or fibre splash liner protecting the wheel arch from stones, water and road salt.', location: where(id).text, failures: 'Loose clips cause rubbing noises on full steering lock.' }) },
  { test: /^cowl_panel$/, data: () => ({ label: 'Cowl panel and wiper cowl', category: 'Body', layer: 'body', description: 'Plastic cowl top between bonnet and windscreen. Contains the cabin fresh-air intake and wiper linkage.', location: 'Base of the windscreen.', maintenance: 'Clear leaves from the cowl drains to keep water out of the cabin-air intake.' }) },
  { test: /^trunk_lid$/, data: () => ({ label: 'Boot lid (trunk lid)', category: 'Body', layer: 'body', description: 'Steel boot lid on gooseneck hinges, carrying the inner tail lamps, licence-plate recess and lamps.', location: 'Rear deck.', maintenance: 'Replace worn lid seals to keep water out of the spare-wheel well.' }) },
  { test: /^trunk_lid_inner_frame$/, data: () => ({ label: 'Boot lid inner frame', category: 'Body', layer: 'body', description: 'Inner reinforcement of the boot lid with the latch and hinge mounting points.', location: 'Underside of the boot lid.' }) },
  { test: /^trunk_lid_hinges$/, data: () => ({ label: 'Boot lid gooseneck hinges', category: 'Body', layer: 'body', description: 'Curved hinge arms that swing into the boot as the lid opens, assisted by torsion bars or struts.', location: 'Front corners of the boot opening.' }) },
  { test: /^trunk_latch$/, data: () => ({ label: 'Boot latch', category: 'Body', layer: 'body', description: 'Electric/cable-released latch engaging a striker; includes the internal emergency release handle.', location: 'Rear end panel, centre.' }) },
  { test: /^license_plate_recess$/, data: () => ({ label: 'Licence-plate recess', category: 'Body', layer: 'trim', description: 'Recessed plate mounting area on the boot lid.', location: 'Centre of the boot lid rear face.' }) },
  { test: /^fuel_filler_door$/, data: () => ({ label: 'Fuel filler door', category: 'Body', layer: 'body', description: 'Hinged flap covering the fuel filler cap; released from inside the cabin.', location: 'Left rear quarter panel.' }) },
  { test: /^door_(front|rear)_(left|right)_outer_panel$/, data: id => ({ label: `${cap(id.split('_')[1])} ${id.split('_')[2]} door`, category: 'Body', layer: 'body', parentAssembly: `${cap(id.split('_')[1])} ${id.split('_')[2]} door assembly`, description: 'Door outer skin over an inner frame containing the window regulator, lock actuator, side-impact beam and speaker.', location: `${cap(id.split('_')[1])} ${id.split('_')[2]} side.`, failures: 'Worn check straps, door lock actuator failure, window regulator cable wear.' }) },
  { test: /^door_.*_trim_panel$/, data: id => ({ label: `${cap(id.split('_')[1])} ${id.split('_')[2]} door trim panel`, category: 'Interior', layer: 'interior', parentAssembly: `${cap(id.split('_')[1])} ${id.split('_')[2]} door assembly`, description: 'Moulded interior door panel with armrest, inside release handle and window switch. Clips on; remove it to reach the regulator and lock.', location: 'Inside face of the door.' }) },
  { test: /^door_.*_window_frame$/, data: id => ({ label: `${cap(id.split('_')[1])} ${id.split('_')[2]} door window frame`, category: 'Body', layer: 'body', parentAssembly: `${cap(id.split('_')[1])} ${id.split('_')[2]} door assembly`, description: 'Full-frame door sash guiding the glass run channel and carrying the upper seal.', location: 'Upper part of the door.' }) },
  { test: /^door_.*_glass$/, data: id => ({ label: `${cap(id.split('_')[1])} ${id.split('_')[2]} door glass`, category: 'Glass', layer: 'glass', parentAssembly: `${cap(id.split('_')[1])} ${id.split('_')[2]} door assembly`, description: 'Tempered side glass raised and lowered by an electric window regulator (manual on some base grades).', location: 'Door window opening.', failures: 'Regulator cable fraying or motor failure; glass dropping out of its clamp.' }) },
  { test: /^door_.*_quarter_glass$/, data: id => ({ label: `Rear ${id.split('_')[2]} fixed quarter glass`, category: 'Glass', layer: 'glass', description: 'Fixed glass at the rear of the rear door, separated from the moving glass by a division bar.', location: 'Rear door, rear edge.' }) },
  { test: /^door_.*_handle$/, data: id => ({ label: `${cap(id.split('_')[1])} ${id.split('_')[2]} exterior door handle`, category: 'Trim', layer: 'trim', description: 'Pull-type outer handle linked to the door latch by a rod or cable.', location: 'Door outer panel.' }) },
  { test: /^side_mirror_/, data: id => ({ label: `Door mirror, ${where(id).side}`, category: 'Trim', layer: 'trim', description: 'Door-mounted exterior mirror with power adjustment on most grades; folds manually toward the glass.', location: `${cap(where(id).side)} front door, at the A-pillar base.` }) },
  { test: /^wiper_arm_/, data: id => ({ label: `${id.endsWith('driver') ? 'Driver' : 'Passenger'} wiper arm and blade`, category: 'Trim', layer: 'trim', description: 'Windscreen wiper arm driven by the wiper motor and linkage under the cowl.', location: 'Base of the windscreen.', maintenance: 'Lift to the service position to change blades; avoid lifting while the arms are parked under the bonnet edge.' }) },
  // --------------------------------------------------------------- Glass & pillars
  { test: /^windshield$/, data: () => ({ label: 'Windscreen', category: 'Glass', layer: 'glass', description: 'Laminated, bonded windscreen. Structural: it contributes to roof strength and supports passenger-airbag deployment.', location: 'Front of the cabin.', maintenance: 'Replace with correctly certified laminated glass; allow the urethane to cure before driving.' }) },
  { test: /^rear_window$/, data: () => ({ label: 'Rear window', category: 'Glass', layer: 'glass', description: 'Bonded tempered backlight with an electric defroster grid.', location: 'Behind the rear seat, above the boot lid.' }) },
  { test: /^roof_panel$/, data: () => ({ label: 'Roof panel', category: 'Body', layer: 'body', description: 'Steel roof skin supported by roof bows and the side rails.', location: 'Top of the cabin.' }) },
  { test: /^(a|b|c)_pillar_/, data: id => ({ label: `${id[0].toUpperCase()}-pillar, ${where(id).side}`, category: 'Structure', layer: 'structure', description: `${id[0] === 'a' ? 'Windscreen pillar; houses the curtain-airbag front end and carries roof-crush loads.' : id[0] === 'b' ? 'Centre pillar between the doors, carrying the front seat-belt retractor and the rear door hinges.' : 'Rear sail pillar between the rear door and the rear window.'}`, location: where(id).text }) },
  { test: /^roof_side_rail_/, data: id => ({ label: `Roof side rail, ${where(id).side}`, category: 'Structure', layer: 'structure', description: 'Closed-section rail along the roof edge. Houses the side-curtain airbag and the door-opening seal flange.', location: where(id).text }) },
  // --------------------------------------------------------------- Lighting & trim
  { test: /^headlamp_/, data: (id, g) => ({ label: `Headlamp, ${where(id).side}`, category: 'Lighting', layer: 'lighting', description: `${g.headlamps}.`, location: `${cap(where(id).side)} front corner.`, maintenance: g.key === 'e170' ? 'LED low-beam modules are not a bulb-change item; high-beam and turn-signal bulbs are serviceable.' : 'Halogen bulbs are replaceable from behind the lamp.' }) },
  { test: /^fog_lamp_/, data: id => ({ label: `Fog lamp, ${where(id).side}`, category: 'Lighting', layer: 'lighting', description: 'Front fog lamp in the lower bumper; fitted on higher grades only.', location: `${cap(where(id).side)} lower bumper.` }) },
  { test: /^tail_lamp_outer_/, data: id => ({ label: `Tail lamp (body-mounted), ${where(id).side}`, category: 'Lighting', layer: 'lighting', description: 'Outer tail-lamp cluster with stop, tail and turn functions.', location: `${cap(where(id).side)} rear quarter.` }) },
  { test: /^tail_lamp_inner_/, data: id => ({ label: `Tail lamp (lid-mounted), ${where(id).side}`, category: 'Lighting', layer: 'lighting', description: 'Inner lamp on the boot lid, typically carrying tail and reversing functions.', location: `Boot lid, ${where(id).side} side.` }) },
  { test: /^rear_reflector_/, data: id => ({ label: `Rear bumper reflector, ${where(id).side}`, category: 'Lighting', layer: 'lighting', description: 'Passive red reflector in the rear bumper cover.', location: `${cap(where(id).side)} rear bumper.` }) },
  { test: /^license_plate_lamps$/, data: () => ({ label: 'Licence-plate lamps', category: 'Lighting', layer: 'lighting', description: 'Small lamps illuminating the rear plate.', location: 'Above the licence-plate recess.' }) },
  { test: /^high_mount_stop_lamp$/, data: () => ({ label: 'High-mounted stop lamp', category: 'Lighting', layer: 'lighting', description: 'Centre high-mounted brake lamp required in North America.', location: 'Rear window area.', accuracyNote: APPROX_PKG }) },
  { test: /^upper_grille$/, data: () => ({ label: 'Upper grille', category: 'Trim', layer: 'trim', description: 'Slim grille between the headlamps carrying the front emblem.', location: 'Front, below the bonnet leading edge.' }) },
  { test: /^lower_grille$/, data: () => ({ label: 'Lower grille', category: 'Trim', layer: 'trim', description: 'Large lower air intake feeding the A/C condenser and radiator. Shape and finish vary by grade (S grades use a sportier treatment).', location: 'Front bumper cover, centre.' }) },
  { test: /^front_emblem$/, data: () => ({ label: 'Front emblem', category: 'Trim', layer: 'trim', description: 'Manufacturer badge location. Shown as a plain oval; no manufacturer artwork is reproduced.', location: 'Centre of the upper grille.' }) },
  // --------------------------------------------------------------- Structure
  { test: /^floor_pan$/, data: () => ({ label: 'Floor pan and tunnel', category: 'Structure', layer: 'structure', description: 'Welded floor of the unibody with a central tunnel for the exhaust and brake lines.', location: 'Under the cabin.' }) },
  { test: /^firewall$/, data: () => ({ label: 'Firewall (dash panel)', category: 'Structure', layer: 'structure', description: 'Bulkhead separating the engine bay from the cabin, with pass-throughs for the steering shaft, brake booster, HVAC and wiring.', location: 'Rear wall of the engine bay.' }) },
  { test: /^front_side_member_/, data: id => ({ label: `Front side member, ${where(id).side}`, category: 'Structure', layer: 'structure', description: 'Main longitudinal crash rail. Designed to fold progressively in a frontal impact.', location: `${cap(where(id).side)} of the engine bay, low.` }) },
  { test: /^strut_tower_/, data: id => ({ label: `Strut tower and apron, ${where(id).side}`, category: 'Structure', layer: 'structure', description: 'Inner wing apron with the front strut tower that carries the MacPherson strut top mount.', location: `${cap(where(id).side)} of the engine bay.` }) },
  { test: /^radiator_support$/, data: () => ({ label: 'Radiator core support', category: 'Structure', layer: 'structure', description: 'Front-end frame carrying the cooling module, bonnet latch and headlamp mounts.', location: 'Front of the engine bay.' }) },
  { test: /^front_bumper_reinforcement$/, data: () => ({ label: 'Front bumper reinforcement', category: 'Structure', layer: 'structure', description: 'Crash beam with crush boxes behind the bumper cover; transfers impact energy into the side members.', location: 'Behind the front bumper cover.' }) },
  { test: /^rear_bumper_reinforcement$/, data: () => ({ label: 'Rear bumper reinforcement', category: 'Structure', layer: 'structure', description: 'Rear crash beam behind the rear bumper cover.', location: 'Behind the rear bumper cover.' }) },
  { test: /^rear_parcel_shelf$/, data: () => ({ label: 'Rear parcel shelf', category: 'Structure', layer: 'structure', description: 'Panel behind the rear seat under the rear window; often carries the rear speakers.', location: 'Behind the rear headrests.' }) },
  { test: /^rear_seat_bulkhead$/, data: () => ({ label: 'Rear seat bulkhead', category: 'Structure', layer: 'structure', description: 'Structure between cabin and boot with the pass-through opening used when the rear seatbacks are folded.', location: 'Behind the rear seatbacks.' }) },
  { test: /^front_subframe$/, data: () => ({ label: 'Front suspension member (subframe)', category: 'Chassis', layer: 'chassis', description: 'Bolted cradle carrying the lower control arms, steering gear and rear engine mount.', location: 'Under the engine bay.' }) },
  // --------------------------------------------------------------- Wheels & brakes
  { test: /^wheel_rim_/, data: (id, g) => ({ label: `Wheel rim, ${where(id).text.split(' (')[0].toLowerCase()}`, category: 'Wheels', layer: 'wheels', parentAssembly: `${where(id).text.split(' (')[0]} wheel`, description: 'Road wheel. The model shows a representative 5-spoke alloy.', location: where(id).text, specs: { 'Bolt pattern': '5 × 100 mm', 'Centre bore': '54.1 mm', 'Lug thread': 'M12 × 1.5 nuts', 'Lug-nut torque': '76 lb-ft (103 N·m)', 'Tyre fitment': g.tyres }, maintenance: 'Tighten lug nuts in a star pattern to 76 lb-ft; re-check after the first 50 miles.', failures: 'Kerb damage, bent inner rim causing vibration, corroded bead seat causing slow leaks.', sources: ['wheels2014', 'torque'] }) },
  { test: /^tyre_/, data: (id, g) => ({ label: `Tyre, ${where(id).text.split(' (')[0].toLowerCase()}`, category: 'Wheels', layer: 'wheels', parentAssembly: `${where(id).text.split(' (')[0]} wheel`, description: 'Radial tyre mounted on the rim bead seats; the model shows four circumferential tread grooves.', location: where(id).text, specs: { 'Fitment': g.tyres, 'Pressure': 'Use the placard on the driver’s door jamb (typically about 30–35 psi)' }, maintenance: 'Check pressure cold, monthly. Rotate tyres at each 5,000–7,500 mile service interval.', failures: 'Under-inflation wear on shoulders, alignment wear on inner edge, sidewall bulges after pothole impacts.', sources: ['wheels2014', 'oilDiy'] }) },
  { test: /^wheel_hub_/, data: id => ({ label: `Wheel hub and bearing, ${where(id).text.split(' (')[0].toLowerCase()}`, category: 'Chassis', layer: 'chassis', description: 'Hub flange with five wheel studs, running on a sealed bearing.', location: where(id).text, specs: where(id).pos === 'rear' ? { 'Rear hub bolt torque': '74 lb-ft' } : undefined, failures: 'Worn bearing: a hum that rises with speed and changes on turning.', sources: ['torque'] }) },
  { test: /^brake_disc_/, data: (id, g) => ({ label: `Front brake disc, ${where(id).side}`, category: 'Brakes', layer: 'chassis', description: 'Ventilated disc (rotor) clamped by the caliper pads.', location: where(id).text, specs: g.key === 'e170' ? { Diameter: '275 mm, ventilated' } : { Type: 'Ventilated disc' }, maintenance: 'Measure thickness and run-out whenever pads are replaced.', failures: 'Thickness variation causing pedal pulsation; scoring from worn pads.', sources: ['wikiE170'] }) },
  { test: /^brake_caliper_/, data: id => ({ label: `Front brake caliper, ${where(id).side}`, category: 'Brakes', layer: 'chassis', description: 'Single-piston floating caliper mounted on a torque plate (bracket).', location: `${where(id).text}; trailing the axle.`, specs: { 'Caliper mounting bolts': '25 lb-ft', 'Torque plate bolts': '79 lb-ft' }, maintenance: 'Clean and lubricate slide pins at pad changes.', failures: 'Seized slide pins causing uneven pad wear; piston seal leaks.', sources: ['torque'] }) },
  { test: /^brake_pads_/, data: id => ({ label: `Front brake pads, ${where(id).side}`, category: 'Brakes', layer: 'chassis', description: 'Inner and outer friction pads with wear indicators that squeal when the lining is thin.', location: 'Inside the front caliper.', maintenance: 'Inspect at every tyre rotation.' }) },
  { test: /^steering_knuckle_/, data: id => ({ label: `Steering knuckle, ${where(id).side}`, category: 'Chassis', layer: 'chassis', description: 'Cast upright carrying the hub bearing; the strut bolts to its top, the lower ball joint to its base and the tie-rod to its steering arm.', location: where(id).text }) },
  { test: /^brake_drum_/, data: id => ({ label: `Rear brake drum, ${where(id).side}`, category: 'Brakes', layer: 'chassis', description: 'Drum brake used on most grades; S Plus / S Premium (E170) use solid rear discs instead.', location: where(id).text, specs: { Diameter: '≈229 mm (9.0 in)' }, maintenance: 'Adjust and inspect shoes; the parking brake acts on this drum.', sources: ['wikiE170', 'carspecs2013'] }) },
  { test: /^brake_shoes_/, data: id => ({ label: `Rear brake shoes, ${where(id).side}`, category: 'Brakes', layer: 'chassis', description: 'Leading/trailing shoes pushed by a wheel cylinder; also applied mechanically by the parking brake.', location: 'Inside the rear drum.' }) },
  { test: /^brake_backing_plate_/, data: id => ({ label: `Rear brake backing plate, ${where(id).side}`, category: 'Brakes', layer: 'chassis', description: 'Fixed plate carrying the shoes, wheel cylinder and parking-brake lever.', location: where(id).text }) },
  // --------------------------------------------------------------- Suspension & steering
  { test: /^front_strut_mount_/, data: id => ({ label: `Front strut top mount, ${where(id).side}`, category: 'Suspension', layer: 'chassis', description: 'Rubber-isolated top mount with bearing, letting the strut rotate with steering.', location: 'Top of the strut tower.', specs: { 'Upper mounting nuts': '37 lb-ft' }, sources: ['torque'] }) },
  { test: /^front_strut_/, data: id => ({ label: `Front strut (damper), ${where(id).side}`, category: 'Suspension', layer: 'chassis', description: 'MacPherson strut damper that also locates the wheel; S grades use firmer tuning.', location: where(id).text, failures: 'Oil leaks, knocking over bumps, bouncing after road undulations.', sources: ['wikiE170'] }) },
  { test: /^front_coil_spring_/, data: id => ({ label: `Front coil spring, ${where(id).side}`, category: 'Suspension', layer: 'chassis', description: 'Coil spring seated on the strut; carries the front corner weight.', location: where(id).text }) },
  { test: /^front_lower_control_arm_/, data: id => ({ label: `Front lower control arm, ${where(id).side}`, category: 'Suspension', layer: 'chassis', description: 'L-shaped arm pivoting on two bushings on the subframe, carrying the lower ball joint.', location: where(id).text, failures: 'Worn rear bushing causing clunks on braking; ball-joint play.' }) },
  { test: /^front_stabilizer_bar$/, data: () => ({ label: 'Front stabiliser (anti-roll) bar and links', category: 'Suspension', layer: 'chassis', description: 'Torsion bar linking both front struts to reduce body roll.', location: 'Front subframe.', failures: 'Worn end links cause a light knocking over uneven roads.' }) },
  { test: /^tie_rod_/, data: id => ({ label: `Tie rod and rack boot, ${where(id).side}`, category: 'Steering', layer: 'chassis', description: 'Inner and outer tie rod transmitting rack movement to the knuckle; the bellows boot keeps dirt out of the rack.', location: where(id).text, maintenance: 'Toe alignment is set on the tie-rod ends.' }) },
  { test: /^steering_rack$/, data: () => ({ label: 'Steering gear (rack and pinion)', category: 'Steering', layer: 'chassis', description: 'Rack-and-pinion gear on the front subframe. Assistance is electric (EPS).', location: 'Behind the engine, on the subframe.', sources: ['wikiE170'] }) },
  { test: /^steering_intermediate_shaft$/, data: () => ({ label: 'Steering intermediate shaft', category: 'Steering', layer: 'chassis', description: 'Jointed shaft connecting the column through the firewall to the rack pinion.', location: 'Driver side of the engine bay.' }) },
  { test: /^steering_column$/, data: () => ({ label: 'Steering column with EPS assist unit', category: 'Steering', layer: 'interior', description: 'Collapsible column with tilt/telescope adjustment and the electric power steering assist unit.', location: 'Behind the instrument panel, driver side.', accuracyNote: APPROX_PKG }) },
  { test: /^steering_wheel$/, data: () => ({ label: 'Steering wheel', category: 'Interior', layer: 'interior', description: 'Three-spoke wheel housing the driver airbag; audio and phone switches on most grades.', location: 'Driver position (left).' }) },
  { test: /^rear_trailing_arm_/, data: id => ({ label: `Rear trailing arm, ${where(id).side}`, category: 'Suspension', layer: 'chassis', description: 'Arm of the rear torsion-beam axle pivoting on a body bushing.', location: where(id).text, specs: { 'Axle beam pivot bolts': '122 lb-ft (tighten at ride height)' }, sources: ['torque'] }) },
  { test: /^rear_torsion_beam$/, data: () => ({ label: 'Rear torsion-beam axle', category: 'Suspension', layer: 'chassis', description: 'Semi-independent twist-beam rear suspension joining both trailing arms.', location: 'Ahead of the rear axle line.', sources: ['wikiE170'] }) },
  { test: /^rear_coil_spring_/, data: id => ({ label: `Rear coil spring, ${where(id).side}`, category: 'Suspension', layer: 'chassis', description: 'Coil spring seated between the torsion beam and the body.', location: where(id).text }) },
  { test: /^rear_shock_absorber_/, data: id => ({ label: `Rear shock absorber, ${where(id).side}`, category: 'Suspension', layer: 'chassis', description: 'Telescopic damper behind the axle line.', location: where(id).text, failures: 'Leaking or weak dampers: floaty rear on undulations.' }) },
  { test: /^rear_hub_carrier_/, data: id => ({ label: `Rear hub carrier, ${where(id).side}`, category: 'Suspension', layer: 'chassis', description: 'Mounting flange at the end of the trailing arm for the rear hub bearing and brake.', location: where(id).text }) },
  // --------------------------------------------------------------- Engine
  { test: /^engine_block$/, data: (id, g) => ({ label: `Engine block (${g.engine.code})`, category: 'Engine', layer: 'engine', description: `${g.engine.displacement}. ${g.engine.block}.`, location: 'Transversely mounted, right side of the engine bay.', specs: { Code: g.engine.code, Displacement: g.engine.displacement, 'Bore × stroke': g.engine.bore, 'Compression ratio': g.engine.compression, Output: g.engine.output, Valvetrain: g.engine.valvetrain, ...(g.engine.eco ? { 'LE Eco variant': g.engine.eco } : {}), 'Firing order': '1-3-4-2' }, sources: ['wikiZR', g.key === 'e170' ? 'edmunds2014' : 'carspecs2013'] }) },
  { test: /^cylinder_head$/, data: () => ({ label: 'Cylinder head', category: 'Engine', layer: 'engine', description: 'Aluminium DOHC head with 16 valves and dual VVT-i (variable intake and exhaust cam timing).', location: 'On top of the block.', specs: { 'Head bolts': 'Torque-angle: 36 lb-ft, then +90°, then +45°' }, sources: ['torque', 'wikiZR'] }) },
  { test: /^valve_cover$/, data: () => ({ label: 'Cylinder-head cover (valve cover)', category: 'Engine', layer: 'engine', description: 'Cover over the camshafts carrying the oil filler cap and the four coil-on-plug ignition coils.', location: 'Top of the engine.', failures: 'Gasket seepage around the edges and plug-tube seals.' }) },
  { test: /^oil_pan$/, data: () => ({ label: 'Oil pan (sump)', category: 'Engine', layer: 'engine', description: 'Engine oil reservoir with the drain plug.', location: 'Bottom of the engine.' }) },
  { test: /^oil_drain_plug$/, data: () => ({ label: 'Oil drain plug', category: 'Engine', layer: 'engine', description: 'Sump drain plug with a crush washer.', location: 'Underside of the oil pan.', specs: { 'Socket': '14 mm', Torque: '27 lb-ft (36 N·m)', 'Oil': 'SAE 0W-20, 4.4 US qt (4.2 L) with filter' }, maintenance: 'Fit a new washer at every change.', sources: ['oilDiy', 'toyotaClub', 'torque'] }) },
  { test: /^oil_filter_housing$/, data: () => ({ label: 'Oil filter housing', category: 'Engine', layer: 'engine', description: 'Housing for the cartridge-type (element) oil filter.', location: 'Front, lower side of the block.', accuracyNote: APPROX_PKG }) },
  { test: /^oil_filter_cartridge$/, data: () => ({ label: 'Oil filter cartridge and cap', category: 'Engine', layer: 'engine', description: 'Replaceable paper element inside a screw-on cap.', location: 'Front, lower side of the block.', specs: { 'Toyota part': '04152-YZZA1 (element)', 'Cap torque': '156 in-lb (≈18 N·m)', 'Oil capacity': '4.4 US qt (4.2 L) with filter', Grade: 'SAE 0W-20 (US market)' }, maintenance: 'Replace the cap O-ring with every element.', sources: ['oilDiy', 'toyotaClub', 'torque'], accuracyNote: APPROX_PKG }) },
  { test: /^timing_chain_cover$/, data: () => ({ label: 'Timing chain cover', category: 'Engine', layer: 'engine', description: 'Covers the camshaft drive chain, tensioner and VVT actuators at the right-hand end of the engine.', location: 'Right end of the engine.', specs: { 'Crankshaft pulley bolt': '140 lb-ft' }, sources: ['torque'] }) },
  { test: /^oil_filler_cap$/, data: () => ({ label: 'Engine oil filler cap', category: 'Engine', layer: 'engine', description: 'Twist-off cap on the valve cover for topping up oil.', location: 'Top of the valve cover.', specs: { Oil: 'SAE 0W-20, 4.4 US qt (4.2 L) with filter' }, sources: ['oilDiy'] }) },
  { test: /^oil_dipstick$/, data: () => ({ label: 'Engine oil dipstick', category: 'Engine', layer: 'engine', description: 'Check with the car level and engine off for a few minutes; the level should sit between the two marks.', location: 'Front of the engine (ring handle).' }) },
  { test: /^oil_dipstick_tube$/, data: () => ({ label: 'Dipstick guide tube', category: 'Engine', layer: 'engine', description: 'Guide tube running from the handle down into the sump.', location: 'Front of the engine.' }) },
  { test: /^ignition_coils$/, data: () => ({ label: 'Ignition coils (coil-on-plug)', category: 'Engine', layer: 'engine', description: 'One coil per cylinder sitting directly on each spark plug.', location: 'Top of the valve cover, in a row.', failures: 'A failing coil causes a misfire code (P0301–P0304) and a rough idle.', maintenance: 'Swap a suspect coil to another cylinder to confirm a misfire follows it.' }) },
  { test: /^spark_plugs$/, data: () => ({ label: 'Spark plugs', category: 'Engine', layer: 'engine', description: 'Long-life iridium plugs threaded into the head beneath each coil.', location: 'Under the ignition coils.', specs: { 'OEM type': 'Denso SC16HR11 / SC20HR11 iridium', Gap: '1.1 mm (0.043 in)', Torque: '15 lb-ft' }, maintenance: 'Remove only with the engine cold; do not re-gap iridium tips.', sources: ['plugs', 'torque'] }) },
  { test: /^intake_manifold$/, data: () => ({ label: 'Intake manifold', category: 'Engine', layer: 'engine', description: 'Resin manifold with four runners feeding the intake ports from a common plenum.', location: 'Front (radiator) side of the engine.', accuracyNote: APPROX }) },
  { test: /^throttle_body$/, data: () => ({ label: 'Electronic throttle body', category: 'Engine', layer: 'engine', description: 'Drive-by-wire throttle regulating air into the plenum.', location: 'Left end of the intake plenum.', maintenance: 'Clean carbon deposits if idle becomes unstable.' }) },
  { test: /^exhaust_manifold$/, data: () => ({ label: 'Exhaust manifold', category: 'Engine', layer: 'engine', description: 'Collects exhaust from the four ports and feeds the close-coupled catalytic converter.', location: 'Rear (firewall) side of the engine.', accuracyNote: APPROX }) },
  { test: /^exhaust_heat_shield$/, data: () => ({ label: 'Exhaust manifold heat shield', category: 'Engine', layer: 'engine', description: 'Pressed shield over the hot manifold.', location: 'Rear of the engine.', failures: 'Loose shields rattle at idle.' }) },
  { test: /^catalytic_converter$/, data: () => ({ label: 'Catalytic converter', category: 'Exhaust', layer: 'fuel', description: 'Three-way catalyst converting CO, HC and NOx.', location: 'Directly below the exhaust manifold.' }) },
  { test: /^oxygen_sensors$/, data: () => ({ label: 'Air-fuel ratio / oxygen sensors', category: 'Exhaust', layer: 'fuel', description: 'Upstream air-fuel sensor and downstream oxygen sensor used for fuel control and catalyst monitoring.', location: 'Before and after the catalytic converter.' }) },
  { test: /^exhaust_pipe$/, data: () => ({ label: 'Exhaust pipe and resonator', category: 'Exhaust', layer: 'fuel', description: 'Front pipe, centre resonator and tailpipe running through the floor tunnel.', location: 'Underbody, centre.', accuracyNote: APPROX }) },
  { test: /^muffler$/, data: () => ({ label: 'Rear muffler', category: 'Exhaust', layer: 'fuel', description: 'Main silencer behind the rear axle.', location: 'Rear underbody.', accuracyNote: APPROX }) },
  { test: /^(crankshaft_pulley|water_pump|drive_belt_tensioner)$/, data: id => ({ label: { crankshaft_pulley: 'Crankshaft pulley', water_pump: 'Water pump and pulley', drive_belt_tensioner: 'Drive-belt tensioner' }[id], category: 'Engine', layer: 'engine', description: { crankshaft_pulley: 'Drives the accessory belt from the crankshaft nose.', water_pump: 'Belt-driven coolant pump.', drive_belt_tensioner: 'Automatic spring tensioner keeping the serpentine belt tight.' }[id], location: 'Right end of the engine (accessory drive).', specs: id === 'crankshaft_pulley' ? { 'Pulley bolt torque': '140 lb-ft' } : undefined, failures: id === 'water_pump' ? 'Weep hole leak or bearing noise.' : undefined, sources: ['torque'] }) },
  { test: /^alternator$/, data: () => ({ label: 'Alternator', category: 'Electrical', layer: 'engine', description: 'Belt-driven generator charging the 12 V battery.', location: 'Front, upper right end of the engine.', failures: 'Battery warning lamp, dimming lights, whining bearing.' }) },
  { test: /^ac_compressor$/, data: () => ({ label: 'A/C compressor', category: 'Engine', layer: 'engine', description: 'Belt-driven air-conditioning compressor.', location: 'Front, lower right end of the engine.' }) },
  { test: /^drive_belt$/, data: () => ({ label: 'Serpentine drive belt', category: 'Engine', layer: 'engine', description: 'Single ribbed belt driving the alternator, water pump and A/C compressor.', location: 'Right end of the engine.', maintenance: 'Inspect for cracks and glazing; squeal on cold starts suggests wear.' }) },
  { test: /^engine_mounts$/, data: () => ({ label: 'Engine and transaxle mounts', category: 'Engine', layer: 'engine', description: 'Right-hand engine mount, left-hand transaxle mount and a rear torque rod to the subframe.', location: 'Around the powertrain.', failures: 'Worn mounts cause vibration at idle and clunks when shifting into gear.', accuracyNote: APPROX_PKG }) },
  { test: /^transaxle$/, data: (id, g) => ({ label: 'Transaxle', category: 'Drivetrain', layer: 'engine', description: `Front-wheel-drive gearbox with integral differential. Fitted type depends on grade: ${g.transmissions}.`, location: 'Left side of the engine bay.', specs: g.key === 'e170' ? { 'CVT fluid': 'Toyota CVT Fluid FE, ≈7.5 L total capacity', 'Manual gearbox oil': 'Toyota MT Gear Oil LV 75W GL-4, ≈2.4 L', 'Automatic fluid (4-speed)': 'ATF WS' } : { 'Automatic fluid': 'ATF WS (4-speed)' }, sources: ['toyotaClub', 'oilDiy'] }) },
  { test: /^starter_motor$/, data: () => ({ label: 'Starter motor', category: 'Electrical', layer: 'engine', description: 'Engages the flywheel ring gear to crank the engine.', location: 'Rear of the engine, at the bell-housing.', accuracyNote: APPROX_PKG }) },
  { test: /^driveshaft_/, data: id => ({ label: `Driveshaft (CV axle), ${where(id).side}`, category: 'Drivetrain', layer: 'engine', description: `Constant-velocity axle from the differential to the front hub.${where(id).side === 'right' ? ' The right shaft is longer and uses an intermediate shaft with a support bearing.' : ''}`, location: where(id).text, failures: 'Torn CV boots lead to clicking on tight turns.' }) },
  // --------------------------------------------------------------- Engine-bay systems
  { test: /^ac_condenser$/, data: () => ({ label: 'A/C condenser', category: 'Cooling', layer: 'bay', description: 'Rejects heat from the refrigerant; mounted ahead of the radiator.', location: 'Front of the cooling module.' }) },
  { test: /^radiator$/, data: () => ({ label: 'Radiator', category: 'Cooling', layer: 'bay', description: 'Aluminium-core radiator with plastic side tanks.', location: 'Front of the engine bay.', specs: { Coolant: 'Toyota Super Long Life Coolant (pink, pre-mixed)', 'Capacity (listed)': '≈5.5 L per Toyota-Club data; confirm for your transmission' }, maintenance: 'Never open the cooling system hot.', sources: ['toyotaClub', 'oilDiy'] }) },
  { test: /^radiator_cap$/, data: () => ({ label: 'Radiator cap', category: 'Cooling', layer: 'bay', description: 'Pressure cap that raises the coolant boiling point.', location: 'Top of the radiator.', maintenance: 'Only remove with the engine fully cold: pressurised coolant can scald.', accuracyNote: APPROX_PKG }) },
  { test: /^cooling_fan$/, data: () => ({ label: 'Electric cooling fan and shroud', category: 'Cooling', layer: 'bay', description: 'Electric fan pulling air through the radiator and condenser at low speed and with A/C on.', location: 'Behind the radiator.' }) },
  { test: /^radiator_hoses$/, data: () => ({ label: 'Radiator hoses', category: 'Cooling', layer: 'bay', description: 'Upper and lower coolant hoses between engine and radiator.', location: 'Front of the engine bay.', accuracyNote: APPROX }) },
  { test: /^heater_hoses$/, data: () => ({ label: 'Heater hoses', category: 'Cooling', layer: 'bay', description: 'Carry hot coolant through the firewall to the heater core.', location: 'Rear of the engine, to the firewall.' }) },
  { test: /^coolant_reservoir(_cap)?$/, data: id => ({ label: id.endsWith('cap') ? 'Coolant reservoir cap' : 'Coolant reservoir', category: 'Cooling', layer: 'bay', description: 'Translucent overflow reservoir with FULL and LOW marks; check the level here with the engine cold.', location: 'Front corner of the engine bay.', specs: { Coolant: 'Toyota Super Long Life Coolant (pink, pre-mixed)' }, sources: ['oilDiy'], accuracyNote: APPROX_PKG }) },
  { test: /^battery_12v$/, data: () => ({ label: '12 V battery', category: 'Electrical', layer: 'bay', description: 'Lead-acid starter battery.', location: 'Front corner of the engine bay, driver side.', maintenance: 'Disconnect the negative terminal first and reconnect it last.', failures: 'Slow cranking; corrosion on terminals.', accuracyNote: APPROX_PKG }) },
  { test: /^battery_(hold_down|tray|cables)$/, data: id => ({ label: { battery_hold_down: 'Battery hold-down', battery_tray: 'Battery tray', battery_cables: 'Battery cables' }[id], category: 'Electrical', layer: 'bay', description: { battery_hold_down: 'Clamp bar that stops the battery moving.', battery_tray: 'Tray supporting the battery.', battery_cables: 'Positive cable to the fuse box and starter; negative cable to body/engine ground.' }[id], location: 'Battery area.' }) },
  { test: /^fuse_relay_box$/, data: () => ({ label: 'Engine-bay fuse and relay box', category: 'Electrical', layer: 'bay', description: 'Main fuses and relays for the engine bay; the lid carries a fuse map.', location: 'Near the battery.', accuracyNote: APPROX_PKG }) },
  { test: /^air_intake_snorkel$/, data: () => ({ label: 'Air intake inlet', category: 'Intake', layer: 'bay', description: 'Cold-air inlet feeding the air cleaner.', location: 'Front of the engine bay.', accuracyNote: APPROX }) },
  { test: /^air_cleaner_(box|lid)$/, data: id => ({ label: id.endsWith('lid') ? 'Air cleaner lid' : 'Air cleaner housing', category: 'Intake', layer: 'bay', description: 'Clip-closed housing holding the engine air filter element.', location: 'Above the transaxle, driver side.', maintenance: 'Release the clips and lift the lid to change the element.', accuracyNote: APPROX_PKG }) },
  { test: /^air_filter_element$/, data: () => ({ label: 'Engine air filter element', category: 'Intake', layer: 'bay', description: 'Pleated paper panel filter.', location: 'Inside the air cleaner housing.', maintenance: 'Inspect every service; replace more often in dusty conditions.' }) },
  { test: /^air_intake_duct$/, data: () => ({ label: 'Air intake duct', category: 'Intake', layer: 'bay', description: 'Flexible duct from the air cleaner to the throttle body.', location: 'Top of the engine bay.' }) },
  { test: /^brake_booster$/, data: () => ({ label: 'Brake booster', category: 'Brakes', layer: 'bay', description: 'Vacuum servo multiplying pedal force.', location: 'Firewall, driver side.' }) },
  { test: /^brake_master_cylinder$/, data: () => ({ label: 'Brake master cylinder', category: 'Brakes', layer: 'bay', description: 'Tandem master cylinder feeding two diagonal hydraulic circuits.', location: 'Front of the brake booster.' }) },
  { test: /^brake_fluid_(reservoir|cap)$/, data: id => ({ label: id.endsWith('cap') ? 'Brake fluid reservoir cap' : 'Brake fluid reservoir', category: 'Brakes', layer: 'bay', description: 'Translucent reservoir with MIN/MAX marks. A falling level usually means worn pads or a leak.', location: 'On top of the master cylinder.', specs: { Fluid: 'DOT 3 (per OilChangeDIY listing)' }, maintenance: 'Brake fluid absorbs water; replace on the maintenance schedule.', sources: ['oilDiy'] }) },
  { test: /^abs_actuator$/, data: () => ({ label: 'ABS / VSC actuator', category: 'Brakes', layer: 'bay', description: 'Hydraulic modulator and control unit for anti-lock braking and stability control.', location: 'Engine bay, near the inner wing.', accuracyNote: APPROX_PKG }) },
  { test: /^brake_lines$/, data: () => ({ label: 'Brake lines', category: 'Brakes', layer: 'chassis', description: 'Steel hydraulic lines from the master cylinder through the ABS actuator to each wheel.', location: 'Engine bay and underbody.', accuracyNote: APPROX }) },
  { test: /^washer_fluid_(reservoir|cap)$/, data: id => ({ label: id.endsWith('cap') ? 'Washer fluid cap' : 'Washer fluid reservoir', category: 'Body electrical', layer: 'bay', description: 'Windscreen washer reservoir with an electric pump.', location: 'Front corner of the engine bay.', accuracyNote: APPROX_PKG }) },
  { test: /^horn$/, data: () => ({ label: 'Horn', category: 'Body electrical', layer: 'bay', description: 'Electric horn behind the bumper.', location: 'Front of the engine bay.', accuracyNote: APPROX_PKG }) },
  { test: /^hood_seal_and_cowl_seal$/, data: () => ({ label: 'Cowl seal', category: 'Body', layer: 'bay', description: 'Seal along the rear of the engine bay that keeps hot air and water from the cowl intake.', location: 'Top of the firewall.' }) },
  // --------------------------------------------------------------- Interior & SRS
  { test: /^instrument_panel_upper$/, data: () => ({ label: 'Instrument panel upper', category: 'Interior', layer: 'interior', description: 'Upper dashboard pad housing the defroster vents and front-passenger airbag.', location: 'Front of the cabin.' }) },
  { test: /^dash_trim_band$/, data: () => ({ label: 'Dashboard trim band', category: 'Interior', layer: 'interior', description: 'Horizontal trim layer across the instrument panel; soft-touch or piano-black finish depending on grade.', location: 'Mid-height across the dashboard.' }) },
  { test: /^instrument_panel_lower$/, data: () => ({ label: 'Instrument panel lower', category: 'Interior', layer: 'interior', description: 'Lower dashboard with the knee airbag (driver) and glovebox opening (passenger).', location: 'Lower dashboard.' }) },
  { test: /^instrument_cluster$/, data: () => ({ label: 'Instrument cluster', category: 'Interior', layer: 'interior', description: 'Speedometer, tachometer and multi-information display (S grades use a sport cluster with a TFT display).', location: 'In front of the driver.', sources: ['fleet2014'] }) },
  { test: /^center_stack$/, data: () => ({ label: 'Centre stack', category: 'Interior', layer: 'interior', description: 'Central fascia carrying the audio unit, climate controls and vents.', location: 'Centre of the dashboard.' }) },
  { test: /^audio_touchscreen$/, data: (id, g) => ({ label: g.key === 'e170' ? 'Audio / Entune touchscreen' : 'Audio head unit', category: 'Interior', layer: 'interior', description: `${g.audio}.`, location: 'Upper centre stack.', sources: g.key === 'e170' ? ['fleet2014', 'carsTrims2014'] : ['carspecs2013'] }) },
  { test: /^climate_controls$/, data: () => ({ label: 'Climate controls', category: 'Interior', layer: 'interior', description: 'Heater, fan and A/C controls (automatic climate control on higher grades).', location: 'Lower centre stack.' }) },
  { test: /^air_vents$/, data: () => ({ label: 'Dashboard air vents', category: 'Interior', layer: 'interior', description: 'Centre and outboard face-level vents.', location: 'Dashboard.' }) },
  { test: /^glovebox$/, data: () => ({ label: 'Glovebox', category: 'Interior', layer: 'interior', description: 'Passenger-side storage compartment; the cabin air filter is typically reached by unclipping the glovebox.', location: 'Passenger side of the lower dashboard.', maintenance: 'Cabin air filter: release the glovebox stops to access the filter door behind it.' }) },
  { test: /^pedals$/, data: () => ({ label: 'Pedal assembly', category: 'Interior', layer: 'interior', description: 'Brake and accelerator pedals (plus clutch on manual cars).', location: 'Driver footwell.' }) },
  { test: /^center_console$/, data: () => ({ label: 'Centre console', category: 'Interior', layer: 'interior', description: 'Floor console with cup holders and armrest storage.', location: 'Between the front seats.' }) },
  { test: /^gear_selector$/, data: (id, g) => ({ label: 'Gear selector / shift lever', category: 'Interior', layer: 'interior', description: `Selector for the fitted transmission: ${g.transmissions}.`, location: 'Centre console.' }) },
  { test: /^parking_brake_lever$/, data: () => ({ label: 'Parking brake lever', category: 'Interior', layer: 'interior', description: 'Hand lever applying the rear brakes mechanically through cables.', location: 'Centre console.', maintenance: 'Adjust if the lever travels too many clicks.' }) },
  { test: /^console_armrest_lid$/, data: () => ({ label: 'Console armrest lid', category: 'Interior', layer: 'interior', description: 'Hinged armrest over the console storage bin.', location: 'Rear of the centre console.' }) },
  { test: /^seat_rails_front_/, data: id => ({ label: `Front seat rails, ${where(id).side}`, category: 'Interior', layer: 'interior', description: 'Slide rails bolted to the floor.', location: where(id).text }) },
  { test: /^seat_cushion_front_/, data: id => ({ label: `Front seat cushion, ${where(id).side}`, category: 'Interior', layer: 'interior', description: 'Seat base with fore-aft slide (driver seat height adjustment on most grades).', location: where(id).text }) },
  { test: /^seat_back_front_/, data: id => ({ label: `Front seatback, ${where(id).side}`, category: 'Interior', layer: 'interior', description: 'Reclining seatback containing the side airbag in the outboard bolster.', location: where(id).text }) },
  { test: /^headrest_front_/, data: id => ({ label: `Front headrest, ${where(id).side}`, category: 'Interior', layer: 'interior', description: 'Height-adjustable head restraint.', location: where(id).text }) },
  { test: /^rear_seat_cushion$/, data: () => ({ label: 'Rear seat cushion', category: 'Interior', layer: 'interior', description: 'Fixed rear bench cushion.', location: 'Rear cabin.' }) },
  { test: /^rear_seatback_(60|40)$/, data: id => ({ label: `Rear seatback (${id.endsWith('60') ? '60' : '40'} % section)`, category: 'Interior', layer: 'interior', description: '60/40 split folding rear seatback opening a pass-through to the boot.', location: 'Rear cabin.' }) },
  { test: /^rear_headrests$/, data: () => ({ label: 'Rear headrests', category: 'Interior', layer: 'interior', description: 'Rear head restraints.', location: 'Top of the rear seatbacks.' }) },
  { test: /^sun_visor_/, data: id => ({ label: `Sun visor, ${where(id).side}`, category: 'Interior', layer: 'interior', description: 'Pivoting visor with vanity mirror.', location: 'Windscreen header.' }) },
  { test: /^rearview_mirror$/, data: () => ({ label: 'Interior rear-view mirror', category: 'Interior', layer: 'interior', description: 'Windscreen-mounted mirror (auto-dimming on higher grades).', location: 'Top centre of the windscreen.' }) },
  { test: /^dome_lamp$/, data: () => ({ label: 'Dome lamp', category: 'Interior', layer: 'interior', description: 'Interior courtesy lamp.', location: 'Headliner.' }) },
  { test: /^airbag_/, data: (id, g) => {
    const names = { airbag_driver_front: 'Driver front airbag', airbag_passenger_front: 'Front-passenger airbag', airbag_knee_driver: 'Driver knee airbag', airbag_seat_cushion_passenger: 'Front-passenger seat-cushion airbag', airbag_curtain_left: 'Side-curtain airbag, left', airbag_curtain_right: 'Side-curtain airbag, right', airbag_seat_side_left: 'Front seat side airbag, left', airbag_seat_side_right: 'Front seat side airbag, right' };
    return { label: names[id] || 'Airbag', category: 'Safety (SRS)', layer: 'safety', description: `Supplemental restraint system module. Vehicle complement: ${g.airbags}.`, location: 'Shown at its deployment zone; the module is concealed behind trim.', maintenance: 'Never probe SRS connectors. Disconnect the battery and wait before working near airbag modules.', sources: g.key === 'e170' ? ['fleet2014'] : ['carspecs2013'], accuracyNote: APPROX_PKG };
  } },
  // --------------------------------------------------------------- Boot & fuel
  { test: /^trunk_floor$/, data: (id, g) => ({ label: 'Boot floor and spare-wheel well', category: 'Structure', layer: 'structure', description: `Boot floor with a recessed well for the compact spare. Boot volume: ${g.dims.cargo}.`, location: 'Boot.' }) },
  { test: /^trunk_floor_board$/, data: () => ({ label: 'Boot floor board', category: 'Interior', layer: 'interior', description: 'Removable board covering the spare-wheel well.', location: 'Boot floor.' }) },
  { test: /^spare_tyre$/, data: () => ({ label: 'Compact spare wheel', category: 'Wheels', layer: 'wheels', description: 'Temporary-use compact spare on a steel wheel. Observe its speed limit and replace with a full-size tyre promptly.', location: 'Spare-wheel well under the boot floor.' }) },
  { test: /^jack_and_tools$/, data: () => ({ label: 'Jack and tool kit', category: 'Wheels', layer: 'wheels', description: 'Scissor jack and wheel-nut wrench for roadside wheel changes. Use the marked sill jacking points.', location: 'Beside the spare wheel.', accuracyNote: APPROX_PKG }) },
  { test: /^fuel_tank$/, data: (id, g) => ({ label: 'Fuel tank', category: 'Fuel', layer: 'fuel', description: 'Resin or steel tank under the rear seat containing the in-tank pump and sender.', location: 'Beneath the rear seat.', specs: { Capacity: g.dims.fuel }, sources: ['toyotaClub', g.key === 'e170' ? 'edmunds2014' : 'carspecs2013'] }) },
  { test: /^fuel_filler_neck$/, data: () => ({ label: 'Fuel filler neck', category: 'Fuel', layer: 'fuel', description: 'Pipe from the filler to the tank, with a vent line.', location: 'Left rear wheel arch area.' }) },
  { test: /^fuel_filler_cap$/, data: () => ({ label: 'Fuel filler cap', category: 'Fuel', layer: 'fuel', description: 'Tethered screw cap. A loose cap can trigger an evaporative-system check-engine code.', location: 'Behind the fuel filler door.' }) },
  { test: /^evap_canister$/, data: () => ({ label: 'EVAP charcoal canister', category: 'Fuel', layer: 'fuel', description: 'Stores fuel vapour for purging into the intake.', location: 'Underbody near the tank.', accuracyNote: APPROX_PKG })
  }
];

export function describeComponent(id, genKey) {
  const g = GENERATIONS[genKey];
  const family = FAMILIES.find(f => f.test.test(id));
  if (!family) throw new Error(`No reference metadata for component ${id}`);
  const d = family.data(id, g);
  const sources = [...new Set([...(d.sources || []), ...g.sources.slice(0, 1)])].map(key => SOURCES[key]);
  const out = {
    id, label: d.label, category: d.category, layer: d.layer, availability: 'available',
    description: d.description, location: d.location,
    ...(d.parentAssembly ? { parentAssembly: d.parentAssembly } : {}),
    ...(d.specs ? { specs: Object.fromEntries(Object.entries(d.specs).filter(([, v]) => v)) } : {}),
    ...(d.maintenance ? { maintenance: d.maintenance } : {}),
    ...(d.failures ? { failures: d.failures } : {}),
    accuracyNote: d.accuracyNote || 'Geometry is a representative procedural model built from published dimensions.',
    sources
  };
  if (out.specs && !Object.keys(out.specs).length) delete out.specs;
  return out;
}

/** Grouped specification sheet for the Guide's left panel. */
export function specSheet(genKey) {
  const g = GENERATIONS[genKey], d = g.dims;
  const groups = [
    { title: 'Overview', rows: [['Model years', g.years], ['Generation', `${g.code} (${g.market})`], ['Platform', g.platform], ['Body', '4-door sedan, front-engine front-wheel drive']] },
    { title: 'Engine', rows: [['Code', g.engine.code], ['Type', g.engine.displacement], ['Bore × stroke', g.engine.bore], ['Compression', g.engine.compression], ['Valvetrain', g.engine.valvetrain], ['Output', g.engine.output], ...(g.engine.eco ? [['LE Eco', g.engine.eco]] : []), ['Firing order', '1-3-4-2']] },
    { title: 'Drivetrain & chassis', rows: [['Transmissions', g.transmissions], ['Suspension', 'MacPherson strut front · torsion-beam rear'], ['Steering', 'Rack and pinion with electric power assistance'], ['Brakes', g.brakes], ['Tyres', g.tyres], ['Wheel fastening', '5 × 100 mm, M12 × 1.5, 76 lb-ft']] },
    { title: 'Dimensions', rows: [['Length', d.length], ['Width', d.width], ['Height', d.height], ['Wheelbase', d.wheelbase], ['Track F / R', `${d.trackF} / ${d.trackR}`], ['Curb weight', d.curb], ['Turning circle', d.turning], ['Boot volume', d.cargo], ['Drag coefficient', d.cd]] },
    { title: 'Capacities & economy', rows: [['Fuel tank', d.fuel], ['Engine oil', 'SAE 0W-20, 4.4 US qt (4.2 L) with filter'], ['Oil filter', 'Toyota 04152-YZZA1 element'], ['Coolant', 'Toyota Super Long Life Coolant (pink)'], ['Spark plugs', 'Iridium, 1.1 mm gap'], ['EPA economy', d.mpg]] },
    { title: 'Cabin & safety', rows: [['Airbags', g.airbags], ['Headlamps', g.headlamps], ['Audio', g.audio], ['Rear seat', '60/40 split folding'], ...Object.entries(g.interior).map(([k, v]) => [({ frontHead: 'Front headroom', frontLeg: 'Front legroom', frontShoulder: 'Front shoulder room', frontHip: 'Front hip room', rearHead: 'Rear headroom', rearLeg: 'Rear legroom', rearShoulder: 'Rear shoulder room', rearHip: 'Rear hip room' })[k], v])] }
  ];
  return {
    schemaVersion: 1, vehicle: g.title, generation: g.code,
    groups: groups.map(group => ({ ...group, rows: group.rows.filter(([, v]) => v) })),
    sources: [...new Set([...g.sources, 'toyotaClub', 'oilDiy', 'torque', 'plugs', 'wheels2014'])].map(k => SOURCES[k]),
    disclaimer: 'Figures come from the public sources listed. Grade, market and production-date differences apply; confirm against the owner’s manual or a dealer before servicing.'
  };
}
