/**
 * Geometry toolkit for Toolbox procedural vehicle packages.
 *
 * Everything here is deterministic and dependency-light (three.js math and
 * primitive generators only) so a package can be regenerated byte-for-byte.
 * Coordinates are metres. Vehicle space: +X forward, +Y up, +Z to the
 * vehicle's right-hand side (left-hand drive driver sits at -Z).
 */
import {
  BufferGeometry, Float32BufferAttribute, Matrix4, Vector3, Quaternion, Euler,
  BoxGeometry, CylinderGeometry, TorusGeometry, LatheGeometry, TubeGeometry,
  ExtrudeGeometry, Shape, CatmullRomCurve3, Vector2, SphereGeometry
} from 'three';

export const TAU = Math.PI * 2;
export const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
export const lerp = (a, b, t) => a + (b - a) * t;
export const smooth = (a, b, v) => { const t = clamp((v - a) / (b - a), 0, 1); return t * t * (3 - 2 * t); };

/** Convert any three geometry to an indexed, position+normal-only geometry. */
export function clean(geometry) {
  let g = geometry;
  if (!g.index) {
    const count = g.attributes.position.count, index = [];
    for (let i = 0; i < count; i++) index.push(i);
    g.setIndex(index);
  }
  for (const name of Object.keys(g.attributes)) if (name !== 'position' && name !== 'normal') g.deleteAttribute(name);
  if (!g.attributes.normal) g.computeVertexNormals();
  g.clearGroups();
  return g;
}

/** Merge indexed geometries that carry position + normal. */
export function merge(list) {
  const parts = list.filter(Boolean).map(clean);
  const positions = [], normals = [], index = [];
  let offset = 0;
  for (const g of parts) {
    const p = g.attributes.position.array, n = g.attributes.normal.array;
    for (let i = 0; i < p.length; i++) { positions.push(p[i]); normals.push(n[i]); }
    for (const i of g.index.array) index.push(i + offset);
    offset += g.attributes.position.count;
  }
  const out = new BufferGeometry();
  out.setAttribute('position', new Float32BufferAttribute(positions, 3));
  out.setAttribute('normal', new Float32BufferAttribute(normals, 3));
  out.setIndex(index);
  return out;
}

/** Apply translation / rotation (Euler XYZ radians) / scale to a geometry. */
export function place(geometry, { at = [0, 0, 0], rot = [0, 0, 0], scale = [1, 1, 1], order = 'XYZ' } = {}) {
  const m = new Matrix4().compose(new Vector3(...at), new Quaternion().setFromEuler(new Euler(...rot, order)), new Vector3(...scale));
  geometry.applyMatrix4(m);
  return geometry;
}

/** Parametric grid surface. fn(u, v) → [x, y, z] with u, v ∈ [0, 1]. */
export function surface(nu, nv, fn, { flip = false } = {}) {
  const positions = [], index = [];
  for (let j = 0; j <= nv; j++) for (let i = 0; i <= nu; i++) positions.push(...fn(i / nu, j / nv));
  const row = nu + 1;
  for (let j = 0; j < nv; j++) for (let i = 0; i < nu; i++) {
    const a = j * row + i, b = a + 1, c = a + row, d = c + 1;
    if (flip) index.push(a, c, b, b, c, d); else index.push(a, b, c, b, d, c);
  }
  const g = new BufferGeometry();
  g.setAttribute('position', new Float32BufferAttribute(positions, 3));
  g.setIndex(index);
  g.computeVertexNormals();
  return g;
}

/** Mirror across the vehicle centre plane (Z → -Z) while keeping outward winding. */
export function mirrorZ(geometry) {
  const g = clean(geometry.clone());
  const p = g.attributes.position, n = g.attributes.normal;
  for (let i = 0; i < p.count; i++) { p.setZ(i, -p.getZ(i)); n.setZ(i, -n.getZ(i)); }
  const idx = g.index.array;
  for (let i = 0; i < idx.length; i += 3) { const t = idx[i + 1]; idx[i + 1] = idx[i + 2]; idx[i + 2] = t; }
  return g;
}

/** Thicken a thin surface into a closed shell so both sides render crisp edges. */
export function shell(geometry, thickness = 0.004) {
  const g = clean(geometry);
  const p = g.attributes.position, n = g.attributes.normal, count = p.count;
  const back = g.clone();
  const bp = back.attributes.position, bn = back.attributes.normal;
  for (let i = 0; i < count; i++) {
    bp.setXYZ(i, p.getX(i) - n.getX(i) * thickness, p.getY(i) - n.getY(i) * thickness, p.getZ(i) - n.getZ(i) * thickness);
    bn.setXYZ(i, -n.getX(i), -n.getY(i), -n.getZ(i));
  }
  const bi = back.index.array;
  for (let i = 0; i < bi.length; i += 3) { const t = bi[i + 1]; bi[i + 1] = bi[i + 2]; bi[i + 2] = t; }
  return merge([g, back]);
}

export function box(w, h, d, opts) { return place(clean(new BoxGeometry(w, h, d)), opts); }

/** Rounded box: rounded rectangle (w × h) extruded through depth d, centred. */
export function roundedBox(w, h, d, r = 0.01, opts, segments = 3) {
  r = Math.min(r, w / 2 - 1e-4, h / 2 - 1e-4);
  const s = new Shape(), x = -w / 2, y = -h / 2;
  s.moveTo(x + r, y); s.lineTo(x + w - r, y); s.quadraticCurveTo(x + w, y, x + w, y + r);
  s.lineTo(x + w, y + h - r); s.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  s.lineTo(x + r, y + h); s.quadraticCurveTo(x, y + h, x, y + h - r);
  s.lineTo(x, y + r); s.quadraticCurveTo(x, y, x + r, y);
  const g = new ExtrudeGeometry(s, { depth: d, bevelEnabled: false, curveSegments: segments });
  g.translate(0, 0, -d / 2);
  return place(clean(g), opts);
}

/** Cylinder along an axis ('x' | 'y' | 'z'), centred on `at`. */
export function cylinder(r1, r2, h, { axis = 'y', seg = 20, at = [0, 0, 0], rot, open = false } = {}) {
  const g = clean(new CylinderGeometry(r2, r1, h, seg, 1, open));
  const base = axis === 'x' ? [0, 0, -Math.PI / 2] : axis === 'z' ? [Math.PI / 2, 0, 0] : [0, 0, 0];
  place(g, { rot: base });
  if (rot) place(g, { rot });
  return place(g, { at });
}

export function sphere(r, { at = [0, 0, 0], scale = [1, 1, 1], seg = 14 } = {}) {
  return place(clean(new SphereGeometry(r, seg, Math.max(6, seg >> 1))), { at, scale });
}

export function torus(r, tube, { axis = 'z', seg = 32, tubeSeg = 8, arc = TAU, at = [0, 0, 0], rot } = {}) {
  const g = clean(new TorusGeometry(r, tube, tubeSeg, seg, arc));
  const base = axis === 'x' ? [0, Math.PI / 2, 0] : axis === 'y' ? [Math.PI / 2, 0, 0] : [0, 0, 0];
  place(g, { rot: base });
  if (rot) place(g, { rot });
  return place(g, { at });
}

/** Lathe a (radius, axial) profile around an axis. */
export function lathe(profile, { axis = 'z', seg = 40, at = [0, 0, 0] } = {}) {
  const g = clean(new LatheGeometry(profile.map(([r, a]) => new Vector2(Math.max(1e-5, r), a)), seg));
  // LatheGeometry revolves around +Y. Re-orient to the requested axis.
  if (axis === 'z') place(g, { rot: [Math.PI / 2, 0, 0] });
  if (axis === 'x') place(g, { rot: [0, 0, -Math.PI / 2] });
  return place(g, { at });
}

export function tube(points, radius, { seg, radial = 8, closed = false, tension = 0.5 } = {}) {
  const curve = new CatmullRomCurve3(points.map(p => new Vector3(...p)), closed, 'catmullrom', tension);
  return clean(new TubeGeometry(curve, seg || Math.max(8, points.length * 8), radius, radial, closed));
}

/** Extrude a 2D outline (points in the XY plane) through depth along Z. */
export function extrude(points, depth, opts, { holes = [], bevel = 0 } = {}) {
  const s = new Shape(points.map(([x, y]) => new Vector2(x, y)));
  for (const hole of holes) s.holes.push(new Shape(hole.map(([x, y]) => new Vector2(x, y))));
  const g = new ExtrudeGeometry(s, { depth, bevelEnabled: bevel > 0, bevelThickness: bevel, bevelSize: bevel, bevelSegments: 1, curveSegments: 10 });
  g.translate(0, 0, -depth / 2);
  return place(clean(g), opts);
}

/** Coil spring as a helix tube along +Y from `base`. */
export function helix(radius, wire, height, turns, { at = [0, 0, 0], rot } = {}) {
  const pts = [], n = Math.round(turns * 14);
  for (let i = 0; i <= n; i++) {
    const a = (i / n) * turns * TAU;
    pts.push([Math.cos(a) * radius, (i / n) * height, Math.sin(a) * radius]);
  }
  const g = tube(pts, wire, { seg: n * 2, radial: 6 });
  if (rot) place(g, { rot });
  return place(g, { at });
}

export function triangleCount(geometry) { return geometry.index ? geometry.index.count / 3 : geometry.attributes.position.count / 3; }

/* ------------------------------------------------------------------ GLB -- */

/**
 * Minimal, deterministic glTF 2.0 binary writer.
 * nodes: [{ name, translation?, rotation?, geometry?, children? }]
 */
export function writeGLB(roots, { generator = 'Toolbox procedural vehicle generator' } = {}) {
  const json = { asset: { version: '2.0', generator }, scene: 0, scenes: [{ nodes: [] }], nodes: [], meshes: [], accessors: [], bufferViews: [], buffers: [] };
  const chunks = []; let byteLength = 0;
  const pushView = (typed, target) => {
    const pad = (4 - (byteLength % 4)) % 4;
    if (pad) { chunks.push(new Uint8Array(pad)); byteLength += pad; }
    const bytes = new Uint8Array(typed.buffer, typed.byteOffset, typed.byteLength);
    chunks.push(bytes);
    json.bufferViews.push({ buffer: 0, byteOffset: byteLength, byteLength: bytes.byteLength, target });
    byteLength += bytes.byteLength;
    return json.bufferViews.length - 1;
  };
  let triangles = 0;
  const addMesh = (name, geometry) => {
    const g = clean(geometry);
    const pos = new Float32Array(g.attributes.position.array), nor = new Float32Array(g.attributes.normal.array);
    for (let i = 0; i < nor.length; i += 3) { // glTF requires unit normals
      const l = Math.hypot(nor[i], nor[i + 1], nor[i + 2]) || 1; nor[i] /= l; nor[i + 1] /= l; nor[i + 2] /= l;
      if (!Number.isFinite(nor[i])) { nor[i] = 0; nor[i + 1] = 1; nor[i + 2] = 0; }
    }
    const count = pos.length / 3, min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
    for (let i = 0; i < pos.length; i += 3) for (let k = 0; k < 3; k++) { min[k] = Math.min(min[k], pos[i + k]); max[k] = Math.max(max[k], pos[i + k]); }
    const indices = count > 65535 ? new Uint32Array(g.index.array) : new Uint16Array(g.index.array);
    triangles += indices.length / 3;
    const pv = pushView(pos, 34962), nv = pushView(nor, 34962), iv = pushView(indices, 34963);
    json.accessors.push({ bufferView: pv, componentType: 5126, count, type: 'VEC3', min, max });
    json.accessors.push({ bufferView: nv, componentType: 5126, count, type: 'VEC3' });
    json.accessors.push({ bufferView: iv, componentType: count > 65535 ? 5125 : 5123, count: indices.length, type: 'SCALAR' });
    const a = json.accessors.length;
    json.meshes.push({ name, primitives: [{ attributes: { POSITION: a - 3, NORMAL: a - 2 }, indices: a - 1, mode: 4 }] });
    return json.meshes.length - 1;
  };
  const addNode = node => {
    const entry = { name: node.name };
    if (node.translation && node.translation.some(v => v !== 0)) entry.translation = node.translation.map(v => +v.toFixed(6));
    if (node.rotation) entry.rotation = node.rotation;
    if (node.extras) entry.extras = node.extras;
    const index = json.nodes.length; json.nodes.push(entry);
    if (node.geometry) entry.mesh = addMesh(node.name, node.geometry);
    if (node.children?.length) entry.children = node.children.map(addNode);
    return index;
  };
  json.scenes[0].nodes = roots.map(addNode);
  const pad = (4 - (byteLength % 4)) % 4; if (pad) { chunks.push(new Uint8Array(pad)); byteLength += pad; }
  json.buffers.push({ byteLength });
  let jsonBytes = new TextEncoder().encode(JSON.stringify(json));
  const jsonPad = (4 - (jsonBytes.length % 4)) % 4;
  if (jsonPad) { const padded = new Uint8Array(jsonBytes.length + jsonPad).fill(0x20); padded.set(jsonBytes); jsonBytes = padded; }
  const total = 12 + 8 + jsonBytes.length + 8 + byteLength;
  const out = new Uint8Array(total), view = new DataView(out.buffer);
  view.setUint32(0, 0x46546c67, true); view.setUint32(4, 2, true); view.setUint32(8, total, true);
  view.setUint32(12, jsonBytes.length, true); view.setUint32(16, 0x4e4f534a, true); out.set(jsonBytes, 20);
  let o = 20 + jsonBytes.length;
  view.setUint32(o, byteLength, true); view.setUint32(o + 4, 0x004e4942, true); o += 8;
  for (const c of chunks) { out.set(c, o); o += c.byteLength; }
  return { bytes: out, triangles, meshes: json.meshes.length, nodes: json.nodes.length };
}
