/**
 * Reference data for the 2008 Lexus GX 470 package.
 *
 * Figures are attributed to the public sources in SOURCES; where sources
 * disagree or a figure depends on options, the text says so. Geometry and
 * placement are Toolbox approximations and say so. Nothing here is taken
 * from a factory repair manual.
 */
import { makeDescriber, makeSheet, cap } from './package-data.mjs';

export const SOURCES = {
  lexusCa: { label: 'Lexus Canada — 2008 GX 470 specifications and features', url: 'https://media.lexus.ca/content/dam/media-lexus/general/unassigned/20145/GX470_2008_specs.pdf' },
  edmunds: { label: 'Edmunds — 2008 Lexus GX 470 features & specs', url: 'https://www.edmunds.com/lexus/gx-470/2008/features-specs/' },
  carspecs: { label: 'CarSpecs — 2008 Lexus GX 470 4.7L V8 4x4', url: 'https://www.carspecs.us/cars/2008/lexus/gx/41603' },
  wikiGX: { label: 'Wikipedia — Lexus GX', url: 'https://en.wikipedia.org/wiki/Lexus_GX' },
  wikiUZ: { label: 'Wikipedia — Toyota UZ engine', url: 'https://en.wikipedia.org/wiki/Toyota_UZ_engine' },
  rearDoor: { label: 'Go-Parts — 2003–2009 GX 470 rear door and flip-up glass', url: 'https://www.go-parts.com/garage/deck-lid-lexus-gx470-2003-2009' },
  amsoil: { label: 'AMSOIL — 2008 Lexus GX 470 (2UZ-FE) lubricant guide', url: 'https://www.amsoil.com/lookup/auto-and-light-truck/2008/lexus/gx470/4-7l-8-cyl-engine-code-2uz-fe-e/' }
};

export const LAYERS = [
  { id: 'body', label: 'Body panels & closures' },
  { id: 'glass', label: 'Glass' },
  { id: 'lighting', label: 'Lighting' },
  { id: 'trim', label: 'Exterior trim' },
  { id: 'structure', label: 'Body structure & frame' },
  { id: 'interior', label: 'Interior' },
  { id: 'safety', label: 'Airbags (SRS)' },
  { id: 'engine', label: 'Engine & transmission' },
  { id: 'bay', label: 'Engine-bay systems' },
  { id: 'driveline', label: '4WD driveline' },
  { id: 'chassis', label: 'Suspension, steering & brakes' },
  { id: 'wheels', label: 'Wheels & tyres' },
  { id: 'fuel', label: 'Fuel & exhaust' }
];

const APPROX = 'Shape and position are a Toolbox approximation for orientation; not a factory drawing.';
const APPROX_PKG = 'Packaging position is approximate. Confirm the location on the vehicle or in the owner’s manual before servicing.';
const sideTxt = s => `${cap(s)} (${s === 'left' ? 'driver' : 'passenger'} side on left-hand-drive vehicles)`;
const pos = (p, s) => `${cap(p)} ${s}`;

const FAMILIES = [
  /* ------------------------------------------------------------------ body */
  { test: /^hood$/, data: () => ({ label: 'Bonnet (hood)', category: 'Body', layer: 'body', description: 'Steel bonnet hinged at the cowl. Released from a lever under the left of the dashboard, then a safety catch under the front edge.', location: 'Front, over the engine bay.' }) },
  { test: /^hood_hinges$/, data: () => ({ label: 'Bonnet hinges', category: 'Body', layer: 'body', description: 'Hinges at the rear corners of the bonnet.', location: 'Rear corners of the bonnet.' }) },
  { test: /^(front|rear)_bumper_cover$/, data: (id, m) => ({ label: `${cap(m[1])} bumper cover`, category: 'Body', layer: 'body', description: m[1] === 'front' ? 'Painted front fascia with the fog lamps and turn signals, over a steel reinforcement bolted to the frame.' : 'Rear bumper cover with a step pad, over the rear reinforcement.', location: `${cap(m[1])} of the vehicle.` }) },
  { test: /^grille_surround$/, data: () => ({ label: 'Grille and lamp surround', category: 'Body', layer: 'body', description: 'Upper front panel around the grille and headlamps.', location: 'Front, above the bumper.', accuracyNote: APPROX }) },
  { test: /^(front|rear)_bumper_reinforcement$/, data: (id, m) => ({ label: `${cap(m[1])} bumper reinforcement`, category: 'Structure', layer: 'structure', description: 'Steel beam behind the bumper cover, bolted to the frame, that takes low-speed impacts.', location: `Behind the ${m[1]} bumper cover.` }) },
  { test: /^front_fender_(left|right)$/, data: (id, m) => ({ label: `Front wing (fender), ${m[1]}`, category: 'Body', layer: 'body', description: 'Bolt-on front wing with a flared wheel arch.', location: sideTxt(m[1]) }) },
  { test: /^rear_quarter_panel_(left|right)$/, data: (id, m) => ({ label: `Rear quarter panel, ${m[1]}`, category: 'Body', layer: 'body', description: 'Welded rear body side around the rear wheel arch; the left one carries the fuel filler door.', location: sideTxt(m[1]) }) },
  { test: /^rocker_panel_(left|right)$/, data: (id, m) => ({ label: `Rocker panel (sill), ${m[1]}`, category: 'Body', layer: 'body', description: 'Sill beneath the doors, behind the running board.', location: sideTxt(m[1]) }) },
  { test: /^([abcd])_pillar_(left|right)$/, data: (id, m) => ({ label: `${m[1].toUpperCase()}-pillar, ${m[2]}`, category: 'Structure', layer: 'structure', description: { a: 'Windscreen pillar.', b: 'Centre pillar between the doors; it carries the front seat-belt anchor.', c: 'Pillar behind the rear doors.', d: 'Rearmost pillar beside the rear door.' }[m[1]], location: sideTxt(m[2]) }) },
  { test: /^roof_panel$/, data: () => ({ label: 'Roof panel', category: 'Body', layer: 'body', description: 'Steel roof with the roof rails.', location: 'Top of the cabin.' }) },
  { test: /^rear_roof_header$/, data: () => ({ label: 'Rear roof header', category: 'Body', layer: 'body', description: 'Rear edge of the roof above the rear door opening.', location: 'Rear of the roof.' }) },
  { test: /^rear_body_panel$/, data: () => ({ label: 'Rear body panel', category: 'Body', layer: 'body', description: 'Body around the rear door opening, carrying the tail lamps.', location: 'Rear of the vehicle.' }) },
  { test: /^cowl_panel$/, data: () => ({ label: 'Cowl panel', category: 'Body', layer: 'body', description: 'Panel between the bonnet and windscreen with the fresh-air intake and wiper pivots.', location: 'Base of the windscreen.' }) },
  { test: /^roof_rails$/, data: () => ({ label: 'Roof rails', category: 'Trim', layer: 'trim', description: 'Roof rails for cross bars and roof loads; they are the highest point of the vehicle, 1,895 mm (74.6 in) off the ground.', location: 'Roof.', sources: ['lexusCa'] }) },
  { test: /^running_board_(left|right)$/, data: (id, m) => ({ label: `Running board, ${m[1]}`, category: 'Trim', layer: 'trim', description: 'Side step for getting in and out.', location: `${cap(m[1])} side, below the doors.` }) },
  { test: /^door_(front|rear)_(left|right)_outer_panel$/, data: (id, m) => ({ label: `${pos(m[1], m[2])} door`, category: 'Body', layer: 'body', parentAssembly: `${pos(m[1], m[2])} door assembly`, description: 'Door skin over a frame with the window regulator, lock, side-impact beam and speaker.', location: sideTxt(m[2]), failures: 'Worn check straps and window-regulator cables are common with age.' }) },
  { test: /^door_(front|rear)_(left|right)_trim_panel$/, data: (id, m) => ({ label: `${pos(m[1], m[2])} door trim panel`, category: 'Interior', layer: 'interior', parentAssembly: `${pos(m[1], m[2])} door assembly`, description: 'Inner door panel with armrest, window switch and inside handle.', location: 'Inside face of the door.' }) },
  { test: /^door_(front|rear)_(left|right)_window_frame$/, data: (id, m) => ({ label: `${pos(m[1], m[2])} door window frame`, category: 'Body', layer: 'body', parentAssembly: `${pos(m[1], m[2])} door assembly`, description: 'Door sash guiding the glass.', location: 'Upper part of the door.' }) },
  { test: /^door_(front|rear)_(left|right)_glass$/, data: (id, m) => ({ label: `${pos(m[1], m[2])} door glass`, category: 'Glass', layer: 'glass', parentAssembly: `${pos(m[1], m[2])} door assembly`, description: 'Tempered power-window glass.', location: 'Door window opening.' }) },
  { test: /^door_(front|rear)_(left|right)_handle$/, data: (id, m) => ({ label: `${pos(m[1], m[2])} door handle`, category: 'Trim', layer: 'trim', description: 'Exterior door handle.', location: 'Door outer panel.' }) },
  { test: /^rear_door$/, data: () => ({ label: 'Rear door (side-hinged)', category: 'Body', layer: 'body', description: 'The GX 470’s rear door swings out to the side rather than lifting. It is hinged on the right (passenger) side, and its glass also opens on its own, hinged at the top, for loading small items.', location: 'Rear of the vehicle.', failures: 'Latch and glass-hatch strut wear; the glass hatch can stop latching.', sources: ['rearDoor'] }) },
  { test: /^rear_glass_hatch$/, data: () => ({ label: 'Rear glass hatch', category: 'Glass', layer: 'glass', description: 'Top-hinged rear window that opens independently of the rear door, with its own latch.', location: 'Upper part of the rear door.', sources: ['rearDoor'] }) },
  { test: /^rear_door_handle$/, data: () => ({ label: 'Rear door handle', category: 'Trim', layer: 'trim', description: 'Handle for the side-hinged rear door.', location: 'Rear door, left edge.' }) },
  { test: /^license_plate_recess$/, data: () => ({ label: 'Licence-plate recess', category: 'Trim', layer: 'trim', description: 'Plate mounting on the rear door.', location: 'Rear door.' }) },
  { test: /^fuel_filler_door$/, data: () => ({ label: 'Fuel filler door', category: 'Body', layer: 'body', description: 'Flap over the fuel cap.', location: 'Left rear quarter panel.', accuracyNote: APPROX_PKG }) },
  { test: /^side_mirror_(left|right)$/, data: (id, m) => ({ label: `Door mirror, ${m[1]}`, category: 'Trim', layer: 'trim', description: 'Power-adjusted door mirror (heated on many vehicles) that folds by hand.', location: sideTxt(m[1]) }) },
  { test: /^wiper_arm_(driver|passenger)$/, data: (id, m) => ({ label: `${cap(m[1])} wiper arm`, category: 'Trim', layer: 'trim', description: 'Windscreen wiper arm and blade.', location: 'Base of the windscreen.' }) },
  { test: /^rear_wiper$/, data: () => ({ label: 'Rear wiper', category: 'Trim', layer: 'trim', description: 'Wiper on the rear glass hatch.', location: 'Rear glass.' }) },
  { test: /^tow_hooks$/, data: () => ({ label: 'Front tow hooks', category: 'Structure', layer: 'structure', description: 'Recovery points on the front of the frame, for straight pulls only.', location: 'Under the front bumper.', accuracyNote: APPROX_PKG }) },
  { test: /^front_skid_plate$/, data: () => ({ label: 'Front skid plate', category: 'Structure', layer: 'structure', description: 'Plate protecting the engine sump and front differential off-road.', location: 'Under the engine.' }) },
  { test: /^wheel_well_liner_(front|rear)_(left|right)$/, data: (id, m) => ({ label: `Wheel-arch liner, ${m[1]} ${m[2]}`, category: 'Body', layer: 'body', description: 'Plastic splash liner in the wheel arch.', location: `${cap(m[1])} ${m[2]} wheel arch.` }) },
  /* ----------------------------------------------------------------- glass */
  { test: /^windshield$/, data: () => ({ label: 'Windscreen', category: 'Glass', layer: 'glass', description: 'Laminated, bonded windscreen.', location: 'Front of the cabin.' }) },
  { test: /^rear_quarter_glass_(left|right)$/, data: (id, m) => ({ label: `Rear quarter window, ${m[1]}`, category: 'Glass', layer: 'glass', description: 'Fixed side glass beside the third row.', location: sideTxt(m[1]) }) },
  /* -------------------------------------------------------------- lighting */
  { test: /^headlamp_(left|right)$/, data: (id, m) => ({ label: `Headlamp, ${m[1]}`, category: 'Lighting', layer: 'lighting', description: 'Headlamp unit with low and high beams and the front parking lamp.', location: `Front ${m[1]} corner.`, accuracyNote: APPROX }) },
  { test: /^fog_lamp_(left|right)$/, data: (id, m) => ({ label: `Fog lamp, ${m[1]}`, category: 'Lighting', layer: 'lighting', description: 'Front fog lamp in the bumper.', location: `Front bumper, ${m[1]}.` }) },
  { test: /^front_turn_signal_(left|right)$/, data: (id, m) => ({ label: `Front turn signal, ${m[1]}`, category: 'Lighting', layer: 'lighting', description: 'Front indicator lamp.', location: `Front bumper corner, ${m[1]}.`, accuracyNote: APPROX }) },
  { test: /^tail_lamp_(left|right)$/, data: (id, m) => ({ label: `Tail lamp, ${m[1]}`, category: 'Lighting', layer: 'lighting', description: 'Tail, stop, turn and reversing lamp cluster on the rear corner.', location: `Rear ${m[1]} corner.` }) },
  { test: /^rear_reflector_(left|right)$/, data: (id, m) => ({ label: `Rear reflector, ${m[1]}`, category: 'Lighting', layer: 'lighting', description: 'Red reflector in the rear bumper.', location: `Rear bumper, ${m[1]}.` }) },
  { test: /^side_marker_(left|right)$/, data: (id, m) => ({ label: `Side marker lamp, ${m[1]}`, category: 'Lighting', layer: 'lighting', description: 'Amber side marker.', location: `Front ${m[1]} wing.`, accuracyNote: APPROX }) },
  { test: /^high_mount_stop_lamp$/, data: () => ({ label: 'High-mounted stop lamp', category: 'Lighting', layer: 'lighting', description: 'Centre brake light at the top of the rear door.', location: 'Top of the rear door.' }) },
  { test: /^radiator_grille$/, data: () => ({ label: 'Radiator grille', category: 'Trim', layer: 'trim', description: 'Chrome grille letting air to the radiator and A/C condenser.', location: 'Front, between the headlamps.' }) },
  { test: /^front_emblem$/, data: () => ({ label: 'Front emblem', category: 'Trim', layer: 'trim', description: 'Badge on the grille (shown as a plain disc).', location: 'Centre of the grille.' }) },
  /* ------------------------------------------------------------ structure */
  { test: /^ladder_frame$/, data: () => ({ label: 'Ladder frame (chassis)', category: 'Structure', layer: 'structure', description: 'Boxed steel ladder frame: two side rails joined by crossmembers. The engine, suspension and body all mount to it (body-on-frame construction), which suits towing and off-road use.', location: 'Under the body, full length.', maintenance: 'Inspect for rust, especially in salted-road climates.', sources: ['wikiGX'] }) },
  { test: /^body_mounts$/, data: () => ({ label: 'Body mounts', category: 'Structure', layer: 'structure', description: 'Rubber-insulated mounts that bolt the body to the frame and isolate road noise.', location: 'Between the frame rails and the floor.', accuracyNote: APPROX_PKG }) },
  { test: /^floor_pan$/, data: () => ({ label: 'Floor pan', category: 'Structure', layer: 'structure', description: 'Body floor sitting on the frame, with the bulkhead to the engine bay.', location: 'Cabin floor.' }) },
  { test: /^firewall$/, data: () => ({ label: 'Firewall (dash panel)', category: 'Structure', layer: 'structure', description: 'Bulkhead between the engine bay and the cabin.', location: 'Behind the engine.' }) },
  { test: /^radiator_support$/, data: () => ({ label: 'Radiator support', category: 'Structure', layer: 'structure', description: 'Frame carrying the radiator, condenser and bonnet latch.', location: 'Front of the engine bay.' }) },
  { test: /^cowl_top_vent$/, data: () => ({ label: 'Cowl top vent', category: 'Body', layer: 'body', description: 'Grille over the fresh-air intake for the heater and air conditioning.', location: 'Base of the windscreen.' }) },
  /* -------------------------------------------------------------- interior */
  { test: /^instrument_panel_(upper|lower)$/, data: (id, m) => ({ label: `Instrument panel, ${m[1]}`, category: 'Interior', layer: 'interior', description: m[1] === 'upper' ? 'Dashboard top with the passenger airbag door and defroster outlets.' : 'Lower dashboard with the glovebox and knee-level trim.', location: 'Front of the cabin.' }) },
  { test: /^instrument_cluster$/, data: () => ({ label: 'Instrument cluster', category: 'Interior', layer: 'interior', description: 'Speedometer, tachometer, fuel and temperature gauges, warning lights and the multi-information display.', location: 'Behind the steering wheel.' }) },
  { test: /^center_stack$/, data: () => ({ label: 'Centre stack', category: 'Interior', layer: 'interior', description: 'Audio (and navigation, where fitted), hazard switch and climate controls.', location: 'Centre of the dashboard.' }) },
  { test: /^audio_display$/, data: () => ({ label: 'Audio / navigation display', category: 'Interior', layer: 'interior', description: 'Audio head unit; the optional navigation system adds a touchscreen.', location: 'Top of the centre stack.' }) },
  { test: /^climate_controls$/, data: () => ({ label: 'Climate controls', category: 'Interior', layer: 'interior', description: 'Automatic climate control; the rear passengers have their own controls.', location: 'Centre stack.', accuracyNote: APPROX }) },
  { test: /^air_vents$/, data: () => ({ label: 'Air vents', category: 'Interior', layer: 'interior', description: 'Dashboard air outlets.', location: 'Dashboard.' }) },
  { test: /^glovebox$/, data: () => ({ label: 'Glovebox', category: 'Interior', layer: 'interior', description: 'Lockable glovebox.', location: 'Passenger side of the dashboard.' }) },
  { test: /^steering_column$/, data: () => ({ label: 'Steering column', category: 'Chassis', layer: 'chassis', description: 'Tilt-and-telescopic column with collapsible energy-absorbing sections.', location: 'Driver side, behind the dashboard.' }) },
  { test: /^steering_wheel$/, data: () => ({ label: 'Steering wheel', category: 'Interior', layer: 'interior', description: 'Steering wheel with audio controls and the driver’s airbag.', location: 'In front of the driver.' }) },
  { test: /^pedals$/, data: () => ({ label: 'Accelerator and brake pedals', category: 'Interior', layer: 'interior', description: 'Automatic transmission: accelerator and brake only.', location: 'Driver’s footwell.' }) },
  { test: /^center_console$/, data: () => ({ label: 'Centre console', category: 'Interior', layer: 'interior', description: 'Console between the front seats with the gear selector, 4WD switches, cupholders and armrest storage.', location: 'Between the front seats.' }) },
  { test: /^console_armrest_lid$/, data: () => ({ label: 'Console armrest lid', category: 'Interior', layer: 'interior', description: 'Hinged armrest over the console box.', location: 'Rear of the centre console.' }) },
  { test: /^gear_selector$/, data: () => ({ label: 'Gear selector', category: 'Interior', layer: 'interior', description: 'Selector for the five-speed automatic: P, R, N, D, and lower gear limits.', location: 'Centre console.' }) },
  { test: /^four_wheel_drive_controls$/, data: () => ({ label: '4WD controls', category: 'Driveline', layer: 'driveline', description: 'Controls for the full-time 4WD system: the centre-differential lock and the transfer case low range (L4), used off-road at low speed.', location: 'Centre console, beside the gear selector.', accuracyNote: 'Switch shapes and positions are approximate; see the owner’s manual for your vehicle.' }) },
  { test: /^seat_cushion_front_(left|right)$/, data: (id, m) => ({ label: `Front seat cushion, ${m[1]}`, category: 'Interior', layer: 'interior', description: 'Power-adjustable front seat (heated on many vehicles).', location: sideTxt(m[1]) }) },
  { test: /^seat_back_front_(left|right)$/, data: (id, m) => ({ label: `Front seatback, ${m[1]}`, category: 'Interior', layer: 'interior', description: 'Front seatback with a side airbag in its outboard edge.', location: sideTxt(m[1]) }) },
  { test: /^headrest_front_(left|right)$/, data: (id, m) => ({ label: `Front head restraint, ${m[1]}`, category: 'Interior', layer: 'interior', description: 'Adjustable head restraint.', location: `Top of the ${m[1]} front seat.` }) },
  { test: /^second_row_seat_(60|40)$/, data: (id, m) => ({ label: `Second-row seat (${m[1]} % section)`, category: 'Interior', layer: 'interior', description: 'Second-row bench split 60/40; each part folds and tumbles forward for access to the third row.', location: 'Second row.' }) },
  { test: /^third_row_seat$/, data: () => ({ label: 'Third-row seat', category: 'Interior', layer: 'interior', description: 'Split third-row seat that folds away to extend the cargo floor; with it the GX 470 seats up to eight.', location: 'Third row, in the cargo area.', sources: ['wikiGX'] }) },
  { test: /^seat_belts$/, data: () => ({ label: 'Seat belts', category: 'Safety (SRS)', layer: 'safety', description: 'Three-point belts with pretensioners and force limiters in front.', location: 'Pillars and seats.' }) },
  { test: /^(floor_carpet|cargo_area_floor|headliner|overhead_console|rearview_mirror)$/, data: (id, m) => ({ label: { floor_carpet: 'Floor carpet', cargo_area_floor: 'Cargo area floor', headliner: 'Headliner', overhead_console: 'Overhead console', rearview_mirror: 'Rear-view mirror' }[m[1]], category: 'Interior', layer: 'interior', description: { floor_carpet: 'Moulded carpet over the floor.', cargo_area_floor: 'Cargo floor behind the second row; the third row folds into it.', headliner: 'Roof lining.', overhead_console: 'Map lights, sunglasses holder and moonroof switch (where fitted).', rearview_mirror: 'Rear-view mirror (auto-dimming on many vehicles).' }[m[1]], location: 'Cabin.' }) },
  { test: /^sun_visor_(left|right)$/, data: (id, m) => ({ label: `Sun visor, ${m[1]}`, category: 'Interior', layer: 'interior', description: 'Sun visor with vanity mirror.', location: 'Top of the windscreen.' }) },
  /* ---------------------------------------------------------------- airbags */
  { test: /^airbag_driver_front$/, data: () => ({ label: 'Driver front airbag', category: 'Safety (SRS)', layer: 'safety', description: 'Airbag in the steering-wheel hub.', location: 'Steering wheel.' }) },
  { test: /^airbag_passenger_front$/, data: () => ({ label: 'Front passenger airbag', category: 'Safety (SRS)', layer: 'safety', description: 'Airbag in the top of the dashboard.', location: 'Passenger side of the dashboard.' }) },
  { test: /^airbag_seat_side_(left|right)$/, data: (id, m) => ({ label: `Front seat side airbag, ${m[1]}`, category: 'Safety (SRS)', layer: 'safety', description: 'Side airbag in the outboard edge of the front seatback.', location: `${cap(m[1])} front seatback.` }) },
  { test: /^airbag_curtain_(left|right)$/, data: (id, m) => ({ label: `Side curtain airbag, ${m[1]}`, category: 'Safety (SRS)', layer: 'safety', description: 'Curtain airbag along the roof rail covering all three rows; it also deploys in a rollover.', location: `${cap(m[1])} roof rail.`, sources: ['wikiGX'] }) },
  /* ---------------------------------------------------------------- engine */
  { test: /^engine_block$/, data: () => ({ label: 'Engine block (2UZ-FE V8)', category: 'Engine', layer: 'engine', description: '4.7-litre 90° V8 with cast-iron block and aluminium heads, mounted lengthwise.', location: 'Engine bay.', specs: { Displacement: '4,664 cc (4.7 L)', Output: '263 hp @ 5,400 rpm · 323 lb-ft @ 3,400 rpm', 'Bore × stroke': '94.0 × 84.0 mm' }, sources: ['wikiUZ', 'lexusCa'] }) },
  { test: /^cylinder_head_(left|right)$/, data: (id, m) => ({ label: `Cylinder head, ${m[1]} bank`, category: 'Engine', layer: 'engine', description: 'Aluminium DOHC head with four valves per cylinder and VVT-i on the intake cams.', location: `${cap(m[1])} bank of the V8.`, sources: ['wikiUZ'] }) },
  { test: /^valve_cover_(left|right)$/, data: (id, m) => ({ label: `Cam cover, ${m[1]} bank`, category: 'Engine', layer: 'engine', description: 'Cover over the camshafts; one carries the oil filler cap.', location: `${cap(m[1])} bank.` }) },
  { test: /^intake_manifold$/, data: () => ({ label: 'Intake manifold', category: 'Engine', layer: 'engine', description: 'Plenum and runners in the vee of the engine.', location: 'Top of the engine.' }) },
  { test: /^throttle_body$/, data: () => ({ label: 'Throttle body', category: 'Engine', layer: 'engine', description: 'Electronically controlled throttle.', location: 'Front of the intake manifold.' }) },
  { test: /^timing_belt_cover$/, data: () => ({ label: 'Timing belt cover', category: 'Engine', layer: 'engine', description: 'Covers the timing belt that drives the four camshafts. The 2UZ-FE uses a belt, not a chain, so it is a scheduled replacement item (often with the water pump).', location: 'Front of the engine.', maintenance: 'Replace the timing belt at the interval in the maintenance schedule (commonly about 90,000 miles).', sources: ['wikiUZ'] }) },
  { test: /^crankshaft_pulley$/, data: () => ({ label: 'Crankshaft pulley', category: 'Engine', layer: 'engine', description: 'Harmonic balancer driving the accessory belt.', location: 'Front of the engine.' }) },
  { test: /^oil_pan$/, data: () => ({ label: 'Oil pan (sump)', category: 'Engine', layer: 'engine', description: 'Engine oil sump with the drain plug.', location: 'Bottom of the engine.', specs: { 'Oil grade': 'SAE 5W-30' }, sources: ['amsoil'] }) },
  { test: /^oil_filter$/, data: () => ({ label: 'Oil filter', category: 'Engine', layer: 'engine', description: 'Spin-on oil filter, reached from underneath.', location: 'Lower front of the engine.', accuracyNote: APPROX_PKG }) },
  { test: /^oil_dipstick$/, data: () => ({ label: 'Engine oil dipstick', category: 'Engine bay', layer: 'bay', description: 'Shows the oil level between the low and full marks; check with the engine off on level ground.', location: 'Engine bay, beside the engine.', accuracyNote: APPROX_PKG }) },
  { test: /^oil_filler_cap$/, data: () => ({ label: 'Oil filler cap', category: 'Engine bay', layer: 'bay', description: 'Top-up point for engine oil.', location: 'Cam cover.', specs: { 'Oil grade': 'SAE 5W-30', Capacity: 'About 7 US qt (6.6 L) with filter; published figures differ, so check the owner’s manual' }, sources: ['amsoil'], accuracyNote: APPROX_PKG }) },
  { test: /^exhaust_manifold_(left|right)$/, data: (id, m) => ({ label: `Exhaust manifold, ${m[1]} bank`, category: 'Engine', layer: 'engine', description: 'Collects exhaust from one bank.', location: `Outside of the ${m[1]} bank.` }) },
  { test: /^ignition_coils$/, data: () => ({ label: 'Ignition coils', category: 'Engine', layer: 'engine', description: 'One coil per cylinder, on top of each spark plug.', location: 'On the cylinder heads.' }) },
  { test: /^spark_plugs$/, data: () => ({ label: 'Spark plugs', category: 'Engine', layer: 'engine', description: 'Long-life iridium plugs, eight in all.', location: 'In the cylinder heads.' }) },
  { test: /^engine_mounts$/, data: () => ({ label: 'Engine mounts', category: 'Engine', layer: 'engine', description: 'Rubber mounts supporting the engine on the frame.', location: 'Each side of the engine.' }) },
  { test: /^transmission$/, data: () => ({ label: 'Automatic transmission', category: 'Engine', layer: 'engine', description: 'Five-speed electronically controlled automatic.', location: 'Behind the engine.', sources: ['lexusCa'] }) },
  /* -------------------------------------------------------------- driveline */
  { test: /^transfer_case$/, data: () => ({ label: 'Transfer case', category: 'Driveline', layer: 'driveline', description: 'Splits drive between the axles through a Torsen limited-slip centre differential that can be locked, and gives a low range for steep or slow off-road work.', location: 'Behind the transmission.', sources: ['lexusCa', 'wikiGX'] }) },
  { test: /^(front|rear)_propeller_shaft$/, data: (id, m) => ({ label: `${cap(m[1])} propeller shaft`, category: 'Driveline', layer: 'driveline', description: `Shaft from the transfer case to the ${m[1]} differential.`, location: 'Under the vehicle.' }) },
  { test: /^front_differential$/, data: () => ({ label: 'Front differential', category: 'Driveline', layer: 'driveline', description: 'Front differential, bolted to the frame for the independent front suspension.', location: 'Front, beside the engine sump.' }) },
  { test: /^front_driveshaft_(left|right)$/, data: (id, m) => ({ label: `Front drive shaft, ${m[1]}`, category: 'Driveline', layer: 'driveline', description: 'CV-jointed half-shaft to the front hub.', location: `Front ${m[1]}.`, maintenance: 'Split CV boots throw grease; replace them before the joint wears.' }) },
  { test: /^rear_differential$/, data: () => ({ label: 'Rear differential', category: 'Driveline', layer: 'driveline', description: 'Differential in the rigid rear axle; its underside sets the minimum ground clearance of 211 mm (8.3 in).', location: 'Centre of the rear axle.', sources: ['lexusCa'] }) },
  { test: /^rear_axle_housing$/, data: () => ({ label: 'Rear axle housing', category: 'Driveline', layer: 'driveline', description: 'Rigid (live) rear axle carrying the differential and half-shafts.', location: 'Rear.' }) },
  /* -------------------------------------------------------------- chassis */
  { test: /^front_(upper|lower)_control_arm_(left|right)$/, data: (id, m) => ({ label: `Front ${m[1]} control arm, ${m[2]}`, category: 'Chassis', layer: 'chassis', description: 'Wishbone of the independent double-wishbone front suspension.', location: `Front ${m[2]}.` }) },
  { test: /^front_coil_spring_(left|right)$/, data: (id, m) => ({ label: `Front coil spring, ${m[1]}`, category: 'Chassis', layer: 'chassis', description: 'Coil spring around the front shock absorber.', location: `Front ${m[1]}.` }) },
  { test: /^(front|rear)_shock_absorber_(left|right)$/, data: (id, m) => ({ label: `${cap(m[1])} shock absorber, ${m[2]}`, category: 'Chassis', layer: 'chassis', description: 'Hydraulic damper.', location: `${cap(m[1])} ${m[2]}.` }) },
  { test: /^(front|rear)_stabilizer_bar$/, data: (id, m) => ({ label: `${cap(m[1])} stabiliser bar`, category: 'Chassis', layer: 'chassis', description: 'Anti-roll bar that limits body lean in corners.', location: `${cap(m[1])} suspension.` }) },
  { test: /^steering_knuckle_(left|right)$/, data: (id, m) => ({ label: `Steering knuckle, ${m[1]}`, category: 'Chassis', layer: 'chassis', description: 'Carries the front hub and brake and turns with the steering.', location: `Front ${m[1]}.` }) },
  { test: /^tie_rod_(left|right)$/, data: (id, m) => ({ label: `Tie rod, ${m[1]}`, category: 'Chassis', layer: 'chassis', description: 'Links the steering rack to the knuckle.', location: `Front ${m[1]}.` }) },
  { test: /^steering_rack$/, data: () => ({ label: 'Steering rack', category: 'Chassis', layer: 'chassis', description: 'Rack-and-pinion steering with hydraulic power assistance.', location: 'Front, behind the axle line.', sources: ['lexusCa'] }) },
  { test: /^rear_air_spring_(left|right)$/, data: (id, m) => ({ label: `Rear air spring, ${m[1]}`, category: 'Chassis', layer: 'chassis', description: 'Air spring of the rear height-control suspension: a compressor and height sensor keep the rear level with a load or trailer.', location: `Rear ${m[1]}, over the axle.`, failures: 'Air springs age and leak; the rear then sits low, often after the vehicle has stood.', sources: ['lexusCa'] }) },
  { test: /^rear_(lower|upper)_control_arms?(_left|_right)?$/, data: (id, m) => ({ label: `Rear ${m[1]} control arm${m[2] ? `, ${m[2].slice(1)}` : 's'}`, category: 'Chassis', layer: 'chassis', description: 'Links of the four-link rear axle location.', location: 'Rear suspension.' }) },
  { test: /^rear_lateral_rod$/, data: () => ({ label: 'Rear lateral rod', category: 'Chassis', layer: 'chassis', description: 'Locates the rear axle sideways (Panhard rod).', location: 'Rear suspension.' }) },
  { test: /^height_control_sensor$/, data: () => ({ label: 'Rear height-control sensor', category: 'Chassis', layer: 'chassis', description: 'Measures ride height for the air suspension.', location: 'Rear frame.', accuracyNote: APPROX_PKG }) },
  /* ------------------------------------------------------------ wheels & brakes */
  { test: /^wheel_rim_(front|rear)_(left|right)$/, data: (id, m) => ({ label: `Wheel, ${m[1]} ${m[2]}`, category: 'Wheels', layer: 'wheels', description: '17-inch alloy wheel on six studs (6 × 139.7 mm).', location: `${cap(m[1])} ${m[2]}.` }) },
  { test: /^tyre_(front|rear)_(left|right)$/, data: (id, m) => ({ label: `Tyre, ${m[1]} ${m[2]}`, category: 'Wheels', layer: 'wheels', description: 'All-season tyre.', location: `${cap(m[1])} ${m[2]}.`, specs: { Size: 'P265/65R17' }, sources: ['lexusCa'] }) },
  { test: /^wheel_hub_(front|rear)_(left|right)$/, data: (id, m) => ({ label: `Wheel hub, ${m[1]} ${m[2]}`, category: 'Wheels', layer: 'wheels', description: 'Hub with six wheel studs.', location: `${cap(m[1])} ${m[2]}.` }) },
  { test: /^brake_disc_(front|rear)_(left|right)$/, data: (id, m) => ({ label: `Brake disc, ${m[1]} ${m[2]}`, category: 'Brakes', layer: 'chassis', description: 'Ventilated disc; the GX 470 has discs on all four wheels.', location: `${cap(m[1])} ${m[2]}.` }) },
  { test: /^brake_caliper_(front|rear)_(left|right)$/, data: (id, m) => ({ label: `Brake caliper, ${m[1]} ${m[2]}`, category: 'Brakes', layer: 'chassis', description: 'Caliper clamping the pads on the disc.', location: `${cap(m[1])} ${m[2]}.` }) },
  { test: /^brake_pads_(front|rear)_(left|right)$/, data: (id, m) => ({ label: `Brake pads, ${m[1]} ${m[2]}`, category: 'Brakes', layer: 'chassis', description: 'Pads with a squeal indicator that warns when they are worn.', location: `${cap(m[1])} ${m[2]} caliper.` }) },
  { test: /^brake_master_cylinder$/, data: () => ({ label: 'Brake master cylinder and booster', category: 'Brakes', layer: 'bay', description: 'Turns pedal effort into hydraulic pressure.', location: 'Driver side of the firewall.' }) },
  { test: /^brake_fluid_reservoir$/, data: () => ({ label: 'Brake fluid reservoir', category: 'Engine bay', layer: 'bay', description: 'Check that the level is between MIN and MAX; a falling level usually means worn pads or a leak.', location: 'On the master cylinder.' }) },
  { test: /^abs_actuator$/, data: () => ({ label: 'ABS / VSC actuator', category: 'Brakes', layer: 'bay', description: 'Hydraulic unit for ABS, stability control (VSC) and active traction control (A-TRAC).', location: 'Engine bay, driver side.', accuracyNote: APPROX_PKG, sources: ['lexusCa'] }) },
  { test: /^spare_tyre$/, data: () => ({ label: 'Spare tyre', category: 'Wheels', layer: 'wheels', description: 'Spare carried under the rear floor on a winch (the Land Cruiser Prado it is based on carries its spare on the rear door).', location: 'Under the rear of the vehicle.', sources: ['rearDoor'] }) },
  { test: /^spare_tyre_carrier$/, data: () => ({ label: 'Spare tyre winch', category: 'Wheels', layer: 'wheels', description: 'Winch that lowers the spare on its cable using the jack handle.', location: 'Under the rear floor.', accuracyNote: APPROX_PKG }) },
  { test: /^jack_and_tools$/, data: () => ({ label: 'Jack and tools', category: 'Wheels', layer: 'wheels', description: 'Jack, handle and wheel-nut wrench.', location: 'Cargo area side trim.', accuracyNote: APPROX_PKG }) },
  /* --------------------------------------------------------- engine bay */
  { test: /^radiator$/, data: () => ({ label: 'Radiator', category: 'Engine bay', layer: 'bay', description: 'Cools the engine coolant; the transmission fluid cooler is built in.', location: 'Front of the engine bay.' }) },
  { test: /^radiator_cap$/, data: () => ({ label: 'Radiator cap', category: 'Engine bay', layer: 'bay', description: 'Pressure cap on the radiator. Never open it when the engine is hot.', location: 'Top of the radiator.' }) },
  { test: /^(cooling_fan|fan_shroud)$/, data: (id, m) => ({ label: m[1] === 'cooling_fan' ? 'Cooling fan' : 'Fan shroud', category: 'Engine bay', layer: 'bay', description: m[1] === 'cooling_fan' ? 'Engine-driven fan with a viscous (fluid) coupling.' : 'Shroud that directs the fan’s air through the radiator.', location: 'Behind the radiator.' }) },
  { test: /^radiator_hoses$/, data: () => ({ label: 'Radiator hoses', category: 'Engine bay', layer: 'bay', description: 'Upper and lower coolant hoses.', location: 'Between the engine and the radiator.' }) },
  { test: /^water_pump$/, data: () => ({ label: 'Water pump', category: 'Engine bay', layer: 'bay', description: 'Coolant pump driven by the timing belt.', location: 'Front of the engine, behind the timing cover.' }) },
  { test: /^coolant_reservoir$/, data: () => ({ label: 'Coolant reservoir', category: 'Engine bay', layer: 'bay', description: 'Expansion tank; top up here when the engine is cold.', location: 'Engine bay.', accuracyNote: APPROX_PKG }) },
  { test: /^drive_belt$/, data: () => ({ label: 'Accessory drive belt', category: 'Engine bay', layer: 'bay', description: 'Serpentine belt driving the alternator, A/C compressor, power-steering pump and fan.', location: 'Front of the engine.' }) },
  { test: /^(alternator|ac_compressor|power_steering_pump)$/, data: (id, m) => ({ label: { alternator: 'Alternator', ac_compressor: 'A/C compressor', power_steering_pump: 'Power-steering pump' }[m[1]], category: 'Engine bay', layer: 'bay', description: { alternator: 'Charges the battery and powers the electrics while the engine runs.', ac_compressor: 'Air-conditioning compressor.', power_steering_pump: 'Pump for the hydraulic power steering.' }[m[1]], location: 'Front of the engine.', accuracyNote: APPROX_PKG }) },
  { test: /^(air_cleaner_housing|air_intake_duct)$/, data: (id, m) => ({ label: m[1] === 'air_cleaner_housing' ? 'Air filter box' : 'Air intake duct', category: 'Engine bay', layer: 'bay', description: m[1] === 'air_cleaner_housing' ? 'Box holding the engine air filter.' : 'Duct from the air filter to the throttle.', location: 'Engine bay.', accuracyNote: APPROX_PKG }) },
  { test: /^battery_12v$/, data: () => ({ label: '12 V battery', category: 'Engine bay', layer: 'bay', description: 'Starting battery.', location: 'Engine bay.', accuracyNote: APPROX_PKG }) },
  { test: /^fuse_relay_box$/, data: () => ({ label: 'Engine-room fuse and relay box', category: 'Engine bay', layer: 'bay', description: 'Fuses and relays for the engine-bay circuits; the lid shows the layout.', location: 'Engine bay.', accuracyNote: APPROX_PKG }) },
  { test: /^washer_fluid_reservoir$/, data: () => ({ label: 'Washer fluid reservoir', category: 'Engine bay', layer: 'bay', description: 'Washer fluid for the windscreen, rear glass and headlamp washers where fitted.', location: 'Engine bay.', accuracyNote: APPROX_PKG }) },
  /* ------------------------------------------------------------ fuel & exhaust */
  { test: /^fuel_tank$/, data: () => ({ label: 'Fuel tank', category: 'Fuel', layer: 'fuel', description: 'Fuel tank with in-tank pump and sender.', location: 'Under the floor ahead of the rear axle.', specs: { Capacity: '23.0 US gal (87 L)' }, accuracyNote: APPROX_PKG, sources: ['lexusCa'] }) },
  { test: /^fuel_filler_(neck|cap)$/, data: (id, m) => ({ label: `Fuel filler ${m[1]}`, category: 'Fuel', layer: 'fuel', description: m[1] === 'cap' ? 'Tethered fuel cap; a loose cap can set the check-engine light.' : 'Pipe from the filler to the tank.', location: 'Behind the fuel door.' }) },
  { test: /^evap_canister$/, data: () => ({ label: 'EVAP charcoal canister', category: 'Fuel', layer: 'fuel', description: 'Stores fuel vapour until the engine burns it.', location: 'Under the rear floor.', accuracyNote: APPROX_PKG }) },
  { test: /^(catalytic_converters|exhaust_pipe|muffler|tailpipe)$/, data: (id, m) => ({ label: { catalytic_converters: 'Catalytic converters', exhaust_pipe: 'Exhaust pipe', muffler: 'Muffler', tailpipe: 'Tailpipe' }[m[1]], category: 'Exhaust', layer: 'fuel', description: { catalytic_converters: 'One converter per bank.', exhaust_pipe: 'Pipe joining both banks to the muffler.', muffler: 'Main silencer.', tailpipe: 'Exits below the rear bumper.' }[m[1]], location: 'Under the vehicle.' }) }
];

export const describeComponent = makeDescriber({ families: FAMILIES, sources: SOURCES, defaultSources: ['lexusCa'], accuracyNote: 'Geometry is a representative procedural model built from published dimensions.' });

export function specSheet() {
  return makeSheet({
    vehicle: '2008 Lexus GX 470', generation: 'J120 (UZJ120)',
    sources: SOURCES, sourceKeys: ['lexusCa', 'edmunds', 'carspecs', 'wikiGX', 'wikiUZ', 'amsoil', 'rearDoor'],
    groups: [
      { title: 'Overview', rows: [['Model year', '2008'], ['Generation', 'First generation (J120, UZJ120), 2003–2009'], ['Body', '4-door SUV, body-on-frame, up to eight seats'], ['Related', 'Toyota Land Cruiser Prado (120 series), Toyota 4Runner (N210)']] },
      { title: 'Engine', rows: [['Code', '2UZ-FE with VVT-i'], ['Type', '4.7 L (4,664 cc) 90° V8, DOHC 32-valve'], ['Bore × stroke', '94.0 × 84.0 mm'], ['Output', '263 hp @ 5,400 rpm · 323 lb-ft @ 3,400 rpm'], ['Cam drive', 'Timing belt'], ['Firing order', '1-8-4-3-6-5-7-2']] },
      { title: 'Drivetrain & chassis', rows: [['Transmission', 'Five-speed automatic'], ['Drive', 'Full-time 4WD: Torsen limited-slip centre differential with lock, two-speed transfer case'], ['Traction aids', 'A-TRAC active traction control, VSC stability control, Downhill Assist and Hill-start Assist'], ['Front suspension', 'Independent double wishbone with coil springs'], ['Rear suspension', 'Four-link rigid axle with height-control air springs'], ['Steering', 'Rack and pinion, hydraulic power assistance'], ['Brakes', 'Four-wheel discs with ABS, brake-force distribution and Brake Assist'], ['Tyres', 'P265/65R17 on 17-inch alloys'], ['Wheel fastening', '6 × 139.7 mm']] },
      { title: 'Dimensions', rows: [['Length', '188.2 in (4,780 mm)'], ['Width', '74.0 in (1,880 mm)'], ['Height', '74.6 in (1,895 mm) with roof rails'], ['Wheelbase', '109.8 in (2,790 mm)'], ['Track F / R', '62.4 in / 62.4 in (1,585 mm)'], ['Ground clearance', '8.3 in (211 mm)'], ['Curb weight', 'About 4,870 lb (2,210 kg), Lexus Canada']] },
      { title: 'Capacities', rows: [['Fuel tank', '23.0 US gal (87 L)'], ['Engine oil', 'SAE 5W-30, about 7 US qt (6.6 L) with filter (published figures differ; check the owner’s manual)'], ['Towing', 'Up to 6,500 lb (2,948 kg), properly equipped']] },
      { title: 'Cabin & safety', rows: [['Seating', 'Up to eight: 2 + 3 (60/40) + 3 (fold-away third row)'], ['Airbags', 'Front, front-seat side, and side curtains covering all three rows'], ['Rear door', 'Side-hinged (on the right) with separately opening glass']] }
    ],
    disclaimer: 'Figures come from the public sources listed and can differ by market and options. Confirm against the owner’s manual or a Lexus dealer before servicing.'
  });
}
