/** 2008 Lexus GX 470 package definition for build-procedural-vehicle.mjs. */
import { buildGX470 } from './gx470-model.mjs';
import { describeComponent, specSheet, LAYERS } from './gx470-data.mjs';

export const GX470_PACKAGE = {
  vehicle: { id: 'lexus-gx-470-2008', make: 'Lexus', model: 'GX 470', displayName: '2008 Lexus GX 470', year: 2008, years: [2008], generation: 'First generation (J120)', variant: 'SUV · 4.7 L V8 · full-time 4WD', bodyStyle: 'SUV', category: 'car', accuracy: 'representative' },
  build: buildGX470,
  describe: describeComponent,
  specSheet,
  layers: LAYERS,
  layerLabel: 'Body, frame, cabin and mechanical',
  attribution: 'Procedural 2008 Lexus GX 470 model generated by Toolbox from published dimensions and specifications',
  notes: 'Procedural model of the 2008 Lexus GX 470 (J120), a body-on-frame SUV. Overall length, width, height, wheelbase, track, ground clearance and tyre size follow Lexus’s published figures; body surfacing, trim shapes and the placement of engine-bay, chassis and cabin components are Toolbox approximations for orientation. Doors, windows, the side-hinged rear door and its separately opening glass, bonnet, fuel door, wheels, brakes, seats and the spare-tyre winch move about their real pivots.',
  quickActions: [
    { id: 'doors', group: 'Doors', on: 'Open all doors', off: 'Close all doors' },
    { id: 'hood', articulations: ['hood'], on: 'Open bonnet', off: 'Close bonnet' },
    { id: 'rear_door', articulations: ['rear_door'], on: 'Open rear door', off: 'Close rear door' },
    { id: 'rear_glass', articulations: ['rear_glass_hatch'], on: 'Open rear glass', off: 'Close rear glass' },
    { id: 'windows', group: 'Windows', on: 'Lower all windows', off: 'Raise all windows' },
    { id: 'wheels', wheels: true, on: 'Remove all wheels', off: 'Refit all wheels' },
    { id: 'shell', layers: ['body'], on: 'Hide body shell (see inside)', off: 'Show body shell' }
  ],
  cabin: { head: 'headrest_front_left', headAt: [0.5, 0.45, 0.5], forward: 0.3, down: 0.03, look: 'steering_wheel', lookAt: [0.5, 0.6, 0.5] },
  catalogEntry: {
    id: 'lexus-gx-470-2008', make: 'Lexus', model: 'GX 470', year: 2008, years: '2008',
    generation: 'First generation (J120)', variant: 'SUV · 4.7 L V8 · full-time 4WD', bodyStyle: 'SUV', category: 'car',
    aliases: ['GX', 'GX470', 'GX 470', 'Lexus GX', 'Lexus GX470', 'UZJ120', 'J120', '2008', 'GX 2008', 'Land Cruiser Prado', 'SUV'],
    specifications: { bodyStyle: 'SUV', layout: 'Front-engine, full-time four-wheel drive', engine: { code: '2UZ-FE 4.7 L V8' }, transmission: { code: '5-speed automatic' }, curbWeight: 'About 4,870 lb', wheelbase: '109.8 in (2,790 mm)' }
  }
};
