/* ============================================================
   TOOLBOX — Cosmetics Database: hair, body, baby, men's grooming,
   oral care, sun care and fragrance

   brand | product | type | launched | size | specs | ingredients (INCI)

   ref=typical marks a list whose key ingredients are confirmed but
   whose full list is representative rather than a copy of one
   label. Fragrance lists name the declared allergens; the scent
   itself is declared as Parfum.
   ============================================================ */

export const MORE_ROWS = `
olaplex | No.3 Hair Perfector | hair treatment | 2014 | 100 ml | hair=damaged,coloured; actives=Bis-aminopropyl diglycol dimaleate; ref=typical | Aqua, Bis-Aminopropyl Diglycol Dimaleate, Propylene Glycol, Cetearyl Alcohol, Behentrimonium Methosulfate, Cetyl Alcohol, Phenoxyethanol, Glycerin, Hydroxyethylcellulose, Stearamidopropyl Dimethylamine, Quaternium-91, Sodium Benzoate, Cetrimonium Methosulfate, Cetrimonium Chloride, Parfum, Behentrimonium Chloride, Polyquaternium-37, Ethylhexylglycerin, Tetrasodium EDTA, Tocopheryl Acetate, Panthenol, Citric Acid
moroccanoil | Moroccanoil Treatment | hair oil | 2007 | 100 ml | hair=all; actives=Argan oil, Linseed extract | Cyclopentasiloxane, Dimethicone, Argania Spinosa Kernel Oil, Linum Usitatissimum Seed Extract, Parfum, CI 47000, CI 26100, Butylphenyl Methylpropional, Coumarin, Benzyl Benzoate, Alpha-Isomethyl Ionone, Benzyl Alcohol, Limonene, Linalool
kerastase | Elixir Ultime L'Huile Originale | hair oil | 2008 | 100 ml | hair=all,dull; actives=Marula oil, Argan oil, Camellia oil; ref=typical | Cyclopentasiloxane, Dimethiconol, Argania Spinosa Kernel Oil, Sclerocarya Birrea Seed Oil, Camellia Japonica Seed Oil, Zea Mays Germ Oil, Limonene, Linalool, Benzyl Salicylate, Parfum
pantene | Pro-V Classic Clean Shampoo | shampoo | 1990 | 400 ml | hair=normal; actives=Panthenol; ref=typical | Aqua, Sodium Laureth Sulfate, Sodium Lauryl Sulfate, Sodium Citrate, Sodium Xylenesulfonate, Cocamidopropyl Betaine, Citric Acid, Sodium Benzoate, Sodium Chloride, Glycol Distearate, Dimethicone, Guar Hydroxypropyltrimonium Chloride, Tetrasodium EDTA, Panthenol, Panthenyl Ethyl Ether, Methylchloroisothiazolinone, Methylisothiazolinone, Parfum
head-and-shoulders | Classic Clean Anti-Dandruff Shampoo | shampoo | 1961 | 400 ml | hair=dandruff; actives=Pyrithione zinc 1%; ref=typical | Aqua, Sodium Laureth Sulfate, Sodium Lauryl Sulfate, Glycol Distearate, Zinc Carbonate, Sodium Chloride, Sodium Xylenesulfonate, Cocamide MEA, Dimethicone, Zinc Pyrithione, Parfum, Sodium Benzoate, Guar Hydroxypropyltrimonium Chloride, Magnesium Carbonate Hydroxide, Methylchloroisothiazolinone, Methylisothiazolinone, CI 42090
dove | Beauty Bar | bar soap | 1957 | 100 g | skin=all; actives=¼ moisturising cream; ref=typical | Sodium Lauroyl Isethionate, Stearic Acid, Sodium Tallowate, Aqua, Sodium Isethionate, Coconut Acid, Sodium Stearate, Cocamidopropyl Betaine, Sodium Cocoate, Parfum, Sodium Chloride, Tetrasodium EDTA, Tetrasodium Etidronate, CI 77891
dove | Deep Moisture Body Wash | body wash | 2011 | 500 ml | skin=dry; actives=NutriumMoisture (stearic acid, glycerin, sunflower oil); ref=typical | Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Glycerin, Stearic Acid, Helianthus Annuus Seed Oil, Lauric Acid, Sodium Chloride, Guar Hydroxypropyltrimonium Chloride, Citric Acid, Sodium Benzoate, Tetrasodium EDTA, Glycine Soja Oil, Zinc Oxide, BHT, Parfum
lux | Soft Rose Beauty Soap | bar soap | 1925 | 150 g | skin=all; ref=typical | Sodium Palmate, Sodium Palm Kernelate, Aqua, Parfum, Glycerin, Sodium Chloride, Titanium Dioxide, Tetrasodium EDTA, Tetrasodium Etidronate, Rosa Damascena Flower Oil, CI 15985, CI 17200
shea-moisture | Coconut & Hibiscus Curl Enhancing Smoothie | styling | 2009 | 340 g | hair=curly,coily; actives=Shea butter, Coconut oil, Hibiscus; ref=typical | Aqua, Butyrospermum Parkii Butter, Cetearyl Alcohol, Glycerin, Cocos Nucifera Oil, Behentrimonium Methosulfate, Hydrolyzed Silk, Hibiscus Sabdariffa Flower Extract, Panthenol, Tocopherol, Aloe Barbadensis Leaf Juice, Caprylyl Glycol, Hydroxyethylcellulose, Parfum
cantu | Shea Butter Leave-In Conditioning Repair Cream | styling | 2003 | 340 g | hair=curly,dry; actives=Shea butter; ref=typical | Aqua, Butyrospermum Parkii Butter, Petrolatum, Paraffinum Liquidum, Cetearyl Alcohol, Glycerin, Behentrimonium Methosulfate, Cocos Nucifera Oil, Simmondsia Chinensis Seed Oil, Panthenol, Tocopheryl Acetate, Hydrolyzed Keratin, Methylparaben, Propylparaben, Parfum
parachute | Pure Coconut Oil | hair oil | | 200 ml | hair=all; ff | Cocos Nucifera Oil
mielle | Rosemary Mint Scalp & Hair Strengthening Oil | hair oil | 2014 | 59 ml | hair=all,scalp; actives=Rosemary oil, Peppermint oil, Biotin; ref=typical | Glycine Soja Oil, Ricinus Communis Seed Oil, Rosmarinus Officinalis Leaf Oil, Mentha Piperita Oil, Simmondsia Chinensis Seed Oil, Biotin, Cocos Nucifera Oil, Olea Europaea Fruit Oil, Tocopheryl Acetate, Limonene, Linalool
vaseline | Intensive Care Advanced Repair Lotion | body lotion | 2006 | 400 ml | skin=very dry; ff; actives=Petrolatum microdroplets, Glycerin; ref=typical | Aqua, Glycerin, Stearic Acid, Petrolatum, Glycol Stearate, Dimethicone, Isopropyl Isostearate, Glyceryl Stearate, Cetyl Alcohol, Magnesium Aluminum Silicate, Triethanolamine, Carbomer, Stearamide AMP, Methylparaben, Propylparaben, Disodium EDTA, Hydroxyethyl Urea
rexona | MotionSense Invisible Antiperspirant Aerosol | deodorant | 2012 | 150 ml | protection=72 hours; actives=Aluminum chlorohydrate; ref=typical | Butane, Isobutane, Propane, Cyclopentasiloxane, Aluminum Chlorohydrate, PPG-14 Butyl Ether, Parfum, Disteardimonium Hectorite, Dimethiconol, Sodium Starch Octenylsuccinate, Propylene Carbonate, Maltodextrin, Mannitol, Silica, BHT, Limonene, Linalool
old-spice | Swagger Deodorant Stick | deodorant | 2008 | 85 g | protection=48 hours; aluminium-free; ref=typical | Propylene Glycol, Aqua, Sodium Stearate, Parfum, PPG-3 Myristyl Ether, Tetrasodium EDTA, CI 42090
johnsons | Baby Oil | baby | 1950 | 300 ml | skin=baby,all | Paraffinum Liquidum, Parfum
johnsons | Baby Shampoo | baby | 1953 | 500 ml | hair=baby; claim=No More Tears; ref=typical | Aqua, Cocamidopropyl Betaine, PEG-80 Sorbitan Laurate, Sodium Trideceth Sulfate, Glycerin, Polyquaternium-10, Sodium Benzoate, Citric Acid, Tetrasodium EDTA, Sodium Chloride, Parfum
sudocrem | Antiseptic Healing Cream | baby | 1931 | 125 g | skin=nappy rash,minor burns; actives=Zinc oxide 15.25%, Benzyl benzoate, Benzyl cinnamate; ref=typical | Zinc Oxide, Lanolin, Benzyl Alcohol, Benzyl Benzoate, Benzyl Cinnamate, Paraffinum Liquidum, Paraffin, Cera Microcristallina, Sodium Benzoate, Propylene Glycol, Citric Acid, BHA, Linalyl Acetate, Aqua
bepanthen | Nappy Care Ointment | baby | 1944 | 100 g | skin=baby nappy area; ff; actives=Panthenol 5%; ref=typical | Panthenol, Aqua, Lanolin, Petrolatum, Paraffinum Liquidum, Cera Alba, Cetyl Alcohol, Stearyl Alcohol, Lanolin Alcohol, Prunus Amygdalus Dulcis Oil
burts-bees | Beeswax Lip Balm | lip balm | 1991 | 4.25 g | lips=dry; actives=Beeswax, Peppermint oil, Vitamin E | Cera Alba, Cocos Nucifera Oil, Helianthus Annuus Seed Oil, Mentha Piperita Oil, Lanolin, Tocopherol, Rosmarinus Officinalis Leaf Extract, Glycine Soja Oil, Canola Oil, Limonene
carmex | Classic Lip Balm Jar | lip balm | 1937 | 7.5 g | lips=dry,chapped; actives=Camphor, Menthol, Phenol | Petrolatum, Lanolin, Cera Alba, Paraffin, Theobroma Cacao Seed Butter, Camphor, Menthol, Phenol, Salicylic Acid, Aroma, Cetyl Esters, Vanillin
labello | Original Care Lip Balm | lip balm | 1909 | 4.8 g | lips=all; actives=Shea butter, Panthenol; ref=typical | Octyldodecanol, Hydrogenated Castor Oil, Cera Alba, Ricinus Communis Seed Oil, Butyrospermum Parkii Butter, Hydrogenated Coco-Glycerides, Cetyl Palmitate, Panthenol, Tocopheryl Acetate, Tocopherol, Glycine Soja Oil, Aroma
gillette | Classic Regular Shave Foam | shaving | 1971 | 200 ml | skin=men,normal; ref=typical | Aqua, Palmitic Acid, Triethanolamine, Isopentane, Isobutane, Laureth-23, Stearic Acid, Parfum, Sodium Lauryl Sulfate, Butylene Glycol, Propylene Glycol, Sorbitol, PEG-90M, PEG-23M, Hydroxyethylcellulose, PEG-150 Distearate
nivea-men | Sensitive Post Shave Balm | shaving | 2000 | 100 ml | skin=men,sensitive; actives=Chamomile, Witch hazel, Vitamin E; ref=typical | Aqua, Glycerin, Cyclomethicone, Isopropyl Palmitate, Cetearyl Alcohol, Panthenol, Chamomilla Recutita Flower Extract, Hamamelis Virginiana Water, Tocopheryl Acetate, Allantoin, Glyceryl Stearate, Carbomer, Sodium Hydroxide, Phenoxyethanol
colgate | Total Clean Mint Toothpaste | toothpaste | 1992 | 100 ml | fluoride=0.454% stannous fluoride (1100 ppm F); ref=typical | Glycerin, Hydrated Silica, Aqua, Phosphates, Aroma, Zinc Phosphate, Cellulose Gum, Sodium Lauryl Sulfate, Stannous Fluoride, Carrageenan, Sodium Saccharin, Sodium Gluconate, Trisodium Phosphate, Stannous Chloride, CI 77891
sensodyne | Repair & Protect Toothpaste | toothpaste | 2011 | 75 ml | fluoride=1450 ppm (sodium fluoride); teeth=sensitive; actives=NovaMin (calcium sodium phosphosilicate) | Glycerin, PEG-8, Silica, Calcium Sodium Phosphosilicate, Sodium Lauryl Sulfate, Aroma, Titanium Dioxide, Carbomer, Potassium Acesulfame, Sodium Fluoride, Limonene
crest | Pro-Health Clean Mint Toothpaste | toothpaste | 2006 | 130 g | fluoride=0.454% stannous fluoride; ref=typical | Glycerin, Hydrated Silica, Sodium Hexametaphosphate, Propylene Glycol, PEG-6, Aqua, Zinc Lactate, Trisodium Phosphate, Aroma, Sodium Lauryl Sulfate, Sodium Gluconate, Carrageenan, Sodium Saccharin, Xanthan Gum, Stannous Fluoride, CI 42090
listerine | Cool Mint Antiseptic Mouthwash | mouthwash | 1879 | 500 ml | actives=Eucalyptol, Menthol, Methyl salicylate, Thymol; alcohol=21.6% | Aqua, Alcohol, Sorbitol, Poloxamer 407, Benzoic Acid, Eucalyptol, Methyl Salicylate, Thymol, Menthol, Sodium Saccharin, Sodium Benzoate, Aroma, CI 42053
closeup | Red Hot Gel Toothpaste | toothpaste | 1967 | 100 ml | fluoride=1450 ppm; ref=typical | Aqua, Sorbitol, Hydrated Silica, PEG-32, Sodium Lauryl Sulfate, Aroma, Cellulose Gum, Sodium Fluoride, Sodium Saccharin, Zinc Sulfate, CI 16255, CI 14720
supergoop | Unseen Sunscreen SPF40 | sunscreen | 2018 | 50 ml | spf=40; uva=broad spectrum; finish=invisible primer; actives=Avobenzone 3%, Homosalate 8%, Octisalate 5%, Octocrylene 4%; ref=typical | Avobenzone, Homosalate, Octisalate, Octocrylene, Isododecane, Dimethicone Crosspolymer, Dimethicone/Vinyl Dimethicone Crosspolymer, Dimethicone, Polymethylsilsesquioxane, Isohexadecane, Boswellia Serrata Extract, Meadowfoam Estolide, Lepidium Meyenii Root Extract, Tocopherol, Polysilicone-11, Silica
eltamd | UV Clear Broad-Spectrum SPF46 | sunscreen | 2008 | 48 g | spf=46; skin=acne-prone,rosacea; actives=Zinc oxide 9%, Octinoxate 7.5%, Niacinamide 5% | Zinc Oxide, Octinoxate, Aqua, Cyclopentasiloxane, Niacinamide, Octyldodecyl Neopentanoate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Polyisobutene, PEG-7 Trimethylolpropane Coconut Ether, Sodium Hyaluronate, Tocopheryl Acetate, Lactic Acid, Oleth-3 Phosphate, Phenoxyethanol, Butylene Glycol, Triethoxycaprylylsilane
anessa | Perfect UV Sunscreen Skincare Milk SPF50+ | sunscreen | 2022 | 60 ml | spf=50+; pa=++++; water=80 min; finish=milk; ref=typical | Dimethicone, Aqua, Zinc Oxide, Ethylhexyl Methoxycinnamate, Alcohol, Isododecane, Talc, Methyl Methacrylate Crosspolymer, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Isopropyl Myristate, PEG-9 Polydimethylsiloxyethyl Dimethicone, Octocrylene, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Glycerin, Titanium Dioxide, Triethylhexanoin, Sodium Hyaluronate, Tocopherol, Stearic Acid, Aluminum Hydroxide, Silica, Triethoxycaprylylsilane, Disodium EDTA, BHT, Parfum
kao-biore | UV Aqua Rich Watery Essence SPF50+ | sunscreen | 2019 | 50 g | spf=50+; pa=++++; finish=watery; ref=typical | Water, Ethylhexyl Methoxycinnamate, Alcohol, Isopropyl Palmitate, Lauryl Methacrylate/Sodium Methacrylate Crosspolymer, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Hydrogenated Polydecene, Dimethicone, Sodium Hyaluronate, Citrus Aurantium Dulcis Fruit Extract, Butylene Glycol, Glycerin, Xylitol, Dextrin Palmitate, Carbomer, Triethanolamine, Silica, Parfum
neutrogena | Ultra Sheer Dry-Touch Sunscreen SPF55 | sunscreen | 2004 | 88 ml | spf=55; uva=broad spectrum (Helioplex); water=80 min; actives=Avobenzone 3%, Homosalate 10%, Octisalate 5%, Octocrylene 2.8%, Oxybenzone 6%; ref=typical | Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone, Aqua, Styrene/Acrylates Copolymer, Silica, Diethylhexyl 2,6-Naphthalate, Dimethicone, Caprylyl Methicone, Ethylhexylglycerin, Glyceryl Stearate, PEG-100 Stearate, Behenyl Alcohol, Phenoxyethanol, Tocopheryl Acetate, Acrylates/Dimethicone Copolymer, Methylparaben, Propylparaben, Disodium EDTA, Parfum
ultra-violette | Queen Screen SPF50+ Luminous Serum | sunscreen | 2019 | 50 ml | spf=50+; uva=broad spectrum; finish=luminous; ref=typical | Aqua, Homosalate, Octocrylene, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Glycerin, Dimethicone, Niacinamide, Silica, Sodium Hyaluronate, Tocopherol, Kakadu Plum Extract, Phenoxyethanol, Ethylhexylglycerin, Parfum
isdin | Fusion Water Magic SPF50 | sunscreen | 2017 | 50 ml | spf=50; skin=all; finish=weightless; ref=typical | Aqua, Diisopropyl Sebacate, Isopropyl Myristate, Ethylhexyl Salicylate, Ethylhexyl Triazone, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Alcohol Denat., Glycerin, Hyaluronic Acid, Tocopheryl Acetate, Carbomer, Triethanolamine, Phenoxyethanol, Parfum
chanel | N°5 Eau de Parfum | fragrance | 1921 | 100 ml | family=floral aldehyde; conc=EDP; perfumer=Ernest Beaux; top=Aldehydes, Neroli, Ylang-ylang; heart=May rose, Jasmine; base=Sandalwood, Vetiver, Vanilla; ref=typical | Alcohol Denat., Parfum, Aqua, Limonene, Linalool, Citronellol, Hydroxycitronellal, Geraniol, Alpha-Isomethyl Ionone, Coumarin, Eugenol, Farnesol, Citral, Benzyl Benzoate, Cinnamyl Alcohol, Benzyl Alcohol, Benzyl Salicylate
chanel | Coco Mademoiselle Eau de Parfum | fragrance | 2001 | 100 ml | family=oriental chypre; conc=EDP; perfumer=Jacques Polge; top=Orange, Bergamot; heart=Rose, Jasmine; base=Patchouli, Vetiver, Vanilla, White musk; ref=typical | Alcohol Denat., Parfum, Aqua, Limonene, Linalool, Citronellol, Coumarin, Hydroxycitronellal, Geraniol, Alpha-Isomethyl Ionone, Eugenol, Citral, Benzyl Benzoate, Benzyl Salicylate, Farnesol
dior | Sauvage Eau de Toilette | fragrance | 2015 | 100 ml | family=aromatic fougère; conc=EDT; perfumer=François Demachy; top=Calabrian bergamot, Pepper; heart=Sichuan pepper, Lavender, Geranium; base=Ambroxan, Cedar, Labdanum; ref=typical | Alcohol Denat., Parfum, Aqua, Limonene, Linalool, Coumarin, Citral, Geraniol, Hydroxycitronellal, Citronellol, Alpha-Isomethyl Ionone, Butylphenyl Methylpropional
dior | J'adore Eau de Parfum | fragrance | 1999 | 100 ml | family=floral; conc=EDP; perfumer=Calice Becker; top=Pear, Melon, Bergamot; heart=Jasmine, Tuberose, Rose; base=Musk, Vanilla, Cedar; ref=typical | Alcohol Denat., Parfum, Aqua, Linalool, Limonene, Benzyl Salicylate, Hydroxycitronellal, Citronellol, Geraniol, Alpha-Isomethyl Ionone, Eugenol, Benzyl Benzoate, Farnesol
ysl-beauty | Libre Eau de Parfum | fragrance | 2019 | 90 ml | family=floral lavender; conc=EDP; perfumer=Anne Flipo, Carlos Benaïm; top=Mandarin, Lavender, Black currant; heart=Lavender, Orange blossom, Jasmine; base=Madagascar vanilla, Cedar, Musk, Ambergris accord; ref=typical | Alcohol, Parfum, Aqua, Linalool, Limonene, Coumarin, Hydroxycitronellal, Geraniol, Citronellol, Benzyl Salicylate, Alpha-Isomethyl Ionone, Citral, Eugenol, Farnesol
lancome | La Vie Est Belle Eau de Parfum | fragrance | 2012 | 100 ml | family=gourmand floral; conc=EDP; perfumer=Olivier Polge, Dominique Ropion, Anne Flipo; top=Black currant, Pear; heart=Iris, Jasmine, Orange blossom; base=Praline, Vanilla, Patchouli, Tonka bean; ref=typical | Alcohol, Parfum, Aqua, Linalool, Benzyl Salicylate, Coumarin, Limonene, Geraniol, Hydroxycitronellal, Citronellol, Benzyl Benzoate, Alpha-Isomethyl Ionone, Eugenol, Farnesol, Citral
maison-francis-kurkdjian | Baccarat Rouge 540 Eau de Parfum | fragrance | 2015 | 70 ml | family=amber floral; conc=EDP; perfumer=Francis Kurkdjian; top=Saffron, Jasmine; heart=Amberwood, Ambergris accord; base=Fir resin, Cedar; ref=typical | Alcohol Denat., Parfum, Aqua, Ethylhexyl Methoxycinnamate, Ethylhexyl Salicylate, Butyl Methoxydibenzoylmethane, Limonene, Linalool
creed | Aventus Eau de Parfum | fragrance | 2010 | 100 ml | family=chypre fruity; conc=EDP; top=Pineapple, Bergamot, Black currant, Apple; heart=Birch, Patchouli, Jasmine, Rose; base=Musk, Oakmoss, Ambergris accord, Vanilla; ref=typical | Alcohol Denat., Parfum, Aqua, Limonene, Linalool, Citral, Coumarin, Evernia Prunastri Extract, Citronellol, Geraniol, Eugenol
jo-malone | Wood Sage & Sea Salt Cologne | fragrance | 2014 | 100 ml | family=woody aromatic; conc=cologne; perfumer=Christine Nagel; top=Ambrette seed, Sea salt; heart=Sage; base=Red algae, Grapefruit; ref=typical | Alcohol Denat., Aqua, Parfum, Limonene, Linalool, Citral, Coumarin, Geraniol
tom-ford-beauty | Black Orchid Eau de Parfum | fragrance | 2006 | 100 ml | family=oriental floral; conc=EDP; top=Truffle, Black currant, Ylang-ylang, Bergamot; heart=Black orchid, Lotus, Spices; base=Patchouli, Vanilla, Incense, Sandalwood; ref=typical | Alcohol Denat., Parfum, Aqua, Benzyl Benzoate, Linalool, Coumarin, Limonene, Eugenol, Cinnamyl Alcohol, Citronellol, Isoeugenol, Benzyl Alcohol, Geraniol
carolina-herrera | Good Girl Eau de Parfum | fragrance | 2016 | 80 ml | family=oriental floral; conc=EDP; perfumer=Louise Turner; top=Almond, Coffee; heart=Tuberose, Jasmine sambac; base=Tonka bean, Cacao; ref=typical | Alcohol Denat., Parfum, Aqua, Benzyl Salicylate, Coumarin, Linalool, Benzyl Benzoate, Limonene, Alpha-Isomethyl Ionone, Citronellol, Eugenol, Farnesol
paco-rabanne | 1 Million Eau de Toilette | fragrance | 2008 | 100 ml | family=spicy leather; conc=EDT; perfumer=Christophe Raynaud, Olivier Pescheux, Michel Girard; top=Grapefruit, Mint, Blood mandarin; heart=Rose, Cinnamon, Spices; base=Leather, Amber, Patchouli; ref=typical | Alcohol Denat., Parfum, Aqua, Limonene, Coumarin, Linalool, Cinnamal, Eugenol, Citral, Geraniol, Citronellol, Benzyl Benzoate
giorgio-armani-beauty | Acqua di Giò Eau de Toilette | fragrance | 1996 | 100 ml | family=aquatic aromatic; conc=EDT; perfumer=Alberto Morillas; top=Lime, Lemon, Bergamot, Jasmine, Orange, Mandarin, Neroli; heart=Sea notes, Jasmine, Calone, Peach, Freesia, Rosemary; base=White musk, Cedar, Oakmoss, Patchouli, Amber; ref=typical | Alcohol Denat., Parfum, Aqua, Limonene, Linalool, Hydroxycitronellal, Citral, Coumarin, Geraniol, Citronellol, Alpha-Isomethyl Ionone, Eugenol
lattafa | Khamrah Eau de Parfum | fragrance | 2022 | 100 ml | family=amber spicy gourmand; conc=EDP; top=Cinnamon, Nutmeg, Bergamot; heart=Dates, Praline, Tuberose, Mahonial; base=Vanilla, Tonka bean, Amberwood, Myrrh, Benzoin; ref=typical | Alcohol Denat., Parfum, Aqua, Benzyl Benzoate, Coumarin, Linalool, Limonene, Cinnamyl Alcohol, Eugenol, Benzyl Salicylate
`;
