/* ============================================================
   TOOLBOX — Cosmetics Database: makeup and nails

   brand | product | type | launched | size | specs; ref=typical | ingredients (INCI)

   Shade ranges carry "may contain" colourants (CI numbers); the
   list here is the published base formula plus those colourants.
   ============================================================ */

export const MAKEUP_ROWS = `
maybelline | Lash Sensational Mascara | mascara | 2014 | 9.5 ml | finish=lengthening,volumising; shades=5; ref=typical | Aqua, Paraffin, Potassium Cetyl Phosphate, Copernicia Cerifera Cera, Acacia Senegal Gum, Hydroxyethylcellulose, Glyceryl Stearate, Ethylenediamine/Stearyl Dimer Dilinoleate Copolymer, Stearic Acid, Palmitic Acid, Aminomethyl Propanediol, Phenoxyethanol, Ethylhexylglycerin, Disodium EDTA, Polyquaternium-10, Silica, Butylene Glycol, Tocopherol, CI 77499
maybelline | Fit Me Matte + Poreless Foundation | foundation | 2013 | 30 ml | skin=normal,oily; finish=matte; coverage=medium; shades=40; ref=typical | Aqua, Cyclohexasiloxane, Nylon-12, Isododecane, Alcohol Denat., Cyclopentasiloxane, PEG-10 Dimethicone, Cetyl PEG/PPG-10/1 Dimethicone, Phenyl Trimethicone, Butylene Glycol, Sodium Chloride, Magnesium Sulfate, Polyglyceryl-4 Isostearate, Disteardimonium Hectorite, Aluminum Hydroxide, Isostearic Acid, Methylparaben, Butylparaben, Dimethicone, Acrylates Copolymer, Disodium Stearoyl Glutamate, Titanium Dioxide, CI 77891, CI 77491, CI 77492, CI 77499
maybelline | SuperStay Matte Ink Liquid Lipstick | lipstick | 2017 | 5 ml | finish=matte; shades=40; wear=16 hours; ref=typical | Dimethicone, Trimethylsiloxysilicate, Isododecane, Nylon-611/Dimethicone Copolymer, Dimethicone Crosspolymer, Polyethylene, Silica Dimethyl Silylate, Phenoxyethanol, Caprylyl Glycol, Tocopherol, Mica, CI 77891, CI 15850, CI 45410, CI 77491, CI 77499, CI 15985, CI 17200, CI 19140
loreal-paris | True Match Super-Blendable Foundation | foundation | 2003 | 30 ml | skin=all; finish=natural; coverage=light to medium; shades=45; spf=17; ref=typical | Octinoxate, Titanium Dioxide, Aqua, Cyclopentasiloxane, Dimethicone, Isododecane, Glycerin, PEG-10 Dimethicone, Butylene Glycol, Cetyl PEG/PPG-10/1 Dimethicone, Alumina, Magnesium Sulfate, Disteardimonium Hectorite, Aluminum Hydroxide, Stearic Acid, Methylparaben, Propylparaben, Tocopherol, Disodium Stearoyl Glutamate, Sodium Dehydroacetate, Iron Oxides
loreal-paris | Lash Paradise Mascara | mascara | 2017 | 6.4 ml | finish=volumising; shades=4; ref=typical | Aqua, Paraffin, Cera Alba, Acacia Senegal Gum, Styrene/Acrylates/Ammonium Methacrylate Copolymer, Stearic Acid, Palmitic Acid, Triethanolamine, Hydroxyethylcellulose, Butylene Glycol, Copernicia Cerifera Cera, Polyquaternium-10, Oryza Sativa Cera, Glycerin, Phenoxyethanol, Caprylyl Glycol, Ricinus Communis Seed Oil, Tocopherol, CI 77499
nyx | Butter Gloss | lip gloss | 2014 | 8 ml | finish=creamy sheen; shades=48; ref=typical | Polybutene, Hydrogenated Polyisobutene, Octyldodecanol, Silica Dimethyl Silylate, Tocopheryl Acetate, Pentaerythrityl Tetra-Di-t-Butyl Hydroxyhydrocinnamate, Aroma, Ethylene/Propylene/Styrene Copolymer, Butylene/Ethylene/Styrene Copolymer, Benzyl Benzoate, Mica, CI 77891, CI 15850, CI 45410, CI 77491, CI 19140
nyx | Setting Spray Matte Finish | setting spray | 2012 | 60 ml | finish=matte; wear=long-lasting; ref=typical | Aqua, Alcohol Denat., PVP, Dimethicone PEG-7 Isostearate, Polysorbate 20, Aloe Barbadensis Leaf Juice, Panthenol, Phenoxyethanol, Ethylhexylglycerin
mac | Studio Fix Fluid SPF15 | foundation | 2005 | 30 ml | spf=15; finish=matte; coverage=medium to full; shades=67; ref=typical | Octinoxate, Titanium Dioxide, Aqua, Cyclopentasiloxane, Dimethicone, Butylene Glycol, Talc, Peg-10 Dimethicone, Polymethyl Methacrylate, Isododecane, Sodium Chloride, Tocopheryl Acetate, Ethylhexylglycerin, Dimethicone Crosspolymer, Disteardimonium Hectorite, Tribehenin, Hydrogen Dimethicone, Laureth-7, Trisodium EDTA, Phenoxyethanol, Iron Oxides
mac | Matte Lipstick Ruby Woo | lipstick | 1999 | 3 g | finish=retro matte; shade=blue-red; ref=typical | Isononyl Isononanoate, Ethylhexyl Palmitate, Silica, Paraffin, Polyethylene, Isopropyl Myristate, Microcrystalline Wax, Candelilla Cera, Kaolin, Copernicia Cerifera Cera, Ethylhexyl Hydroxystearate, Tocopheryl Acetate, Ascorbyl Palmitate, Tocopherol, Phenoxyethanol, Aroma, Mica, CI 15850, CI 77891, CI 77491, CI 15985, CI 45410
estee-lauder | Double Wear Stay-in-Place Foundation SPF10 | foundation | 1997 | 30 ml | spf=10; finish=matte; coverage=medium to full; shades=56; wear=24 hours; ref=typical | Octinoxate, Titanium Dioxide, Aqua, Cyclopentasiloxane, Dimethicone, Butylene Glycol, Cyclohexasiloxane, PEG-10 Dimethicone, Trimethylsiloxysilicate, Polypropylsilsesquioxane, Polyglyceryl-4 Isostearate, Sodium Chloride, Disteardimonium Hectorite, Tocopheryl Acetate, Alumina, Sodium Dehydroacetate, Phenoxyethanol, Iron Oxides
fenty-beauty | Pro Filt'r Soft Matte Longwear Foundation | foundation | 2017 | 32 ml | skin=normal,oily; finish=soft matte; coverage=medium to full; shades=50; ref=typical | Aqua, Dimethicone, Isododecane, Talc, Alcohol, Trimethylsiloxysilicate, Butylene Glycol, PEG-10 Dimethicone, Dimethicone/Vinyl Dimethicone Crosspolymer, Sodium Chloride, Sodium Dehydroacetate, Disteardimonium Hectorite, Silica, Phenoxyethanol, Iron Oxides, Titanium Dioxide
fenty-beauty | Gloss Bomb Universal Lip Luminizer | lip gloss | 2017 | 9 ml | finish=high shine; shade=Fenty Glow; ref=typical | Polybutene, Diisostearyl Malate, Hydrogenated Polyisobutene, Octyldodecanol, Silica Dimethyl Silylate, Pentaerythrityl Tetraisostearate, Tocopheryl Acetate, Butyrospermum Parkii Butter, Aroma, Ethylene/Propylene/Styrene Copolymer, Butylene/Ethylene/Styrene Copolymer, Benzyl Benzoate, Calcium Aluminum Borosilicate, Calcium Sodium Borosilicate, Tin Oxide, Mica, CI 77891, CI 77491
rare-beauty | Soft Pinch Liquid Blush | blush | 2020 | 7.5 ml | finish=dewy or matte; shades=16; ref=typical | Aqua, Dimethicone, Dimethicone Crosspolymer, Isododecane, Butylene Glycol, Lauryl PEG-9 Polydimethylsiloxyethyl Dimethicone, Polysilicone-11, Trimethylsiloxysilicate, Sodium Chloride, Disteardimonium Hectorite, Lilium Candidum Flower Extract, Gardenia Taitensis Flower Extract, Nymphaea Caerulea Flower Extract, Glycerin, Tocopherol, Phenoxyethanol, Caprylyl Glycol, Ethylhexylglycerin, Mica, CI 77891, CI 15850, CI 45410, CI 77491
charlotte-tilbury | Airbrush Flawless Setting Spray | setting spray | 2018 | 100 ml | finish=natural; wear=16 hours; ref=typical | Aqua, Alcohol Denat., Glycerin, Acrylates/Octylacrylamide Copolymer, Polysorbate 20, Rosa Damascena Flower Water, Hydrolyzed Hyaluronic Acid, Caprylyl Glycol, Phenoxyethanol, Parfum
charlotte-tilbury | Pillow Talk Matte Revolution Lipstick | lipstick | 2016 | 3.5 g | finish=matte; shade=nude pink; ref=typical | Octyldodecanol, Polyethylene, Silica, Caprylic/Capric Triglyceride, Bis-Diglyceryl Polyacyladipate-2, Tridecyl Trimellitate, Microcrystalline Wax, Diisostearyl Malate, Ethylhexyl Palmitate, Copernicia Cerifera Cera, Tocopheryl Acetate, Rosa Damascena Flower Oil, Pentaerythrityl Tetra-Di-t-Butyl Hydroxyhydrocinnamate, Aroma, Mica, CI 77891, CI 77491, CI 15850, CI 77492, CI 77499
nars | Radiant Creamy Concealer | concealer | 2013 | 6 ml | finish=radiant; coverage=medium to full; shades=30; ref=typical | Aqua, Dimethicone, Glycerin, Butylene Glycol, Isododecane, Cyclopentasiloxane, PEG-9 Polydimethylsiloxyethyl Dimethicone, Dimethicone/Vinyl Dimethicone Crosspolymer, Sodium Chloride, Phenoxyethanol, Magnesium Ascorbyl Phosphate, Tocopheryl Acetate, Morus Alba Leaf Extract, Vitex Agnus Castus Extract, Disteardimonium Hectorite, Titanium Dioxide, CI 77491, CI 77492, CI 77499
nars | Orgasm Blush | blush | 1999 | 4.8 g | finish=shimmer; shade=peachy pink with golden shimmer; ref=typical | Talc, Mica, Dimethicone, Zinc Stearate, Nylon-12, Ethylhexyl Palmitate, Silica, Phenoxyethanol, Caprylyl Glycol, Sorbic Acid, CI 77891, CI 77491, CI 15850
benefit | Hoola Matte Bronzer | bronzer | 2004 | 8 g | finish=matte; ref=typical | Talc, Kaolin, Zinc Stearate, Dimethicone, Octyldodecyl Stearoyl Stearate, Silica, Polyethylene, Tocopheryl Acetate, Methylparaben, Propylparaben, Iron Oxides, Titanium Dioxide
benefit | They're Real! Lengthening Mascara | mascara | 2011 | 8.5 g | finish=lengthening,lifting; ref=typical | Aqua, Cera Alba, Paraffin, Stearic Acid, Butylene Glycol, Aminomethyl Propanediol, Acacia Senegal Gum, Hydroxyethylcellulose, Copernicia Cerifera Cera, Polyvinyl Alcohol, Silica, Phenoxyethanol, Caprylyl Glycol, Ethylhexylglycerin, Tocopherol, Sodium Dehydroacetate, CI 77499
too-faced | Better Than Sex Mascara | mascara | 2014 | 8 ml | finish=volumising; ref=typical | Aqua, Paraffin, Glyceryl Stearate, Acrylates Copolymer, Butylene Glycol, Stearic Acid, Cera Alba, Polyisobutene, Copernicia Cerifera Cera, Aminomethyl Propanediol, Hydroxyethylcellulose, Polysorbate 20, Phenoxyethanol, Silica, Polyvinylpyrrolidone, Peptide Complex, Ethylhexylglycerin, CI 77499
huda-beauty | Easy Bake Loose Baking & Setting Powder | powder | 2018 | 20 g | finish=matte; shades=8; ref=typical | Talc, Silica, Dimethicone, Magnesium Myristate, Zinc Stearate, Caprylyl Glycol, Ethylhexylglycerin, Hexylene Glycol, Phenoxyethanol, Titanium Dioxide, CI 77491, CI 77492, CI 77499
anastasia-beverly-hills | Brow Wiz | brow | 2008 | 0.085 g | shades=13; ref=typical | Dimethicone, Synthetic Beeswax, Polyethylene, Stearic Acid, Silica, Talc, Ethylene/VA Copolymer, Tocopheryl Acetate, Tocopherol, CI 77491, CI 77492, CI 77499, CI 77891
urban-decay | All Nighter Setting Spray | setting spray | 2008 | 118 ml | finish=natural; wear=16 hours; ref=typical | Aqua, Alcohol Denat., Acrylates/Octylacrylamide Copolymer, PPG-26-Buteth-26, PEG-40 Hydrogenated Castor Oil, Polysorbate 20, Phenoxyethanol, Aloe Barbadensis Leaf Extract, Panthenol, Caprylyl Glycol, Ethylhexylglycerin
elf | Power Grip Primer | primer | 2022 | 24 ml | finish=grippy; actives=Hyaluronic acid, Niacinamide; ref=typical | Aqua, Glycerin, Butylene Glycol, Polyvinyl Alcohol, Niacinamide, Sodium Hyaluronate, Polysorbate 20, Squalane, Hydroxyethylcellulose, Allantoin, Phenoxyethanol, Ethylhexylglycerin, Disodium EDTA
elf | Halo Glow Liquid Filter | highlighter | 2022 | 31.5 ml | finish=luminous; shades=12; ref=typical | Aqua, Cyclopentasiloxane, Glycerin, Dimethicone, Butylene Glycol, Isododecane, Niacinamide, Sodium Hyaluronate, Squalane, Polysilicone-11, PEG-10 Dimethicone, Disteardimonium Hectorite, Phenoxyethanol, Ethylhexylglycerin, Mica, Titanium Dioxide, CI 77491, CI 77492, CI 77499, Tin Oxide
glossier | Boy Brow | brow | 2015 | 3 g | shades=6; finish=brushed-up; ref=typical | Aqua, Cera Alba, Stearic Acid, Copernicia Cerifera Cera, Glyceryl Stearate, Polyvinylpyrrolidone, Aminomethyl Propanediol, Hydroxyethylcellulose, Palmitic Acid, Oryza Sativa Cera, Butylene Glycol, Phenoxyethanol, Caprylyl Glycol, Tocopherol, CI 77491, CI 77492, CI 77499
rimmel | Stay Matte Pressed Powder | powder | 2009 | 14 g | finish=matte; shades=11; ref=typical | Talc, Mica, Zinc Stearate, Dimethicone, Silica, Octyldodecyl Stearoyl Stearate, Caprylyl Glycol, Hexylene Glycol, Phenoxyethanol, Titanium Dioxide, CI 77491, CI 77492, CI 77499
covergirl | Clean Fresh Skin Milk | foundation | 2019 | 30 ml | finish=dewy; coverage=light; vegan; ref=typical | Aqua, Coconut Alkanes, Propanediol, Glycerin, Coco-Caprylate/Caprate, Polyglyceryl-4 Isostearate, Aloe Barbadensis Leaf Juice, Cocos Nucifera Water, Cucumis Sativus Fruit Extract, Sodium Chloride, Disteardimonium Hectorite, Tocopherol, Phenoxyethanol, Ethylhexylglycerin, Titanium Dioxide, CI 77491, CI 77492, CI 77499
kiko-milano | 3D Hydra Lipgloss | lip gloss | 2014 | 6.5 ml | finish=3D shine; shades=30; ref=typical | Hydrogenated Polyisobutene, Ethylhexyl Palmitate, Silica Dimethyl Silylate, Pentaerythrityl Tetraisostearate, Tocopheryl Acetate, Aroma, Benzyl Alcohol, Mica, CI 77891, CI 15850, CI 45410, CI 77491
essence | Lash Princess False Lash Effect Mascara | mascara | 2016 | 12 ml | finish=volume and length; ref=typical | Aqua, Paraffin, Glyceryl Stearate, Acacia Senegal Gum, Butylene Glycol, Stearic Acid, Copernicia Cerifera Cera, Aminomethyl Propanediol, Hydroxyethylcellulose, Palmitic Acid, Polyvinyl Alcohol, Phenoxyethanol, Ethylhexylglycerin, Tocopherol, CI 77499
romand | Juicy Lasting Tint | lip gloss | 2016 | 5.5 g | finish=glassy tint; shades=35; ref=typical | Hydrogenated Polyisobutene, Diisostearyl Malate, Polybutene, Hydrogenated Poly(C6-14 Olefin), Silica Dimethyl Silylate, Dextrin Palmitate, Pentaerythrityl Tetraisostearate, Tocopheryl Acetate, Flavor, CI 15850, CI 45410, CI 77491, CI 77891
opi | Nail Lacquer Big Apple Red | nail polish | 1990 | 15 ml | finish=creme; formula=7-free; ref=typical | Butyl Acetate, Ethyl Acetate, Nitrocellulose, Acetyl Tributyl Citrate, Propyl Acetate, Isopropyl Alcohol, Adipic Acid/Neopentyl Glycol/Trimellitic Anhydride Copolymer, Stearalkonium Bentonite, Acrylates Copolymer, Benzophenone-1, Silica, Diacetone Alcohol, Phosphoric Acid, CI 15850, CI 77891
essie | Nail Polish Ballet Slippers | nail polish | 1989 | 13.5 ml | finish=sheer creme; shade=sheer pale pink; ref=typical | Butyl Acetate, Ethyl Acetate, Nitrocellulose, Adipic Acid/Neopentyl Glycol/Trimellitic Anhydride Copolymer, Acetyl Tributyl Citrate, Isopropyl Alcohol, Stearalkonium Bentonite, Styrene/Acrylates Copolymer, Benzophenone-1, Diacetone Alcohol, Silica, Phosphoric Acid, Mica, CI 77891, CI 15850, CI 77491
sally-hansen | Hard as Nails Strengthener | nail polish | 1970 | 13.3 ml | finish=clear; actives=Nylon fibres, Keratin; ref=typical | Ethyl Acetate, Butyl Acetate, Nitrocellulose, Tosylamide/Epoxy Resin, Isopropyl Alcohol, Acetyl Tributyl Citrate, Nylon, Stearalkonium Hectorite, Hydrolyzed Keratin, Citric Acid, Benzophenone-1, Violet 2
`;
