/* ============================================================
   Chemistry Data Layer — Periodic Table & Comprehensive Chemical / Drug Database.
   ============================================================ */

import { COMPOUNDS_DATA } from './compounds-dataset.js';


/**
 * @typedef {Object} ChemicalElement
 * @property {number} number - Atomic number (Z)
 * @property {string} symbol - Chemical symbol (e.g. "Fe")
 * @property {string} name - Element name (e.g. "Iron")
 * @property {number} weight - Standard atomic weight (u)
 * @property {number} period - Periodic table period (1-7)
 * @property {number} group - Periodic table group (1-18)
 * @property {'s'|'p'|'d'|'f'} block - Valence electron block
 * @property {string} category - Category (alkali-metal, alkaline-earth, transition-metal, post-transition, metalloid, polyatomic-nonmetal, diatomic-nonmetal, noble-gas, lanthanide, actinide)
 * @property {'solid'|'liquid'|'gas'|'unknown'} phase - State at 298.15 K
 * @property {number|null} density - Density in g/cm³ (or g/L for gases)
 * @property {number|null} melt - Melting point in Kelvin
 * @property {number|null} boil - Boiling point in Kelvin
 * @property {number|null} electronegativity - Pauling scale
 * @property {string} electronConfig - Electron configuration
 * @property {number[]} oxidationStates - Common oxidation states
 * @property {number|null} ionizationEnergy - First ionization energy (kJ/mol)
 * @property {number|null} atomicRadius - Empirical atomic radius (pm)
 * @property {string} [discoverer] - Discovered by
 * @property {number|string} [year] - Discovery year
 * @property {string} summary - Scientific summary and role
 */

export const ELEMENT_CATEGORIES = [
  { id: 'all', label: 'All Categories', color: 'var(--g500)' },
  { id: 'alkali-metal', label: 'Alkali Metals', color: '#ef4444' },
  { id: 'alkaline-earth', label: 'Alkaline Earth Metals', color: '#f97316' },
  { id: 'transition-metal', label: 'Transition Metals', color: '#eab308' },
  { id: 'post-transition', label: 'Post-Transition Metals', color: '#22c55e' },
  { id: 'metalloid', label: 'Metalloids', color: '#14b8a6' },
  { id: 'polyatomic-nonmetal', label: 'Reactive Nonmetals', color: '#3b82f6' },
  { id: 'halogen', label: 'Halogens', color: '#8b5cf6' },
  { id: 'noble-gas', label: 'Noble Gases', color: '#ec4899' },
  { id: 'lanthanide', label: 'Lanthanides', color: '#06b6d4' },
  { id: 'actinide', label: 'Actinides', color: '#a855f7' },
];

/**
 * Complete IUPAC 118 Chemical Elements Database (Z=1 to Z=118)
 * @type {ChemicalElement[]}
 */
export const ELEMENTS = [
  // Period 1
  { number: 1, symbol: 'H', name: 'Hydrogen', weight: 1.008, period: 1, group: 1, block: 's', category: 'polyatomic-nonmetal', phase: 'gas', density: 0.08988, melt: 14.01, boil: 20.28, electronegativity: 2.20, electronConfig: '1s¹', oxidationStates: [1, -1], ionizationEnergy: 1312.0, atomicRadius: 53, discoverer: 'Henry Cavendish', year: 1766, summary: 'Most abundant chemical substance in the universe (75% of baryonic mass); fuels stellar fusion and forms water and organic biomolecules.' },
  { number: 2, symbol: 'He', name: 'Helium', weight: 4.0026, period: 1, group: 18, block: 's', category: 'noble-gas', phase: 'gas', density: 0.1786, melt: 0.95, boil: 4.22, electronegativity: null, electronConfig: '1s²', oxidationStates: [0], ionizationEnergy: 2372.3, atomicRadius: 31, discoverer: 'Pierre Janssen, Norman Lockyer', year: 1868, summary: 'Colorless, inert noble gas with lowest boiling point of any element; critical cryogenic coolant for superconducting MRI magnets.' },

  // Period 2
  { number: 3, symbol: 'Li', name: 'Lithium', weight: 6.94, period: 2, group: 1, block: 's', category: 'alkali-metal', phase: 'solid', density: 0.534, melt: 453.69, boil: 1603, electronegativity: 0.98, electronConfig: '[He] 2s¹', oxidationStates: [1], ionizationEnergy: 520.2, atomicRadius: 167, discoverer: 'Johan August Arfwedson', year: 1817, summary: 'Least dense solid element with highest electrochemical potential; foundational in rechargeable lithium-ion battery technology.' },
  { number: 4, symbol: 'Be', name: 'Beryllium', weight: 9.0122, period: 2, group: 2, block: 's', category: 'alkaline-earth', phase: 'solid', density: 1.85, melt: 1560, boil: 2742, electronegativity: 1.57, electronConfig: '[He] 2s²', oxidationStates: [2], ionizationEnergy: 899.5, atomicRadius: 112, discoverer: 'Louis Nicolas Vauquelin', year: 1798, summary: 'Light, rigid aerospace metal with high thermal conductivity and low X-ray absorption; used in space telescope mirrors and beryllium alloys.' },
  { number: 5, symbol: 'B', name: 'Boron', weight: 10.81, period: 2, group: 13, block: 'p', category: 'metalloid', phase: 'solid', density: 2.34, melt: 2349, boil: 4200, electronegativity: 2.04, electronConfig: '[He] 2s² 2p¹', oxidationStates: [3], ionizationEnergy: 800.6, atomicRadius: 87, discoverer: 'Gay-Lussac, Thénard', year: 1808, summary: 'Metalloid forming electron-deficient cluster compounds; utilized in borosilicate glass (Pyrex), boron fibers, and semiconductor dopants.' },
  { number: 6, symbol: 'C', name: 'Carbon', weight: 12.011, period: 2, group: 14, block: 'p', category: 'polyatomic-nonmetal', phase: 'solid', density: 2.267, melt: 3823, boil: 4098, electronegativity: 2.55, electronConfig: '[He] 2s² 2p²', oxidationStates: [-4, -2, 2, 4], ionizationEnergy: 1086.5, atomicRadius: 67, discoverer: 'Antiquity', year: 'Ancient', summary: 'Basis of all organic chemistry and life; forms allotropes including diamond, graphite, graphene, fullerenes, and carbon nanotubes.' },
  { number: 7, symbol: 'N', name: 'Nitrogen', weight: 14.007, period: 2, group: 15, block: 'p', category: 'polyatomic-nonmetal', phase: 'gas', density: 1.251, melt: 63.15, boil: 77.36, electronegativity: 3.04, electronConfig: '[He] 2s² 2p³', oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5], ionizationEnergy: 1402.3, atomicRadius: 56, discoverer: 'Daniel Rutherford', year: 1772, summary: 'Comprises 78% of Earth’s atmosphere as stable diatomic N₂; essential component of amino acids, proteins, RNA, and DNA.' },
  { number: 8, symbol: 'O', name: 'Oxygen', weight: 15.999, period: 2, group: 16, block: 'p', category: 'polyatomic-nonmetal', phase: 'gas', density: 1.429, melt: 54.36, boil: 90.20, electronegativity: 3.44, electronConfig: '[He] 2s² 2p⁴', oxidationStates: [-2, -1, 2], ionizationEnergy: 1313.9, atomicRadius: 48, discoverer: 'Scheele, Priestley', year: 1774, summary: 'Highly reactive nonmetal and oxidizing agent; essential for aerobic cellular respiration, combustion, and Earth’s water and silicate crust.' },
  { number: 9, symbol: 'F', name: 'Fluorine', weight: 18.998, period: 2, group: 17, block: 'p', category: 'halogen', phase: 'gas', density: 1.696, melt: 53.53, boil: 85.03, electronegativity: 3.98, electronConfig: '[He] 2s² 2p⁵', oxidationStates: [-1], ionizationEnergy: 1681.0, atomicRadius: 42, discoverer: 'Henri Moissan', year: 1886, summary: 'Most electronegative and reactive of all chemical elements; forms fluorochemicals, non-stick PTFE (Teflon), and dental fluoride enamel treatments.' },
  { number: 10, symbol: 'Ne', name: 'Neon', weight: 20.180, period: 2, group: 18, block: 'p', category: 'noble-gas', phase: 'gas', density: 0.9002, melt: 24.56, boil: 27.07, electronegativity: null, electronConfig: '[He] 2s² 2p⁶', oxidationStates: [0], ionizationEnergy: 2080.7, atomicRadius: 38, discoverer: 'Ramsay, Travers', year: 1898, summary: 'Inert noble gas emitting a distinctive reddish-orange glow under electric discharge; used in high-voltage indicators and cryogenic refrigeration.' },

  // Period 3
  { number: 11, symbol: 'Na', name: 'Sodium', weight: 22.990, period: 3, group: 1, block: 's', category: 'alkali-metal', phase: 'solid', density: 0.968, melt: 370.87, boil: 1156, electronegativity: 0.93, electronConfig: '[Ne] 3s¹', oxidationStates: [1], ionizationEnergy: 495.8, atomicRadius: 190, discoverer: 'Humphry Davy', year: 1807, summary: 'Soft, silver-white alkali metal; vital extracellular electrolyte in animals regulating osmotic pressure and action potential propagation.' },
  { number: 12, symbol: 'Mg', name: 'Magnesium', weight: 24.305, period: 3, group: 2, block: 's', category: 'alkaline-earth', phase: 'solid', density: 1.738, melt: 923, boil: 1363, electronegativity: 1.31, electronConfig: '[Ne] 3s²', oxidationStates: [2], ionizationEnergy: 737.7, atomicRadius: 145, discoverer: 'Joseph Black, Humphry Davy', year: 1755, summary: 'Lightweight structural metal; central ion in photosynthetic chlorophyll complexes and enzymatic cofactor for over 300 biochemical reactions.' },
  { number: 13, symbol: 'Al', name: 'Aluminium', weight: 26.982, period: 3, group: 13, block: 'p', category: 'post-transition', phase: 'solid', density: 2.70, melt: 933.47, boil: 2792, electronegativity: 1.61, electronConfig: '[Ne] 3s² 3p¹', oxidationStates: [3], ionizationEnergy: 577.5, atomicRadius: 118, discoverer: 'Hans Christian Ørsted', year: 1825, summary: 'Most abundant metal in Earth’s crust; lightweight, ductile, and corrosion-resistant through self-passivating surface oxide film.' },
  { number: 14, symbol: 'Si', name: 'Silicon', weight: 28.085, period: 3, group: 14, block: 'p', category: 'metalloid', phase: 'solid', density: 2.329, melt: 1687, boil: 3538, electronegativity: 1.90, electronConfig: '[Ne] 3s² 3p²', oxidationStates: [-4, 2, 4], ionizationEnergy: 786.5, atomicRadius: 111, discoverer: 'Jöns Jacob Berzelius', year: 1824, summary: 'Semiconductor metalloid; the backbone of modern electronics, computer processors, photovoltaic solar cells, and silicone polymers.' },
  { number: 15, symbol: 'P', name: 'Phosphorus', weight: 30.974, period: 3, group: 15, block: 'p', category: 'polyatomic-nonmetal', phase: 'solid', density: 1.823, melt: 317.3, boil: 553.6, electronegativity: 2.19, electronConfig: '[Ne] 3s² 3p³', oxidationStates: [-3, 3, 5], ionizationEnergy: 1011.8, atomicRadius: 98, discoverer: 'Hennig Brand', year: 1669, summary: 'Exists in white, red, and black allotropes; essential constituent of ATP cellular energy transfer, DNA phosphodiester backbones, and fertilizers.' },
  { number: 16, symbol: 'S', name: 'Sulfur', weight: 32.06, period: 3, group: 16, block: 'p', category: 'polyatomic-nonmetal', phase: 'solid', density: 2.07, melt: 388.36, boil: 717.8, electronegativity: 2.58, electronConfig: '[Ne] 3s² 3p⁴', oxidationStates: [-2, 2, 4, 6], ionizationEnergy: 999.6, atomicRadius: 88, discoverer: 'Antiquity', year: 'Ancient', summary: 'Yellow crystalline nonmetal; required in cysteine and methionine amino acid disulfide bridges and sulfuric acid industrial production.' },
  { number: 17, symbol: 'Cl', name: 'Chlorine', weight: 35.45, period: 3, group: 17, block: 'p', category: 'halogen', phase: 'gas', density: 3.20, melt: 171.6, boil: 239.11, electronegativity: 3.16, electronConfig: '[Ne] 3s² 3p⁵', oxidationStates: [-1, 1, 3, 5, 7], ionizationEnergy: 1251.2, atomicRadius: 79, discoverer: 'Carl Wilhelm Scheele', year: 1774, summary: 'Pungent greenish-yellow halogen gas; major component of table salt (NaCl), water chlorination disinfectants, and polyvinyl chloride (PVC).' },
  { number: 18, symbol: 'Ar', name: 'Argon', weight: 39.948, period: 3, group: 18, block: 'p', category: 'noble-gas', phase: 'gas', density: 1.784, melt: 83.80, boil: 87.30, electronegativity: null, electronConfig: '[Ne] 3s² 3p⁶', oxidationStates: [0], ionizationEnergy: 1520.6, atomicRadius: 71, discoverer: 'Lord Rayleigh, William Ramsay', year: 1894, summary: 'Third most abundant atmospheric gas (0.93%); inert shielding gas in TIG arc welding, silicon crystal pulling, and incandescent lighting.' },

  // Period 4
  { number: 19, symbol: 'K', name: 'Potassium', weight: 39.098, period: 4, group: 1, block: 's', category: 'alkali-metal', phase: 'solid', density: 0.862, melt: 336.53, boil: 1032, electronegativity: 0.82, electronConfig: '[Ar] 4s¹', oxidationStates: [1], ionizationEnergy: 418.8, atomicRadius: 243, discoverer: 'Humphry Davy', year: 1807, summary: 'Major intracellular cation in physiology maintaining cellular resting membrane potentials and muscle contractions.' },
  { number: 20, symbol: 'Ca', name: 'Calcium', weight: 40.078, period: 4, group: 2, block: 's', category: 'alkaline-earth', phase: 'solid', density: 1.54, melt: 1115, boil: 1757, electronegativity: 1.00, electronConfig: '[Ar] 4s²', oxidationStates: [2], ionizationEnergy: 589.8, atomicRadius: 194, discoverer: 'Humphry Davy', year: 1808, summary: 'Primary structural mineral in bones, teeth, and shells (hydroxyapatite); essential intracellular signal messenger in neurotransmission.' },
  { number: 21, symbol: 'Sc', name: 'Scandium', weight: 44.956, period: 4, group: 3, block: 'd', category: 'transition-metal', phase: 'solid', density: 2.985, melt: 1814, boil: 3109, electronegativity: 1.36, electronConfig: '[Ar] 3d¹ 4s²', oxidationStates: [3], ionizationEnergy: 633.1, atomicRadius: 184, discoverer: 'Lars Fredrik Nilson', year: 1879, summary: 'Light transition metal; alloyed with aluminium in aerospace components and sporting goods to dramatically enhance weld strength.' },
  { number: 22, symbol: 'Ti', name: 'Titanium', weight: 47.867, period: 4, group: 4, block: 'd', category: 'transition-metal', phase: 'solid', density: 4.506, melt: 1941, boil: 3560, electronegativity: 1.54, electronConfig: '[Ar] 3d² 4s²', oxidationStates: [2, 3, 4], ionizationEnergy: 658.8, atomicRadius: 176, discoverer: 'William Gregor', year: 1791, summary: 'High strength-to-weight ratio and exceptional biocompatibility; gold standard for surgical orthopedic implants and jet turbine components.' },
  { number: 23, symbol: 'V', name: 'Vanadium', weight: 50.942, period: 4, group: 5, block: 'd', category: 'transition-metal', phase: 'solid', density: 6.11, melt: 2183, boil: 3680, electronegativity: 1.63, electronConfig: '[Ar] 3d³ 4s²', oxidationStates: [2, 3, 4, 5], ionizationEnergy: 650.9, atomicRadius: 171, discoverer: 'Andrés Manuel del Río', year: 1801, summary: 'Steel-strengthening transition metal used in high-speed tools, vanadium redox flow batteries (VRFB), and chemical catalysts.' },
  { number: 24, symbol: 'Cr', name: 'Chromium', weight: 51.996, period: 4, group: 6, block: 'd', category: 'transition-metal', phase: 'solid', density: 7.19, melt: 2180, boil: 2944, electronegativity: 1.66, electronConfig: '[Ar] 3d⁵ 4s¹', oxidationStates: [2, 3, 6], ionizationEnergy: 652.9, atomicRadius: 166, discoverer: 'Louis Nicolas Vauquelin', year: 1797, summary: 'Corrosion-resistant metal imparting rust immunity to stainless steel (≥10.5% Cr) and vivid colors to emeralds and rubies.' },
  { number: 25, symbol: 'Mn', name: 'Manganese', weight: 54.938, period: 4, group: 7, block: 'd', category: 'transition-metal', phase: 'solid', density: 7.21, melt: 1519, boil: 2334, electronegativity: 1.55, electronConfig: '[Ar] 3d⁵ 4s²', oxidationStates: [2, 3, 4, 6, 7], ionizationEnergy: 717.3, atomicRadius: 161, discoverer: 'Carl Wilhelm Scheele, Johan Gottlieb Gahn', year: 1774, summary: 'Essential industrial alloying element in carbon steel and aluminium alloys; central catalytic cluster in photosystem II water oxidation.' },
  { number: 26, symbol: 'Fe', name: 'Iron', weight: 55.845, period: 4, group: 8, block: 'd', category: 'transition-metal', phase: 'solid', density: 7.874, melt: 1811, boil: 3134, electronegativity: 1.83, electronConfig: '[Ar] 3d⁶ 4s²', oxidationStates: [2, 3, 4, 6], ionizationEnergy: 762.5, atomicRadius: 156, discoverer: 'Antiquity', year: 'Ancient', summary: 'Most abundant element by mass on Earth; central core of planetary magnetic field and active oxygen-binding center in hemoglobin.' },
  { number: 27, symbol: 'Co', name: 'Cobalt', weight: 58.933, period: 4, group: 9, block: 'd', category: 'transition-metal', phase: 'solid', density: 8.90, melt: 1768, boil: 3200, electronegativity: 1.88, electronConfig: '[Ar] 3d⁷ 4s²', oxidationStates: [2, 3], ionizationEnergy: 760.4, atomicRadius: 152, discoverer: 'Georg Brandt', year: 1735, summary: 'Ferromagnetic transition metal used in superalloys for jet engines, lithium-ion battery cathodes (NMC), and vitamin B12 (cobalamin).' },
  { number: 28, symbol: 'Ni', name: 'Nickel', weight: 58.693, period: 4, group: 10, block: 'd', category: 'transition-metal', phase: 'solid', density: 8.908, melt: 1728, boil: 3186, electronegativity: 1.91, electronConfig: '[Ar] 3d⁸ 4s²', oxidationStates: [2, 3], ionizationEnergy: 737.1, atomicRadius: 149, discoverer: 'Axel Fredrik Cronstedt', year: 1751, summary: 'Ductile corrosion-resistant metal used in stainless steel, rechargeable nickel batteries, coinage, and hydrogenation catalysis.' },
  { number: 29, symbol: 'Cu', name: 'Copper', weight: 63.546, period: 4, group: 11, block: 'd', category: 'transition-metal', phase: 'solid', density: 8.96, melt: 1357.77, boil: 2835, electronegativity: 1.90, electronConfig: '[Ar] 3d¹⁰ 4s¹', oxidationStates: [1, 2], ionizationEnergy: 745.5, atomicRadius: 145, discoverer: 'Antiquity', year: 'Ancient', summary: 'Exceptional electrical and thermal conductor; critical for global electrical grids, telecommunication cables, plumbing, and bronze/brass alloys.' },
  { number: 30, symbol: 'Zn', name: 'Zinc', weight: 65.38, period: 4, group: 12, block: 'd', category: 'transition-metal', phase: 'solid', density: 7.14, melt: 692.68, boil: 1180, electronegativity: 1.65, electronConfig: '[Ar] 3d¹⁰ 4s²', oxidationStates: [2], ionizationEnergy: 906.4, atomicRadius: 142, discoverer: 'Indian metallurgists', year: 'Ancient', summary: 'Anti-corrosion coating for galvanized steel and vital trace element for human immune health, DNA synthesis, and zinc-finger transcription.' },
  { number: 31, symbol: 'Ga', name: 'Gallium', weight: 69.723, period: 4, group: 13, block: 'p', category: 'post-transition', phase: 'solid', density: 5.91, melt: 302.91, boil: 2673, electronegativity: 1.81, electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹', oxidationStates: [3], ionizationEnergy: 578.8, atomicRadius: 136, discoverer: 'Lecoq de Boisbaudran', year: 1875, summary: 'Melts in the palm of a hand (29.76 °C); key component of gallium arsenide (GaAs) and gallium nitride (GaN) high-efficiency power electronics.' },
  { number: 32, symbol: 'Ge', name: 'Germanium', weight: 72.630, period: 4, group: 14, block: 'p', category: 'metalloid', phase: 'solid', density: 5.323, melt: 1211.40, boil: 3106, electronegativity: 2.01, electronConfig: '[Ar] 3d¹⁰ 4s² 4p²', oxidationStates: [2, 4], ionizationEnergy: 762.0, atomicRadius: 125, discoverer: 'Clemens Winkler', year: 1886, summary: 'Semiconductor metalloid used in fiber-optic communications, infrared night-vision optics, and high-speed silicon-germanium transistors.' },
  { number: 33, symbol: 'As', name: 'Arsenic', weight: 74.922, period: 4, group: 15, block: 'p', category: 'metalloid', phase: 'solid', density: 5.727, melt: 1090, boil: 887, electronegativity: 2.18, electronConfig: '[Ar] 3d¹⁰ 4s² 4p³', oxidationStates: [-3, 3, 5], ionizationEnergy: 947.0, atomicRadius: 114, discoverer: 'Albertus Magnus', year: 1250, summary: 'Metalloid forming poisonous compounds; historically used in pigments, metallurgy, and modern III-V semiconductor materials (GaAs).' },
  { number: 34, symbol: 'Se', name: 'Selenium', weight: 78.971, period: 4, group: 16, block: 'p', category: 'polyatomic-nonmetal', phase: 'solid', density: 4.819, melt: 494, boil: 958, electronegativity: 2.55, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴', oxidationStates: [-2, 2, 4, 6], ionizationEnergy: 941.0, atomicRadius: 103, discoverer: 'Jöns Jacob Berzelius', year: 1817, summary: 'Photoconductive nonmetal whose electrical conductivity surges under light exposure; used in solar cells and selenocysteine enzymes.' },
  { number: 35, symbol: 'Br', name: 'Bromine', weight: 79.904, period: 4, group: 17, block: 'p', category: 'halogen', phase: 'liquid', density: 3.1028, melt: 265.8, boil: 332.0, electronegativity: 2.96, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵', oxidationStates: [-1, 1, 3, 5], ionizationEnergy: 1139.9, atomicRadius: 94, discoverer: 'Antoine Jérôme Balard', year: 1826, summary: 'Dense reddish-brown fuming liquid halogen; used in brominated flame retardants, water purification, and photographic silver bromide.' },
  { number: 36, symbol: 'Kr', name: 'Krypton', weight: 83.798, period: 4, group: 18, block: 'p', category: 'noble-gas', phase: 'gas', density: 3.749, melt: 115.79, boil: 119.93, electronegativity: 3.00, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶', oxidationStates: [0, 2], ionizationEnergy: 1350.8, atomicRadius: 88, discoverer: 'Ramsay, Travers', year: 1898, summary: 'Noble gas utilized in energy-efficient insulated window glazing, airport runway flash lamps, and laser eye surgery excimer lasers.' },

  // Period 5
  { number: 37, symbol: 'Rb', name: 'Rubidium', weight: 85.468, period: 5, group: 1, block: 's', category: 'alkali-metal', phase: 'solid', density: 1.532, melt: 312.46, boil: 961, electronegativity: 0.82, electronConfig: '[Kr] 5s¹', oxidationStates: [1], ionizationEnergy: 403.0, atomicRadius: 265, discoverer: 'Bunsen, Kirchhoff', year: 1861, summary: 'Soft alkali metal that spontaneously ignites in air; standard frequency reference in telecommunication rubidium atomic clocks.' },
  { number: 38, symbol: 'Sr', name: 'Strontium', weight: 87.62, period: 5, group: 2, block: 's', category: 'alkaline-earth', phase: 'solid', density: 2.64, melt: 1050, boil: 1655, electronegativity: 0.95, electronConfig: '[Kr] 5s²', oxidationStates: [2], ionizationEnergy: 549.5, atomicRadius: 219, discoverer: 'Adair Crawford', year: 1790, summary: 'Alkaline earth metal that burns with a brilliant crimson red flame in pyrotechnics; optical lattice atomic clocks reach 10⁻¹⁸ precision.' },
  { number: 39, symbol: 'Y', name: 'Yttrium', weight: 88.906, period: 5, group: 3, block: 'd', category: 'transition-metal', phase: 'solid', density: 4.472, melt: 1799, boil: 3609, electronegativity: 1.22, electronConfig: '[Kr] 4d¹ 5s²', oxidationStates: [3], ionizationEnergy: 600.0, atomicRadius: 212, discoverer: 'Johan Gadolin', year: 1794, summary: 'Rare-earth transition metal; essential constituent of YBCO high-temperature superconductors and Nd:YAG medical/industrial lasers.' },
  { number: 40, symbol: 'Zr', name: 'Zirconium', weight: 91.224, period: 5, group: 4, block: 'd', category: 'transition-metal', phase: 'solid', density: 6.52, melt: 2128, boil: 4682, electronegativity: 1.33, electronConfig: '[Kr] 4d² 5s²', oxidationStates: [4], ionizationEnergy: 640.1, atomicRadius: 206, discoverer: 'Martin Heinrich Klaproth', year: 1789, summary: 'Extremely low thermal neutron absorption cross-section; standard cladding material (Zircaloy) for nuclear reactor uranium fuel rods.' },
  { number: 41, symbol: 'Nb', name: 'Niobium', weight: 92.906, period: 5, group: 5, block: 'd', category: 'transition-metal', phase: 'solid', density: 8.57, melt: 2750, boil: 5017, electronegativity: 1.6, electronConfig: '[Kr] 4d⁴ 5s¹', oxidationStates: [3, 5], ionizationEnergy: 652.1, atomicRadius: 198, discoverer: 'Charles Hatchett', year: 1801, summary: 'Superconducting transition metal forming Nb-Ti and Nb3Sn wire coils used in CERN particle accelerators and fusion tokamaks.' },
  { number: 42, symbol: 'Mo', name: 'Molybdenum', weight: 95.95, period: 5, group: 6, block: 'd', category: 'transition-metal', phase: 'solid', density: 10.28, melt: 2896, boil: 4912, electronegativity: 2.16, electronConfig: '[Kr] 4d⁵ 5s¹', oxidationStates: [2, 3, 4, 5, 6], ionizationEnergy: 684.3, atomicRadius: 190, discoverer: 'Carl Wilhelm Scheele', year: 1778, summary: 'High-temperature refractory metal; strengthens structural steel and forms Mo-99 medical isotopes for millions of diagnostic imaging scans.' },
  { number: 43, symbol: 'Tc', name: 'Technetium', weight: 98, period: 5, group: 7, block: 'd', category: 'transition-metal', phase: 'solid', density: 11.5, melt: 2430, boil: 4538, electronegativity: 1.9, electronConfig: '[Kr] 4d⁵ 5s²', oxidationStates: [4, 7], ionizationEnergy: 702.0, atomicRadius: 183, discoverer: 'Perrier, Segrè', year: 1937, summary: 'First artificially produced element; Tc-99m gamma-emitter is the most widely used radiopharmaceutical tracer in nuclear cardiology.' },
  { number: 44, symbol: 'Ru', name: 'Ruthenium', weight: 101.07, period: 5, group: 8, block: 'd', category: 'transition-metal', phase: 'solid', density: 12.45, melt: 2607, boil: 4423, electronegativity: 2.2, electronConfig: '[Kr] 4d⁷ 5s¹', oxidationStates: [2, 3, 4, 6, 8], ionizationEnergy: 710.2, atomicRadius: 178, discoverer: 'Karl Ernst Claus', year: 1844, summary: 'Platinum-group noble metal; hardens platinum/palladium alloys and catalyzes olefin metathesis reactions (Grubbs catalysts).' },
  { number: 45, symbol: 'Rh', name: 'Rhodium', weight: 102.91, period: 5, group: 9, block: 'd', category: 'transition-metal', phase: 'solid', density: 12.41, melt: 2237, boil: 3968, electronegativity: 2.28, electronConfig: '[Kr] 4d⁸ 5s¹', oxidationStates: [3], ionizationEnergy: 719.7, atomicRadius: 173, discoverer: 'William Hyde Wollaston', year: 1804, summary: 'Precious noble metal; the primary catalytic agent in three-way catalytic converters to reduce harmful nitrogen oxide vehicle emissions.' },
  { number: 46, symbol: 'Pd', name: 'Palladium', weight: 106.42, period: 5, group: 10, block: 'd', category: 'transition-metal', phase: 'solid', density: 12.023, melt: 1828.05, boil: 3236, electronegativity: 2.20, electronConfig: '[Kr] 4d¹⁰', oxidationStates: [2, 4], ionizationEnergy: 804.4, atomicRadius: 169, discoverer: 'William Hyde Wollaston', year: 1802, summary: 'Absorbs up to 900 times its own volume of hydrogen gas; central catalyst in Suzuki and Heck cross-coupling pharmaceutical synthesis.' },
  { number: 47, symbol: 'Ag', name: 'Silver', weight: 107.87, period: 5, group: 11, block: 'd', category: 'transition-metal', phase: 'solid', density: 10.49, melt: 1234.93, boil: 2435, electronegativity: 1.93, electronConfig: '[Kr] 4d¹⁰ 5s¹', oxidationStates: [1], ionizationEnergy: 731.0, atomicRadius: 165, discoverer: 'Antiquity', year: 'Ancient', summary: 'Highest electrical conductivity, thermal conductivity, and optical reflectivity of any known metallic element.' },
  { number: 48, symbol: 'Cd', name: 'Cadmium', weight: 112.41, period: 5, group: 12, block: 'd', category: 'transition-metal', phase: 'solid', density: 8.65, melt: 594.22, boil: 1040, electronegativity: 1.69, electronConfig: '[Kr] 4d¹⁰ 5s²', oxidationStates: [2], ionizationEnergy: 867.8, atomicRadius: 161, discoverer: 'Friedrich Stromeyer', year: 1817, summary: 'Soft bluish-white metal used in rechargeable Ni-Cd batteries, cadmium telluride (CdTe) solar panels, and neutron-absorbing control rods.' },
  { number: 49, symbol: 'In', name: 'Indium', weight: 114.82, period: 5, group: 13, block: 'p', category: 'post-transition', phase: 'solid', density: 7.31, melt: 429.75, boil: 2345, electronegativity: 1.78, electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹', oxidationStates: [3], ionizationEnergy: 558.3, atomicRadius: 156, discoverer: 'Reich, Richter', year: 1863, summary: 'Soft metal whose transparent conducting oxide (Indium Tin Oxide, ITO) coats virtually all smartphone touchscreens and OLED flat panels.' },
  { number: 50, symbol: 'Sn', name: 'Tin', weight: 118.71, period: 5, group: 14, block: 'p', category: 'post-transition', phase: 'solid', density: 7.287, melt: 505.08, boil: 2875, electronegativity: 1.96, electronConfig: '[Kr] 4d¹⁰ 5s² 5p²', oxidationStates: [2, 4], ionizationEnergy: 708.6, atomicRadius: 145, discoverer: 'Antiquity', year: 'Ancient', summary: 'Malleable post-transition metal; alloyed with copper to initiate the Bronze Age and used globally in electrical solder.' },
  { number: 51, symbol: 'Sb', name: 'Antimony', weight: 121.76, period: 5, group: 15, block: 'p', category: 'metalloid', phase: 'solid', density: 6.697, melt: 903.78, boil: 1860, electronegativity: 2.05, electronConfig: '[Kr] 4d¹⁰ 5s² 5p³', oxidationStates: [-3, 3, 5], ionizationEnergy: 834.0, atomicRadius: 133, discoverer: 'Antiquity', year: 'Ancient', summary: 'Lustrous metalloid used in lead-acid battery grid plates, microelectronic infrared detectors, and antimony trioxide flame retardants.' },
  { number: 52, symbol: 'Te', name: 'Tellurium', weight: 127.60, period: 5, group: 16, block: 'p', category: 'metalloid', phase: 'solid', density: 6.24, melt: 722.66, boil: 1261, electronegativity: 2.1, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴', oxidationStates: [-2, 2, 4, 6], ionizationEnergy: 869.3, atomicRadius: 123, discoverer: 'Franz-Joseph Müller von Reichenstein', year: 1782, summary: 'Brittle metalloid used in phase-change memory alloys (rewritable optical discs and PCRAM) and thermoelectric energy generators (Bi2Te3).' },
  { number: 53, symbol: 'I', name: 'Iodine', weight: 126.90, period: 5, group: 17, block: 'p', category: 'halogen', phase: 'solid', density: 4.933, melt: 386.85, boil: 457.4, electronegativity: 2.66, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵', oxidationStates: [-1, 1, 3, 5, 7], ionizationEnergy: 1008.4, atomicRadius: 115, discoverer: 'Bernard Courtois', year: 1811, summary: 'Lustrous purple halogen; essential dietary micronutrient required by the thyroid gland to synthesize thyroxine (T4) and triiodothyronine (T3).' },
  { number: 54, symbol: 'Xe', name: 'Xenon', weight: 131.29, period: 5, group: 18, block: 'p', category: 'noble-gas', phase: 'gas', density: 5.894, melt: 161.4, boil: 165.03, electronegativity: 2.6, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶', oxidationStates: [0, 2, 4, 6, 8], ionizationEnergy: 1170.4, atomicRadius: 108, discoverer: 'Ramsay, Travers', year: 1898, summary: 'Heavy noble gas used as xenon ion propulsion propellant on deep-space satellites and as a neuroprotective surgical anesthetic.' },

  // Period 6
  { number: 55, symbol: 'Cs', name: 'Caesium', weight: 132.91, period: 6, group: 1, block: 's', category: 'alkali-metal', phase: 'solid', density: 1.93, melt: 301.59, boil: 944, electronegativity: 0.79, electronConfig: '[Xe] 6s¹', oxidationStates: [1], ionizationEnergy: 375.7, atomicRadius: 298, discoverer: 'Bunsen, Kirchhoff', year: 1860, summary: 'Hyperfine ground-state transition of Caesium-133 (9,192,631,770 Hz) defines the SI unit of the second in atomic timekeeping.' },
  { number: 56, symbol: 'Ba', name: 'Barium', weight: 137.33, period: 6, group: 2, block: 's', category: 'alkaline-earth', phase: 'solid', density: 3.51, melt: 1000, boil: 2170, electronegativity: 0.89, electronConfig: '[Xe] 6s²', oxidationStates: [2], ionizationEnergy: 502.9, atomicRadius: 253, discoverer: 'Carl Wilhelm Scheele, Humphry Davy', year: 1772, summary: 'Dense alkaline earth metal; barium sulfate (BaSO4) is an insoluble radiopaque suspension used in GI gastrointestinal X-ray imaging.' },
  { number: 57, symbol: 'La', name: 'Lanthanum', weight: 138.91, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 6.162, melt: 1193, boil: 3737, electronegativity: 1.1, electronConfig: '[Xe] 5d¹ 6s²', oxidationStates: [3], ionizationEnergy: 538.1, atomicRadius: 195, discoverer: 'Carl Gustaf Mosander', year: 1839, summary: 'First of the lanthanide series; used in hybrid car NiMH battery anodes, camera lens optical glass, and petroleum cracking catalysts.' },
  { number: 58, symbol: 'Ce', name: 'Cerium', weight: 140.12, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 6.77, melt: 1068, boil: 3716, electronegativity: 1.12, electronConfig: '[Xe] 4f¹ 5d¹ 6s²', oxidationStates: [3, 4], ionizationEnergy: 534.4, atomicRadius: 185, discoverer: 'Klaproth, Berzelius, Hisinger', year: 1803, summary: 'Most abundant rare earth element; cerium oxide is the premier glass polishing abrasive and automotive catalytic converter promoter.' },
  { number: 59, symbol: 'Pr', name: 'Praseodymium', weight: 140.91, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 6.77, melt: 1208, boil: 3793, electronegativity: 1.13, electronConfig: '[Xe] 4f³ 6s²', oxidationStates: [3, 4], ionizationEnergy: 527.0, atomicRadius: 247, discoverer: 'Carl Auer von Welsbach', year: 1885, summary: 'Lanthanide metal alloyed with neodymium in ultra-high-strength permanent magnets and yellow didymium glass welder lenses.' },
  { number: 60, symbol: 'Nd', name: 'Neodymium', weight: 144.24, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 7.01, melt: 1297, boil: 3347, electronegativity: 1.14, electronConfig: '[Xe] 4f⁴ 6s²', oxidationStates: [3], ionizationEnergy: 533.1, atomicRadius: 206, discoverer: 'Carl Auer von Welsbach', year: 1885, summary: 'Forms the strongest known permanent magnets (Nd2Fe14B); essential for electric vehicle traction motors, wind turbines, and hard drives.' },
  { number: 61, symbol: 'Pm', name: 'Promethium', weight: 145, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 7.26, melt: 1315, boil: 3273, electronegativity: 1.13, electronConfig: '[Xe] 4f⁵ 6s²', oxidationStates: [3], ionizationEnergy: 540.0, atomicRadius: 205, discoverer: 'Marinsky, Glendenin, Coryell', year: 1945, summary: 'Only radioactive lanthanide with no stable isotopes; used in nuclear betavoltaic atomic batteries for space probes and cardiac pacemakers.' },
  { number: 62, symbol: 'Sm', name: 'Samarium', weight: 150.36, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 7.52, melt: 1345, boil: 2067, electronegativity: 1.17, electronConfig: '[Xe] 4f⁶ 6s²', oxidationStates: [2, 3], ionizationEnergy: 544.5, atomicRadius: 238, discoverer: 'Lecoq de Boisbaudran', year: 1879, summary: 'Used in high-temperature samarium-cobalt (SmCo) magnets and Sm-153 radiopharmaceutical treatment for bone cancer metastases.' },
  { number: 63, symbol: 'Eu', name: 'Europium', weight: 151.96, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 5.244, melt: 1099, boil: 1802, electronegativity: 1.2, electronConfig: '[Xe] 4f⁷ 6s²', oxidationStates: [2, 3], ionizationEnergy: 547.1, atomicRadius: 231, discoverer: 'Eugène-Anatole Demarçay', year: 1901, summary: 'Most reactive lanthanide; bright red phosphors in Euro banknotes and color TV screens utilize europium fluorescence.' },
  { number: 64, symbol: 'Gd', name: 'Gadolinium', weight: 157.25, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 7.90, melt: 1585, boil: 3546, electronegativity: 1.2, electronConfig: '[Xe] 4f⁷ 5d¹ 6s²', oxidationStates: [3], ionizationEnergy: 593.4, atomicRadius: 233, discoverer: 'Jean Charles Galissard de Marignac', year: 1880, summary: 'Highly paramagnetic element with 7 unpaired f-electrons; standard chelating intravenous contrast agent for clinical MRI brain scans.' },
  { number: 65, symbol: 'Tb', name: 'Terbium', weight: 158.93, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 8.23, melt: 1629, boil: 3503, electronegativity: 1.2, electronConfig: '[Xe] 4f⁹ 6s²', oxidationStates: [3, 4], ionizationEnergy: 565.8, atomicRadius: 225, discoverer: 'Carl Gustaf Mosander', year: 1843, summary: 'Lanthanide producing brilliant green luminescence; component of Terfenol-D magnetostrictive sonar transducers.' },
  { number: 66, symbol: 'Dy', name: 'Dysprosium', weight: 162.50, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 8.54, melt: 1680, boil: 2840, electronegativity: 1.22, electronConfig: '[Xe] 4f¹⁰ 6s²', oxidationStates: [3], ionizationEnergy: 573.0, atomicRadius: 228, discoverer: 'Lecoq de Boisbaudran', year: 1886, summary: 'Possesses the highest magnetic susceptibility of any element; prevents demagnetization of EV motor magnets at high operating temperatures.' },
  { number: 67, symbol: 'Ho', name: 'Holmium', weight: 164.93, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 8.79, melt: 1734, boil: 2993, electronegativity: 1.23, electronConfig: '[Xe] 4f¹¹ 6s²', oxidationStates: [3], ionizationEnergy: 581.0, atomicRadius: 226, discoverer: 'Marc Delafontaine, Jacques-Louis Soret', year: 1878, summary: 'Highest magnetic moment of any naturally occurring element; holmium (Ho:YAG) solid-state lasers pulverize kidney stones in urology.' },
  { number: 68, symbol: 'Er', name: 'Erbium', weight: 167.26, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 9.066, melt: 1802, boil: 3141, electronegativity: 1.24, electronConfig: '[Xe] 4f¹² 6s²', oxidationStates: [3], ionizationEnergy: 589.3, atomicRadius: 226, discoverer: 'Carl Gustaf Mosander', year: 1843, summary: 'Doped into optical fibers (Erbium-Doped Fiber Amplifiers, EDFA) to boost internet light signals across undersea transoceanic cables.' },
  { number: 69, symbol: 'Tm', name: 'Thulium', weight: 168.93, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 9.32, melt: 1818, boil: 2223, electronegativity: 1.25, electronConfig: '[Xe] 4f¹³ 6s²', oxidationStates: [3], ionizationEnergy: 596.7, atomicRadius: 222, discoverer: 'Per Teodor Cleve', year: 1879, summary: 'Least abundant stable lanthanide; used in portable X-ray radiation sources and specialized surgical thulium fiber lasers.' },
  { number: 70, symbol: 'Yb', name: 'Ytterbium', weight: 173.05, period: 6, group: 3, block: 'f', category: 'lanthanide', phase: 'solid', density: 6.90, melt: 1097, boil: 1469, electronegativity: 1.1, electronConfig: '[Xe] 4f¹⁴ 6s²', oxidationStates: [2, 3], ionizationEnergy: 603.4, atomicRadius: 222, discoverer: 'Jean Charles Galissard de Marignac', year: 1878, summary: 'Soft silvery metal used as a dopant in high-power industrial fiber laser cutting systems and atomic clocks.' },
  { number: 71, symbol: 'Lu', name: 'Lutetium', weight: 174.97, period: 6, group: 3, block: 'd', category: 'lanthanide', phase: 'solid', density: 9.841, melt: 1925, boil: 3675, electronegativity: 1.27, electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²', oxidationStates: [3], ionizationEnergy: 523.5, atomicRadius: 217, discoverer: 'Georges Urbain, Carl Auer von Welsbach', year: 1907, summary: 'Densest and hardest lanthanide; Lutetium-177 PSMA is a targeted radio-ligand therapy curing metastatic prostate cancer.' },
  { number: 72, symbol: 'Hf', name: 'Hafnium', weight: 178.49, period: 6, group: 4, block: 'd', category: 'transition-metal', phase: 'solid', density: 13.31, melt: 2506, boil: 4876, electronegativity: 1.3, electronConfig: '[Xe] 4f¹⁴ 5d² 6s²', oxidationStates: [4], ionizationEnergy: 658.5, atomicRadius: 208, discoverer: 'Coster, Hevesy', year: 1923, summary: 'High dielectric constant (high-k dielectric gate oxide) in modern microprocessors; excellent neutron absorber for submarine nuclear reactors.' },
  { number: 73, symbol: 'Ta', name: 'Tantalum', weight: 180.95, period: 6, group: 5, block: 'd', category: 'transition-metal', phase: 'solid', density: 16.69, melt: 3290, boil: 5731, electronegativity: 1.5, electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²', oxidationStates: [5], ionizationEnergy: 761.0, atomicRadius: 200, discoverer: 'Anders Gustaf Ekeberg', year: 1802, summary: 'Extremely corrosion-resistant metal forming miniature high-capacitance electrolytic capacitors in mobile electronics and medical pacemakers.' },
  { number: 74, symbol: 'W', name: 'Tungsten', weight: 183.84, period: 6, group: 6, block: 'd', category: 'transition-metal', phase: 'solid', density: 19.25, melt: 3695, boil: 5828, electronegativity: 2.36, electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²', oxidationStates: [2, 3, 4, 5, 6], ionizationEnergy: 770.0, atomicRadius: 193, discoverer: 'Carl Wilhelm Scheele, Elhuyar brothers', year: 1783, summary: 'Highest melting point of all metals (3422 °C); tungsten carbide (WC) machine tooling bits cut steel, titanium, and rock.' },
  { number: 75, symbol: 'Re', name: 'Rhenium', weight: 186.21, period: 6, group: 7, block: 'd', category: 'transition-metal', phase: 'solid', density: 21.02, melt: 3459, boil: 5869, electronegativity: 1.9, electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²', oxidationStates: [-1, 2, 4, 6, 7], ionizationEnergy: 760.0, atomicRadius: 188, discoverer: 'Noddack, Berg, Tacke', year: 1925, summary: 'One of the rarest elements; alloyed with nickel in single-crystal superalloys for commercial jet engine high-pressure combustion turbines.' },
  { number: 76, symbol: 'Os', name: 'Osmium', weight: 190.23, period: 6, group: 8, block: 'd', category: 'transition-metal', phase: 'solid', density: 22.59, melt: 3306, boil: 5285, electronegativity: 2.2, electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²', oxidationStates: [2, 3, 4, 8], ionizationEnergy: 840.0, atomicRadius: 185, discoverer: 'Smithson Tennant', year: 1803, summary: 'Densest naturally occurring element (22.59 g/cm³); toxic volatile osmium tetroxide (OsO4) stains biological tissue lipids for electron microscopy.' },
  { number: 77, symbol: 'Ir', name: 'Iridium', weight: 192.22, period: 6, group: 9, block: 'd', category: 'transition-metal', phase: 'solid', density: 22.56, melt: 2719, boil: 4701, electronegativity: 2.20, electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²', oxidationStates: [2, 3, 4, 6], ionizationEnergy: 880.0, atomicRadius: 180, discoverer: 'Smithson Tennant', year: 1803, summary: 'Most corrosion-resistant metal; global iridium layer at the K-Pg boundary provided definitive proof of the asteroid dinosaur extinction.' },
  { number: 78, symbol: 'Pt', name: 'Platinum', weight: 195.08, period: 6, group: 10, block: 'd', category: 'transition-metal', phase: 'solid', density: 21.45, melt: 2041.4, boil: 4098, electronegativity: 2.28, electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹', oxidationStates: [2, 4], ionizationEnergy: 870.0, atomicRadius: 177, discoverer: 'Antonio de Ulloa', year: 1735, summary: 'Noble transition metal; platinum complexes (Cisplatin, Carboplatin) are frontline chemotherapy drugs cross-linking cancer cell DNA.' },
  { number: 79, symbol: 'Au', name: 'Gold', weight: 196.97, period: 6, group: 11, block: 'd', category: 'transition-metal', phase: 'solid', density: 19.30, melt: 1337.33, boil: 3243, electronegativity: 2.54, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', oxidationStates: [1, 3], ionizationEnergy: 890.1, atomicRadius: 174, discoverer: 'Antiquity', year: 'Ancient', summary: 'Dense, malleable noble metal resistant to oxidation; world reserve currency standard and critical for microchip bonding wire connectors.' },
  { number: 80, symbol: 'Hg', name: 'Mercury', weight: 200.59, period: 6, group: 12, block: 'd', category: 'transition-metal', phase: 'liquid', density: 13.534, melt: 234.32, boil: 629.88, electronegativity: 2.00, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', oxidationStates: [1, 2], ionizationEnergy: 1007.1, atomicRadius: 171, discoverer: 'Antiquity', year: 'Ancient', summary: 'Only metallic element that is liquid at standard conditions; historic instrument fluid and precursor to toxic bioaccumulative methylmercury.' },
  { number: 81, symbol: 'Tl', name: 'Thallium', weight: 204.38, period: 6, group: 13, block: 'p', category: 'post-transition', phase: 'solid', density: 11.85, melt: 577, boil: 1746, electronegativity: 1.62, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', oxidationStates: [1, 3], ionizationEnergy: 589.4, atomicRadius: 156, discoverer: 'William Crookes', year: 1861, summary: 'Highly toxic post-transition metal mimicking potassium in biology; used in low-temperature infrared optical lenses and cardiology imaging.' },
  { number: 82, symbol: 'Pb', name: 'Lead', weight: 207.2, period: 6, group: 14, block: 'p', category: 'post-transition', phase: 'solid', density: 11.34, melt: 600.61, boil: 2022, electronegativity: 2.33, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', oxidationStates: [2, 4], ionizationEnergy: 715.6, atomicRadius: 154, discoverer: 'Antiquity', year: 'Ancient', summary: 'Dense heavy metal; final stable decay product of uranium and thorium radioactive decay chains; shields against X-rays and gamma rays.' },
  { number: 83, symbol: 'Bi', name: 'Bismuth', weight: 208.98, period: 6, group: 15, block: 'p', category: 'post-transition', phase: 'solid', density: 9.78, melt: 544.7, boil: 1837, electronegativity: 2.02, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', oxidationStates: [3, 5], ionizationEnergy: 703.0, atomicRadius: 143, discoverer: 'Claude François Geoffroy', year: 1753, summary: 'Heaviest non-toxic metal with vivid rainbow oxidation layers; bismuth subsalicylate (Pepto-Bismol) treats gastrointestinal disorders.' },
  { number: 84, symbol: 'Po', name: 'Polonium', weight: 209, period: 6, group: 16, block: 'p', category: 'metalloid', phase: 'solid', density: 9.196, melt: 527, boil: 1235, electronegativity: 2.0, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', oxidationStates: [2, 4], ionizationEnergy: 812.1, atomicRadius: 135, discoverer: 'Marie & Pierre Curie', year: 1898, summary: 'Intensely radioactive alpha-emitter named after Marie Curie’s homeland Poland; thermoelectric power source for Soviet Lunokhod lunar rovers.' },
  { number: 85, symbol: 'At', name: 'Astatine', weight: 210, period: 6, group: 17, block: 'p', category: 'halogen', phase: 'solid', density: 6.35, melt: 575, boil: 610, electronegativity: 2.2, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', oxidationStates: [-1, 1, 3, 5], ionizationEnergy: 890.0, atomicRadius: 127, discoverer: 'Corson, MacKenzie, Segrè', year: 1940, summary: 'Rarest naturally occurring element in Earth’s crust (<1 gram total); Astatine-211 is under intense trial for targeted alpha-particle cancer therapy.' },
  { number: 86, symbol: 'Rn', name: 'Radon', weight: 222, period: 6, group: 18, block: 'p', category: 'noble-gas', phase: 'gas', density: 9.73, melt: 202, boil: 211.3, electronegativity: 2.2, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', oxidationStates: [0, 2], ionizationEnergy: 1037.0, atomicRadius: 120, discoverer: 'Ernest Rutherford, Robert Owens', year: 1899, summary: 'Radioactive noble gas generated by uranium decay in soil; second leading cause of lung cancer globally due to airborne alpha daughter inhalation.' },

  // Period 7
  { number: 87, symbol: 'Fr', name: 'Francium', weight: 223, period: 7, group: 1, block: 's', category: 'alkali-metal', phase: 'solid', density: 1.87, melt: 300, boil: 950, electronegativity: 0.7, electronConfig: '[Rn] 7s¹', oxidationStates: [1], ionizationEnergy: 380.0, atomicRadius: 348, discoverer: 'Marguerite Perey', year: 1939, summary: 'Extremely unstable alkali metal with a half-life of only 22 minutes; studied via laser magneto-optical atom traps in nuclear physics.' },
  { number: 88, symbol: 'Ra', name: 'Radium', weight: 226, period: 7, group: 2, block: 's', category: 'alkaline-earth', phase: 'solid', density: 5.5, melt: 1233, boil: 2010, electronegativity: 0.9, electronConfig: '[Rn] 7s²', oxidationStates: [2], ionizationEnergy: 509.3, atomicRadius: 283, discoverer: 'Marie & Pierre Curie', year: 1898, summary: 'Historic luminescent radioactive alkaline earth metal; Radium-223 dichloride targets bone metastases in castrate-resistant prostate cancer.' },
  { number: 89, symbol: 'Ac', name: 'Actinium', weight: 227, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 10.07, melt: 1323, boil: 3473, electronegativity: 1.1, electronConfig: '[Rn] 6d¹ 7s²', oxidationStates: [3], ionizationEnergy: 499.0, atomicRadius: 215, discoverer: 'Friedrich Oskar Giesel', year: 1902, summary: 'First of the actinide series; Actinium-225 is the premier alpha-emitter in targeted targeted oncology (TAT).' },
  { number: 90, symbol: 'Th', name: 'Thorium', weight: 232.04, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 11.72, melt: 2023, boil: 5061, electronegativity: 1.3, electronConfig: '[Rn] 6d² 7s²', oxidationStates: [4], ionizationEnergy: 587.0, atomicRadius: 206, discoverer: 'Jöns Jacob Berzelius', year: 1829, summary: 'Three times more abundant than uranium; fertile nuclear fuel bred into fissile U-233 in next-generation molten salt reactors (MSR).' },
  { number: 91, symbol: 'Pa', name: 'Protactinium', weight: 231.04, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 15.37, melt: 1841, boil: 4300, electronegativity: 1.5, electronConfig: '[Rn] 5f² 6d¹ 7s²', oxidationStates: [4, 5], ionizationEnergy: 568.0, atomicRadius: 200, discoverer: 'Fajans, Gohring, Hahn, Meitner', year: 1913, summary: 'Dense radioactive actinide intermediate in the thorium nuclear fuel cycle, highly toxic and bioaccumulative.' },
  { number: 92, symbol: 'U', name: 'Uranium', weight: 238.03, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 19.1, melt: 1405.3, boil: 4404, electronegativity: 1.38, electronConfig: '[Rn] 5f³ 6d¹ 7s²', oxidationStates: [3, 4, 5, 6], ionizationEnergy: 597.6, atomicRadius: 196, discoverer: 'Martin Heinrich Klaproth', year: 1789, summary: 'Dense radioactive actinide; U-235 isotope undergoes thermal neutron-induced nuclear fission fueling commercial nuclear power plants.' },
  { number: 93, symbol: 'Np', name: 'Neptunium', weight: 237, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 20.45, melt: 917, boil: 4273, electronegativity: 1.36, electronConfig: '[Rn] 5f⁴ 6d¹ 7s²', oxidationStates: [3, 4, 5, 6, 7], ionizationEnergy: 604.5, atomicRadius: 190, discoverer: 'McMillan, Abelson', year: 1940, summary: 'First synthetic transuranic element; irradiated in reactors to synthesize pure Plutonium-238 for NASA deep-space radioisotope batteries.' },
  { number: 94, symbol: 'Pu', name: 'Plutonium', weight: 244, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 19.86, melt: 912.5, boil: 3505, electronegativity: 1.28, electronConfig: '[Rn] 5f⁶ 7s²', oxidationStates: [3, 4, 5, 6, 7], ionizationEnergy: 584.7, atomicRadius: 187, discoverer: 'Seaborg, McMillan, Kennedy, Wahl', year: 1940, summary: 'Fissile actinide; Pu-239 fuels nuclear weapons and fast breeder reactors; Pu-238 powers Voyager 1, Voyager 2, Curiosity, and Perseverance rovers.' },
  { number: 95, symbol: 'Am', name: 'Americium', weight: 243, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 12.0, melt: 1449, boil: 2880, electronegativity: 1.3, electronConfig: '[Rn] 5f⁷ 7s²', oxidationStates: [3, 4, 5, 6], ionizationEnergy: 578.0, atomicRadius: 180, discoverer: 'Seaborg, James, Morgan, Ghiorso', year: 1944, summary: 'Synthetic actinide; tiny microgram quantities of Americium-241 ionize air in residential ionization smoke detectors saving millions of lives.' },
  { number: 96, symbol: 'Cm', name: 'Curium', weight: 247, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 13.51, melt: 1613, boil: 3383, electronegativity: 1.3, electronConfig: '[Rn] 5f⁷ 6d¹ 7s²', oxidationStates: [3, 4], ionizationEnergy: 581.0, atomicRadius: 169, discoverer: 'Seaborg, James, Ghiorso', year: 1944, summary: 'Hard radioactive actinide named in honor of Marie and Pierre Curie; alpha particle X-ray spectrometers on Mars rovers analyze planetary rocks.' },
  { number: 97, symbol: 'Bk', name: 'Berkelium', weight: 247, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 14.78, melt: 1259, boil: 2900, electronegativity: 1.3, electronConfig: '[Rn] 5f⁹ 7s²', oxidationStates: [3, 4], ionizationEnergy: 601.0, atomicRadius: 170, discoverer: 'Lawrence Berkeley National Lab', year: 1949, summary: 'Synthesized by bombarding americium with alpha particles; target material used to discover tennessine (element 117).' },
  { number: 98, symbol: 'Cf', name: 'Californium', weight: 251, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 15.1, melt: 1173, boil: 1743, electronegativity: 1.3, electronConfig: '[Rn] 5f¹⁰ 7s²', oxidationStates: [2, 3, 4], ionizationEnergy: 608.0, atomicRadius: 168, discoverer: 'Lawrence Berkeley National Lab', year: 1950, summary: 'Extremely potent neutron emitter; Californium-252 is used for neutron radiography startup sources for reactors and luggage explosives detection.' },
  { number: 99, symbol: 'Es', name: 'Einsteinium', weight: 252, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 8.84, melt: 1133, boil: 1269, electronegativity: 1.3, electronConfig: '[Rn] 5f¹¹ 7s²', oxidationStates: [2, 3], ionizationEnergy: 619.0, atomicRadius: 165, discoverer: 'Albert Ghiorso et al.', year: 1952, summary: 'Discovered in the radioactive debris of the Ivy Mike thermonuclear hydrogen bomb explosion; named in honor of Albert Einstein.' },
  { number: 100, symbol: 'Fm', name: 'Fermium', weight: 257, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 9.7, melt: 1800, boil: null, electronegativity: 1.3, electronConfig: '[Rn] 5f¹² 7s²', oxidationStates: [2, 3], ionizationEnergy: 627.0, atomicRadius: 167, discoverer: 'Albert Ghiorso et al.', year: 1952, summary: 'Heaviest element that can be produced by neutron bombardment; named after nuclear pioneer Enrico Fermi.' },
  { number: 101, symbol: 'Md', name: 'Mendelevium', weight: 258, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 10.3, melt: 1100, boil: null, electronegativity: 1.3, electronConfig: '[Rn] 5f¹³ 7s²', oxidationStates: [2, 3], ionizationEnergy: 635.0, atomicRadius: 173, discoverer: 'Albert Ghiorso et al.', year: 1955, summary: 'Synthesized one atom at a time; named after Dmitri Mendeleev, father of the Periodic Table.' },
  { number: 102, symbol: 'No', name: 'Nobelium', weight: 259, period: 7, group: 3, block: 'f', category: 'actinide', phase: 'solid', density: 9.9, melt: 1100, boil: null, electronegativity: 1.3, electronConfig: '[Rn] 5f¹⁴ 7s²', oxidationStates: [2, 3], ionizationEnergy: 642.0, atomicRadius: 176, discoverer: 'Joint Institute for Nuclear Research / Berkeley', year: 1966, summary: 'Named after Alfred Nobel; exhibits an unusually stable divalent (+2) oxidation state in aqueous solution due to a closed 5f¹⁴ subshell.' },
  { number: 103, symbol: 'Lr', name: 'Lawrencium', weight: 266, period: 7, group: 3, block: 'd', category: 'actinide', phase: 'solid', density: 15.6, melt: 1900, boil: null, electronegativity: 1.3, electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹', oxidationStates: [3], ionizationEnergy: 470.0, atomicRadius: 161, discoverer: 'Albert Ghiorso et al.', year: 1961, summary: 'Final actinide element; named after Ernest O. Lawrence, inventor of the cyclotron particle accelerator.' },
  { number: 104, symbol: 'Rf', name: 'Rutherfordium', weight: 267, period: 7, group: 4, block: 'd', category: 'transition-metal', phase: 'solid', density: 23.2, melt: 2400, boil: 5800, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d² 7s²', oxidationStates: [4], ionizationEnergy: 580.0, atomicRadius: 157, discoverer: 'JINR (Dubna) & Berkeley', year: 1969, summary: 'First transactinide superheavy 6d-transition metal; named after Ernest Rutherford.' },
  { number: 105, symbol: 'Db', name: 'Dubnium', weight: 268, period: 7, group: 5, block: 'd', category: 'transition-metal', phase: 'solid', density: 29.3, melt: null, boil: null, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²', oxidationStates: [5], ionizationEnergy: null, atomicRadius: 149, discoverer: 'JINR (Dubna) & Berkeley', year: 1970, summary: 'Superheavy group 5 element; named after the Russian nuclear research center in Dubna.' },
  { number: 106, symbol: 'Sg', name: 'Seaborgium', weight: 269, period: 7, group: 6, block: 'd', category: 'transition-metal', phase: 'solid', density: 35.0, melt: null, boil: null, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²', oxidationStates: [6], ionizationEnergy: null, atomicRadius: 143, discoverer: 'Lawrence Berkeley National Lab', year: 1974, summary: 'Named after Glenn T. Seaborg, the first living scientist to have an element named in his honor.' },
  { number: 107, symbol: 'Bh', name: 'Bohrium', weight: 270, period: 7, group: 7, block: 'd', category: 'transition-metal', phase: 'solid', density: 37.1, melt: null, boil: null, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²', oxidationStates: [7], ionizationEnergy: null, atomicRadius: 141, discoverer: 'GSI Helmholtz Centre (Germany)', year: 1981, summary: 'Named after Danish quantum physicist Niels Bohr; forms volatile oxychloride compounds analogous to rhenium.' },
  { number: 108, symbol: 'Hs', name: 'Hassium', weight: 277, period: 7, group: 8, block: 'd', category: 'transition-metal', phase: 'solid', density: 40.7, melt: null, boil: null, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²', oxidationStates: [8], ionizationEnergy: null, atomicRadius: 134, discoverer: 'GSI Helmholtz Centre (Germany)', year: 1984, summary: 'Forms hassium tetroxide (HsO4); named after the German state of Hesse (Hassia).' },
  { number: 109, symbol: 'Mt', name: 'Meitnerium', weight: 278, period: 7, group: 9, block: 'd', category: 'transition-metal', phase: 'solid', density: 37.4, melt: null, boil: null, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²', oxidationStates: [1, 3, 9], ionizationEnergy: null, atomicRadius: 129, discoverer: 'GSI Helmholtz Centre (Germany)', year: 1982, summary: 'Named in honor of Austrian physicist Lise Meitner, co-discoverer of nuclear fission.' },
  { number: 110, symbol: 'Ds', name: 'Darmstadtium', weight: 281, period: 7, group: 10, block: 'd', category: 'transition-metal', phase: 'solid', density: 34.8, melt: null, boil: null, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²', oxidationStates: [6, 8], ionizationEnergy: null, atomicRadius: 128, discoverer: 'GSI Helmholtz Centre (Germany)', year: 1994, summary: 'Superheavy group 10 metal synthesized by fusing nickel-64 with lead-208.' },
  { number: 111, symbol: 'Rg', name: 'Roentgenium', weight: 282, period: 7, group: 11, block: 'd', category: 'transition-metal', phase: 'solid', density: 28.7, melt: null, boil: null, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s²', oxidationStates: [3, 5], ionizationEnergy: null, atomicRadius: 121, discoverer: 'GSI Helmholtz Centre (Germany)', year: 1994, summary: 'Superheavy coinage metal named in honor of Wilhelm Röntgen, discoverer of X-rays.' },
  { number: 112, symbol: 'Cn', name: 'Copernicium', weight: 285, period: 7, group: 12, block: 'd', category: 'transition-metal', phase: 'liquid', density: 23.7, melt: 283, boil: 340, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', oxidationStates: [2], ionizationEnergy: null, atomicRadius: 122, discoverer: 'GSI Helmholtz Centre (Germany)', year: 1996, summary: 'Relativistic effects make it a volatile liquid metal at room temperature; named after astronomer Nicolaus Copernicus.' },
  { number: 113, symbol: 'Nh', name: 'Nihonium', weight: 286, period: 7, group: 13, block: 'p', category: 'post-transition', phase: 'solid', density: 16.0, melt: 700, boil: 1400, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', oxidationStates: [1, 3], ionizationEnergy: null, atomicRadius: 136, discoverer: 'RIKEN (Japan)', year: 2004, summary: 'First chemical element discovered in Asia; named after Nihon (Japan).' },
  { number: 114, symbol: 'Fl', name: 'Flerovium', weight: 289, period: 7, group: 14, block: 'p', category: 'post-transition', phase: 'solid', density: 14.0, melt: 200, boil: 380, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', oxidationStates: [2, 4], ionizationEnergy: null, atomicRadius: 143, discoverer: 'JINR (Dubna) & LLNL', year: 1998, summary: 'Located in the theoretical "island of nuclear stability"; named after the Flerov Laboratory of Nuclear Reactions.' },
  { number: 115, symbol: 'Mc', name: 'Moscovium', weight: 290, period: 7, group: 15, block: 'p', category: 'post-transition', phase: 'solid', density: 13.5, melt: 670, boil: 1400, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', oxidationStates: [1, 3], ionizationEnergy: null, atomicRadius: 162, discoverer: 'JINR (Dubna), LLNL, ORNL', year: 2003, summary: 'Synthesized by bombarding americium-243 with calcium-48; named in honor of the Moscow region.' },
  { number: 116, symbol: 'Lv', name: 'Livermorium', weight: 293, period: 7, group: 16, block: 'p', category: 'post-transition', phase: 'solid', density: 12.9, melt: 700, boil: 1100, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', oxidationStates: [2, 4], ionizationEnergy: null, atomicRadius: 175, discoverer: 'JINR (Dubna) & LLNL', year: 2000, summary: 'Named after the Lawrence Livermore National Laboratory in California.' },
  { number: 117, symbol: 'Ts', name: 'Tennessine', weight: 294, period: 7, group: 17, block: 'p', category: 'halogen', phase: 'solid', density: 7.2, melt: 723, boil: 883, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', oxidationStates: [-1, 1, 3], ionizationEnergy: null, atomicRadius: 165, discoverer: 'JINR (Dubna), LLNL, ORNL, Vanderbilt', year: 2010, summary: 'Superheavy halogen; named after the state of Tennessee, home to Oak Ridge National Laboratory.' },
  { number: 118, symbol: 'Og', name: 'Oganesson', weight: 294, period: 7, group: 18, block: 'p', category: 'noble-gas', phase: 'solid', density: 5.0, melt: 325, boil: 350, electronegativity: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', oxidationStates: [0, 2, 4], ionizationEnergy: null, atomicRadius: 157, discoverer: 'JINR (Dubna) & LLNL', year: 2002, summary: 'Heaviest known chemical element with Z=118; predicted to be a solid rather than gas due to relativistic electron spin-orbit coupling. Named after Yuri Oganessian.' },
];

/**
 * Comprehensive Chemical & Pharmaceutical Compound Database
 */
/**
 * Comprehensive Chemical & Pharmaceutical Compound Database (1,050+ verified entries)
 */
export const COMMON_COMPOUNDS = COMPOUNDS_DATA;
