/* Device database schema.
   Every category lists its fields once: key, label, unit, which direction is better
   ('high' | 'low' | null), the spec group it is shown under, and its type.
   Types: num | text | bool | list (array of strings) | nums (array of numbers). */

const f = (key, label, unit, better, group, type = 'num') => ({ key, label, unit, better, group, type });

const COMMON = [
  f('brand', 'Brand', '', null, 'Overview', 'text'),
  f('released', 'Released', '', 'high', 'Overview', 'text'),     // 'YYYY-MM'
  f('price', 'Launch price', 'USD', 'low', 'Overview'),
];

export const CATEGORIES = {
  phones: {
    label: 'Phones', singular: 'phone',
    fields: [
      ...COMMON,
      f('os', 'Operating system', '', null, 'Overview', 'text'),
      f('updates', 'OS update promise', 'years', 'high', 'Overview'),
      f('chip', 'Chipset', '', null, 'Performance', 'text'),
      f('chipId', 'Chipset id', '', null, 'Performance', 'text'),
      f('cpu', 'CPU', '', null, 'Performance', 'text'),
      f('gpu', 'GPU', '', null, 'Performance', 'text'),
      f('ram', 'RAM', 'GB', 'high', 'Performance'),
      f('storage', 'Storage options', 'GB', 'high', 'Performance', 'nums'),
      f('sd', 'Memory card slot', '', 'high', 'Performance', 'bool'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('antutu', 'AnTuTu 10', '', 'high', 'Benchmarks'),
      f('displaySize', 'Screen size', 'in', 'high', 'Display'),
      f('displayRes', 'Resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Panel', '', null, 'Display', 'text'),
      f('refresh', 'Refresh rate', 'Hz', 'high', 'Display'),
      f('nits', 'Peak brightness', 'nits', 'high', 'Display'),
      f('ppi', 'Pixel density', 'ppi', 'high', 'Display'),
      f('protection', 'Screen protection', '', null, 'Display', 'text'),
      f('camMain', 'Main camera', 'MP', 'high', 'Camera'),
      f('camMainSensor', 'Main sensor size', '', null, 'Camera', 'text'),
      f('camMainAperture', 'Main aperture', 'f/', 'low', 'Camera'),
      f('ois', 'Optical stabilisation', '', 'high', 'Camera', 'bool'),
      f('camUltra', 'Ultra-wide camera', 'MP', 'high', 'Camera'),
      f('camTele', 'Telephoto camera', 'MP', 'high', 'Camera'),
      f('teleZoom', 'Optical zoom', 'x', 'high', 'Camera'),
      f('camFront', 'Selfie camera', 'MP', 'high', 'Camera'),
      f('video', 'Max video', '', null, 'Camera', 'text'),
      f('battery', 'Battery', 'mAh', 'high', 'Battery'),
      f('wired', 'Wired charging', 'W', 'high', 'Battery'),
      f('wireless', 'Wireless charging', 'W', 'high', 'Battery'),
      f('reverse', 'Reverse wireless charging', '', 'high', 'Battery', 'bool'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('thickness', 'Thickness', 'mm', 'low', 'Design'),
      f('dimensions', 'Dimensions', 'mm', null, 'Design', 'text'),
      f('ip', 'Water resistance', '', null, 'Design', 'text'),
      f('materials', 'Materials', '', null, 'Design', 'text'),
      f('fingerprint', 'Fingerprint', '', null, 'Design', 'text'),
      f('fiveG', '5G', '', 'high', 'Connectivity', 'bool'),
      f('wifi', 'Wi-Fi', '', null, 'Connectivity', 'text'),
      f('bt', 'Bluetooth', '', 'high', 'Connectivity'),
      f('usb', 'USB', '', null, 'Connectivity', 'text'),
      f('nfc', 'NFC', '', 'high', 'Connectivity', 'bool'),
      f('esim', 'eSIM', '', 'high', 'Connectivity', 'bool'),
      f('jack', 'Headphone jack', '', 'high', 'Connectivity', 'bool'),
      f('speakers', 'Speakers', '', null, 'Connectivity', 'text'),
    ],
  },
  tablets: {
    label: 'Tablets', singular: 'tablet',
    fields: [
      ...COMMON,
      f('os', 'Operating system', '', null, 'Overview', 'text'),
      f('chip', 'Chipset', '', null, 'Performance', 'text'),
      f('chipId', 'Chipset id', '', null, 'Performance', 'text'),
      f('ram', 'RAM', 'GB', 'high', 'Performance'),
      f('storage', 'Storage options', 'GB', 'high', 'Performance', 'nums'),
      f('sd', 'Memory card slot', '', 'high', 'Performance', 'bool'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('antutu', 'AnTuTu 10', '', 'high', 'Benchmarks'),
      f('displaySize', 'Screen size', 'in', 'high', 'Display'),
      f('displayRes', 'Resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Panel', '', null, 'Display', 'text'),
      f('refresh', 'Refresh rate', 'Hz', 'high', 'Display'),
      f('nits', 'Peak brightness', 'nits', 'high', 'Display'),
      f('ppi', 'Pixel density', 'ppi', 'high', 'Display'),
      f('camMain', 'Rear camera', 'MP', 'high', 'Camera'),
      f('camFront', 'Front camera', 'MP', 'high', 'Camera'),
      f('video', 'Max video', '', null, 'Camera', 'text'),
      f('battery', 'Battery', 'mAh', 'high', 'Battery'),
      f('wired', 'Wired charging', 'W', 'high', 'Battery'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('thickness', 'Thickness', 'mm', 'low', 'Design'),
      f('stylus', 'Stylus support', '', null, 'Design', 'text'),
      f('keyboard', 'Keyboard accessory', '', null, 'Design', 'text'),
      f('cellular', 'Cellular option', '', 'high', 'Connectivity', 'bool'),
      f('wifi', 'Wi-Fi', '', null, 'Connectivity', 'text'),
      f('usb', 'USB', '', null, 'Connectivity', 'text'),
      f('speakers', 'Speakers', '', null, 'Connectivity', 'text'),
      f('jack', 'Headphone jack', '', 'high', 'Connectivity', 'bool'),
    ],
  },
  laptops: {
    label: 'Laptops', singular: 'laptop',
    fields: [
      ...COMMON,
      f('os', 'Operating system', '', null, 'Overview', 'text'),
      f('type', 'Type', '', null, 'Overview', 'text'),            // ultrabook, gaming, 2-in-1, workstation, chromebook
      f('cpu', 'Processor', '', null, 'Performance', 'text'),
      f('cpuId', 'Processor id', '', null, 'Performance', 'text'),
      f('gpu', 'Graphics', '', null, 'Performance', 'text'),
      f('gpuId', 'Graphics id', '', null, 'Performance', 'text'),
      f('ram', 'RAM', 'GB', 'high', 'Performance'),
      f('ramMax', 'Max RAM', 'GB', 'high', 'Performance'),
      f('ramType', 'Memory type', '', null, 'Performance', 'text'),
      f('storage', 'Storage', 'GB', 'high', 'Performance'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('displaySize', 'Screen size', 'in', 'high', 'Display'),
      f('displayRes', 'Resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Panel', '', null, 'Display', 'text'),
      f('refresh', 'Refresh rate', 'Hz', 'high', 'Display'),
      f('nits', 'Brightness', 'nits', 'high', 'Display'),
      f('touch', 'Touchscreen', '', 'high', 'Display', 'bool'),
      f('batteryWh', 'Battery', 'Wh', 'high', 'Battery'),
      f('batteryLife', 'Rated battery life', 'h', 'high', 'Battery'),
      f('charger', 'Charger', 'W', 'high', 'Battery'),
      f('weight', 'Weight', 'kg', 'low', 'Design'),
      f('thickness', 'Thickness', 'mm', 'low', 'Design'),
      f('materials', 'Materials', '', null, 'Design', 'text'),
      f('webcam', 'Webcam', '', null, 'Design', 'text'),
      f('keyboard', 'Keyboard', '', null, 'Design', 'text'),
      f('ports', 'Ports', '', null, 'Connectivity', 'text'),
      f('wifi', 'Wi-Fi', '', null, 'Connectivity', 'text'),
      f('bt', 'Bluetooth', '', 'high', 'Connectivity'),
    ],
  },
  socs: {
    label: 'Mobile chips', singular: 'chip',
    fields: [
      ...COMMON.filter(x => x.key !== 'price'),
      f('node', 'Process', '', null, 'Overview', 'text'),
      f('transistors', 'Transistors', 'billion', 'high', 'Overview'),
      f('cores', 'CPU cores', '', 'high', 'CPU'),
      f('cpu', 'CPU layout', '', null, 'CPU', 'text'),
      f('maxClock', 'Max clock', 'GHz', 'high', 'CPU'),
      f('arch', 'Architecture', '', null, 'CPU', 'text'),
      f('gpu', 'GPU', '', null, 'Graphics', 'text'),
      f('gpuCores', 'GPU cores', '', 'high', 'Graphics'),
      f('gpuClock', 'GPU clock', 'MHz', 'high', 'Graphics'),
      f('npu', 'NPU', 'TOPS', 'high', 'AI'),
      f('memory', 'Memory', '', null, 'Memory', 'text'),
      f('modem', 'Modem', '', null, 'Connectivity', 'text'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('antutu', 'AnTuTu 10', '', 'high', 'Benchmarks'),
      f('wildlife', '3DMark Wild Life Extreme', '', 'high', 'Benchmarks'),
      f('usedIn', 'Found in', '', null, 'Overview', 'list'),
    ],
  },
  cpus: {
    label: 'Processors', singular: 'processor',
    fields: [
      ...COMMON,
      f('segment', 'Segment', '', null, 'Overview', 'text'),        // Desktop | Laptop | Workstation
      f('socket', 'Socket', '', null, 'Overview', 'text'),
      f('node', 'Process', '', null, 'Overview', 'text'),
      f('arch', 'Architecture', '', null, 'Overview', 'text'),
      f('cores', 'Cores', '', 'high', 'Cores'),
      f('threads', 'Threads', '', 'high', 'Cores'),
      f('pcores', 'Performance cores', '', 'high', 'Cores'),
      f('ecores', 'Efficiency cores', '', 'high', 'Cores'),
      f('baseClock', 'Base clock', 'GHz', 'high', 'Clocks'),
      f('boostClock', 'Boost clock', 'GHz', 'high', 'Clocks'),
      f('l3', 'L3 cache', 'MB', 'high', 'Clocks'),
      f('tdp', 'TDP', 'W', 'low', 'Power'),
      f('maxPower', 'Max turbo power', 'W', 'low', 'Power'),
      f('memory', 'Memory support', '', null, 'Platform', 'text'),
      f('pcie', 'PCIe', '', 'high', 'Platform'),
      f('igpu', 'Integrated graphics', '', null, 'Platform', 'text'),
      f('npu', 'NPU', 'TOPS', 'high', 'Platform'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('cb24s', 'Cinebench 2024 single', '', 'high', 'Benchmarks'),
      f('cb24m', 'Cinebench 2024 multi', '', 'high', 'Benchmarks'),
    ],
  },
  gpus: {
    label: 'Graphics cards', singular: 'graphics card',
    fields: [
      ...COMMON,
      f('segment', 'Segment', '', null, 'Overview', 'text'),        // Desktop | Laptop | Workstation
      f('arch', 'Architecture', '', null, 'Overview', 'text'),
      f('node', 'Process', '', null, 'Overview', 'text'),
      f('shaders', 'Shader units', '', 'high', 'Core'),
      f('rtCores', 'RT cores / units', '', 'high', 'Core'),
      f('tensor', 'AI / tensor cores', '', 'high', 'Core'),
      f('baseClock', 'Base clock', 'MHz', 'high', 'Core'),
      f('boostClock', 'Boost clock', 'MHz', 'high', 'Core'),
      f('tflops', 'FP32 compute', 'TFLOPS', 'high', 'Core'),
      f('vram', 'Memory', 'GB', 'high', 'Memory'),
      f('memType', 'Memory type', '', null, 'Memory', 'text'),
      f('bus', 'Memory bus', 'bit', 'high', 'Memory'),
      f('bandwidth', 'Bandwidth', 'GB/s', 'high', 'Memory'),
      f('tdp', 'Board power', 'W', 'low', 'Power'),
      f('connector', 'Power connector', '', null, 'Power', 'text'),
      f('pcie', 'Interface', '', null, 'Power', 'text'),
      f('outputs', 'Outputs', '', null, 'Power', 'text'),
      f('upscaler', 'Upscaling', '', null, 'Features', 'text'),
      f('timespy', '3DMark Time Spy graphics', '', 'high', 'Benchmarks'),
      f('steelnomad', '3DMark Steel Nomad', '', 'high', 'Benchmarks'),
    ],
  },
  watches: {
    label: 'Smartwatches', singular: 'watch',
    fields: [
      ...COMMON,
      f('os', 'Platform', '', null, 'Overview', 'text'),
      f('compat', 'Works with', '', null, 'Overview', 'text'),
      f('chip', 'Chipset', '', null, 'Performance', 'text'),
      f('ram', 'RAM', 'GB', 'high', 'Performance'),
      f('storage', 'Storage', 'GB', 'high', 'Performance'),
      f('caseSize', 'Case size', 'mm', null, 'Design', 'text'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('materials', 'Case material', '', null, 'Design', 'text'),
      f('water', 'Water rating', '', null, 'Design', 'text'),
      f('displaySize', 'Screen size', 'in', 'high', 'Display'),
      f('displayRes', 'Resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Panel', '', null, 'Display', 'text'),
      f('nits', 'Peak brightness', 'nits', 'high', 'Display'),
      f('aod', 'Always-on display', '', 'high', 'Display', 'bool'),
      f('batteryDays', 'Battery life', 'days', 'high', 'Battery'),
      f('battery', 'Battery', 'mAh', 'high', 'Battery'),
      f('sensors', 'Health sensors', '', null, 'Health', 'list'),
      f('ecg', 'ECG', '', 'high', 'Health', 'bool'),
      f('spo2', 'Blood oxygen', '', 'high', 'Health', 'bool'),
      f('gps', 'GPS', '', null, 'Connectivity', 'text'),
      f('lte', 'LTE option', '', 'high', 'Connectivity', 'bool'),
      f('nfc', 'Payments (NFC)', '', 'high', 'Connectivity', 'bool'),
    ],
  },
  audio: {
    label: 'Headphones & earbuds', singular: 'headphone',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),              // Earbuds | Over-ear | On-ear | Open-ear
      f('anc', 'Active noise cancelling', '', 'high', 'Sound', 'bool'),
      f('driver', 'Driver size', 'mm', 'high', 'Sound'),
      f('driverType', 'Driver type', '', null, 'Sound', 'text'),
      f('codecs', 'Codecs', '', null, 'Sound', 'list'),
      f('spatial', 'Spatial audio', '', 'high', 'Sound', 'bool'),
      f('hires', 'Hi-Res wireless', '', 'high', 'Sound', 'bool'),
      f('battery', 'Battery (ANC on)', 'h', 'high', 'Battery'),
      f('batteryTotal', 'Battery with case', 'h', 'high', 'Battery'),
      f('wirelessCharging', 'Wireless charging', '', 'high', 'Battery', 'bool'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('water', 'Water resistance', '', null, 'Design', 'text'),
      f('bt', 'Bluetooth', '', 'high', 'Connectivity'),
      f('multipoint', 'Multipoint', '', 'high', 'Connectivity', 'bool'),
      f('mics', 'Microphones', '', 'high', 'Connectivity'),
      f('wired', 'Wired / USB audio', '', null, 'Connectivity', 'text'),
    ],
  },
  consoles: {
    label: 'Consoles & handhelds', singular: 'console',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),              // Home console | Handheld | Hybrid | Handheld PC
      f('cpu', 'CPU', '', null, 'Performance', 'text'),
      f('gpu', 'GPU', '', null, 'Performance', 'text'),
      f('tflops', 'GPU compute', 'TFLOPS', 'high', 'Performance'),
      f('ram', 'Memory', 'GB', 'high', 'Performance'),
      f('storage', 'Storage', 'GB', 'high', 'Performance'),
      f('maxRes', 'Max output', '', null, 'Display', 'text'),
      f('maxFps', 'Max frame rate', 'fps', 'high', 'Display'),
      f('displaySize', 'Built-in screen', 'in', 'high', 'Display'),
      f('displayRes', 'Screen resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Screen panel', '', null, 'Display', 'text'),
      f('refresh', 'Screen refresh', 'Hz', 'high', 'Display'),
      f('batteryWh', 'Battery', 'Wh', 'high', 'Battery'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('media', 'Disc drive', '', null, 'Design', 'text'),
      f('connectivity', 'Connectivity', '', null, 'Design', 'text'),
    ],
  },
  tvs: {
    label: 'TVs', singular: 'TV',
    fields: [
      ...COMMON,
      f('series', 'Series', '', null, 'Overview', 'text'),
      f('os', 'Smart platform', '', null, 'Overview', 'text'),
      f('processor', 'Picture processor', '', null, 'Overview', 'text'),
      f('panel', 'Panel', '', null, 'Picture', 'text'),
      f('displaySize', 'Screen size', 'in', 'high', 'Picture'),
      f('displayRes', 'Resolution', 'px', null, 'Picture', 'text'),
      f('dimming', 'Dimming', '', null, 'Picture', 'text'),
      f('zones', 'Local dimming zones', '', 'high', 'Picture'),
      f('dciP3', 'DCI-P3 coverage', '%', 'high', 'Picture'),
      f('nits', 'Peak HDR brightness', 'nits', 'high', 'HDR'),
      f('hdr', 'HDR formats', '', null, 'HDR', 'list'),
      f('refresh', 'Native refresh rate', 'Hz', 'high', 'Gaming'),
      f('inputLag', 'Input lag (4K 60 Hz)', 'ms', 'low', 'Gaming'),
      f('hdmi21', 'HDMI 2.1 ports', '', 'high', 'Gaming'),
      f('vrr', 'Variable refresh rate', '', null, 'Gaming', 'list'),
      f('audio', 'Speakers', '', null, 'Audio', 'text'),
      f('audioW', 'Speaker power', 'W', 'high', 'Audio'),
      f('atmos', 'Dolby Atmos', '', 'high', 'Audio', 'bool'),
      f('hdmi', 'HDMI ports', '', 'high', 'Connectivity'),
      f('wifi', 'Wi-Fi', '', null, 'Connectivity', 'text'),
      f('vesa', 'VESA mount', 'mm', null, 'Design', 'text'),
      f('weight', 'Weight (without stand)', 'kg', null, 'Design'),
      f('power', 'Typical power (SDR)', 'W', 'low', 'Design'),
    ],
  },
  monitors: {
    label: 'Monitors', singular: 'monitor',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),              // Gaming OLED | Gaming | Esports | Productivity | Professional
      f('panel', 'Panel', '', null, 'Picture', 'text'),
      f('displaySize', 'Screen size', 'in', 'high', 'Picture'),
      f('displayRes', 'Resolution', 'px', null, 'Picture', 'text'),
      f('aspect', 'Aspect ratio', '', null, 'Picture', 'text'),
      f('ppi', 'Pixel density', 'ppi', 'high', 'Picture'),
      f('curve', 'Curvature', '', null, 'Picture', 'text'),
      f('zones', 'Local dimming zones', '', 'high', 'Picture'),
      f('dciP3', 'DCI-P3 coverage', '%', 'high', 'Picture'),
      f('nits', 'Peak brightness (HDR)', 'nits', 'high', 'HDR'),
      f('sdrNits', 'Typical brightness (SDR)', 'nits', 'high', 'HDR'),
      f('hdrCert', 'HDR certification', '', null, 'HDR', 'text'),
      f('refresh', 'Refresh rate', 'Hz', 'high', 'Motion'),
      f('response', 'Response time (GtG)', 'ms', 'low', 'Motion'),
      f('vrr', 'Variable refresh rate', '', null, 'Motion', 'list'),
      f('dp', 'DisplayPort', '', null, 'Connectivity', 'text'),
      f('hdmi', 'HDMI', '', null, 'Connectivity', 'text'),
      f('usbPd', 'USB-C power delivery', 'W', 'high', 'Connectivity'),
      f('kvm', 'KVM switch', '', 'high', 'Connectivity', 'bool'),
      f('speakers', 'Built-in speakers', '', 'high', 'Connectivity', 'bool'),
      f('stand', 'Stand adjustment', '', null, 'Design', 'text'),
      f('vesa', 'VESA mount', 'mm', null, 'Design', 'text'),
      f('weight', 'Weight (with stand)', 'kg', null, 'Design'),
    ],
  },
  guitars: {
    label: 'Electric guitars', singular: 'guitar',
    note: 'Scores rate features and versatility (pickup layout, coil split, frets, hardware), not tone or feel. Try guitars in person before buying.',
    fields: [
      ...COMMON,
      f('series', 'Series', '', null, 'Overview', 'text'),
      f('madeIn', 'Made in', '', null, 'Overview', 'text'),
      f('shape', 'Body shape', '', null, 'Body', 'text'),
      f('construction', 'Construction', '', null, 'Body', 'text'),       // Solid body | Semi-hollow | Hollow body
      f('body', 'Body wood', '', null, 'Body', 'text'),
      f('top', 'Top', '', null, 'Body', 'text'),
      f('weight', 'Typical weight', 'kg', 'low', 'Body'),
      f('neck', 'Neck wood', '', null, 'Neck', 'text'),
      f('neckJoint', 'Neck joint', '', null, 'Neck', 'text'),            // Bolt-on | Set neck | Neck-through
      f('neckProfile', 'Neck profile', '', null, 'Neck', 'text'),
      f('fretboard', 'Fretboard', '', null, 'Neck', 'text'),
      f('radius', 'Fretboard radius', '', null, 'Neck', 'text'),
      f('frets', 'Frets', '', 'high', 'Neck'),
      f('scale', 'Scale length', 'in', null, 'Neck'),
      f('nut', 'Nut width', 'mm', null, 'Neck'),
      f('strings', 'Strings', '', null, 'Neck'),
      f('pickups', 'Pickup layout', '', null, 'Electronics', 'text'),     // SSS | HSS | HH | P90 …
      f('pickupModels', 'Pickups', '', null, 'Electronics', 'text'),
      f('active', 'Active pickups', '', null, 'Electronics', 'bool'),
      f('coilSplit', 'Coil split / tap', '', 'high', 'Electronics', 'bool'),
      f('controls', 'Controls', '', null, 'Electronics', 'text'),
      f('bridge', 'Bridge', '', null, 'Hardware', 'text'),
      f('tremolo', 'Tremolo', '', 'high', 'Hardware', 'bool'),
      f('lockingTuners', 'Locking tuners', '', 'high', 'Hardware', 'bool'),
      f('case', 'Case or gig bag', '', null, 'Hardware', 'text'),
    ],
  },
  keyboards: {
    label: 'Keyboards & pianos', singular: 'keyboard',
    note: 'Speaker output is total wattage. MIDI controllers make no sound of their own, so their sound score is left blank.',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),                    // Digital piano | Stage piano | Arranger | Synthesizer | Workstation | MIDI controller
      f('keys', 'Keys', '', 'high', 'Keys'),
      f('action', 'Key action', '', null, 'Keys', 'text'),
      f('weighted', 'Weighted keys', '', 'high', 'Keys', 'bool'),
      f('touchLevels', 'Touch sensitivity levels', '', 'high', 'Keys'),
      f('aftertouch', 'Aftertouch', '', 'high', 'Keys', 'bool'),
      f('engine', 'Sound engine', '', null, 'Sound', 'text'),
      f('polyphony', 'Max polyphony', 'notes', 'high', 'Sound'),
      f('voices', 'Voices / presets', '', 'high', 'Sound'),
      f('rhythms', 'Rhythms / styles', '', 'high', 'Sound'),
      f('speakers', 'Speaker output', 'W', 'high', 'Sound'),
      f('sequencer', 'Recorder / sequencer', '', null, 'Features', 'text'),
      f('display', 'Display', '', null, 'Features', 'text'),
      f('lessons', 'Learning features', '', null, 'Features', 'text'),
      f('bluetooth', 'Bluetooth audio / MIDI', '', 'high', 'Connectivity', 'bool'),
      f('usb', 'USB', '', null, 'Connectivity', 'text'),
      f('outputs', 'Audio outputs', '', null, 'Connectivity', 'text'),
      f('pedals', 'Pedals', '', null, 'Connectivity', 'text'),
      f('battery', 'Battery power', '', 'high', 'Design', 'bool'),
      f('weight', 'Weight', 'kg', 'low', 'Design'),
      f('dimensions', 'Dimensions', 'mm', null, 'Design', 'text'),
    ],
  },
  coffee: {
    label: 'Coffee makers', singular: 'coffee maker',
    note: "Pump pressure is the maker's rating; good espresso extracts at about 9 bar whatever the pump is rated at. Drip and pod machines are scored on convenience and capacity.",
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),                    // Espresso | Bean-to-cup | Drip | Pod | Pour-over | Cold brew
      f('pressure', 'Pump pressure', 'bar', 'high', 'Brewing'),
      f('heating', 'Heating system', '', null, 'Brewing', 'text'),
      f('heatUp', 'Heat-up time', 's', 'low', 'Brewing'),
      f('pid', 'PID temperature control', '', 'high', 'Brewing', 'bool'),
      f('grinder', 'Built-in grinder', '', 'high', 'Brewing', 'bool'),
      f('grindSettings', 'Grind settings', '', 'high', 'Brewing'),
      f('milk', 'Milk system', '', null, 'Milk', 'text'),
      f('autoMilk', 'Automatic milk', '', 'high', 'Milk', 'bool'),
      f('drinks', 'Preset drinks', '', 'high', 'Features'),
      f('cups', 'Carafe / batch', 'cups', 'high', 'Features'),
      f('programmable', 'Programmable / timer', '', 'high', 'Features', 'bool'),
      f('app', 'App control', '', 'high', 'Features', 'bool'),
      f('tank', 'Water tank', 'L', 'high', 'Capacity'),
      f('beans', 'Bean hopper', 'g', 'high', 'Capacity'),
      f('power', 'Power', 'W', null, 'Design'),
      f('weight', 'Weight', 'kg', 'low', 'Design'),
      f('dimensions', 'Dimensions', 'mm', null, 'Design', 'text'),
    ],
  },
  chargers: {
    label: 'Chargers & cables', singular: 'charger or cable',
    note: 'Cables and chargers share this list; cables are scored mostly on power rating and data speed. USB 2.0 cables carry 0.48 Gbps.',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),                    // Wall charger | Car charger | Wireless charger | Charging station | Cable
      f('maxW', 'Max output', 'W', 'high', 'Power'),
      f('singleW', 'Max from one port', 'W', 'high', 'Power'),
      f('ports', 'Ports / connectors', '', null, 'Power', 'text'),
      f('portCount', 'Number of ports', '', 'high', 'Power'),
      f('pd', 'USB Power Delivery', '', null, 'Standards', 'text'),
      f('pps', 'PPS (Samsung super fast)', '', 'high', 'Standards', 'bool'),
      f('qc', 'Qualcomm Quick Charge', '', null, 'Standards', 'text'),
      f('qi', 'Wireless standard', '', null, 'Standards', 'text'),
      f('gan', 'GaN', '', 'high', 'Design', 'bool'),
      f('foldingPlug', 'Folding plug', '', 'high', 'Design', 'bool'),
      f('display', 'Power display', '', 'high', 'Design', 'bool'),
      f('length', 'Cable length', 'm', null, 'Cable'),
      f('data', 'Data speed', 'Gbps', 'high', 'Cable'),
      f('video', 'Video (DisplayPort)', '', 'high', 'Cable', 'bool'),
      f('emarker', 'E-marker chip', '', 'high', 'Cable', 'bool'),
      f('braided', 'Braided', '', 'high', 'Cable', 'bool'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('dimensions', 'Dimensions', 'mm', null, 'Design', 'text'),
    ],
  },
  powerbanks: {
    label: 'Power banks & stations', singular: 'power bank',
    note: 'Airlines allow power banks under 100 Wh in cabin bags; 100–160 Wh needs airline approval; power stations are not allowed on aircraft.',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),                    // Power bank | Magnetic power bank | Power station
      f('capacity', 'Capacity', 'mAh', 'high', 'Capacity'),
      f('wh', 'Energy', 'Wh', 'high', 'Capacity'),
      f('cells', 'Cell type', '', null, 'Capacity', 'text'),
      f('maxOut', 'Max output', 'W', 'high', 'Charging'),
      f('singleOut', 'Max from one port', 'W', 'high', 'Charging'),
      f('input', 'Recharge speed', 'W', 'high', 'Charging'),
      f('rechargeTime', 'Full recharge', 'h', 'low', 'Charging'),
      f('ports', 'Ports', '', null, 'Charging', 'text'),
      f('portCount', 'Number of ports', '', 'high', 'Charging'),
      f('pd', 'USB Power Delivery', '', null, 'Charging', 'text'),
      f('pps', 'PPS (Samsung super fast)', '', 'high', 'Charging', 'bool'),
      f('qc', 'Qualcomm Quick Charge', '', null, 'Charging', 'text'),
      f('wireless', 'Wireless output', 'W', 'high', 'Charging'),
      f('acW', 'AC outlets (continuous)', 'W', 'high', 'Charging'),
      f('magnetic', 'Magnetic (MagSafe / Qi2)', '', 'high', 'Charging', 'bool'),
      f('passthrough', 'Pass-through charging', '', 'high', 'Charging', 'bool'),
      f('display', 'Display', '', null, 'Design', 'text'),
      f('builtInCable', 'Built-in cable', '', 'high', 'Design', 'bool'),
      f('flight', 'Airline carry-on', '', null, 'Design', 'text'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('dimensions', 'Dimensions', 'mm', null, 'Design', 'text'),
    ],
  },
  speakers: {
    label: 'Bluetooth speakers', singular: 'speaker',
    note: "Output power is the maker's figure. UE, Bose, Sony, Apple and Sonos don't publish watts, so those rows are blank rather than guessed.",
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),                    // Portable | Rugged | Party | Smart home
      f('outputW', 'Output power', 'W', 'high', 'Sound'),
      f('drivers', 'Drivers', '', null, 'Sound', 'text'),
      f('bassLow', 'Low-frequency limit', 'Hz', 'low', 'Sound'),
      f('stereo', 'Stereo in one speaker', '', 'high', 'Sound', 'bool'),
      f('codecs', 'Codecs', '', null, 'Sound', 'list'),
      f('battery', 'Battery life', 'h', 'high', 'Battery'),
      f('chargeOut', 'Charges your phone', '', 'high', 'Battery', 'bool'),
      f('ac', 'Mains powered', '', null, 'Battery', 'bool'),
      f('water', 'Water / dust rating', '', null, 'Design', 'text'),
      f('floats', 'Floats', '', 'high', 'Design', 'bool'),
      f('lights', 'Light show', '', null, 'Design', 'bool'),
      f('weight', 'Weight', 'kg', 'low', 'Design'),
      f('bt', 'Bluetooth', '', 'high', 'Connectivity'),
      f('pairing', 'Multi-speaker pairing', '', null, 'Connectivity', 'text'),
      f('wifi', 'Wi-Fi streaming', '', 'high', 'Connectivity', 'bool'),
      f('mic', 'Microphone / speakerphone', '', 'high', 'Connectivity', 'bool'),
      f('aux', 'Aux / USB audio in', '', 'high', 'Connectivity', 'bool'),
      f('app', 'App with EQ', '', 'high', 'Connectivity', 'bool'),
    ],
  },
  printers: {
    label: 'Printers', singular: 'printer',
    note: 'Cost per page is an estimate in US cents from official ink/toner yields and list prices. Third-party supplies change it a lot.',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),                    // Inkjet | Ink tank | Mono laser | Colour laser | Photo | Label
      f('functions', 'Functions', '', null, 'Overview', 'text'),
      f('ppmBlack', 'Print speed, black (ISO)', 'ppm', 'high', 'Speed'),
      f('ppmColor', 'Print speed, colour (ISO)', 'ppm', 'high', 'Speed'),
      f('firstPage', 'First page out', 's', 'low', 'Speed'),
      f('dpi', 'Max print resolution', 'dpi', 'high', 'Quality'),
      f('colors', 'Inks / toners', '', 'high', 'Quality'),
      f('duplex', 'Automatic two-sided', '', 'high', 'Paper', 'bool'),
      f('adf', 'Document feeder', 'sheets', 'high', 'Paper'),
      f('tray', 'Paper input', 'sheets', 'high', 'Paper'),
      f('maxSize', 'Largest paper', '', null, 'Paper', 'text'),
      f('duty', 'Monthly duty cycle', 'pages', 'high', 'Paper'),
      f('yieldBlack', 'Black yield (ink/toner)', 'pages', 'high', 'Running cost'),
      f('yieldColor', 'Colour yield', 'pages', 'high', 'Running cost'),
      f('cppBlack', 'Cost per page, black', '¢', 'low', 'Running cost'),
      f('cppColor', 'Cost per page, colour', '¢', 'low', 'Running cost'),
      f('wifi', 'Wi-Fi', '', 'high', 'Connectivity', 'bool'),
      f('ethernet', 'Ethernet', '', 'high', 'Connectivity', 'bool'),
      f('mobile', 'Mobile printing', '', null, 'Connectivity', 'text'),
      f('screen', 'Control panel', '', null, 'Design', 'text'),
      f('weight', 'Weight', 'kg', 'low', 'Design'),
    ],
  },
  copiers: {
    label: 'Photocopiers', singular: 'photocopier',
    note: 'Office copiers are sold and leased through dealers, so there is no list price and no Better buy verdict. Capacities with optional paper decks are listed as maximums.',
    fields: [
      ...COMMON,
      f('series', 'Series', '', null, 'Overview', 'text'),
      f('type', 'Type', '', null, 'Overview', 'text'),                    // A3 mono MFP | A3 colour MFP | A4 colour MFP …
      f('ppmBlack', 'Copy/print speed, black', 'ppm', 'high', 'Speed'),
      f('ppmColor', 'Copy/print speed, colour', 'ppm', 'high', 'Speed'),
      f('firstCopy', 'First copy out', 's', 'low', 'Speed'),
      f('warmUp', 'Warm-up time', 's', 'low', 'Speed'),
      f('scanIpm', 'Scan speed (simplex)', 'ipm', 'high', 'Scanning'),
      f('feeder', 'Document feeder', '', null, 'Scanning', 'text'),
      f('adf', 'Feeder capacity', 'sheets', 'high', 'Scanning'),
      f('maxSize', 'Largest paper', '', null, 'Paper', 'text'),
      f('paperStd', 'Standard paper capacity', 'sheets', 'high', 'Paper'),
      f('paperMax', 'Maximum paper capacity', 'sheets', 'high', 'Paper'),
      f('duplex', 'Duplex copying', '', 'high', 'Paper', 'bool'),
      f('volume', 'Recommended monthly volume', 'pages', 'high', 'Paper'),
      f('dpi', 'Print resolution', 'dpi', 'high', 'Quality'),
      f('memory', 'Memory', 'GB', 'high', 'Controller'),
      f('storage', 'Storage', 'GB', 'high', 'Controller'),
      f('screen', 'Touchscreen', 'in', 'high', 'Controller'),
      f('fax', 'Fax option', '', 'high', 'Options', 'bool'),
      f('finisher', 'Finisher options', '', null, 'Options', 'text'),
      f('weight', 'Weight', 'kg', null, 'Design'),
    ],
  },
  inverters: {
    label: 'Inverters', singular: 'inverter',
    note: 'Prices are approximate street prices; most are installed by professionals. Grid-tie units need the grid (or a battery system) to work during an outage.',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),                    // Hybrid solar | Off-grid solar | Inverter/charger | Grid-tie
      f('ratedW', 'Rated output', 'W', 'high', 'Output'),
      f('surgeW', 'Surge power', 'W', 'high', 'Output'),
      f('phase', 'Phase', '', null, 'Output', 'text'),
      f('waveform', 'Waveform', '', null, 'Output', 'text'),
      f('efficiency', 'Peak efficiency', '%', 'high', 'Output'),
      f('transfer', 'Transfer time', 'ms', 'low', 'Output'),
      f('batteryV', 'Battery voltage', 'V', null, 'Battery'),
      f('lithium', 'Lithium battery comms', '', 'high', 'Battery', 'bool'),
      f('chargeA', 'Max charge current', 'A', 'high', 'Battery'),
      f('pvW', 'Max solar input', 'W', 'high', 'Solar'),
      f('pvVoc', 'Max solar voltage (Voc)', 'V', 'high', 'Solar'),
      f('mppt', 'MPPT trackers', '', 'high', 'Solar'),
      f('gridTie', 'Can export to grid', '', 'high', 'Solar', 'bool'),
      f('parallel', 'Parallel units', '', 'high', 'Features'),
      f('generator', 'Generator input', '', 'high', 'Features', 'bool'),
      f('monitoring', 'Monitoring', '', null, 'Features', 'text'),
      f('ip', 'Enclosure rating', '', null, 'Design', 'text'),
      f('weight', 'Weight', 'kg', null, 'Design'),
    ],
  },
  ups: {
    label: 'UPS', singular: 'UPS',
    note: "Runtime at half load is read from the maker's runtime chart with the internal battery and is approximate.",
    fields: [
      ...COMMON,
      f('type', 'Topology', '', null, 'Overview', 'text'),                // Standby | Line-interactive | Online double-conversion
      f('form', 'Form factor', '', null, 'Overview', 'text'),
      f('va', 'Capacity', 'VA', 'high', 'Power'),
      f('watts', 'Real power', 'W', 'high', 'Power'),
      f('waveform', 'Output waveform', '', null, 'Power', 'text'),
      f('avr', 'Automatic voltage regulation', '', 'high', 'Power', 'bool'),
      f('inputRange', 'Input voltage range', '', null, 'Power', 'text'),
      f('transfer', 'Transfer time', 'ms', 'low', 'Power'),
      f('outlets', 'Battery-backed outlets', '', 'high', 'Outlets'),
      f('outletType', 'Outlet type', '', null, 'Outlets', 'text'),
      f('runtimeHalf', 'Runtime at half load', 'min', 'high', 'Battery'),
      f('battery', 'Battery', '', null, 'Battery', 'text'),
      f('hotSwap', 'Hot-swappable battery', '', 'high', 'Battery', 'bool'),
      f('extBattery', 'External battery packs', '', 'high', 'Battery', 'bool'),
      f('display', 'Display', '', null, 'Management', 'text'),
      f('usb', 'USB / serial monitoring', '', 'high', 'Management', 'bool'),
      f('network', 'Network card', '', null, 'Management', 'text'),
      f('weight', 'Weight', 'kg', null, 'Design'),
    ],
  },
  evs: {
    label: 'Electric cars', singular: 'electric car',
    note: "Range cycles differ: EPA is the most conservative, WLTP sits in the middle and China's CLTC is the most optimistic. The range score converts all three to an EPA-like figure. Prices for cars not sold in the US are converted from the home-market list price.",
    fields: [
      ...COMMON,
      f('market', 'Main markets', '', null, 'Overview', 'text'),
      f('body', 'Body', '', null, 'Overview', 'text'),
      f('seats', 'Seats', '', 'high', 'Overview'),
      f('drive', 'Drive', '', null, 'Performance', 'text'),
      f('powerKw', 'Power', 'kW', 'high', 'Performance'),
      f('torque', 'Torque', 'Nm', 'high', 'Performance'),
      f('accel', '0–100 km/h', 's', 'low', 'Performance'),
      f('topSpeed', 'Top speed', 'km/h', 'high', 'Performance'),
      f('batteryKwh', 'Battery (usable)', 'kWh', 'high', 'Battery'),
      f('chemistry', 'Cell chemistry', '', null, 'Battery', 'text'),
      f('rangeWltp', 'Range (WLTP)', 'km', 'high', 'Range'),
      f('rangeEpa', 'Range (EPA)', 'km', 'high', 'Range'),
      f('rangeCltc', 'Range (CLTC)', 'km', 'high', 'Range'),
      f('efficiency', 'Consumption (WLTP)', 'kWh/100 km', 'low', 'Range'),
      f('voltage', 'Architecture', 'V', 'high', 'Charging'),
      f('dcKw', 'Peak DC charging', 'kW', 'high', 'Charging'),
      f('dc10to80', 'DC 10–80%', 'min', 'low', 'Charging'),
      f('acKw', 'AC charging', 'kW', 'high', 'Charging'),
      f('v2l', 'Vehicle-to-load', '', 'high', 'Charging', 'bool'),
      f('cargo', 'Boot space', 'L', 'high', 'Practicality'),
      f('frunk', 'Front trunk', 'L', 'high', 'Practicality'),
      f('length', 'Length', 'mm', null, 'Practicality'),
      f('weight', 'Kerb weight', 'kg', 'low', 'Practicality'),
      f('screen', 'Main screen', 'in', 'high', 'Tech'),
      f('adas', 'Driver assistance', '', null, 'Tech', 'text'),
    ],
  },
};

export const CATEGORY_ORDER = ['phones', 'tablets', 'laptops', 'tvs', 'monitors', 'socs', 'cpus', 'gpus', 'watches', 'audio', 'speakers', 'consoles', 'chargers', 'powerbanks', 'printers', 'copiers', 'coffee', 'inverters', 'ups', 'guitars', 'keyboards', 'evs'];

/* Category groups for the picker (every category appears once). */
export const CATEGORY_GROUPS = [
  { id: 'computing', label: 'Phones & computers', cats: ['phones', 'tablets', 'laptops', 'tvs', 'monitors', 'watches', 'consoles'] },
  { id: 'chips', label: 'Chips & graphics', cats: ['socs', 'cpus', 'gpus'] },
  { id: 'audio', label: 'Audio', cats: ['audio', 'speakers'] },
  { id: 'charging', label: 'Charging', cats: ['chargers', 'powerbanks'] },
  { id: 'office', label: 'Office & home', cats: ['printers', 'copiers', 'coffee'] },
  { id: 'power', label: 'Backup power', cats: ['inverters', 'ups'] },
  { id: 'music', label: 'Music gear', cats: ['guitars', 'keyboards'] },
  { id: 'vehicles', label: 'Vehicles', cats: ['evs'] },
];
