/* Device database schema.
   Every category lists its fields once: key, label, unit, which direction is better
   ('high' | 'low' | null), the spec group it is shown under, and its type.
   Types: num | text | bool | list (array of strings) | nums (array of numbers). */

const f = (key, label, unit, better, group, type = 'num') => ({ key, label, unit, better, group, type });

const COMMON = [
  f('brand', 'Brand', '', null, 'Overview', 'text'),
  f('released', 'Released', '', 'high', 'Overview', 'text'),     // 'YYYY-MM'
  f('price', 'Launch price', 'USD', 'low', 'Overview'),
];

export const CATEGORIES = {
  phones: {
    label: 'Phones', singular: 'phone',
    fields: [
      ...COMMON,
      f('os', 'Operating system', '', null, 'Overview', 'text'),
      f('updates', 'OS update promise', 'years', 'high', 'Overview'),
      f('chip', 'Chipset', '', null, 'Performance', 'text'),
      f('chipId', 'Chipset id', '', null, 'Performance', 'text'),
      f('cpu', 'CPU', '', null, 'Performance', 'text'),
      f('gpu', 'GPU', '', null, 'Performance', 'text'),
      f('ram', 'RAM', 'GB', 'high', 'Performance'),
      f('storage', 'Storage options', 'GB', 'high', 'Performance', 'nums'),
      f('sd', 'Memory card slot', '', 'high', 'Performance', 'bool'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('antutu', 'AnTuTu 10', '', 'high', 'Benchmarks'),
      f('displaySize', 'Screen size', 'in', 'high', 'Display'),
      f('displayRes', 'Resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Panel', '', null, 'Display', 'text'),
      f('refresh', 'Refresh rate', 'Hz', 'high', 'Display'),
      f('nits', 'Peak brightness', 'nits', 'high', 'Display'),
      f('ppi', 'Pixel density', 'ppi', 'high', 'Display'),
      f('protection', 'Screen protection', '', null, 'Display', 'text'),
      f('camMain', 'Main camera', 'MP', 'high', 'Camera'),
      f('camMainSensor', 'Main sensor size', '', null, 'Camera', 'text'),
      f('camMainAperture', 'Main aperture', 'f/', 'low', 'Camera'),
      f('ois', 'Optical stabilisation', '', 'high', 'Camera', 'bool'),
      f('camUltra', 'Ultra-wide camera', 'MP', 'high', 'Camera'),
      f('camTele', 'Telephoto camera', 'MP', 'high', 'Camera'),
      f('teleZoom', 'Optical zoom', 'x', 'high', 'Camera'),
      f('camFront', 'Selfie camera', 'MP', 'high', 'Camera'),
      f('video', 'Max video', '', null, 'Camera', 'text'),
      f('battery', 'Battery', 'mAh', 'high', 'Battery'),
      f('wired', 'Wired charging', 'W', 'high', 'Battery'),
      f('wireless', 'Wireless charging', 'W', 'high', 'Battery'),
      f('reverse', 'Reverse wireless charging', '', 'high', 'Battery', 'bool'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('thickness', 'Thickness', 'mm', 'low', 'Design'),
      f('dimensions', 'Dimensions', 'mm', null, 'Design', 'text'),
      f('ip', 'Water resistance', '', null, 'Design', 'text'),
      f('materials', 'Materials', '', null, 'Design', 'text'),
      f('fingerprint', 'Fingerprint', '', null, 'Design', 'text'),
      f('fiveG', '5G', '', 'high', 'Connectivity', 'bool'),
      f('wifi', 'Wi-Fi', '', null, 'Connectivity', 'text'),
      f('bt', 'Bluetooth', '', 'high', 'Connectivity'),
      f('usb', 'USB', '', null, 'Connectivity', 'text'),
      f('nfc', 'NFC', '', 'high', 'Connectivity', 'bool'),
      f('esim', 'eSIM', '', 'high', 'Connectivity', 'bool'),
      f('jack', 'Headphone jack', '', 'high', 'Connectivity', 'bool'),
      f('speakers', 'Speakers', '', null, 'Connectivity', 'text'),
    ],
  },
  tablets: {
    label: 'Tablets', singular: 'tablet',
    fields: [
      ...COMMON,
      f('os', 'Operating system', '', null, 'Overview', 'text'),
      f('chip', 'Chipset', '', null, 'Performance', 'text'),
      f('chipId', 'Chipset id', '', null, 'Performance', 'text'),
      f('ram', 'RAM', 'GB', 'high', 'Performance'),
      f('storage', 'Storage options', 'GB', 'high', 'Performance', 'nums'),
      f('sd', 'Memory card slot', '', 'high', 'Performance', 'bool'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('antutu', 'AnTuTu 10', '', 'high', 'Benchmarks'),
      f('displaySize', 'Screen size', 'in', 'high', 'Display'),
      f('displayRes', 'Resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Panel', '', null, 'Display', 'text'),
      f('refresh', 'Refresh rate', 'Hz', 'high', 'Display'),
      f('nits', 'Peak brightness', 'nits', 'high', 'Display'),
      f('ppi', 'Pixel density', 'ppi', 'high', 'Display'),
      f('camMain', 'Rear camera', 'MP', 'high', 'Camera'),
      f('camFront', 'Front camera', 'MP', 'high', 'Camera'),
      f('video', 'Max video', '', null, 'Camera', 'text'),
      f('battery', 'Battery', 'mAh', 'high', 'Battery'),
      f('wired', 'Wired charging', 'W', 'high', 'Battery'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('thickness', 'Thickness', 'mm', 'low', 'Design'),
      f('stylus', 'Stylus support', '', null, 'Design', 'text'),
      f('keyboard', 'Keyboard accessory', '', null, 'Design', 'text'),
      f('cellular', 'Cellular option', '', 'high', 'Connectivity', 'bool'),
      f('wifi', 'Wi-Fi', '', null, 'Connectivity', 'text'),
      f('usb', 'USB', '', null, 'Connectivity', 'text'),
      f('speakers', 'Speakers', '', null, 'Connectivity', 'text'),
      f('jack', 'Headphone jack', '', 'high', 'Connectivity', 'bool'),
    ],
  },
  laptops: {
    label: 'Laptops', singular: 'laptop',
    fields: [
      ...COMMON,
      f('os', 'Operating system', '', null, 'Overview', 'text'),
      f('type', 'Type', '', null, 'Overview', 'text'),            // ultrabook, gaming, 2-in-1, workstation, chromebook
      f('cpu', 'Processor', '', null, 'Performance', 'text'),
      f('cpuId', 'Processor id', '', null, 'Performance', 'text'),
      f('gpu', 'Graphics', '', null, 'Performance', 'text'),
      f('gpuId', 'Graphics id', '', null, 'Performance', 'text'),
      f('ram', 'RAM', 'GB', 'high', 'Performance'),
      f('ramMax', 'Max RAM', 'GB', 'high', 'Performance'),
      f('ramType', 'Memory type', '', null, 'Performance', 'text'),
      f('storage', 'Storage', 'GB', 'high', 'Performance'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('displaySize', 'Screen size', 'in', 'high', 'Display'),
      f('displayRes', 'Resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Panel', '', null, 'Display', 'text'),
      f('refresh', 'Refresh rate', 'Hz', 'high', 'Display'),
      f('nits', 'Brightness', 'nits', 'high', 'Display'),
      f('touch', 'Touchscreen', '', 'high', 'Display', 'bool'),
      f('batteryWh', 'Battery', 'Wh', 'high', 'Battery'),
      f('batteryLife', 'Rated battery life', 'h', 'high', 'Battery'),
      f('charger', 'Charger', 'W', 'high', 'Battery'),
      f('weight', 'Weight', 'kg', 'low', 'Design'),
      f('thickness', 'Thickness', 'mm', 'low', 'Design'),
      f('materials', 'Materials', '', null, 'Design', 'text'),
      f('webcam', 'Webcam', '', null, 'Design', 'text'),
      f('keyboard', 'Keyboard', '', null, 'Design', 'text'),
      f('ports', 'Ports', '', null, 'Connectivity', 'text'),
      f('wifi', 'Wi-Fi', '', null, 'Connectivity', 'text'),
      f('bt', 'Bluetooth', '', 'high', 'Connectivity'),
    ],
  },
  socs: {
    label: 'Mobile chips', singular: 'chip',
    fields: [
      ...COMMON.filter(x => x.key !== 'price'),
      f('node', 'Process', '', null, 'Overview', 'text'),
      f('transistors', 'Transistors', 'billion', 'high', 'Overview'),
      f('cores', 'CPU cores', '', 'high', 'CPU'),
      f('cpu', 'CPU layout', '', null, 'CPU', 'text'),
      f('maxClock', 'Max clock', 'GHz', 'high', 'CPU'),
      f('arch', 'Architecture', '', null, 'CPU', 'text'),
      f('gpu', 'GPU', '', null, 'Graphics', 'text'),
      f('gpuCores', 'GPU cores', '', 'high', 'Graphics'),
      f('gpuClock', 'GPU clock', 'MHz', 'high', 'Graphics'),
      f('npu', 'NPU', 'TOPS', 'high', 'AI'),
      f('memory', 'Memory', '', null, 'Memory', 'text'),
      f('modem', 'Modem', '', null, 'Connectivity', 'text'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('antutu', 'AnTuTu 10', '', 'high', 'Benchmarks'),
      f('wildlife', '3DMark Wild Life Extreme', '', 'high', 'Benchmarks'),
      f('usedIn', 'Found in', '', null, 'Overview', 'list'),
    ],
  },
  cpus: {
    label: 'Processors', singular: 'processor',
    fields: [
      ...COMMON,
      f('segment', 'Segment', '', null, 'Overview', 'text'),        // Desktop | Laptop | Workstation
      f('socket', 'Socket', '', null, 'Overview', 'text'),
      f('node', 'Process', '', null, 'Overview', 'text'),
      f('arch', 'Architecture', '', null, 'Overview', 'text'),
      f('cores', 'Cores', '', 'high', 'Cores'),
      f('threads', 'Threads', '', 'high', 'Cores'),
      f('pcores', 'Performance cores', '', 'high', 'Cores'),
      f('ecores', 'Efficiency cores', '', 'high', 'Cores'),
      f('baseClock', 'Base clock', 'GHz', 'high', 'Clocks'),
      f('boostClock', 'Boost clock', 'GHz', 'high', 'Clocks'),
      f('l3', 'L3 cache', 'MB', 'high', 'Clocks'),
      f('tdp', 'TDP', 'W', 'low', 'Power'),
      f('maxPower', 'Max turbo power', 'W', 'low', 'Power'),
      f('memory', 'Memory support', '', null, 'Platform', 'text'),
      f('pcie', 'PCIe', '', 'high', 'Platform'),
      f('igpu', 'Integrated graphics', '', null, 'Platform', 'text'),
      f('npu', 'NPU', 'TOPS', 'high', 'Platform'),
      f('gb6s', 'Geekbench 6 single-core', '', 'high', 'Benchmarks'),
      f('gb6m', 'Geekbench 6 multi-core', '', 'high', 'Benchmarks'),
      f('cb24s', 'Cinebench 2024 single', '', 'high', 'Benchmarks'),
      f('cb24m', 'Cinebench 2024 multi', '', 'high', 'Benchmarks'),
    ],
  },
  gpus: {
    label: 'Graphics cards', singular: 'graphics card',
    fields: [
      ...COMMON,
      f('segment', 'Segment', '', null, 'Overview', 'text'),        // Desktop | Laptop | Workstation
      f('arch', 'Architecture', '', null, 'Overview', 'text'),
      f('node', 'Process', '', null, 'Overview', 'text'),
      f('shaders', 'Shader units', '', 'high', 'Core'),
      f('rtCores', 'RT cores / units', '', 'high', 'Core'),
      f('tensor', 'AI / tensor cores', '', 'high', 'Core'),
      f('baseClock', 'Base clock', 'MHz', 'high', 'Core'),
      f('boostClock', 'Boost clock', 'MHz', 'high', 'Core'),
      f('tflops', 'FP32 compute', 'TFLOPS', 'high', 'Core'),
      f('vram', 'Memory', 'GB', 'high', 'Memory'),
      f('memType', 'Memory type', '', null, 'Memory', 'text'),
      f('bus', 'Memory bus', 'bit', 'high', 'Memory'),
      f('bandwidth', 'Bandwidth', 'GB/s', 'high', 'Memory'),
      f('tdp', 'Board power', 'W', 'low', 'Power'),
      f('connector', 'Power connector', '', null, 'Power', 'text'),
      f('pcie', 'Interface', '', null, 'Power', 'text'),
      f('outputs', 'Outputs', '', null, 'Power', 'text'),
      f('upscaler', 'Upscaling', '', null, 'Features', 'text'),
      f('timespy', '3DMark Time Spy graphics', '', 'high', 'Benchmarks'),
      f('steelnomad', '3DMark Steel Nomad', '', 'high', 'Benchmarks'),
    ],
  },
  watches: {
    label: 'Smartwatches', singular: 'watch',
    fields: [
      ...COMMON,
      f('os', 'Platform', '', null, 'Overview', 'text'),
      f('compat', 'Works with', '', null, 'Overview', 'text'),
      f('chip', 'Chipset', '', null, 'Performance', 'text'),
      f('ram', 'RAM', 'GB', 'high', 'Performance'),
      f('storage', 'Storage', 'GB', 'high', 'Performance'),
      f('caseSize', 'Case size', 'mm', null, 'Design', 'text'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('materials', 'Case material', '', null, 'Design', 'text'),
      f('water', 'Water rating', '', null, 'Design', 'text'),
      f('displaySize', 'Screen size', 'in', 'high', 'Display'),
      f('displayRes', 'Resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Panel', '', null, 'Display', 'text'),
      f('nits', 'Peak brightness', 'nits', 'high', 'Display'),
      f('aod', 'Always-on display', '', 'high', 'Display', 'bool'),
      f('batteryDays', 'Battery life', 'days', 'high', 'Battery'),
      f('battery', 'Battery', 'mAh', 'high', 'Battery'),
      f('sensors', 'Health sensors', '', null, 'Health', 'list'),
      f('ecg', 'ECG', '', 'high', 'Health', 'bool'),
      f('spo2', 'Blood oxygen', '', 'high', 'Health', 'bool'),
      f('gps', 'GPS', '', null, 'Connectivity', 'text'),
      f('lte', 'LTE option', '', 'high', 'Connectivity', 'bool'),
      f('nfc', 'Payments (NFC)', '', 'high', 'Connectivity', 'bool'),
    ],
  },
  audio: {
    label: 'Headphones & earbuds', singular: 'headphone',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),              // Earbuds | Over-ear | On-ear | Open-ear
      f('anc', 'Active noise cancelling', '', 'high', 'Sound', 'bool'),
      f('driver', 'Driver size', 'mm', 'high', 'Sound'),
      f('driverType', 'Driver type', '', null, 'Sound', 'text'),
      f('codecs', 'Codecs', '', null, 'Sound', 'list'),
      f('spatial', 'Spatial audio', '', 'high', 'Sound', 'bool'),
      f('hires', 'Hi-Res wireless', '', 'high', 'Sound', 'bool'),
      f('battery', 'Battery (ANC on)', 'h', 'high', 'Battery'),
      f('batteryTotal', 'Battery with case', 'h', 'high', 'Battery'),
      f('wirelessCharging', 'Wireless charging', '', 'high', 'Battery', 'bool'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('water', 'Water resistance', '', null, 'Design', 'text'),
      f('bt', 'Bluetooth', '', 'high', 'Connectivity'),
      f('multipoint', 'Multipoint', '', 'high', 'Connectivity', 'bool'),
      f('mics', 'Microphones', '', 'high', 'Connectivity'),
      f('wired', 'Wired / USB audio', '', null, 'Connectivity', 'text'),
    ],
  },
  consoles: {
    label: 'Consoles & handhelds', singular: 'console',
    fields: [
      ...COMMON,
      f('type', 'Type', '', null, 'Overview', 'text'),              // Home console | Handheld | Hybrid | Handheld PC
      f('cpu', 'CPU', '', null, 'Performance', 'text'),
      f('gpu', 'GPU', '', null, 'Performance', 'text'),
      f('tflops', 'GPU compute', 'TFLOPS', 'high', 'Performance'),
      f('ram', 'Memory', 'GB', 'high', 'Performance'),
      f('storage', 'Storage', 'GB', 'high', 'Performance'),
      f('maxRes', 'Max output', '', null, 'Display', 'text'),
      f('maxFps', 'Max frame rate', 'fps', 'high', 'Display'),
      f('displaySize', 'Built-in screen', 'in', 'high', 'Display'),
      f('displayRes', 'Screen resolution', 'px', null, 'Display', 'text'),
      f('panel', 'Screen panel', '', null, 'Display', 'text'),
      f('refresh', 'Screen refresh', 'Hz', 'high', 'Display'),
      f('batteryWh', 'Battery', 'Wh', 'high', 'Battery'),
      f('weight', 'Weight', 'g', 'low', 'Design'),
      f('media', 'Disc drive', '', null, 'Design', 'text'),
      f('connectivity', 'Connectivity', '', null, 'Design', 'text'),
    ],
  },
};

export const CATEGORY_ORDER = ['phones', 'tablets', 'laptops', 'socs', 'cpus', 'gpus', 'watches', 'audio', 'consoles'];
